### ISSUE TITLE
Update flytesnacks pod.py does not mount volumes correctly.

### ISSUE THREAD

**Issue by ajsalow** [flyteorg/flyte#1000]
**Describe the bug**
cookbook/integrations/kubernetes/pod/pod.py does not actually mount the created `shared_volume_mount` to the containers. `volumeMounts` needs to be replaced with `volume_mounts` on line 59 and 60

It is a quick fix so I can open a PR for it shortly.

**Comment by kumare3** [comment]
@ajsalow please open a PR
