### ISSUE TITLE
[flytekit-java] Support BranchNode

### ISSUE THREAD

**Issue by kanterov** [flyteorg/flyte#1005]
**Why would this be helpful to the Flyte community**
`BranchNode` allows adding conditional logic to workflows graphs.

**Comment by kanterov** [comment]
It's in progress, ETA 1 week.

**Comment by kumare3** [comment]
cc @kanterov / @vglocus do you guys know if this is already resolved?

**Comment by ckiosidis** [comment]
BranchNode is already supported, I am closing this issue https://github.com/flyteorg/flytekit-java/blob/master/flytekit-api/src/main/java/org/flyte/api/v1/BranchNode.java
