### ISSUE TITLE
[Housekeeping] [flytekit] Logging cleanup

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#1034]
**Describe the Issue**
We need better logging.  Logging of flytekit is not smooth, and doesn't help sufficiently in debugging either user code or our own issues when developing flytekit.

We already have some [specific](https://github.com/flyteorg/flytekit/blob/master/flytekit/loggers.py#L9) loggers.  We should go through flytekit, using proper loggers and levels for the correct scenario.

During things like serialize, local wf execution, or local task execution, logs should give a clear indication of what's happening at the info level, and give good debugging information at the debug level.

**What if we do not do this?**
Harder to debug, uncleanliness, lack of polish.

**Comment by samhita-alla** [comment]
@sccalabr, thank you for looking into this! @wild-endeavor, can you please clarify?

**Comment by pingsutw** [comment]
done https://github.com/flyteorg/flytekit/pull/871
