### ISSUE TITLE
[Flytectl Feature] Fltyetcl should return a non zero error code on failure

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#1037]
**Describe the feature/command for flytectl**
Flytectl currently has a catch all in the main.go and which causes all errors to be caught at that level and main routine returns an 0 error code.

Instead a non zero error code should be returned from the main that way any callers can rely on the exit status of the command.

Right now even on an error the return stats is 0.
Heres an example where flytectl is not able to communicate with the admin and throws an error. The error is logged but return is 0

```
flytectl get launchplans -p flytectldemo -d development
Warn: No metricsProvider set for the workqueue
INFO[0000] [0] Couldn't find a config file []. Relying on env vars and pflags. 
INFO[0000] Config section [admin] updated. Firing updated event. 
INFO[0000] Config section [storage] updated. No update handler registered. 
INFO[0000] Config section [adminutils] updated. No update handler registered. 
INFO[0000] Config section [root] updated. No update handler registered. 
INFO[0000] Config section [logger] updated. Firing updated event. 
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: missing address"
```

If you now do
```
echo $?         
0
```

**Provide a possible output or ux example**
If an error occurs like in the example above a non-zero status should be returned.

**Comment by pmahindrakar-oss** [comment]
cc : @wild-endeavor

**Comment by kumare3** [comment]
this has been merged and available in latest flytectl
