### ISSUE TITLE
[BUG] console not available in flytesnack sandbox

### ISSUE THREAD

**Issue by milton0825** [flyteorg/flyte#1038]
**Describe the bug**

After I started the sandbox in flytesnack with:
```
make start

Finished scanning 75 files
Flyte is ready! Flyte UI is available at http://localhost:30081/console.
```
Then I went to the console webpage following the link and I see:
```
This page isn’t workinglocalhost didn’t send any data.
ERR_EMPTY_RESPONSE
```

**Expected behavior**
I should be able to visit the console UI

**[Optional] Additional context**
***To Reproduce***
1. Clone flytesnack repo
2. `make start`
3. Follow the link to go to flyte console

***Screenshots***
![image](https://user-images.githubusercontent.com/6065051/118543233-dec4e880-b708-11eb-96ce-d8240c1a1f5f.png)

**Comment by milton0825** [comment]
cc: @wild-endeavor

**Comment by EngHabu** [comment]
@jeevb @evalsocket

**Comment by EngHabu** [comment]
I just tried the repro steps but failed to reproduce. Can you try to `docker pull ghcr.io/flyteorg/flyte-sandbox:dind` before running `make start` to make sure you have the latest?

**Comment by milton0825** [comment]
hmm...
```
➜ docker pull ghcr.io/flyteorg/flyte-sandbox:dind
dind: Pulling from flyteorg/flyte-sandbox
Digest: sha256:3f254bd6109e7b2b2e6d94af33bff662437b9961f368fcb3a3d76408b69faf31
Status: Image is up to date for ghcr.io/flyteorg/flyte-sandbox:dind
ghcr.io/flyteorg/flyte-sandbox:dind
```

**Comment by milton0825** [comment]
After I switched to another port the issue go away..
