### ISSUE TITLE
[Housekeeping] Migrate `make register` in flytesnacks (and python-template) to use flytectl

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1040]
**Describe the Issue**
Flytectl is quickly becoming the standard CLI for interacting with flyte control plane. We should encourage the best practice by moving to it in flytesnacks and python-template repos...

**Comment by evalsocket** [comment]
@EngHabu Can we first resolve the issue of flytectl flags? Currently `--admin.endpoint` flag is not working in flytectl. 
CC: @pmahindrakar-oss

**Comment by pmahindrakar-oss** [comment]
@evalsocket i am working on that issue and the bind flags PR is checkedin but while migrating existing configs I found that some types like URL are not supported by cobra spflags.

We might have to contribute to spflags to resolve this issue.

But current issue need not wait as we support config from homedir/.flyte directory now

**Comment by evalsocket** [comment]
@pmahindrakar-oss pr is merged in flytectl. You can start your work on python-template. Also add workflow like this https://github.com/flyteorg/flytesnacks/pull/257
