### ISSUE TITLE
[BUG] scrolling and text selection with node window open doesn't work.

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#1047]
**Describe the bug**
Not sure if this is a duplicate.

If you go to the link sent in DM (or open any execution really that failed) - and click on the "expand" to see the full selection, you'll notice you can scroll and click-and-drag to select the text.  Now click on `n0` - the node window should pop open to the right.  However the text no longer is scrollable/selectable.

CC @jsonporter

**Expected behavior**
Scolling to continue to work.

**Comment by georgesnelling** [comment]
Hey @wild-endeavor, can you provide a link to the demo site that shows this?  We're missing the context of the DM mentioned above.

**Comment by jsonporter** [comment]
This is currently a limitation of material-ui; will not fix.
