### ISSUE TITLE
[Core Feature] [flytekit] Map support for Pod Tasks

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#1051]
# Map support for Pod Tasks
## Motivation
Currently the [map_task](https://github.com/flyteorg/flytekit/blob/1d6b6842b0ebbcb3567af3882e580824758b44b1/flytekit/core/map_task.py#L189) construct only works for regular `PythonFunctionTask`s.  Pod tasks are close enough to regular function tasks however that they should be supported as well.

## Goal
To be able to map over Pod Tasks and have the correct `PodSpec` applied to the run-time pod.

## Alternatives
None

## Additional Context
Currently the container object generated by the map task looks something like this, when mapping over a basic `PythonFunctionTask`.

```
      container {
        image: "flytecookbook:core-732e20036452a7798086bf5abee1ede985f25e51"
        args: "pyflyte-map-execute"
        args: "--inputs"
        args: "{{.input}}"
        args: "--output-prefix"
        args: "{{.outputPrefix}}"
        args: "--raw-output-data-prefix"
        args: "{{.rawOutputDataPrefix}}"
        args: "--resolver"
        args: "flytekit.core.python_auto_container.default_task_resolver"
        args: "--"
        args: "task-module"
        args: "core.control_flow.map_task"
        args: "task-name"
        args: "a_mappable_task"
        resources {
        }
        env {
          key: "FLYTE_INTERNAL_CONFIGURATION_PATH"
          value: "/root/sandbox.config"
        }
        env {
          key: "FLYTE_INTERNAL_IMAGE"
          value: "flytecookbook:core-732e20036452a7798086bf5abee1ede985f25e51"
        }
      }
      task_type_version: 1
    }
```

This ends up actually kinda working, since Pod tasks are closely related to regular function tasks, but all the Pod dependencies are missing.

The `custom` field in the map task TaskTemplate today is an `ArrayJob`. We'll have to figure out how to add the `PodSpec` in addition to the [`ArrayJob`](https://github.com/flyteorg/flytekit/blob/1d6b6842b0ebbcb3567af3882e580824758b44b1/flytekit/core/map_task.py#L97), and how to invoke the Pod plugin instead of just the container plugin.

This is related to https://github.com/flyteorg/flyte/issues/1050

**Comment by jeevb** [comment]
@apatel-fn: FYI
