### ISSUE TITLE
[Flytectl Bug] flytectl get launchplan --config is not respected

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1054]
**Describe the feature/command for flytectl**
If I do not have the config.yaml under ~/.flyte/config.yaml, and instead, attempt to pass it as a parameter to `flytectl get launchplan --config` it doesn't seem to find it... it works fine with other commands I tried...

**Provide a possible output or ux example**
A clear and concise description of what you want to happen or achieve.

**Comment by pmahindrakar-oss** [comment]
I am able to do  get launchplan using a custom config passed in the arguments.

-  mv ~/.flyte/config.yaml ~/.config.yaml
-  flytectl get launchplan -d development -p flytectldemo  core.flyte_basics.lp.child_workflow --config ~/config.yaml 

```
INFO[0000] Using config file: [/Users/praful/config.yaml] 
INFO[0000] Config section [root] updated. No update handler registered.  src="viper.go:349"
INFO[0000] Config section [logger] updated. Firing updated event.  src="viper.go:351"
 --------- ------------------------------------- ------ ------- ---------- 
| VERSION | NAME                                | TYPE | STATE | SCHEDULE |
 --------- ------------------------------------- ------ ------- ---------- 
| v1      | core.flyte_basics.lp.child_workflow |      |       |          |
 --------- ------------------------------------- ------ ------- ---------- 
```

Can you check if there is something i am missing here.
I even tried workflow which works with custom config

**Comment by kumare3** [comment]
@EngHabu / @pmahindrakar-oss I tested this. You both are right!
So if you have a `~/.flyte/config.yaml` then `--config` is not respected. But in the methodology that @pmahindrakar-oss tried, he actually renamed the `~/.flyte/config.yaml`. This uses the right config.yaml

@pmahindrakar-oss the fix should be that if `--config` is provided then the default path should be ignored.

**Comment by evalsocket** [comment]
It is done. I am closing this
