### ISSUE TITLE
[BUG] UI is not correctly rendering nested nodes' names

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1085]
**Describe the bug**
The UI seems to be confusing the first node with the first sub-node..

![Screen Shot 2021-06-01 at 1 58 25 PM](https://user-images.githubusercontent.com/27159/120389691-9fd68b80-c2e1-11eb-882c-1e934bd7f125.png)

In this picture the UI seems to pick the first node to render within the main workflow as well as for every subsequent sub-workflow... (same goes for 2nd, 3rd node... etc.)

**Expected behavior**
Node names should be coming from each sub-workflow's respective spec.

**Comment by jsonporter** [comment]
Fixed. https://github.com/flyteorg/flyteconsole/commit/67dd18397caf40e350da40e0672e500eaa9f338a
