### ISSUE TITLE
[Housekeeping] Flytectl Refactoring 

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#1097]
**Describe the Issue**
-  Migrate the existing commands to use `pkg/ext` model for communication with flyteadmin communication
-  Our current coverage is around 68%, We want at least 72% 

**What if we do not do this?**
Short description of potential consequences

***Related component***
Either Specific / all

**Comment by evalsocket** [comment]
CC: @pmahindrakar-oss

**Comment by kumare3** [comment]
@evalsocket i like the pkg/ext but 75% sounds high

**Comment by evalsocket** [comment]
@kumare3 I made flytectl up to 70%. I don't want to add more changes in the same pr(filters) that's why created a new issue. but we will see where can we reach?
