### ISSUE TITLE
[Housekeeping] Make MaxParallelism configurable

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#1099]
**Describe the Issue**
There's no way to set [MaxParallelism](https://github.com/flyteorg/flytepropeller/blob/aa6c625e3e05a307b54513e86e46044560c99d75/pkg/apis/flyteworkflow/v1alpha1/execution_config.go#L22) for a workflow execution, currently. Exposing this as a matchable entity that can be configured will allow flyte users to better manage propeller performance.

**What if we do not do this?**
Short description of potential consequences

***Related component***
Flyteadmin & propeller

**Comment by kumare3** [comment]
@katrogan what part is remaining in this? Is it flytectl. Else can we close this one?

**Comment by kumare3** [comment]
@katrogan I also wanted to add it to LaunchPlan

**Comment by katrogan** [comment]
@kumare3 yep https://github.com/flyteorg/flyte/issues/1101

we can keep this open for the launch plan work
