### ISSUE TITLE
[BUG] flytesnacks `make start` should always `pull` docker image 

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1103]
**Describe the bug**
flyte-sandbox image keeps getting updated whenever we release flyte repo.. which is great. however, without manually pulling that image, users can get stuck running older versions...

**Expected behavior**
`make start` should always start fresh new cluster

the easiest fix is to `docker pull ghcr.io/flyteorg/flyte-sandbox:dind` in `make start` in flytesnacks

**Comment by evalsocket** [comment]
@EngHabu Do we need this after `flytectl sandbox command`. In flytectl, we pull the latest images each time

**Comment by evalsocket** [comment]
I am closing this because the new flytectl sandbox command will always pull the image. No need to do anything in flytesnacks.
