### ISSUE TITLE
[Docs] Broken link in house price tutorial

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1110]
https://docs.flyte.org/projects/cookbook/en/latest/auto/case_studies/ml_training/house_price_prediction/index.html 
refers to "Write a dynamic task"  which attempts to go to: https://docs.flyte.org/projects/cookbook/en/latest/auto_core_intermediate/dynamics.html but that url no longer exists...

**Comment by SandraGH5** [comment]
Replaced broken link with https://docs.flyte.org/projects/cookbook/en/latest/auto/core/control_flow/dynamics.html in PR https://github.com/flyteorg/flytesnacks/pull/290

**Comment by SandraGH5** [comment]
Link Fixed.
