### ISSUE TITLE
[Housekeeping] Publish Helm Chart

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1111]
**Describe the Issue**
We can use an action like this: https://github.com/marketplace/actions/helm-publish
to publish helm charts on release in flyte repo

**Comment by evalsocket** [comment]
Should we use the same branch https://github.com/flyteorg/flyte/tree/gh-pages that we are using for documentation ?

**Comment by EngHabu** [comment]
Can you clarify what's the branch is needed for?

**Comment by evalsocket** [comment]
in helm we can publish our chart artifacts in `gh-pages`, gh-pages URL is publically accessible and user can use it as a registry. I found some documentation code in `gh-pages`, It's not a problem we can use the same branch for docs/helm. 

```
$ helm repo add https://flyteorg.github.com/flyte
$ helm install flyte 
```

Or else move helm out of flyte repo. 

```
$ helm repo add https://flyteorg.github.com/helm
$ helm install flyte 
```

**Comment by kumare3** [comment]
@evalsocket / @EngHabu can we make a new domain helm.Flyte.org

**Comment by evalsocket** [comment]
@kumare3 yes we can but first we need our artifacts in `gh-pages`

**Comment by sbrunk** [comment]
There's also another official action for publishing charts: https://github.com/marketplace/actions/helm-chart-releaser

Once the publishing infra is in place we should also add the chart to [Artifact Hub](https://artifacthub.io/) ([Docs](https://artifacthub.io/docs/topics/repositories/)).

**Comment by evalsocket** [comment]
@sbrunk yes I used the same GitHub action in my PR. It has one open issue related to dir structure. It needs `charts/flyte`.

**Comment by sbrunk** [comment]
Ah I didn't see #1147 😄

**Comment by sbrunk** [comment]
> @sbrunk yes I used the same GitHub action in my PR. It has one open issue related to dir structure. It needs `charts/flyte`.

So @evalsocket in order to use the action we'd need to move from

```
├── ...
├── helm
├── ...
```
to
```
├── ...
├── charts
│   └── flyte
├── ...
```
or, I guess since we can set `charts_dir`
```
├── ...
├── helm
│   └── flyte
├── ...
```
would also work?

**Comment by evalsocket** [comment]
@sbrunk i used `helm/dir`
