### ISSUE TITLE
Support branch nodes in FlyteWorkflow.fetch

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#1116]
`SdkWorkflow.fetch` (the legacy control plane class) doesn't support fetching workflows that have branch nodes. This issue should address this issue in the equivalent new control plane class https://github.com/flyteorg/flytekit/blob/master/flytekit/control_plane/workflow.py#L17

For more context see conversation in https://flyte-org.slack.com/archives/CNMKCU6FR/p1623320382058400

**Comment by kanterov** [comment]
@cosmicBboy are branch nodes going to be supported in FlyteRemote?

**Comment by cosmicBboy** [comment]
@kanterov we'll make it so! if not in the MVP release of the `remote` module, then as a quick follow-up

**Comment by kumare3** [comment]
@wild-endeavor I think you merged this right?
