### ISSUE TITLE
[BUG] Flytectl shouldn't report a "failure" if an exact entity already exist

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1119]
**Describe the bug**
When registering an entity, flyteadmin reports failure if an entity already exist... but it does so with a specific error code so that clients can know to ignore it... flytectl seem to still report a failure:

 -------------------------------------------------------- -------- -------------------------------------------------------------- 
| _pb/7_k8s_spark.pyspark_pi.my_spark_3.pb               | Failed | Error registering file due to rpc error: code =              |
|                                                        |        | AlreadyExists desc = identical launch plan already           |
|                                                        |        | exists with id resource_type:LAUNCH_PLAN                     |
|                                                        |        | project:"flytesnacks" domain:"development"                   |
|                                                        |        | name:"k8s_spark.pyspark_pi.my_spark" version:"v1"            |
 -------------------------------------------------------- -------- -------------------------------------------------------------- 

Note that this is different from entity exist with a different structure error..

**Expected behavior**
Should not be considered an error or at least should indicate that it's ignored...

**Comment by kumare3** [comment]
@EngHabu i think this has been resolved, what version of flytectl are you using?

**Comment by EngHabu** [comment]
True
