### ISSUE TITLE
[BUG] flytectl failing to parse config file should be a fatal error

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1120]
**Describe the bug**
`flytectl register files -c ~/.flyte/config.yaml -p flytesnacks -d development _pb/*`
I think the file is valid but I'm seeing:
| /Users/haythamabuelfutuh/.flyte/config.yaml            | Failed | Error unmarshalling file due to failed unmarshalling         |
|                                                        |        | file /Users/haythamabuelfutuh/.flyte/config.yaml             |

However, it seems to have ignored the error and kept going...

**Expected behavior**
It should fail immediately and not attempt to proceed further...

**Comment by pmahindrakar-oss** [comment]
Hi @EngHabu , the -c option is not the config file option but the short command for --continueOnError and hence you saw the behavior.Not sure why the unmarshal failed though. Can you provide the file contents itself .

@evalsocket is adding a fix to correctly use the -c flag which would be used for config file.
Also @evalsocket lets remove the short flag options from register which have been manually been added (flytestdlib pflag generator currently doesn't generate short flags) and update the docs

**Comment by evalsocket** [comment]
@pmahindrakar-oss done https://github.com/flyteorg/flytectl/pull/91

**Comment by pmahindrakar-oss** [comment]
Thanks @evalsocket for taking care of this. And also the unmarshalling error is due to ~/.flyte/config.yaml being interpreted as input file for registering which needs to be task, workflow or launchplan pb.

**Comment by pmahindrakar-oss** [comment]
This has been fixed.
