### ISSUE TITLE
[Core Feature] Introduce Array Nodes

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#1131]
**Motivation: Why do you think this is important?**
Array tasks currently intermingle array task and child task definitions in the task template. This is messy and leads to shared task template values being re-used/interpreted differently.

**Goal: What should the final outcome look like, ideally?**
Array specification should be encapsulated as a new [Node Target ](https://github.com/flyteorg/flyteidl/blob/9d34056ef0dde9247ebce31e863961a06c97b440/protos/flyteidl/core/workflow.proto#L118)type.

**Describe alternatives you've considered**
Continuing to use the task template to specify array task and child task behavior.

**[Optional] Propose: Link/Inline OR Additional context**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Comment by cosmicBboy** [comment]
@hamersaw to write an RFC for this

**Comment by hamersaw** [comment]
`ArrayNode` execution of maptasks is now available as an experimental feature with https://github.com/flyteorg/flytepropeller/pull/550 and https://github.com/flyteorg/flytekit/pull/1640.
