### ISSUE TITLE
[Docs] Getting started hello_world.py missing

### ISSUE THREAD

**Issue by kevbutler** [flyteorg/flyte#1133]
I'm trying to follow the Getting Started documentations (https://docs.flyte.org/en/latest/getting_started.html) which instructs me to use `cookbook/core/basic/hello_world.py` from flytesnacks. This file does not exist, and I cannot find anything similar in a different directory.

**Comment by kumare3** [comment]
uhho, this is absolutely right. We have been restructuring the docs, I think the restructure got released sooner. Fixing it right away. So sorry about that
cc @samhita-alla  / @cosmicBboy / @SandraGH5

**Comment by kumare3** [comment]
Undeleting the file:
https://github.com/flyteorg/flytesnacks/pull/287
And then fixing getting started
https://github.com/flyteorg/flyte/pull/1134

**Comment by kumare3** [comment]
This is resolved now. @kevbutler  thank you for the issue and we are extremely sorry for the troubles
