### ISSUE TITLE
Update flytesnacks workflow and cluster deployment pages

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#1137]
The content in the [cluster deployment](https://docs.flyte.org/projects/cookbook/en/latest/auto/deployment/cluster/index.html) page should be moved to [workflow deployment](https://docs.flyte.org/projects/cookbook/en/latest/auto/deployment/workflow/index.html) and new copy should be added to the cluster deployment page

**Comment by EngHabu** [comment]
These two links no longer point to a valid page. Mind updating and clarifying what needs to happen here? @cosmicBboy

**Comment by cosmicBboy** [comment]
@EngHabu I think this issue is now defunct since our documentation sprint
