### ISSUE TITLE
[Core Feature] Implement named workflow outputs

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#1139]
**Motivation: Why do you think this is important?**
It should be straightforward to use a NamedTuple to implement named workflow outputs. This is useful for workflow understanding, chaining workflow executions and eventually for searchability.

**Goal: What should the final outcome look like, ideally?**
Users should be able to name workflow outputs.

**Describe alternatives you've considered**
Leaving as/is

**[Optional] Propose: Link/Inline OR Additional context**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Comment by kumare3** [comment]
I tested this in the serialization and i think Flytekit is doing the right things. Here are the examples
```python
    @task
    def t1() -> str:
        return "Hello"

    @workflow
    def wf() -> typing.NamedTuple("OP", a=str):
        return t1()

    wf_spec = get_serializable(OrderedDict(), serialization_settings, wf)
    assert len(wf_spec.template.interface.outputs) == 1
    assert list(wf_spec.template.interface.outputs.keys()) == ["a"]
```
``` python
    @task
    def t1() -> str:
        return "Hello"

    @workflow
    def wf() -> typing.NamedTuple("OP", a=str, b=str):
        return t1(), t1()

    wf_spec = get_serializable(OrderedDict(), serialization_settings, wf)
    assert len(wf_spec.template.interface.outputs) == 2
    assert list(wf_spec.template.interface.outputs.keys()) == ["a", "b"]
```
