### ISSUE TITLE
[BUG] FlyteAdmin config should default to not using signed urls

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#1148]
**Describe the bug**
GetExecutionData calls are moving to return inputs & outputs inline rather than passing a signed url. For ease of deployment, FlyteAdmin should default to not even returning signed urls.

**Expected behavior**
Straightforward deployment of Flyte lets users see inputs and outputs in the console with finagling configs/debugging signed urls.

**[Optional] Additional context**
***To Reproduce***
1. 
2. 

***Screenshots***

**Comment by sbrunk** [comment]
Related to this issue and flyteorg/flyteadmin#207, we also set this in the default Helm values. Is it still needed for a sandbox deployment with minio?
https://github.com/flyteorg/flyte/blob/06b2e2cb226b8e8a9e2ce37d0377240b6051536a/helm/values.yaml#L634-L639

**Comment by katrogan** [comment]
@sbrunk we should be able to remove it after the next flyte release

**Comment by kumare3** [comment]
@sbrunk fair point- I think the UI was using it. If not we can remove it
