### ISSUE TITLE
TFOperator support in FlytePlugins

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#115]
TL;DR
Add support for new "tensorflow" task type, that uses TFOperator under the hood. 

Summary:
Flyte allows orchestrating across different orchestrators. Though a simple TF job could be python code, using TFOperator allows other benefits. Namely Tensorboard and ability to run distributed tf jobs.

Operator to use:
https://github.com/kubeflow/tf-operator

Components:

- [ ] Golang Flyteplugins client for TFOperator
- [ ] Protobuf schema for operator metadata
- [ ] Input / Output unmarshalling
- [ ] Python flytekit task definition for Tensorflow jobs

**Comment by kumare3** [comment]
cc @swiftdiaries is interested in doing this
https://github.com/swiftdiaries

**Comment by swiftdiaries** [comment]
Ack :) I'll start work on this next week

**Comment by kumare3** [comment]
@igorvalko recently contributed pytorch-operator plugin for Flyte. The issue is https://github.com/lyft/flyte/issues/338

**Comment by kumare3** [comment]
I have added all of his PRs to the issue - https://github.com/lyft/flyte/issues/338#issuecomment-645060821

**Comment by kumare3** [comment]
https://github.com/pingsutw has volunteered to help with this

**Comment by kumare3** [comment]
Work in progress at - https://github.com/flyteorg/kfplugins

**Comment by kumare3** [comment]
@pingsutw / @EngHabu please help me close this issue. I think we should also add documentation to flytecookbook once the code is ready

**Comment by pingsutw** [comment]
These issues are almost done, so I'm going to close it.
Thank you everyone for the help.

**Comment by kumare3** [comment]
@pingsutw i think let's close the pr before closing the issue. That way we can ensure that the PR doesn't fall through the cracks
