### ISSUE TITLE
[Flytectl Feature]Flytectl can provide a encoded link to hosted graphviz viewer

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1150]
**Describe the feature/command for flytectl**
Flytectl is working on supporting visualization of Flyte Workflows using the Graphviz format. We have decided not to use the embedded graphviz library as it has various c compilation requirements and may result in a brittle flytectl. Our aim is to keep flytectl as stable and as portable as we can. 
But, to support visualization we have decided to use the `--output "dot"` mode, which can output a graphviz `.dot` file.

We can further enhance this and add an additional mode `--output "dot-url"`  which can output a link to a hosted graphviz renderer like https://dreampuf.github.io/GraphvizOnline/

**Provide a possible output or ux example**
```
$ flytectl get workflows -p flytesnacks -d development core.flyte_basics.hello_world --latest -o dot
digraph {
...
}

$ flytectl get workflows -p flytesnacks -d development core.flyte_basics.hello_world --latest -o dot-url
```
https://dreampuf.github.io/GraphvizOnline/#digraph%20G%20%7B%0A%0A%20%20subgraph%20cluster_0%20%7B%0A%20%20%20%20style%3Dfilled%3B%0A%20%20%20%20color%3Dlightgrey%3B%0A%20%20%20%20node%20%5Bstyle%3Dfilled%2Ccolor%3Dwhite%5D%3B%0A%20%20%20%20a0%20-%3E%20a1%20-%3E%20a2%20-%3E%20a3%3B%0A%20%20%20%20label%20%3D%20%22process%20%231%22%3B%0A%20%20%7D%0A%0A%20%20subgraph%20cluster_1%20%7B%0A%20%20%20%20node%20%5Bstyle%3Dfilled%5D%3B%0A%20%20%20%20b0%20-%3E%20b1%20-%3E%20b2%20-%3E%20b3%3B%0A%20%20%20%20label%20%3D%20%22process%20%232%22%3B%0A%20%20%20%20color%3Dblue%0A%20%20%7D%0A%20%20start%20-%3E%20a0%3B%0A%20%20start%20-%3E%20b0%3B%0A%20%20a1%20-%3E%20b3%3B%0A%20%20b2%20-%3E%20a3%3B%0A%20%20a3%20-%3E%20a0%3B%0A%20%20a3%20-%3E%20end%3B%0A%20%20b3%20-%3E%20end%3B%0A%0A%20%20start%20%5Bshape%3DMdiamond%5D%3B%0A%20%20end%20%5Bshape%3DMsquare%5D%3B%0A%7D

**Comment by EngHabu** [comment]
btw, I forked and deployed that to https://graph.flyte.org
