### ISSUE TITLE
[BUG][Flytekit] No NamedTuple attribute '_field_types' in Python 3.9

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#1166]
**Describe the bug**
The test `test_named_tuple` in `tests/flytekit/unit/core/test_type_engine.py` is resulting in an error: `AttributeError: type object 'Outputs' has no attribute '_field_types'`. The issue is, there's no `_field_types` attribute in Python 3.9; will have to replace it with `__annotations__`.

**Expected behavior**
No error should pop up.

***To Reproduce***
Fetch `_field_types` of a NamedTuple.

**Comment by samhita-alla** [comment]
https://github.com/flyteorg/flytekit/blob/f31048b8abb2ca54cbc567fb6e5002d609403199/flytekit/core/interface.py#L246 has to be modified as well.

**Comment by kumare3** [comment]
This has been fixed.
