### ISSUE TITLE
[DataCatalog] Implement Tag Stealing

### ISSUE THREAD

**Issue by chanadian** [flyteorg/flyte#118]
Implement functionality in `AddTag` to re-assign the tag if it is currently being used. It would examine if there is an existing artifact that is tagged and assign to the new artifact in a transaction.

**Comment by kumare3** [comment]
Important thing to note is that this becomes a transactional call. @chanadian can we please get a more descriptive post here, for example that explains the usecase and if the design proposal is around, can you please open it up or add the relevant excerpts here?

**Comment by chanadian** [comment]
Currently Flyte Caching is immutable, meaning once you cache an execution we cannot change that entry. In the future, Flyte will want to have the capability to clear/change the cache without going through and updating the `cache_version`. For example when:
- the first execution of the execution produced the incorrect result because it had a bug
- the underlying data of a blob was corrupt producing an incorrect result that was cached
- a user wants to manually make the cache entry point to another execution's results
- the user just wants to reset the cache

That means in DataCatalog we need a way to reassign the tag to a different artifact. This can be done as a transaction in the database to:
1. search for the tag pointing to the artifact
2. remove that row from the database (can be a soft delete)
3. add the new row or resurrect a soft deleted row
