### ISSUE TITLE
Register kubectl-flyte in Krew

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#121]
Krew is Kubectl plugin management system
https://github.com/kubernetes-sigs/krew-index/blob/master/plugins.md

We should deliver kubectl-flyte through Krew

**Comment by evalsocket** [comment]
@kumare3 I have idea about krew. can this assigned to me ?

**Comment by kumare3** [comment]
@evalsocket absolutely. Also check my previous comment, we can use the slack channel to get faster comms if interested

**Comment by kumare3** [comment]
@evalsocket kubectl-flyte is part of flytepropeller. I think the entire cmdline for flytepropeller needs a little more TLC, let me know if you want to improve it.

**Comment by evalsocket** [comment]
@kumare3  I am interested? I didn't find the link for joining slack ?

**Comment by kumare3** [comment]
@evalsocket yes we already have an issue for that. We have done it for flytestdlib. The aim is to do it for most of the repos - https://github.com/lyft/flytestdlib (where we have binaries)
