### ISSUE TITLE
[UI Feature] Enum type support in Launch form

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1217]
**Motivation: Why do you think this is important?**
Related to https://github.com/flyteorg/flyte/issues/590
There is currently no way to launch a Workflow / Task that accepts an enum type as an input from the Flyteconsole.

**Goal: What should the final outcome look like, ideally?**
Users should be able to launch workflows / tasks that accept an Enum type. Enum type is a simple list of string values, with the first one being default. The UX can be a simple drop down

**Example workflow in FlyteSnacks** https://github.com/flyteorg/flytesnacks/blob/master/cookbook/core/type_system/enums.py

**[Optional] Propose: Link/Inline OR Additional context AND/OR Mock ideas**
A Simple dropdown list 
![Screen Shot 2021-07-07 at 12 11 37 PM](https://user-images.githubusercontent.com/16888709/124815911-b1343880-df1c-11eb-8bf5-b7a1ebf7b7da.png)

**Comment by jsonporter** [comment]
Support for this feature has been merged to master and will be included in the next release.

https://github.com/flyteorg/flyteconsole/pull/178
