### ISSUE TITLE
[BUG] Fetching data on start-node throws an exception 

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#1221]
**Describe the bug**

GetNodeExecutionData on start-node throws this error

```
Error: rpc error: code = Internal desc = failed to get object size for s3://my-s3-bucket/metadata/propeller/flytesnacks-development-f36591c12455b43dc81c/start-node/data/inputs.pb with NotFound: Not Found
	status code: 404, request id: 168FCC4219C36810, host id: 
```

There are no inputs but on this path 
http://localhost:30084/minio/my-s3-bucket/metadata/propeller/flytesnacks-development-f36591c12455b43dc81c/start-node/data/0/output.pb exists

This is not the case with any of the other nodes in the execution
**Expected behavior**

**[Optional] Additional context**
***To Reproduce***
1. Create any execution 
2. Call GetNodeExecutionData on the start-node

***Screenshots***

**Comment by pmahindrakar-oss** [comment]
cc : @kumare3 @katrogan

**Comment by kumare3** [comment]
@pmahindrakar-oss i dont know if you should fetch data for start node, but I do agree if there is an event for it, we should probably be smarter in flyteadmin

**Comment by pmahindrakar-oss** [comment]
@kumare3 The api should behave in a graceful manner here if it's not supported.

I have to circumvent by doing check if it's start-node in flytectl code to avoid this issue.Same solution I have noticed in flytecli.

Also the url which admin is trying to get data from is incorrect .
so we should fix both
- having no url in start node if we can't call get data on it
- also the api should block it at initial level itself
