### ISSUE TITLE
[Housekeeping] Modularize Flyte Helm Chart 

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1228]
**Describe the Issue**
The [Flyte Helm Chart](https://artifacthub.io/packages/helm/flyte/flyte) references 14 different images, only 5 of which are maintained by the Flyte team. I think it might be better to break it down into:
1. A Core helm chart that deploys flyte (FlyteAdmin, FlytePropeller, DataCatalog & FlyteConsole) only...
1. A Deployment helm chart that depends on that ^ plus other dependencies' helm charts (e.g. [contour](https://artifacthub.io/packages/helm/bitnami/contour), [minio](https://artifacthub.io/packages/helm/bitnami/minio), [postgres](https://artifacthub.io/packages/helm/nicholaswilde/postgres), ...)
   and if a dependency doesn't have a helm chart, it's ok to include its manifests like we do today...

**Comment by EngHabu** [comment]
I know you've a lot on your plate now. Is this something you can take on, @evalsocket?

**Comment by evalsocket** [comment]
As per discussion with @EngHabu on call. 

Action Items -

- [ ] Change Helm chart dir from `helm` to `charts/flyte`
- [ ] Use current helm charts without any change 
- [ ] Create a new helm chart (flyte-core). It only has flyte component. 
- [ ] Create a documentation for installing operators like a spark, PyTorch, etc (Each section should explain the process of operator installation and also describe the change in `value.yaml` of the helm).  Users can use different processes for installing these component 
- [ ] Create a documentation  for installing ingress (start with aws/Nginx/contour)
- [ ] Replace Sandbox docker image with helm deployment
