### ISSUE TITLE
[Flytectl Feature] Upgrade flytectl 

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#1233]
**Describe the feature/command for flytectl**
Current way of flytectl upgrade is manual and the user needs to do a brew upgrade flytectl if he is mac user 
or perform installer again and copy the binary 
`curl -s https://raw.githubusercontent.com/lyft/flytectl/master/install.sh | bash`

flytectl version command already recommends whats the latest version . 
eg :

```
flytectl version
A newer version of flytectl is available [v0.2.11] Please upgrade using - https://docs.flyte.org/projects/flytectl/en/latest/index.html
{
  "App": "flytectl",
  "Build": "baccce4",
  "Version": "v0.1.2-76-gbaccce4",
  "BuildTime": "2021-07-13 09:20:57.287839 +0530 IST m=+0.015317172"
}{
  "App": "controlPlane",
  "Build": "821d232",
  "Version": "v0.6.0",
  "BuildTime": "2021-07-02 11:31:27.4897923 +0000 UTC m=+0.042514701"
}
```

We should also support upgrade through flytectl 
eg : one suggestion is to introduce another flytectl upgrade command

https://equinox.io/ has a cool feature which supports self upgrading cli across various distribution channels.

This ticket is to explore the various aspects of providing a seamless upgrade  experience to user and implement it.

**Provide a possible output or ux example**
A clear and concise description of what you want to happen or achieve.

**Comment by pmahindrakar-oss** [comment]
cc : @EngHabu @evalsocket @kumare3

**Comment by evalsocket** [comment]
@pmahindrakar-oss @kumare3 @EngHabu I like the approach of GitHub cli.....They print the upgrade message after each command if you are using an older binary. 

Message:
```
A new release of flytectl is available: 1.11.0 → v1.13.1
To upgrade, run: brew update && brew upgrade flytectl
https://github.com/flyteorg/flytectl/releases/tag/v1.13.1
```

**Comment by pmahindrakar-oss** [comment]
This looks good . @evalsocket can we also check what it displays for linux and windows

**Comment by evalsocket** [comment]
@pmahindrakar-oss https://equinox.io/blog/shutting-down
