### ISSUE TITLE
[Docs] ... Flow chart that helps you decide when to write a backend / flytekit plugin?

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#1246]
**Describe the documentation update**
`Flow chart that helps you decide when to write a backend / flytekit plugin?` ... is missing from https://docs.flyte.org/projects/cookbook/en/latest/auto/core/extend_flyte/custom_task_plugin.html#writing-your-own-flytekit-task-plugins

Am told it exists (somewhere).  Get it on the website!

**Comment by SandraGH5** [comment]
Thank you for bringing this to our attention @brucearctor.

The flowchart has been added to [Extending Flyte](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/extend_flyte/index.html#sphx-glr-auto-core-extend-flyte).
