### ISSUE TITLE
Support complex CRD sharding

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#125]
To be able to shard workflows to different propellers in different deployments, we need a more generic way to shard CRDs. We think this can be a generic enough binary that belongs in stdlib.

The basic premise is:
- This tool will monitor all resources of kind X (e.g. FlyteWorkflow) that are not yet "sharded"
- It applies some logic based on the TypeMeta and ObjectMeta fields only to figure out the ShardName and add it as a label,
- The controller for that resource (e.g. Propeller), can be configured to serve certain shards only (only one shard per instance).

As a more concrete example:
- The config for this tool is:
    - Namespace: *-development -> Shard1
    - Namespace: *-staging -> Shard2
    - Namespace: *-production -> Shard2
This translates to: 
    - All workflows in development domain will go to shard1, all workflows for staging and prod will got to shard 2
- We will have two propeller instances; one to server Shard1 and another to serve Shard2

**Comment by kumare3** [comment]
I think we should also have consistent hashing support in this, which will allow it create a constant size hash ring (or buckets)

**Comment by kumare3** [comment]
We will be writing a spec for this and we will support basic sharding primitives in next release
