### ISSUE TITLE
[Housekeeping] Copilot should be allowed to download unlimited data - if needed

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#1251]
**Describe the Issue**
The issue is reported in the slack channel by Bernhard Stadlbauer.
```
Hi!
We're using a ContainerTask to run some of our native things. Some of the inputs that the container receives are ~500mb. When running the Task, the flyte-copilot-downloader container in the pod fails with:
{"json":{},"level":"error","msg":"Failed to persist [<INPUT_NAME>], err failed to read Blob from storage: [LIMIT_EXCEEDED] limit exceeded. 479mb \u003e 2mb.","ts":"2021-07-16T09:06:19Z"}
When this happens, the Task does not fail directly (which would be nice), but only when we try to open the input file in the actual container on the pod.
Is there a way to increase this limit?

```

Fix:  Copilot should be allowed to download as much as needed. We don't need any limit.

**What if we do not do this?**
Short description of potential consequences

***Related component***
Either Specific / all

**Comment by kumare3** [comment]
This will need changes in flytestdlib to support default limits of `0` which would mean unlimited.
https://github.com/flyteorg/flytestdlib/blob/master/storage/config.go#L103
