### ISSUE TITLE
[Housekeeping] Update Code of conduct for Flyte project 

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1252]
**Describe the Issue**
Code of conduct for Flyte should follow Linux foundation guidelines.
https://github.com/flyteorg/flyte/blob/master/CODE_OF_CONDUCT.md
Also this needs to be updated in flytekit-java.

**What if we do not do this?**
The code of conduct is currently not appropriate

***Related component***
Either Specific / all

**Comment by kumare3** [comment]
cc @samhita-alla can you please take care of this one?

**Comment by brucearctor** [comment]
this probably also needs to be addressed in with most of the repos in flyteorg?  Ex: https://github.com/flyteorg/flyteadmin/blob/master/CODE_OF_CONDUCT.md

**Comment by samhita-alla** [comment]
> cc @samhita-alla can you please take care of this one?

Sure, Ketan. 
@brucearctor: I'll update it in the other repos as well. Thank you!

**Comment by samhita-alla** [comment]
@kumare3, I haven't updated the code of conduct in flytekit-java as they've Spotify's code of conduct. I'm not sure if we want to modify it.

**Comment by brucearctor** [comment]
Imagining all projects in github.com/Flyteorg need to say they follow LF AI's Code of Conduct?  The specifics of Spotify/other policy and wording isn't troubling to me, but highlighting what I imagine is expected from projects within the foundation (and probably worth confirming)....

**Comment by kumare3** [comment]
@samhita-alla yes we should be updating the code of conduct in flytekit-java. So flytekit-java is now part of flyteorg, and no longer a spotify only project. They have donated it to LF AI (pending announcement)  - cc @kanterov
