### ISSUE TITLE
[Docs] Sandbox documentation should provide credentials for Minio

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1264]
**Describe the documentation update**
Minio is used as the s3 replacement in Sandbox and explosed on port
http://localhost:30084/. The username: `minio` and password: `miniostorage` are used. We should document this, so that users can easily access, get the UI and test.

Moreover, we should also document `postgres` and `redis` passwords./

**Comment by evalsocket** [comment]
@kumare3 Where do we want the documentation ? In getting started guide or sandbox documnetation
