### ISSUE TITLE
Enhancement Proposal: Add FlyteHub to Flyte Sandbox Deployment

### ISSUE THREAD

**Issue by jonathanburns** [flyteorg/flyte#127]
---
title: Add FlyteHub to Flyte Sandbox Deployment
authors:
  - "@jonathanburns"
editor: "@jonathanburns"
creation-date: 2019-11-24
last-updated: 2019-11-24
status: implementable
---

# Add FlyteHub to Flyte Sandbox Deployment

## Table of Contents

- [Summary](#summary)
- [Motivation](#motivation)
  - [Goals](#goals)
  - [Non-Goals](#non-goals)
- [Proposal](#proposal)
- [References](#references)

## Summary

The Flyte "getting started" guide currently instructs users to pull a docker image and register Tasks, Workflows, and Launch Plans using the Flyte SDK. The bash commands are confusing to new users and they don't work on most k8s deployment variants. This could discourage adoption for new users.

FlyteHub is a central public registry of Flyte tasks, workflows, and launch plans. It was built to enable simple importing of public Flyte workflows directly from the Flyte web interface.

Allowing users to import workflows through the UI makes running your first workflow much easier. It also provides useful workflows "out-of-the-box" with no coding, and promotes community collaboration, providing a central repository for sharing "open-source" workflows.    

This doc proposes adding FlyteHub to Flyte sandbox deployment.

## Motivation

* Make getting started in Flyte easier.
* Make getting started docs work on all common k8s deployments.
* Provide useful "out-of-the-box" workflows.
* Enable community task & workflow collaboration.
 
### Goals

* Improve user experience.
* Increase collaboration.
* Build community.

### Non-Goals

* Make workflows portable to every possible Flyte configuration.

_Certain configs, such as the storage endpoint, currently need to be hard-coded inside the docker image for a task. There is work on a separate proposal to make workflows more portable across Flyte configurations. When Flyte supports it, new portable workflows will be uploaded to the public registry._ 

## Proposal

Provide access to the FlyteHub public workflow registry in the Flyte sandbox deployment.

When a user installs Flyte and visits the web interface for the first time, they'll have access to "open-source" workflows. Users can "click-to-import" these workflows and execute them without writing any code.

Upon "Import", the workflows will be cloned from the public registry to their local Flyte deployment. This cloning ensures that Flyte does not depend on the registry at runtime to execute workflows.

This proposal fixes a few issues:

* The current "getting started" guide doesn't work if docker is not installed on your local machine.
* The current "getting started" guide doesn't work if your kubernetes cluster is anything other than localhost (minikube, cloud deployments, on-prem cluster, etc).

This proposal also makes Flyte much easier to digest for a first-time user. The improved "getting started" flow can be seen [here](https://flytehub.org/installflyte). Learning how to run workflows without worrying about development tools provides gentle introduction to Flyte.

Having a central task/workflow repository also bolsters the Flyte community by encouraging developers to collaborate on workflows.

## Required Changes

Importing workflows directly in the web interface requires changes to the Flyte console. These changes have already been developed, but will need to be merged into the lyft/flyteconsole codebase.

Publishing public workflows requires authentication to the public registry. Support for that authentication is in PR here: https://github.com/lyft/flytekit/pull/56/files

## References

* [FlyteHub](https://flytehub.org)

**Comment by kumare3** [comment]
This is amazing @jonathanburns, but there are a few problems. I am +1 releasing this as an alpha feature. There are some problems that I have not really thought about like versioning etc. But, I do agree there is some learning that we could do by making this as an alpha feature. Lets tag this as part of the next release.


+1

**Comment by jonathanburns** [comment]
Sounds good. I'll submit the console PR which allows this.

Also happy to talk about the versioning concerns.
