### ISSUE TITLE
[Docs] projectcontour namespace needed in docs for quickstart

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#1270]
**Describe the documentation update**
Following instructions in https://docs.flyte.org/en/latest/deployment/sandbox.html

`kubectl port-forward svc/envoy 30081:80`

needs to be 
`kubectl port-forward svc/envoy 30081:80 -n projectcontour`

Given envoy is deployed into the projectcontour namespace

**Comment by kumare3** [comment]
This has been merged
