### ISSUE TITLE
[Housekeeping] Deprecated API version for ClusterRoleBinding in sandbox deployment ( https://raw.githubusercontent.com/flyteorg/flyte/master/deployment/sandbox/flyte_generated.yaml )

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#1272]
**Describe the bug**
````Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding``` is pointed out when running instructions found https://docs.flyte.org/en/latest/deployment/sandbox.html due to version of K8s cluster

**Expected behavior**
Current version of K8s is 1.21 -- we should upgrade that to refer to rbac.authorization.k8s.io/v1  by v.1.22+ release

**Comment by askalik** [comment]
@brucearctor  I believe I have this one completed on #1720 

Question,  should this be updated globally across the repo?

**Comment by evalsocket** [comment]
@brucearctor current helm chart handles the depreciation api, I am closing this for now.

**Comment by brucearctor** [comment]
👍
