### ISSUE TITLE
Flytekit MultipartBlob/CSV should support single files as well (degenerate case)

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#128]
Currently multipart CSV or Blob only support uploading local directories
https://github.com/lyft/flytekit/blob/master/flytekit/common/types/impl/blobs.py#L47-L53

If a director is not given it assumes the string is a remote path. This is a problem.
Ideally if the string is a file then we should upload the single file. Just adding a file check is not enough as upload() actually needs a directory

**Comment by matthewphsmith** [comment]
This is by design so I wouldn't classify this as a bug. Happy to collect interest on it as an enhancement after considering potential repercussions.

**Comment by kumare3** [comment]
Resolving this, as in the new flytekit api, this has been resolved.
