### ISSUE TITLE
[Docs] The search results are cluttering in  the left panel probably due to size restrictions

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#1291]
**Describe the documentation update**
Search keyword : filter

<img width="1274" alt="Screenshot 2021-07-27 at 4 32 00 PM" src="https://user-images.githubusercontent.com/77798312/127143538-6ec16b86-cc3f-4066-bd48-c5eb798ae880.png">

**Comment by samhita-alla** [comment]
@pmahindrakar-oss: Niels mistakenly deleted the CSS. https://github.com/flyteorg/furo/commit/f60e59c218be6a4c30ebe3bb6b325d3fc6e1ea5f. I've pushed the change already. We'll have to rebuild the docs.

**Comment by pmahindrakar-oss** [comment]
Thanks @samhita-alla for checking on this .You can close this one once it's merged

**Comment by SandraGH5** [comment]
@samhita-alla this can be closed, right?
