### ISSUE TITLE
[UI Feature] Add recover option to console

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#1293]
**Motivation: Why do you think this is important?**
Similar to relaunch, it might be useful to trigger a recovery execution from the console directly.

**Goal: What should the final outcome look like, ideally?**
Users should be able to trigger a recovery execution which calls this [API service method](https://github.com/flyteorg/flyteidl/blob/2537302a1c19f17a0a2834fb9db1d38a4a6eeeba/protos/flyteidl/service/admin.proto#L256). This should behave similarly to "Relaunch" which itself calls the Relaunch API.

**[Optional] Propose: Link/Inline OR Additional context AND/OR Mock ideas**
For more background, see https://github.com/flyteorg/flyte/issues/1151

**Comment by katrogan** [comment]
cc @jsonporter @Pianist038801 this is pretty low priority but wanted to make sure to keep track of it

**Comment by jsonporter** [comment]
Finished and added to milestones.
