### ISSUE TITLE
[BUG] Dynamic tasks fail if function name is too long

### ISSUE THREAD

**Issue by kimoktm** [flyteorg/flyte#1306]
**Describe the bug**
Dynamic tasks workflow fails, raising `malformed dynamic workflow` error when the dynamic task function name is 52 characters or longer.

Raised error:
```python
[User] malformed dynamic workflow, caused by: Collected Errors: 3
	Error 0: Code: NodeReferenceNotFound, Node Id: f1waozpy, Description: Referenced node [f1waozpy] not found.
	Error 1: Code: NodeReferenceNotFound, Node Id: fequ45eq, Description: Referenced node [fequ45eq] not found.
	Error 2: Code: NodeReferenceNotFound, Node Id: fzzt6uqq, Description: Referenced node [fzzt6uqq] not found.
```

**Expected behavior**
The dynamic workflow should work even if function names are longer than 52 characters

**Additional context**
***To Reproduce***
Here is a quick snippet to reproduce the issue:
```python
@flytekit.task
def count_length(a: Dict[str, str]) -> FlyteFile:
    ctx = flytekit.current_context()
    working_dir = ctx.working_directory
    fname = os.path.join(working_dir, a["name"])
    fname = fname + ".json"
    ctx.logging.warning(f"Working dir is: {working_dir} Filename is: {fname}")
    with open(fname, "w") as fh:
        fh.write(f"{len(a['role'])}\n")

    return fname


@flytekit.workflow
def wf_demo(wf_in1: Dict[str, str]) -> FlyteFile:
    return count_length(a=wf_in1)


wf_default = flytekit.LaunchPlan.get_or_create(wf_demo)


@flytekit.dynamic
def abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz(data: str) -> List[FlyteFile]:
    ctx = flytekit.current_context()
    working_dir = ctx.working_directory
    file_path = os.path.join(working_dir, "file")

    with open(file_path, "w") as data_file:
        data_file.write(data.replace(".", "\n"))

    result_files: List[FlyteFile] = []
    with open(file_path) as f:
        reader = DictReader(f, delimiter=",")
        for row in reader:
            result_file = wf_default(wf_in1=row)
            result_files.append(result_file)
    return result_files


if __name__ == "__main__":
    data = "name,role.alice,sender.bob,receiver.eve,eavesdropper"
    out = abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz(data=data)
    print(out)
```

Renaming the dynamic task from `abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz` to `abc` or anything shorter than 52 characters will lead to a successful execution.

***Screenshots***
<img width="1621" alt="Screenshot 2021-08-03 at 12 33 52" src="https://user-images.githubusercontent.com/3511664/128008625-9b25cd2d-5d25-4727-82ea-647d55131463.png">

**Comment by kumare3** [comment]
@kimoktm thank you for the issue, we will definitely look into this soon, but as a work-around if you name the task something smaller does it work?
also cc @katrogan / @EngHabu

**Comment by kimoktm** [comment]
> @kimoktm thank you for the issue, we will definitely look into this soon, but as a work-around if you name the task something smaller does it work?
> also cc @katrogan / @EngHabu

Thanks for looking into it @kumare3!
Yes, renaming the task a shorter name works fine, so I'm not currently blocked

**Comment by kumare3** [comment]
@eapolinario my recent fix in progress might fix this issue as well. https://github.com/flyteorg/flytekit/pull/698
