### ISSUE TITLE
[BUG] FlyteConsole --> Login returns "Not found"

### ISSUE THREAD

**Issue by marcoskv** [flyteorg/flyte#1307]
**Describe the bug**
On FlyteConsole, once I click on Login, I receive a "Not found" error.

**Expected behavior**
I was expecting a form to log in with some credentials.

**[Optional] Additional context**
***To Reproduce***
1. Installed k3s on a Centos 7 VM (IP 192.168.60.5)
```
hostnamectl set-hostname flyte-dev
systemctl disable firewalld --now
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik --disable servicelb" sh
```

2. From the host, I installed flyte with
```
kubectl config set-context flyte
kubectl create -f https://raw.githubusercontent.com/flyteorg/flyte/master/deployment/sandbox/flyte_generated.yaml
```
3. Opened FlyteConsole (URL: http://192.168.60.5:30081/console/ ), click on Login redirects to `http://192.168.60.5:30081/login?redirect_url=http://192.168.60.5:30081/console/` and returns "Not found"

More info:

* Flyte looks good to me
```
$ kubectl get pods -A
NAMESPACE              NAME                                         READY   STATUS      RESTARTS   AGE
kube-system            metrics-server-86cbb8457f-4m4wr              1/1     Running     0          38m
kube-system            coredns-7448499f4d-vlsz8                     1/1     Running     0          38m
kube-system            local-path-provisioner-5ff76fc89d-b4zdx      1/1     Running     0          38m
flyte                  flyteconsole-66c5575f79-9n2hw                1/1     Running     0          37m
flyte                  postgres-6c64cd5c48-svljz                    1/1     Running     0          37m
kubernetes-dashboard   dashboard-metrics-scraper-856586f554-79gxf   1/1     Running     0          37m
projectcontour         contour-8579c7fd75-q8pqd                     1/1     Running     0          37m
projectcontour         contour-8579c7fd75-gxhwr                     1/1     Running     0          37m
flyte                  minio-8564dc858c-2w24w                       1/1     Running     0          37m
kubernetes-dashboard   kubernetes-dashboard-7685ffbdfc-wr784        1/1     Running     0          37m
flyte                  flytepropeller-76b94f8c6c-xbxhc              1/1     Running     0          37m
projectcontour         envoy-8qxtk                                  2/2     Running     0          37m
flyte                  flyteadmin-74c8498cd6-s8c48                  3/3     Running     0          37m
flyte                  flyte-pod-webhook-75dc55f774-lf898           1/1     Running     0          37m
flyte                  datacatalog-77d7b668b-rhvzd                  1/1     Running     0          37m
flyte                  syncresources-27133309-lrldt                 0/1     Completed   0          2m36s
flyte                  syncresources-27133310-42xz5                 0/1     Completed   0          96s
flyte                  syncresources-27133311-nzlxs                 0/1     Completed   0          36s
```

***Screenshots***

![Screenshot from 2021-08-03 15-54-59](https://user-images.githubusercontent.com/11202172/128027927-5b98306c-b1a8-40cf-9603-a2a7e8b2300b.png)

![Screenshot from 2021-08-03 15-55-22](https://user-images.githubusercontent.com/11202172/128027931-a0d64d7a-4dfb-421d-9589-c1645496f276.png)

**Comment by kumare3** [comment]
@marcoskv flyte does not ship with some basic auth today (maybe we should). It ships with full oauth2 support which you need to enable for your deployment. The guide for setting it up is available here - https://docs.flyte.org/en/latest/deployment/cluster_config/auth_setup.html#deployment-cluster-config-auth-setup

Thus Flyte will not have a login form, but just use your IDP, like google SSO etc

**Comment by marcoskv** [comment]
Many thanks for your quick reply!

In the [sandbox documentation](https://docs.flyte.org/en/latest/deployment/sandbox.html), this extra step was not clear. Will take a look at the authentication docs. Thanks
