### ISSUE TITLE
[BUG] flytekit no longer supports python 3.6 while it's not reached end of life yet

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1316]
**Describe the bug**
Python 3.6 end of life is set for [December, 23rd, 2021](https://endoflife.date/python). flytekit should continue to support 3.6 until then.

**Comment by kumare3** [comment]
I think the new annotations API does not work (well) for python 3.6. But yes for the legacy users, we can support python3.6. This is the pre-annotations api. cc @wild-endeavor
