### ISSUE TITLE
[BUG] Flyte sandbox: Back-off pulling image 

### ISSUE THREAD

**Issue by tekumara** [flyteorg/flyte#1319]
**Describe the bug**

Execution inside flyte sandbox fails with:

```
[1/1] currentAttempt done. Last Error: USER::containers with unready status: [fu29mt2yqe-n0-0]|Back-off pulling image "flytecookbook:pima_diabetes-ff4e179abe231d65fe06f24a181f96ad737d40ee"
```

***To Reproduce***

I'm following the [flytesnacks readme](https://github.com/flyteorg/flytesnacks):
```
git clone git@github.com:flyteorg/flytesnacks.git
flytectl sandbox start --source flytesnacks
cd flytesnacks 
SANDBOX=1 make -C cookbook/case_studies/ml_training/pima_diabetes register
flytectl get launchplan -p flytesnacks -d development pima_diabetes.diabetes.diabetes_xgboost_model --execFile exec.yaml
flytectl create execution --project flytesnacks --domain development --execFile exec.yaml
``` 

***Screenshots***

**Comment by evalsocket** [comment]
@tekumara Your image doesn't exist inside the  [sandbox cluster](https://docs.flyte.org/en/latest/deployment/sandbox.html#deployment-sandbox).   that's why you are getting the error image doesn't exist.  

You can check the docker image inside the container 
```bash
$ cd flytesnacks
$ make shell (Get shell of sandbox container)
$ docker images # You can also build image inside the container
$ make -C cookbook/case_studies/ml_training/pima_diabetes docker_build

$ #Alternative way to build docker image 
$ cd cookbook/case_studies/ml_training
$ flytectl sandbox exec -- docker build . --tag "myapp:v1" -f pima_diabetes/Dockerfile
```

If you didn't go through the getting started then please first try the [getting started](https://docs.flyte.org/en/latest/getting_started.html#gettingstarted-implement)

**Comment by tekumara** [comment]
Thanks @evalsocket if I run register using the sandbox shell it works, ie: 

```
git clone git@github.com:flyteorg/flytesnacks.git
flytectl sandbox start --source flytesnacks
cd flytesnacks

# enter sandbox container
make shell 
make -C cookbook/case_studies/ml_training/pima_diabetes register
exit

# execute from host
flytectl get launchplan -p flytesnacks -d development pima_diabetes.diabetes.diabetes_xgboost_model --execFile exec.yaml
flytectl create execution --project flytesnacks --domain development --execFile exec.yaml
```

Would you accept a flytesnacks PR to update the docs as above?

**Comment by kumare3** [comment]
@tekumara we always accept great Prs please do not hesitate to open one. What you suggest is interesting, we are thinking of further streamlining flytesnacks to match getting started

**Comment by evalsocket** [comment]
@tekumara thanks for the contribution. I am closing this issue for now
