### ISSUE TITLE
[Plugin][Pod] Support local execution of simple pod tasks

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1328]
**Why would this plugin be helpful to the Flyte community**
K8sPods are supported as a separate entity from regular tasks in Flyte. Pods allow developers to access raw K8s features and are useful for extending infrastructure from the user pov. In many cases users of Flyte are forced to use pod tasks, because container tasks do not expose things like affinity, node pools etc. This is by design to allow maximum portability and reduce assumptions for the task author. 

But, when users use pod tasks just to affinitize their workloads and not actually to run multiple containers, local execution can be extremely useful. Flytekit can allow local execution of Flyte pod tasks that do not use more than one container. In other cases it can continue to raise as error (current behavior)
This would make it simple for users to use pod tasks and test it locally.

**Type of Plugin**
- [ ] Python/Java interface only plugin
- [ ] Web Service (e.g. AWS Sagemaker, GCP DataFlow, Qubole etc...)
- [ ] Kubernetes Operator (e.g. TfOperator, SparkOperator, FlinkK8sOperator, etc...)
- [ ] Customized Plugin using native kubernetes constructs
- [x] Other

**Can you help us with the implementation?**
- [ ] Yes
- [ ] No

**Comment by wild-endeavor** [comment]
This was updated recently and new behavior should be sufficient https://github.com/flyteorg/flytekit/pull/852
