### ISSUE TITLE
[BUG] Tasks with no resource requests should default to platform defaults for both requests and limits

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1336]
**Describe the bug**
What I see is that when I launch a task that doesn't have requests nor limits, flyteadmin now applies the task_resources defaults to requests and limits to limits... Because of how resource allocation works in K8s, the schedulers waits for a node that has enough resources (factoring in overcommit ratios and all) to accommodate limits . I wonder if the right behavior is to use "defaults" in both requests and limits instead? and we use limits only to enforce the upper limit of user-provided resource requests and limits...

**Expected behavior**
task limits should also get set to platform defaults.

**Comment by anmyachev** [comment]
Hi @EngHabu!

The current behavior is not obvious to those who are just starting to learn Flyte. I didn't find any mention of this behavior in the documentation.

If [these limits](https://github.com/flyteorg/flyte/blob/cb382d0f85cc9e2dc52e6e96dd7a6ae79801eb39/deployment/sandbox/flyte_generated.yaml#L2199) do not affect the pod in which the task is running, can this field be removed from the config?
