### ISSUE TITLE
[Flytectl Feature] support local registry for sandbox

### ISSUE THREAD

**Issue by tekumara** [flyteorg/flyte#1338]
**Describe the feature/command for flytectl**

Any locally built images need to be created inside the sandbox. This means mounting the local directory at sandbox creation time, and entering the sandbox to build the image. The sandbox can only build images for the mounted directory (ie: repo) it was started with. To switch repos, a new sandbox needs to be created. Overall the process is a little unituitative and leads to scenarios like https://github.com/flyteorg/flyte/issues/1319

**Provide a possible output or ux example**

It might be a better UX to run a [local registry](https://docs.docker.com/registry/) that both the sandbox and host have access to. Images can then be pushed to the local registry and be accessed from the sandbox without mounting local source directories. This would also make it easier to move between source repos.

**Comment by hamersaw** [comment]
@eapolinario this is completed correct?

**Comment by eapolinario** [comment]
Correct, we ship sandbox now with a registry that persists across resets / updates.
