### ISSUE TITLE
[Core Feature] flytekit - option to disable logging input/output contents

### ISSUE THREAD

**Issue by tekumara** [flyteorg/flyte#1340]
Provide an option to disable the logging of the contents of inputs and outputs of tasks/workflows. 

**Motivation: Why do you think this is important?**

Inputs/outputs can include sensitive data, and also flood the logs when the inputs/outputs are large. This is particularly true of a large FlyteSchema/Dataframe.

**Comment by kumare3** [comment]
@tekumara where do we log the input/outputs, if we are doing it, this is probably a bug, i.e for debugging. Are you talking about in the UI?

**Comment by tekumara** [comment]
flytekit logs on stderr, which appear in the kubernetes logs, eg:

```
INFO:flytekit:Invoking aircraft.02_etl_flow.extract_reference_data with inputs: {}
{"asctime": "2021-08-15 10:01:18,154", "name": "flytekit", "levelname": "INFO", "message": "Task executed successfully in user level, outputs: OpenFlightsData(routes=[{'airline': 'C7', 'from': 'MAO', 'to': 'CIZ', 'codeshare': '', 'stops': '0', 'equipment': 'EMB'}, {'airline': '0B', 'from': 'BCM', 'to': 'BGY', 'codeshare': '', 'stops': '0', 'equipment': '735'}, ...
```

**Comment by kumare3** [comment]
ohh these are debugging logs, we are cleaning up the logs - cc @wild-endeavor. Thank you for the suggestion

**Comment by georgesnelling** [comment]
@wild-endeavor @eapolinario:  good issue to address together perhaps as a step to hand-off...

**Comment by wild-endeavor** [comment]
Should work alongside https://github.com/flyteorg/flyte/issues/1034

**Comment by pingsutw** [comment]
Should work alongside https://github.com/flyteorg/flytekit/pull/871
