### ISSUE TITLE
Add the ability to mark significance of an input parameter

### ISSUE THREAD

**Issue by honnix** [flyteorg/flyte#135]
To support the use case that when fetching result in datacatalog, only significant input parameters will be used to compute the hash.

This would work similar as https://github.com/spotify/luigi/blob/master/luigi/parameter.py#L142

**Comment by kumare3** [comment]
@honnix do you think this is a requirement? This breaks an intrinsic contract, that all input parameters affect the output of a task. Is that not true?

**Comment by honnix** [comment]
I cannot recall which specific use case I had in mind when creating this issue, but we do have many use cases that users would like to ignore a certain parameter. I will dig a bit more and come back.

**Comment by kumare3** [comment]
This is not supported in Flyte, as it is a fundamental change. Closing it
