### ISSUE TITLE
[Core Feature] [flytekit] Task configuration modification within dynamic tasks

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#1355]
**Motivation: Why do you think this is important?**
Allow a better interface to modify the definition of tasks within dynamic tasks.  See this [thread](https://flyte-org.slack.com/archives/CREL4QVAQ/p1628882234154200) for more information.

When users call tasks within a dynamic task, because the definition of those tasks is explicitly included in the [subworkflow returned](https://github.com/flyteorg/flyteidl/blob/master/protos/flyteidl/core/dynamic_job.proto#L28) (`DynamicJobSpec`s are basically subworkflow), those tasks can be modified without affecting Admin's version of the task.  This allows users to dynamically change the tasks being returned based on inputs at run time. 

**Goal: What should the final outcome look like, ideally?**
An elegant way to allow users to modify elements of tasks (including plugin tasks).

**Comment by kumare3** [comment]
Is this related to the new override system, just a simpler form? Cc @ByronHsu

**Comment by kumare3** [comment]
isnt this already supported with `with_overrides`?
