### ISSUE TITLE
[flytekit] pytest-flyte and integration test framework

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#1364]
**Motivation: Why do you think this is important?**
This issue should probably be a design doc instead of an issue, but let's start here.  We currently have a pytest [plugin](https://github.com/flyteorg/pytest-flyte) that is lightly used to do some integration [testing](https://github.com/flyteorg/flytekit/tree/master/tests/flytekit/integration) in flytekit.

There are many places where we could use something like this
* Users that want more confidence beyond unit tests that things will work when deployed.
* Integration testing flytekit changes using flytesnacks examples.
* Integration testing where multiple components are changing.

To do this...

**Comment by kumare3** [comment]
we now use single binary in ci

**Comment by EternalDeiwos** [comment]
@eapolinario @kumare3 it is not very clear how or if we should use pytest. Any chance you could give some pointers for this?

Also see flyteorg/pytest-flyte#17

**Comment by eapolinario** [comment]
@EternalDeiwos , `pytest-flyte` is no longer used. This was from a time when we were running integration tests using a different method. I'm going to make sure that project gets deprecated shortly.
