### ISSUE TITLE
[BUG] Pyflyte should complain about duplicate task name in serialize. 

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#1368]
**Describe the bug**
Example workflow :- https://github.com/flyteorg/flytesnacks/blob/73cfdfc2c4a97987ab873fbce592cebc3fc96f11/cookbook/integrations/kubernetes/pod/pod.py

Example workflow has two tasks with the duplicate name `my_pod_task`. It got serialize successfully but on the register, it got failed because of a duplicate name. 

**Expected behavior**
Pyflyte should complain about duplicate names in serialize.

**Comment by evalsocket** [comment]
CC: @kumare3  @wild-endeavor  @katrogan

**Comment by katrogan** [comment]
hey @evalsocket are you using pyflyte serialize or pyflyte package? I'm not sure how the former could always detect identical task names, but certainly makes sense that the latter should!

**Comment by evalsocket** [comment]
I tested it with the pyflyte package and serialize both. Same issue
