### ISSUE TITLE
[Housekeeping] Write a script to copy latest proto from flyteidl to flytekit-java 

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#1384]
**Describe the Issue**
Context:- https://flyte-org.slack.com/archives/CP2HDHKE1/p1629490579048600

Currently, we are moving the latest flyteidl proto in flytekit-java manually. Need an automated way like `update_boilerplate` in the makefile of flytekit-java. 

Solution:
- Add a new make target `update_flyteidl` in makefile(https://github.com/flyteorg/flytekit-java/blob/master/Makefile) 
- Write a shell script like https://github.com/flyteorg/flytekit-java/blob/master/boilerplate/update.sh for automation (It will  clone the flyteidl in temp dir and copy the latest proto(https://github.com/flyteorg/flyteidl/tree/master/protos/flyteidl) to flytekit-java(https://github.com/flyteorg/flytekit-java/tree/master/jflyte/src/main/proto)
- Write a GitHub workflow that will automate the process (example workflow https://github.com/flyteorg/flytekit-java/blob/master/.github/workflows/boilerplate-automation.yml)

**What if we do not do this?**
Someone has to manually update proto in each release,

***Related component***
flytekit-java

**Comment by rajatk-31** [comment]
I would like to work on this.

**Comment by evalsocket** [comment]
@rajatk-31 thanks for picking up this task
