### ISSUE TITLE
[UI Feature] TaskType is not correctly shown in the Executions View

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1393]
**Motivation: Why do you think this is important?**
When a TaskExecution is retrieved, it contains the TaskType for the execution. It seems the UI today, only shows some tasktypes - PythonTask, SubWorkflow, dynamic etc. But the task types are actually a free form string field and can be arbitrary

![Screen Shot 2021-08-30 at 10 20 15 AM](https://user-images.githubusercontent.com/16888709/131379528-f75619e5-573f-4cd0-b03c-d974bf941a72.png)

In the above the screen capture, we should have instead of Unknown shown `mpi` as can be seen in the response message for the TaskExecutionClosure
```json
{
    "task_executions": [
        {
            "id": {
                "task_id": {
                    "resource_type": "TASK",
                    "project": "flytesnacks",
                    "domain": "development",
                    "name": "myapp.workflows.example.mnist_pytorch_job",
                    "version": "v21"
                },
                "node_execution_id": {
                    "node_id": "n0",
                    "execution_id": {
                        "project": "flytesnacks",
                        "domain": "development",
                        "name": "hklphzalss"
                    }
                }
            },
            "input_uri": "<...>",
            "closure": {
                "error": {
                    "code": "Task Aborted",
                    "message": "max number of system retry attempts [51/50] exhausted - system failure."
                },
                "phase": "ABORTED",
                "created_at": "2021-08-28T07:54:25.260269827Z",
                "updated_at": "2021-08-28T09:34:37.232874066Z",
                "reason": "task submitted to K8s",
                "task_type": "mpi"
            }
        }
    ]
}
```
As can be seen above, the TaskType is seen in the following JSON Path `JSON.task_executions[0].closure.task_type` -> value `mpi`

**Goal: What should the final outcome look like, ideally?**
users should be able to see the task type. It should not be hard coded in the UI, but allowed to be an arbitrary string.

**Comment by jsonporter** [comment]
Reopenning - did not understand the problem; we still need to fix this on FE.
