### ISSUE TITLE
[BUG] flytectl panic on get for resource w/o expected output

### ISSUE THREAD

**Issue by vglocus** [flyteorg/flyte#1396]
**Describe the bug**
`flytectl get task/workflow/launchplan -o table` panics if resource has no expected output variables.
We encountered `FormatVariableDescriptions at pkg/printer/printer.go:173` to panic when using the get command on a resource without expected output.
This happened with both explicit table output as well as default.

Replicated on latest master
```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/flyteorg/flytectl/pkg/printer.FormatVariableDescriptions(0x0)
	/workspace/flyteorg/flytectl/pkg/printer/printer.go:202 +0x307
github.com/flyteorg/flytectl/cmd/get.LaunchplanToTableProtoMessages({0xc000a30938, 0x1, 0x7ffeefbff977})
	/workspace/flyteorg/flytectl/cmd/get/launch_plan.go:136 +0xee
github.com/flyteorg/flytectl/cmd/get.getLaunchPlanFunc({0x2dfbf98, 0xc0000580b8}, {0xc0002fb8c0, 0x1, 0x11519b4}, {{0x2e55850, 0xc000a30120}, {0x2e472c0, 0xc0009a3110}, {0x2ddff60, ...}, ...})
	/workspace/flyteorg/flytectl/cmd/get/launch_plan.go:158 +0x307
github.com/flyteorg/flytectl/cmd/core.generateCommandFunc.func1(0xc000481680, {0xc0002fb8c0, 0x1, 0x6})
	/workspace/flyteorg/flytectl/cmd/core/cmd.go:69 +0x47d
github.com/spf13/cobra.(*Command).execute(0xc000481680, {0xc0002fb860, 0x6, 0x6})
	/workspace/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000480000)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/flyteorg/flytectl/cmd.ExecuteCmd()
	/workspace/flyteorg/flytectl/cmd/root.go:135 +0x1e
main.main()
	/workspace/flyteorg/flytectl/main.go:12 +0x1d
exit status 2
```

**Expected behavior**
The command to output table with empty representation for output.

**[Optional] Additional context**
***To Reproduce***
1. Have task/workflow/launchplan which does not have any ExpectedOutput.Variables
2. `flytectl get launchplans -p demo-1 -d production --latest demo-1.no-output`

Validated that nil check on `cmd/get/launch_plan.go:135` passes but the map passed to `FormatVariableDescriptions at pkg/printer/printer.go:173` is nil and causes panic.

Suggested solution is to check for nil on argument map before calling `FormatVariableDescriptions`.

**Comment by pingsutw** [comment]
This issue is already been resolved. https://github.com/flyteorg/flytectl/commit/142cb8070623c9e0e6f522ae58ef4fa649de0314

**Comment by EngHabu** [comment]
v0.2.42
