### ISSUE TITLE
[BUG] flytectl register examples should use the version of the flytesnacks release

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1404]
**Describe the bug**
Currently when we register examples, it defaults to using version `v1`. We should instead use the version of the release in flytesnacks.

**Expected behavior**
Use the release version from flytesnacks

**[Optional] Additional context**
***To Reproduce***
```
flytectl register examples -p flytesnacks -d development --outputLocationPrefix <xyz>
```

**Comment by evalsocket** [comment]
@mayitbeegh I want some more changes in `register example`. Currently, we read the `flyte-test-manifest.yaml` from the flytesnack example and then generate the URL for all examples.....but I found that we have an extra dependency to update flyte-test-manifest.yaml in flytesnacks each time....it is an overhead...and can be overcome with GitHub client.   

Using GitHub client we can read all assets of a release,  then get the URL of assets.  

You can assign the task to me and you can pick another flytectl issue.
