### ISSUE TITLE
[BUG] flytesnacks release and associated tars - race!

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1406]
**Describe the bug**
We add all the archives of protos to the release. But, this causes a race condition when using flytectl register examples.
the latest examples may not be available as the github workflow slowly populates all the archives

**Expected behavior**
When register examples is run, all archives in the manifest should be available.

**Potential solution**
Flytesnacks can create the latest release as a `pre-release` and then add the archives. Then mark the release as a `release`.
flytectl then can ignore the pre-releases!

**Comment by evalsocket** [comment]
@kumare3 I am planning to remove dependency from flyte-test-manifest.yaml....I added a comment in issue https://github.com/flyteorg/flyte/issues/1404

**Comment by kumare3** [comment]
i actually like that we know all the files to get? ya the dependency may not be needed, but we need to handle the race as well

**Comment by evalsocket** [comment]
@kumare3 there is no race condition.....If there is a release and assets are not available then flytectl will not fail. For more details please check https://github.com/flyteorg/flytectl/pull/172

**Comment by kumare3** [comment]
@evalsocket I have different opinion. this is a race. The race is - the github process writing the tars and flytectl downloading them. The behaviour that we will download only some tars in the case when only some tars are partially uploaded and all tars otherwise is a definition of a data race. 
I actually really like the idea of a manifest, as this way, we know what should exist. Any thing that is missing should actually raise an problem.
Best way to solve the race is to make the release atomic, this is not simply possible. So Making a pre-release and then switching it will achieve this atomic releasing.

**Comment by evalsocket** [comment]
@kumare3 ok I understand the data race condition and I will create a separate PR in flytesnacks. Do you want to use manifest for registering the example? currently I made some changes and used GitHub client to register all example

**Comment by kumare3** [comment]
this is now resolved.

**Comment by evalsocket** [comment]
@kumare3 Their is small thing missing in this, I will pick up this today. We need pre release before making it release, I have the solution and i am planing to write a github action for doing this
