### ISSUE TITLE
[Docs] Move the schedules examples from deployment to remote_access

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#1415]
**Describe the documentation update**
With the flyte native scheduler it now possible to run the cron and fixed rate schedules in sandbox environment.

Following examples which only used to work on AWS can now work in local sandbox using the native scheduler
 https://docs.flyte.org/projects/cookbook/en/latest/auto/deployment/lp_schedules.html#sphx-glr-auto-deployment-lp-schedules-py

Move to
https://docs.flyte.org/projects/cookbook/en/latest/auto/remote_access/index.html

**Comment by pmahindrakar-oss** [comment]
cc : @kumare3

**Comment by kumare3** [comment]
@wild-endeavor / @cosmicBboy - I think we should get all schedule related docs as part of the regular flow as it works in sandbox

**Comment by pmahindrakar-oss** [comment]
We will have to wait for this to be checked in https://github.com/flyteorg/flyte/pull/1374 to work in sandbox e2e
