### ISSUE TITLE
[BUG] invalid logs url for python task

### ISSUE THREAD

**Issue by tekumara** [flyteorg/flyte#1434]
**Describe the bug**

The logs URL for Python tasks is http://localhost:30082/#/log///pod?namespace=

**Expected behavior**

A valid Kubernetes dashboard URL

**[Optional] Additional context**

Run a python task in the sandbox

***Screenshots***

<img width="1068" alt="Screen Shot 2021-09-05 at 4 28 16 pm" src="https://user-images.githubusercontent.com/125105/132117720-2fb954aa-2b73-4a54-8e9f-bea16eff39bd.png">

**Comment by evalsocket** [comment]
Thanks for reporting it

Related to release v0.17.1 sandbox changes

**Comment by evalsocket** [comment]
@tekumara It is fixed in the master branch and a fix will be available in the next patch release.
