### ISSUE TITLE
[Docs] Document Maptask Backend Plugin

### ISSUE THREAD

**Issue by georgesnelling** [flyteorg/flyte#1445]
Client docs here:  https://docs.flyte.org/projects/flytekit/en/latest/generated/flytekit.map_task.html?highlight=map%20task

We need to document the backend.  Context here:  https://github.com/flyteorg/flyte/discussions/1444.

**Comment by samhita-alla** [comment]
merging this with https://github.com/flyteorg/flyte/issues/2413
