### ISSUE TITLE
[BUG] Error registering file due to rpc error: code = Unavailable dec = connection error: desc = “transport: Error while dialing dial tcp ...:443: i/o timeout”

### ISSUE THREAD

**Issue by RustamovAzer** [flyteorg/flyte#1448]
**Describe the bug**
I want to create a Flyte Cluster on AWS, upload my workflows on that cluster and run them with different cluster count. I ran into several problems, some of them I managed to circumvent, but I ran into the problem when I tried to upload my workflows.

**Expected behavior**
`flytectl register files` should not result in error

**[Optional] Additional context**
***To Reproduce***
I followed [this]( https://docs.flyte.org/en/latest/deployment/aws/opta.html#deployment-aws-opta) tutorial, but I got this error multiple times `Error: error creating public access block policy for S3 bucket`. I solved that problem by deleting these blocks:

* `resource "aws_s3_bucket_public_access_block" "block"` and `resource "aws_s3_bucket_policy" "log_bucket_policy"` in `~/.opta/config/tf_modules/aws-base/log_bucket.tf`,

* `resource "aws_s3_bucket_public_access_block" "block"` in `~\.opta\config\tf_modules\aws-s3\bucket_tf`,

* `resource "aws_s3_bucket_policy" "replica_bucket_policy"` in `~\.opta\config\tf_modules\aws-s3\replication.tf`

After editing above mentioned files, I ran these commands: 

1. `opta apply -c env.yaml`(twice, since the first time it fails immediately with error ` botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutPublicAccessBlock operation: Access Denied `)
2. `opta apply -c flyte.yaml `
3. `aws eks --region <region> update-kubeconfig --name <name of cluster>`
4. `kubectl get pods -n flyte -o wide` to get FLYTEADMIN_URL
5. `flytectl config init --host=<FLYTEADMIN_URL> --storage`
6. Edited `~/.flyte/config.yaml` to add region and s3 bucket.
7. Built and pushed my workflows
8. `flytectl register files --project flytesnacks --domain development --archive flyte-package.tgz --version v1`

***Screenshots***
Screenshot of an output of the command:

![error1](https://i.snipboard.io/MJFPjQ.jpg)

If instead I run `flytectl register examples --project flytesnacks --domain development` I get the same error:

![error2](https://i.snipboard.io/M6dptY.jpg)

**Comment by evalsocket** [comment]
CC: @pmahindrakar-oss

**Comment by evalsocket** [comment]
@RustamovAzer If you are not using the secure connection then use `--insecure` flag

**Comment by juandiegopalomino** [comment]
What where the exact errors you where getting with opta when you saw Error: error creating public access block policy for S3 bucket ?

**Comment by juandiegopalomino** [comment]
also, could you drop in your opta file?

**Comment by RustamovAzer** [comment]
@evalsocket Tried that today, sadly, got the same error.

@juandiegopalomino Do you need every error? I'm pretty sure they are the same type:
![error3](https://i.snipboard.io/yQeYsz.jpg)
If you do, I can give them to you, but it will take some time.

Also, what do you mean by opta file? I got the attached files are from `helm` branch in `opta` folder
[files.zip](https://github.com/flyteorg/flyte/files/7136312/files.zip)

**Comment by juandiegopalomino** [comment]
Reading the error, it looks like you don't have the required IAM permissions.
Please make sure you have PutBucketPublicAccessBlock for all buckets, PutAccountPublicAccessBlock, PutBucketPolicy, DeleteBucketPolicy, PutBucketAcl and try running again after changing the opta terraform files to the original state

**Comment by RustamovAzer** [comment]
Requesting permissions will take some time, is there anything else that I can do to try to fix this issue?

**Comment by kumare3** [comment]
Resolving the issue as this is related to perms
