### ISSUE TITLE
[flytekit] Test pytest with `--import-mode=importlib`

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#1469]
**Describe the bug**
See the [slack](https://flyte-org.slack.com/archives/CREL4QVAQ/p1631245738119700) thread.  Running pytest with `--import-mode=importlib` causes tests to fail in certain cases.  We should find out why, and fix.

***To Reproduce***
See slack thread for error.  Basically the detection of nested tasks is incorrect when this flag is set.

**Comment by eapolinario** [comment]
Relevant `pytest` issue: https://github.com/pytest-dev/pytest/issues/7245

I could reproduce the issue in `pytest==6.2.5`, but not in `6.3.0` which contains https://github.com/pytest-dev/pytest/pull/7870. 

There's talk of making `importlib` the default import mode (as implied by the [`pytest` docs](https://docs.pytest.org/en/6.2.x/pythonpath.html#import-modes)), but it will probably be a while until that happens.
