### ISSUE TITLE
[Docs] Flytesnacks - core should have an example of Pure task orchestration

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1486]
**Describe the documentation update**
Flyte supports data flow orchestration. Additionally, it also supports task orchestration. There is no example explaining the latter topic in the docs.

Reference: https://github.com/flyteorg/flytekit/blob/master/tests/flytekit/unit/core/test_node_creation.py#L71-L74.

Let's codify this into the flytesnacks repo. `core` is the directory that should house this example.

**GitHub repo(s)**
[flytesnacks](https://github.com/flyteorg/flytesnacks)

**Comment by askalik** [comment]
Could I be assigned this task?  I think I understand the ask, but could use some clarification.

**Comment by kumare3** [comment]
@askalik absolutely, so for clarifications please join the hacktoberfest channel in Flyte slack and someone will be more than happy to assist.

Thank you

**Comment by eapolinario** [comment]
https://docs.flyte.org/projects/cookbook/en/latest/auto/core/control_flow/chain_tasks.html contains an example of this.
