### ISSUE TITLE
[Core Feature] Improve health check to include DB connection

### ISSUE THREAD

**Issue by veggiemonk** [flyteorg/flyte#1493]
**Motivation: Why do you think this is important?**
The health of the service only reports that it is running. See [Code](https://github.com/flyteorg/flyteadmin/blob/master/cmd/entrypoints/serve.go#L150-L151)
The health check should contain a connection "ping" to the database as the service is useless without it.

**Goal: What should the final outcome look like, ideally?**
The `/healthcheck` endpoint returns a 200 only if the connection to the database is successful.

**Describe alternatives you've considered**
Leaving the status of the health check as is. This push the burden of testing/monitoring a reliable connection to the DB to the end user. That work involves creating another layer to the open source version of the container in order to add custom tooling. That work is non trivial and add to the burden of monitoring flyte components using a DB (i.e. flyteadmin).

**[Optional] Propose: Link/Inline OR Additional context**

A quick search reveal similar pattern: https://github.com/darlinggo/healthcheck/blob/v0.1.0/sql.go

**Comment by pmahindrakar-oss** [comment]
Slack conversation snippet

```
Prafulla Mahindrakar  1 hour ago
Hi @Julien Bisconti i was reading through the code and and according to my understanding the health check api happens to be registered during admin bootup when bringingup the httpServer which happens after the grpcServer
https://github.com/flyteorg/flyteadmin/blob/d9f09e4eda5260d7d0fbb589b26117a42db7f5cc/cmd/entrypoints/serve.go#L343
The newGrpcServer registers the admin service here
https://github.com/flyteorg/flyteadmin/blob/d9f09e4eda5260d7d0fbb589b26117a42db7f5cc/cmd/entrypoints/serve.go#L119
Which in turn get the db repository
https://github.com/flyteorg/flyteadmin/blob/d9f09e4eda5260d7d0fbb589b26117a42db7f5cc/pkg/rpc/adminservice/base.go#L85
https://github.com/flyteorg/flyteadmin/blob/d9f09e4eda5260d7d0fbb589b26117a42db7f5cc/pkg/repositories/factory.go#L46
And without the db it would raise a panic
https://github.com/flyteorg/flyteadmin/blob/d9f09e4eda5260d7d0fbb589b26117a42db7f5cc/pkg/repositories/config/postgres.go#L77
Already before the admin container comes up we have init-container for check-db-ready which checks if db is healthy and only then allows admin to come up .
Let me know if we still need this

Prafulla Mahindrakar  36 minutes ago
 spec:
      initContainers:
        {{- if .Values.postgres.enabled }}
        - name: check-db-ready
          image: postgres:10.16-alpine
          command:
          - sh
          - -c
          - until pg_isready -h {{ tpl .Values.db.admin.database.host $ }} -p {{ .Values.db.admin.database.port }}; do echo waiting for database; sleep 2; done;
New

Julien Bisconti  16 minutes ago
Hi @Prafulla Mahindrakar, thank you so much for the detailed answer. If it is ok with you, we could continue this discussion on github? I believe, slack is not the best medium to communicate about that. It would allow us to keep important architecture decision in a "google searchable" github issue.

Julien Bisconti  15 minutes ago
or maybe there is no need because Gorm already ping the DB at intervals: https://gorm.io/docs/gorm_config.html#DisableAutomaticPing
GORMGORM
GORM Config
GORM provides Config can be used during initialization type Config struct &#123; SkipDefaultTransaction bool NamingStrategy schema.Namer Logger logger.Interface NowFu
Sep 10th

Julien Bisconti  11 minutes ago
I need to figure out how to do that in GCP with cloudsql_proxy that run as a sidecar: The reason I asked for is to run cloudsql_proxy as a sidecar: https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine#running_the_as_a_sidecar
Google CloudGoogle Cloud
Connecting from Google Kubernetes Engine  |  Cloud SQL for MySQL (17 kB)
https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine#running_the_as_a_sidecar


Prafulla Mahindrakar  < 1 minute ago
Sure . Let me move this discussion to the github issue. I will copy this discussion over there. I believe we are using older gorm layer which doesnt support automatic pings but upgrading should allow this feature.
```
cc :  @EngHabu

**Comment by katrogan** [comment]
hey @veggiemonk thanks for opening this issue. as part of the standard flyte helm deployments, we actually have an [initContainer](https://github.com/flyteorg/flyte/blob/master/charts/flyte/templates/admin/deployment.yaml#L22) which verifies that the db is up and running before proceeding with the flyteadmin deployment

can you explain more about your deployment process and whether the initContainer approach could work?

**Comment by veggiemonk** [comment]
There are few limitations with the design. 

What if something happens to the database *after* the init container and the application is started? 
Can a service calling the DB still be considered up and running when the DB cannot be reached ?

What I proposed was to make sure the health check really handles the health of the service and its dependencies (such as a DB).

**Comment by evalsocket** [comment]
@veggiemonk I think we can close this now, As we discussed

**Comment by veggiemonk** [comment]
@evalsocket go ahead

**Comment by katrogan** [comment]
@evalsocket @veggiemonk mind summarizing the resolution/what you discussed?
