### ISSUE TITLE
[BUG] Overly long task inputs not fully viewable

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#1499]
**Describe the bug**
When I click to view a task and the left-hand pane opens up and I navigate to the inputs, I reach the end of the scrollbar but the inputs aren't fully visible.

**Expected behavior**
The task inputs margins should extend to view the entirety of the inputs.

**GitHub repo(s)**
[flyteconsole](https://github.com/flyteorg/flyteconsole)

**[Optional] Additional context**
***To Reproduce***
1. Run a task with a huge number of inputs

***Screenshot(s)***
<img width="437" alt="Screen Shot 2021-09-20 at 12 43 00 PM" src="https://user-images.githubusercontent.com/953358/134065206-a0f2a57c-98c5-4424-9f02-bd4b25152c82.png">

**Comment by samhita-alla** [comment]
@katrogan Can you let me know the example you have run? Do we have it in flytesnacks?

**Comment by katrogan** [comment]
okay this was user error 🤦‍♀️ when you're outside the task details pane you have to scroll down all the way, and then inside the pain you can scroll to the bottom
