### ISSUE TITLE
[Docs] Update all Flyteconsole Gifs to show the new Graph UI

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1507]
**Describe the documentation update**
Need to update all Flyteconsole GIFs in the [README](https://github.com/flyteorg/flyte#----quick-start), [getting started](https://docs.flyte.org/en/latest/getting_started.html), and [user guide](https://docs.flyte.org/projects/cookbook/en/latest/user_guide.html) to showcase Flyte's shiny graph UI. 

New UI snapshot
<img width="882" alt="image" src="https://user-images.githubusercontent.com/27777173/134671633-e20c9f9c-650f-41f7-b239-ee52ac892cf2.png">

**GitHub repo(s)**
[flyte](https://github.com/flyteorg/flyte), [flytesnacks](https://github.com/flyteorg/flytesnacks)

**Comment by AnirudhPanda** [comment]
Can you help me walk through this issue?

**Comment by askalik** [comment]
Can I take this issue?

**Comment by kumare3** [comment]
@askalik absolutely

**Comment by samhita-alla** [comment]
@AnirudhPanda You will have to run code examples on Flyte sandbox and capture the execution process. The [getting started guide](https://docs.flyte.org/en/latest/getting_started.html) should capture the creation of the sandbox, running workflows, etc. You have to update all the concerning GIFs to showcase our new graphs.

**Comment by samhita-alla** [comment]
@AnirudhPanda / @askalik When you create a PR, please add this issue in the description.
