### ISSUE TITLE
[BUG] Integer values within dict and dataclass are converted to float when passed to a task

### ISSUE THREAD

**Issue by pradithya** [flyteorg/flyte#1510]
**Describe the bug**
Integer values within `dict` and `dataclass` inputs are getting converted into `float`. This happen specifically in following case:
1. `dict`: the conversion happen for both `int` and list of `int`
2. `dataclass`: the conversion happen only for list of `int`

**Expected behavior**
Maintain `int` type, at least for the `dataclass` case.

**[Optional] Additional context**
***To Reproduce***
1. Create following workflow
```
@dataclass_json
@dataclass
class Data(object):
    int_val: int
    int_list: typing.List[int]

@task
def my_task(my_dict: dict, my_data: Data)->str:
    print(my_dict)
    print(my_data)
    return "done"

@workflow
def my_wf():
    my_task(my_dict={"int_val": 1, "int_list": [1,2,3]}, 
                  my_data=Data(int_val=1, int_list=[1, 2, 3]))

```
2. run locally
3. following logs are printed
```
DEBUG:flytekit:Task returns unnamed native tuple <class 'str'>
{"asctime": "2021-09-22 11:34:43,373", "name": "flytekit", "levelname": "INFO", "message": "Invoking __main__.my_task with inputs: {'my_dict': {'int_val': 1.0, 'int_list': [1.0, 2.0, 3.0]}, 'my_data': Data(int_val=1, int_list=[1.0, 2.0, 3.0])}"}
INFO:flytekit:Invoking __main__.my_task with inputs: {'my_dict': {'int_val': 1.0, 'int_list': [1.0, 2.0, 3.0]}, 'my_data': Data(int_val=1, int_list=[1.0, 2.0, 3.0])}
{'int_val': 1.0, 'int_list': [1.0, 2.0, 3.0]}
Data(int_val=1, int_list=[1.0, 2.0, 3.0])
{"asctime": "2021-09-22 11:34:43,374", "name": "flytekit", "levelname": "INFO", "message": "Task executed successfully in user level, outputs: done"}


```
***Screenshots***

**Comment by kumare3** [comment]
Cc @pingsutw / @eapolinario

**Comment by kumare3** [comment]
A few things that are relevant here
1. Protobuf Struct only stores `Number` Type and not `integer and number`. [here](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Value)
2. JsonEncoder converts ints to json.number - [here](https://docs.python.org/3/library/json.html#json.JSONEncoder)
3. Interesting thing is `type int` is maintained in dataclasses. but `type list[int]` is lost. This seems to be a library problem

**Comment by kumare3** [comment]
Actually, The Dataclass Transformer handles this case - https://github.com/flyteorg/flytekit/blob/master/flytekit/core/type_engine.py#L249-L254. We should extend this logic to traverse to nested structures and for list of integer cases
