### ISSUE TITLE
[BUG] [flytekit] Trying to read from Typed Columns in a Typed Schema results in an AttributeError

### ISSUE THREAD

**Issue by mdjong1** [flyteorg/flyte#1511]
**Describe the bug**
When using typed columns I am unable to read the pandas.DataFrame back again as indicated in the [documentation](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/type_system/typed_schema.html). Calling `schema.open().all()` returns `AttributeError: 'PandasSchemaWriter' object has no attribute 'all'`.

**Expected behavior**
I would expect `schema.open().all()` to return a pandas.DataFrame.

**Current workaround**
Since I only need to read the object afterwards I am currently calling `schema.as_readonly().open().all()` which does correctly return the pandas.DataFrame.

**Comment by samhita-alla** [comment]
@mdjong1 Which flytekit version are you using?

**Comment by mdjong1** [comment]
Ahh yeah that's a good point, I forgot to add that, my bad

We're on flytekit 0.21.5

**Comment by samhita-alla** [comment]
`schema.open().all()` is calling a PandasSchemaWriter but not a PandasSchemaReader. @mdjong1, are you by any chance instantiating the mode to be `SchemaOpenMode.WRITE`?

**Comment by mdjong1** [comment]
I'm instantiating it as suggested [here](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/type_system/typed_schema.html?highlight=flyteschema#typed-columns-in-a-schema), as far as I can tell at least.

```
CreatedKeysSchema = FlyteSchema[kwtypes(quadkey=str)]

...

created_keys = CreatedKeysSchema()
keys_as_df = pd.DataFrame(data={"keys": keys})
created_keys.open().write(keys_as_df)
```

**Comment by samhita-alla** [comment]
Are you trying to read `created_keys` in a different task?

**Comment by samhita-alla** [comment]
If so, you'll have to send `supported_mode` and `remote_path`:

```python
from flytekit.types.schema import SchemaOpenMode

...
created_keys = CreatedKeysSchema(supported_mode=SchemaOpenMode.READ, remote_path="...")
```

**Comment by mdjong1** [comment]
I'll give that a try. I am indeed trying to access the `created_keys` from another task.

Is there no way to do this without specifying a remote path? Or is there a way that it can pick a 'normal' flyte path i.e. self-generated instead of specifying something myself.

Trying this I'm getting another error though, with `suppoorted_mode=SchemaOpenMode.READ, remote_path="s3://some-path")`
```
test_.py:52: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.8/dist-packages/flytekit/core/base_task.py:316: in __call__
    return self.execute(**kwargs)
/usr/local/lib/python3.8/dist-packages/flytekit/core/python_function_task.py:157: in execute
    return exception_scopes.user_entry_point(self._task_function)(**kwargs)
/usr/local/lib/python3.8/dist-packages/flytekit/common/exceptions/scopes.py:198: in user_entry_point
    return wrapped(*args, **kwargs)
.py:412: in 
    return get_result(keys)
.py:54: in 
    created_keys.open().write(keys_as_df)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <flytekit.types.schema.types.FlyteSchema.__class_getitem__.<locals>._TypedSchema object at 0x7facfedfe520>
dataframe_fmt = <class 'pandas.core.frame.DataFrame'>, override_mode = None

    def open(
        self, dataframe_fmt: type = pandas.DataFrame, override_mode: SchemaOpenMode = None
    ) -> typing.Union[SchemaReader, SchemaWriter]:
        """
        Will return a reader or writer depending on the mode of the object when created. This mode can be
        overridden, but will depend on whether the override can be performed. For example, if the Object was
        created in a read-mode a "write mode" override is not allowed.
        if the object was created in write-mode, a read is allowed.
    
        :param dataframe_fmt: Type of the dataframe for example pandas.DataFrame etc
        :param override_mode: overrides the default mode (Read, Write) SchemaOpenMode.READ, SchemaOpenMode.Write
               So if you have written to a schema and want to re-open it for reading, you can use this
               mode. A ReadOnly Schema object cannot be opened in write mode.
        """
        if override_mode and self._supported_mode == SchemaOpenMode.READ and override_mode == SchemaOpenMode.WRITE:
            raise AssertionError("Readonly schema cannot be opened in write mode!")
    
        mode = override_mode if override_mode else self._supported_mode
        h = SchemaEngine.get_handler(dataframe_fmt)
        if not h.handles_remote_io:
            # The Schema Handler does not manage its own IO, and this it will expect the files are on local file-system
            if self._supported_mode == SchemaOpenMode.READ and not self._downloaded:
                # Only for readable objects if they are not downloaded already, we should download them
                # Write objects should already have everything written to
**>               self._downloader(self.remote_path, self.local_path)
E               TypeError: 'NoneType' object is not callable**

```

**Comment by samhita-alla** [comment]
You can do one other thing. Instead of specifying the mode in init, you can specify the `override_mode` in `open()`, like:

```python
schema.open(override_mode=SchemaOpenMode.READ).all()
```

**Comment by samhita-alla** [comment]
<img width="606" alt="Screenshot 2021-09-24 at 2 25 14 PM" src="https://user-images.githubusercontent.com/27777173/134647374-6dea7480-580b-4b3d-a6f9-87ce9ef8db55.png">

**Comment by mdjong1** [comment]
Using the `override_mode` seems to work; though it feels a bit off. But thank you 👌🏼

**Comment by samhita-alla** [comment]
> Using the `override_mode` seems to work; though it feels a bit off. But thank you 👌🏼

The thing is, if you use tasks just like the example in documentation, you needn't worry about the modes. `override_mode` is essential in this case because the default mode is set to WRITE. READ isn't used as we need to input the `remote_path` where we have our dataframe.

**Comment by mdjong1** [comment]
That makes sense, thanks

**Comment by kumare3** [comment]
@mdjong1 can you join the slack channel, this above feels like a chat? [slack](https://docs.google.com/forms/d/e/1FAIpQLScWPJZncyL-bBCWbuQ9HWuMzA8-r2RJc__CSWJoAYUQADN-BQ/viewform)
