### ISSUE TITLE
[Docs] Flytectl docs cleanup

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#1524]
**Describe the documentation update**
* Fix typos, grammar in flytectl docs
* Format code and content to properly render the docs
* Add any missing command docs and also add some more examples if there's a possibility (optional)
* Make sure flags' descriptions respect capitalized case
* Getting the docs consistent to have flytectl command instead of `bin/flytectl` which is used in some places
* Providing output for the example commands

On the whole, improve flytectl user experience through docs!

**GitHub repo(s)**
[flytectl](https://github.com/flyteorg/flytectl)

**Comment by samhita-alla** [comment]
@pmahindrakar-oss / @evalsocket Do we have anything specific that needs to be improved or updated in flytectl docs?

**Comment by pmahindrakar-oss** [comment]
I think the main thing would be to find any grammatical issues and fix those , add any missing command docs and also add some more examples wherever missing.
Getting the docs consistent to have flytectl command instead of bin/flytectl which is use in some places.

Providing output for the example commands would be helpful too.

**Comment by evalsocket** [comment]
Currently, filters have less documentation, It would be great if we can add some more documentation that is aligned with the flyteadmin filter. 

Our contribution guide is also not up to date with new changes. We should update that.

**Comment by samhita-alla** [comment]
> Our contribution guide is also not up to date with new changes. We should update that.

I'm working on updating the contribution guide. I'll send you the PR once it's up for review.

**Comment by evalsocket** [comment]
@samhita-alla I also found one inconsistency in the description of flags. Some descriptions start with Capital and some start with small char. It should be consistent

**Comment by samhita-alla** [comment]
> @samhita-alla I also found one inconsistency in the description of flags. Some descriptions start with Capital and some start with small char. It should be consistent

Which one do we prefer? Capital or small case?

**Comment by pankaj892** [comment]
@samhita-alla Can I work on fixing the grammatical errors,typos in the docs ?

**Comment by evalsocket** [comment]
@samhita-alla flytestdlib has all standard flags and they use Captial. Using capital everywhere make sens

**Comment by samhita-alla** [comment]
> @samhita-alla Can I work on fixing the grammatical errors,typos in the docs ?

Absolutely, @pankaj892! Apologies for the delayed response. 
If possible, please make sure to take care of the additional things we discussed in the comments. Let us know if you have any questions. You can join our [slack channel](https://docs.google.com/forms/d/e/1FAIpQLScWPJZncyL-bBCWbuQ9HWuMzA8-r2RJc__CSWJoAYUQADN-BQ/viewform).

**Comment by divigarg** [comment]
Can I get to work on this issue?

**Comment by samhita-alla** [comment]
Hi, @divigarg! Yes, you can. There are two of them who have contacted me regarding this. I'm not sure if @pankaj892 is working on it, and @Sayanta66 hasn't worked on the issue wholly. 

If you start working on it, please share the PR here. :)

**Comment by samhita-alla** [comment]
**If this issue requires time and effort, which we typically measure through code/content contribution, we can take this as a combination of PRs—two or three.  Quality is key!**

**Comment by pankaj892** [comment]
@samhita-alla to make edits in docs do i need to clone the whole repo of flyte or just docs folder would be fine ?

**Comment by idivyanshbansal** [comment]
I would like to work on this issue.

**Comment by kumare3** [comment]
@idivyanshbansal please go for it

**Comment by kumare3** [comment]
> @samhita-alla to make edits in docs do i need to clone the whole repo of flyte or just docs folder would be fine ?

Ya you have to fork and work on the fork and request for a merge

**Comment by cyberwizard1001** [comment]
@samhita-alla Hi! I'd love to work on this.

**Comment by samhita-alla** [comment]
> @samhita-alla Hi! I'd love to work on this.

Hi, @cyberwizard1001! Please go ahead. :) Let us know if you have any questions.

**Comment by samhita-alla** [comment]
@SmritiSatyanV, can you please add your FlyteCTL PRs here?

**Comment by SmritiSatyanV** [comment]
https://github.com/flyteorg/flytectl/pull/269

**Comment by SmritiSatyanV** [comment]
https://github.com/flyteorg/flytectl/pull/272
