### ISSUE TITLE
[Docs] Flyte dataplane cluster cert setup in flyteadmin for Out-of-cluster control plane

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1525]
**Describe the documentation update**
There is no documentation that shows how to configure flyteadmin to connect to multiple flyte-dataplane clusters or how to configure a dataplane cluster that is separate from the flyteadmin. The default assumes incluster configuration only.

Example of this config can be found [here](https://github.com/flyteorg/flyteadmin/blob/2d81c1eec24cffb43346b56fc0017fd29db33a38/pkg/executioncluster/impl/testdata/clusters_config.yaml#L1-L31)

**Comment by katrogan** [comment]
Existing documentation for a multiple data-plane cluster set-up should exist here: https://docs.flyte.org/projects/cookbook/en/stable/auto/deployment/multiple_k8s.html

**Comment by katrogan** [comment]
as part of this documentation issue we should better catalog the in-cluster configuration, specifically

https://github.com/flyteorg/flyteadmin/blob/611a85f0db7325457c714c0dcd689bf2c5d818e5/pkg/config/config.go#L18,L19

given that both Master and KubeConfig are optional flags and in their absence we default to the [InClusterConfig](https://pkg.go.dev/k8s.io/client-go/rest#InClusterConfig)

**Comment by davidmirror-ops** [comment]
Current multicluster docs include how to setup multiple dataplane clusters to a control plane cluster including TLS https://docs.flyte.org/en/latest/deployment/deployment/multicluster.html
