### ISSUE TITLE
[Housekeeping] Deprecate duplicate helm chart

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#1537]
**Describe the Issue**
Currently, we are maintaining both chart `flyte` and `flyte-core`  but idea is to convert `flyte` helm chart into a sandbox chart, It will depend on `flyte-core` for flyte core component deployment. 

Flyte charts 
- Flyte (It will install the sandbox deployment)
- Flyte-core (It will only deploy the core component of flyte)

**What if we do not do this?**
For any new changes, We need to replicate that change in `flyte-core`. It's a overhead and there can be a difference between both charts along the time. 

***Related component***
Either Specific / all

**Comment by Pretty-19** [comment]
Hi @evalsocket  can you assign this task to me ?

**Comment by evalsocket** [comment]
Awesome! Please do. :) 

Let us know if you have any questions. You can join our [slack](https://docs.google.com/forms/d/e/1FAIpQLScWPJZncyL-bBCWbuQ9HWuMzA8-r2RJc__CSWJoAYUQADN-BQ/viewform) channel.

**Comment by samhita-alla** [comment]
Hi, @Pretty-19! Would you mind creating a PR within the next 2-3 days? :)

**Comment by Pretty-19** [comment]
@samhita-alla  was a bit behind on schedule, yes will do that
