### ISSUE TITLE
[BUG] Garbage collection does not seem to work always

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1554]
**Describe the bug**
The default setting of 23 hours for ttl in flytepropeller, seems to leave certain workflows behind. When the setting is changed to 1 hour, all workflows except current hour got deleted. This is because you cannot run GC every 12 hours, but have a ttl of 23 hours, as the logic only uses the hour of the day to delete. This is calculated based on the GC run interval.

**Expected behavior**
Workflows should be deleted after their TTL. 

Reason for this complicated setup is because we want to reduce the strain on KubeAPI. We should try and find an alternative solution

**Comment by kumare3** [comment]
As a simple workaround for now, set the 
`gc-interval` to `< 1 hour` Something like 30 minutes should be great.

**Comment by aeioulisa** [comment]
pls assign me I would like to work on this
