### ISSUE TITLE
[Plugin]  Add some plugin

### ISSUE THREAD

**Issue by ramadh-an** [flyteorg/flyte#1562]
**Why would this plugin be helpful to the Flyte community**
Explain the usecases for the plugin

**Type of Plugin**
- [Dark Mode and Weather checker] Python/Java interface only plugin
- [GCP Dataflow] Web Service (e.g. AWS Sagemaker, GCP DataFlow, Qubole etc...)
- [x] Kubernetes Operator (e.g. TfOperator, SparkOperator, FlinkK8sOperator, etc...)
- [x] Customized Plugin using native kubernetes constructs
- [x] Other

**Can you help us with the implementation?**
- [x] Yes
- [No] No

**Comment by kumare3** [comment]
This issue does not make sense, sorry closing
