### ISSUE TITLE
[UI Feature] Add ip address display and name feature or plugin

### ISSUE THREAD

**Issue by ramadh-an** [flyteorg/flyte#1563]
**Motivation: Why do you think this is important?**
Because so many people access your app/website and we want to know about the name, ip address.

**Goal: What should the final outcome look like, ideally?**
Let the UI be a clear and cool

**[Optional] Propose: Link/Inline OR Additional context AND/OR Mock ideas**
An interesting additional feature is a welcome greeting or displaying the user's ip address (https://chrome.google.com/webstore/detail/display-ip-address-plugin/bdkjfcbjopmjplpfplpbgkbmehdhbkke?hl=en-GB)

**Comment by kumare3** [comment]
Where do you want to add the IP address?

**Comment by ramadh-an** [comment]
In your UI app or web

Pada tanggal Sel, 5 Okt 2021 pukul 21.47 Ketan Umare <
***@***.***> menulis:
