### ISSUE TITLE
[Docs] Document how to use node_overrides to set map task resources

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#1574]
### Description

The map task [documentation](https://docs.flyte.org/projects/flytekit/en/latest/generated/flytekit.map_task.html#flytekit-map-task) and [flytesnacks example](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/control_flow/map_task.html#sphx-glr-auto-core-control-flow-map-task-py) omits examples of how to use [node_overrides](https://github.com/flyteorg/flytekit/blob/1cb6e80a650cc267966b414a9db98a68a1e739b5/tests/flytekit/unit/core/test_node_creation.py#L183) to set individual map task resource assignment.

We should add a section documenting this behavior

### 

- [X] Are you sure this issue hasn't been raised already?

### 

- [X] Have you read the [Code of Conduct](https://github.com/flyteorg/flyte/blob/master/CODE_OF_CONDUCT.md)?

**Comment by katrogan** [comment]
cc @nicklofaso

**Comment by parzival272000** [comment]
@katrogan can you assign this to me if it is beginner friendly.

**Comment by katrogan** [comment]
done, thanks @parzival272000

**Comment by parzival272000** [comment]
Thanks
