### ISSUE TITLE
[Docs] Documentation that explains how to configure AWS Batch Backend for Flyte Map Tasks

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1580]
### Description

Flyte Map tasks can be executed on AWS Batch natively. This is not documented. Let us document how to configure this.

The code can be found [here](https://github.com/flyteorg/flyteplugins/tree/master/go/tasks/plugins/array/awsbatch)

cc @gigi-at-zymergen

### 

- [X] Are you sure this issue hasn't been raised already?

### 

- [X] Have you read the [Code of Conduct](https://github.com/flyteorg/flyte/blob/master/CODE_OF_CONDUCT.md)?

**Comment by EngHabu** [comment]
Docs are now available at the [official docs page](https://docs.flyte.org/en/latest/deployment/plugin_setup/aws/batch.html#deployment-plugin-setup-aws-array). Please let us know when you get a chance to try it out...
