### ISSUE TITLE
[Core feature] Caching for non-flyte specific offloaded objects

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1581]
### Motivation: Why do you think this is important?

Currently, if users use pandas.DataFrame or a pyspark.DataFrame or pander.DataFrameSchema, Flytekit simply extracts the data from the transport `Literaltype.Schema`. So consider the following function

```python
@task(cache=True, cache_version="1.0")
def sub_foo(df: pandas.DataFrame) -> pandas.DataFrame:
    return df
```

The above function will be cached, because the input type has the file path that is cached and hence the function is not run.

But, now consider the following

```python
@dynamic
def foo(df: pandas.DataFrame) -> pandas.DataFrame:
     return sub_foo(df=df)
```
This task will not be cached. This is because the dataframe is downloaded and then re-uploaded, as the underlying task transforms are not aware that the passed dataframe was not mutated. But, if FlyteSchema is used, this would work fine.

### Goal: What should the final outcome look like, ideally?

Either this should work as the user expects, i.e., cache hit, else this abnormality should be documented.

### Describe alternatives you've considered 

NA

### 

- [X] Are you sure this issue hasn't been raised already?

### 

- [X] Have you read the [Code of Conduct](https://github.com/flyteorg/flyte/blob/master/CODE_OF_CONDUCT.md)?

**Comment by cosmicBboy** [comment]
**Update:**
Consider a mechanism that uses s3 etag (or whatever the blob storage equivalent is) as the hash metadata for a particular reference-based data artifact (dataframe, files, etc). This offloads the burden of computing that hash to blob storage instead of manually computing the hash in the container.
