### ISSUE TITLE
[Docs] Document how pods are named in the executions

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1582]
### Description

Pod names or downstream resource names are either
`executionid-node-id-attempt` or somethings just plain hashes.
The reason for the hash is that downstream services usually have limits on the size of the name for the object.

Thus to prevent overrunning the limit, Flyte will optionally hash the objects. This should be clearly documented

### 

- [X] Are you sure this issue hasn't been raised already?

### 

- [X] Have you read the [Code of Conduct](https://github.com/flyteorg/flyte/blob/master/CODE_OF_CONDUCT.md)?

**Comment by cosmicBboy** [comment]
Notable places to document this:
- https://docs.flyte.org/en/latest/community/troubleshoot.html#troubleshoot
- https://docs.flyte.org/en/latest/deployment/sandbox.html

**Comment by marc-union** [comment]
@eapolinario succeeded in finding the code that assigns the pod name:

https://github.com/flyteorg/flyteplugins/blob/master/go/tasks/pluginmachinery/flytek8s/container_helper.go#L208

Note: If the pod name doesn't conform to DNS1123, as required by k8s, then Flyte assigns a random string of 4 characters instead.
