### ISSUE TITLE
[Docs] Document FlyteAdmin architecture

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1586]
### Description

- [ ] Database requirements
- [ ] High level overview diagram
- [ ] Monitoring metrics
- [ ] Scaling considerations

### 

- [X] Are you sure this issue hasn't been raised already?

### 

- [X] Have you read the [Code of Conduct](https://github.com/flyteorg/flyte/blob/master/CODE_OF_CONDUCT.md)?

**Comment by wild-endeavor** [comment]
Could I get more clarity on this ticket?  https://docs.flyte.org/en/latest/concepts/admin.html#divedeep-admin already exists - what topics in particular do we need to add to?
