### ISSUE TITLE
[BUG] Flyte propeller fatal error: concurrent map writes

### ISSUE THREAD

**Issue by eanakhl** [flyteorg/flyte#1595]
### Describe the bug

fatal error: concurrent map writes
when running the load test

### Expected behavior

no panic

### Additional context to reproduce

import time

from flytekit import LaunchPlan, Resources, dynamic, task, workflow

@task(
    requests=Resources(mem="200Mi", cpu="50m"),
    limits=Resources(mem="200Mi", cpu="50m"),
)
def just_sleep(n: int):
    """
    Just sleep for 10sec"""
    time.sleep(10)

@dynamic
def call_ndynamicsleeps(n: int):
    for i in range(n):
        just_sleep(n=n)

@workflow
def start_10sleeps(n: int):
    # looping through the string s1
    call_ndynamicsleeps(n=n)

launch_sleep2 = LaunchPlan.create(
    "dynamicSleepfromlp2",
    start_10sleeps,
    max_parallelism=30,
    default_inputs={"n": 1},
)

@workflow
def wf2(n: int):
    """
    Calls the dynamic workflow and returns the result"""
    for i in range(30):
        launch_sleep2(n=n)

launch_sleep = LaunchPlan.create(
    "dynamicSleepfromlp",
    wf2,
    max_parallelism=30,
    default_inputs={"n": 1},
)

@workflow
def wf(n: int):
    """
    Calls the dynamic workflow and returns the result"""
    for i in range(100):
        launch_sleep(n=n)

lp = LaunchPlan.create(
    "dynamicLP",
    wf,
    max_parallelism=30,
)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
Cc @EngHabu, had a fix for this
