### ISSUE TITLE
[BUG] Allow for caching of map_tasks

### ISSUE THREAD

**Issue by nicklofaso** [flyteorg/flyte#1609]
### Describe the bug

There does not seem to be a way for a user to enable caching for `map_tasks` even though it seems possible via the `metadata` parameter

```
mappy = map_task(
        myfunc,
        metadata=TaskMetadata(
            cache=True,
            cache_version="1.1.0",
            retries=1),
)
```

### Expected behavior

If I specify caching as enabled via the `metadata` parameter the map_task should utilize caching

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
cc @eapolinario

**Comment by kumare3** [comment]
@nicklofaso do you want to override the caching behavior for your task `myfunc` otherwise you should be able to add
```
@task(cache=True, cache_version="1.0")
def myfunc(...):
   ...
```

**Comment by kumare3** [comment]
@nicklofaso one of the issues related has been merged - https://github.com/flyteorg/flyte/issues/1912. We are working on fixing the caching issue in the backend. We found an issue in the way we were indexing into the dataset for map tasks
