### ISSUE TITLE
[Housekeeping] Generate pflag for AuthType

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#1616]
### Describe the issue

Currently, in flytestdlib, we are not generating the flag for AuthType. That means the user can't change the value from flags.

The user should be able to pass all the config through cli flags 

### What if we do not do this?

The user can't change the value from flags, They always need config

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
@evalsocket, is this issue resolved?

**Comment by jamindy** [comment]
您好，已收到您的邮件，我会尽快给您回复。

**Comment by evalsocket** [comment]
Yes
