### ISSUE TITLE
[Housekeeping] Flytectl register files command doesn't fail without --countinueOnError 

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#1618]
### Describe the bug

`flytectl register files` command doesn't fail without `--countinueOnError`. It should fail with exit code 0.

### Expected behavior

- Flytectl register should fail if there is an error
- Flytectl register should not fail if the user passes the `--countinueOnError `

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by AsianCat54x** [comment]
I think this issue has to be fixed in flytectl repository, right?

**Comment by samhita-alla** [comment]
> I think this issue has to be fixed in flytectl repository, right?

Yes!

**Comment by samhita-alla** [comment]
@evalsocket, can you provide some context? The files that @AsianCat54x has to work on, etc.?

**Comment by AsianCat54x** [comment]
TT, I tried to figure the proble in this repository and ended up being the issue in other repo TT

**Comment by samhita-alla** [comment]
@AsianCat54x, which repo?

**Comment by AsianCat54x** [comment]
@samhita-alla  In flytectl one

**Comment by evalsocket** [comment]
Not required now. it is fixed
