### ISSUE TITLE
[Docs] Write an example of documented workflow inputs/outputs

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1632]
### Description

1. Workflow with default inputs

``` python
@workflow
def my_wf(a: int = 5, b: str = "hello") -> int:
   ...
```

2. Workflow/tasks with docstrings

``` python
@workflow
def my_wf(a: int = 5, b: str = "hello") -> int:
  '''
  One line summary.

  Extended description.

  Args:
      arg1(int): Description of `arg1`
      arg2(str): Description of `arg2`
  Returns:
      str: Description of return value.
  '''
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
cc @mayitbeegh do you have any samples? @samhita-alla can you help with this one?
