### ISSUE TITLE
flytepropeller: pass command line args 

### ISSUE THREAD

**Issue by rstanevich** [flyteorg/flyte#167]
Using **flyteadmin** or **datacatalog** we have an option to update storage configuration with command line flags.
Using **flytepropeller**, looks it doesn't work 

Steps to reproduce:
1. Deploy **flyte** with default sandbox configuration
2. E.g., remove lines with access-key and secret-key from **storage** section in propeller config file https://github.com/lyft/flyte/blob/master/kustomize/overlays/sandbox/propeller/config.yaml#L40-L49
3. Update entry point for **flytepropeller** container as follows:
```
flytepropeller \
--config "/etc/flyte/config*/config.yaml" \
--storage.connection.access-key 'minio' \
--storage.connection.secret-key 'miniostorage'
```

Expected behavior:
- The provided flags should update **flytepropeller** configuration and the container should starts correctly

Actual behaviour:
- An error occurred
`{"json":{"src":"root.go:221"},"level":"fatal","msg":"Failed to start Controller - [Failed to create Metadata storage: unable to configure the storage for s3. Error: missing Access Key ID]","ts":"2020-02-05T12:19:16Z"}`

**Comment by kumare3** [comment]
@rstanevich this is definitely a bug! This should work. All of these systems use our common configuration system, source for which is available in https://github.com/lyft/flytestdlib/tree/master/config

We will take a look into this, you can always change the configmap to unblock yourself

**Comment by kumare3** [comment]
We need to initialize Pflags - https://github.com/lyft/flytestdlib/tree/master/config

**Comment by kumare3** [comment]
@jonathanburns does this https://github.com/lyft/flytepropeller/pull/63 handle this issue?

**Comment by honnix** [comment]
Any update on this? `go run ./cmd/controller/main.go --alsologtostderr --propeller.kube-config=$HOME/.kube/config` does not work and it falls back to InCluster mode.

**Comment by evalsocket** [comment]
@EngHabu You can assign to me if you is not working on it.

**Comment by EngHabu** [comment]
Thank you @evalsocket for picking up my slack :)

**Comment by evalsocket** [comment]
@EngHabu can we close this ?

**Comment by kumare3** [comment]
this is because flytestdlib/config and k8s globa flags conflict. We can run a simple check with this

**Comment by evalsocket** [comment]
I verified it and flytepropeller is working fine with command-line flags. We can close it
