### ISSUE TITLE
[Docs] Deadlink on deployment page

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#1674]
### Description

https://docs.flyte.org/en/latest/deployment/overview.html#usage-of-helm

The link in this screenshot is dead:
![image](https://user-images.githubusercontent.com/2816689/137384293-f93f322d-5796-4d6c-be70-87dd640a5c19.png)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by EngHabu** [comment]
Should take you to https://github.com/flyteorg/flyte/tree/master/charts instead...

@samhita-alla @evalsocket ... mind fixing that?
