### ISSUE TITLE
[Docs] Show how to add annotations to the workflow pod

### ISSUE THREAD

**Issue by SandraGH5** [flyteorg/flyte#1675]
### Description

We have an EKS installation with the cilium network overlay. This means that node roles don't work unless workflows run on hostNetwork. We could set up the service accounts and bind those to the roles, but project-namespaces makes it a bit complex (in our case it means a terraforming per project). 
One solution could be to use kube2iam, but I am not sure how to add annotations to the workflow pod. Do you have some recommendations about which documentation could help us? Tips to solve the problem are also very welcome. And please let us know if cilium networking is pure madness with eks/flyte. 

[Sami Kallio - [Slack thread](https://flyte-org.slack.com/archives/C01P3B761A6/p1632315455164000) ]

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
Will https://docs.flyte.org/projects/cookbook/en/latest/auto/core/containerization/workflow_labels_annotations.html not suffice? cc: @katrogan

**Comment by katrogan** [comment]
At a per-workflow level the docs @samhita-alla linked should work! At a per-execution level, users can individually specify annotations too when they create the execution.

Generally, I think https://github.com/flyteorg/flyte/issues/2070 would perfectly handle this scenario, but work hasn't yet begun.

As a side note, we currently have per-project labels which get applied to all executions within a project, but no such mechanism for annotations

**Comment by samhita-alla** [comment]
> At a per-workflow level the docs @samhita-alla linked should work! At a per-execution level, users can individually specify annotations too when they create the execution.
> 
> Generally, I think #2070 would perfectly handle this scenario, but work hasn't yet begun.
> 
> As a side note, we currently have per-project labels which get applied to all executions within a project, but no such mechanism for annotations

Thanks for the detailed explanation! As per my understanding, there's no additional content that needs to be added to the docs. If so, can we close this issue? Please let me know if this isn't the case.

**Comment by katrogan** [comment]
yup I think the current documentation specifies the only currently supported ways of adding annotations
