### ISSUE TITLE
[Docs] Document flyteadmin task resource config application

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#1677]
### Description

The [task_resources](https://github.com/flyteorg/flyte/blob/5e0647a0d0b2532dbc085d92f25ba6e58f52b047/charts/flyte-core/values.yaml#L417) config block in admin should be explicitly documented.

**Defaults**: are values injected into task containers at execution time when a static task definition fails to specify both requests and limits

**Limits**: Are used to enforce that individual tasks do not set resource requests or limits that exceed the config default.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by katrogan** [comment]
cc @kumare3

**Comment by cosmicBboy** [comment]
This should be handled by combustion team

**Comment by katrogan** [comment]
oh this should be covered by https://github.com/flyteorg/flyte/pull/2081

**Comment by cosmicBboy** [comment]
nice! closing
