### ISSUE TITLE
[Core feature] Create a Conda package for flytekit

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1679]
### Motivation: Why do you think this is important?

A lot of Python users especially in ML and DataScience use conda. Having a conda installable variant will help these users.

### Goal: What should the final outcome look like, ideally?

conda install flytekit

### Describe alternatives you've considered 

NA

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Qiwen-Yu** [comment]
@kumare3 
Can I take this one? I am planning to create a meta.yaml file first and creating a conda-forge package, if I could get the chance.

**Comment by kumare3** [comment]
@Qiwen-Yu my pleasure. Please do. Let me know if you need a new package in flyteorg to host it

**Comment by Qiwen-Yu** [comment]
@kumare3  I am still working on this one. Can I have a couple of more days?

**Comment by kumare3** [comment]
> @kumare3  I am still working on this one. Can I have a couple of more days?

That is absolutely ok ✅

**Comment by Qiwen-Yu** [comment]
@samhita-alla  If this meta.yaml was good, me or someone else need to publish it to https://github.com/conda-forge/staged-recipes. From there, they can build and deploy a conda package. Thank you.

**Comment by Qiwen-Yu** [comment]
@kumare3 @samhita-alla I will make an update by tomorrow.

**Comment by kumare3** [comment]
Actually @Qiwen-Yu, @cosmicBboy was thinking we will publish it to conda-forge channel.

**Comment by Qiwen-Yu** [comment]
@kumare3, that's good. This is what I am doing now. First, have a good meta.yaml file, then we can submit that file as a PR to   https://github.com/conda-forge/staged-recipes, If the PR got passed there, the package can be deployed to conda-forge automatically. Btw, FYI, the current [meta.yaml](https://github.com/flyteorg/flytekit/pull/731/files#diff-5a5337441477e00e6c0a02451ae889fd6b4702ef08b29cf2eec5d7860fde8e09R8), the 8th line, source, will make the conda package sync with package published in pypi.
