### ISSUE TITLE
[Plugin]Model serving using kserve 

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1686]
### Motivation: Why do you think this is important?

Currently Flyte does not have a native integration with any of the model serving systems. For many users, training a model in flyte and deploying it seamlessly to kserve would make their lives easier. 

This also jives well with the kubernetes native eco-system.
More information on kserve can be found [here](https://github.com/kserve/kserve)

### Goal: What should the final outcome look like, ideally?

Ideally we could achieve this in 2 steps
Step 1: Simple deployment
Users can train a model and then invoke a method that deploys the model to kserve
Step 2: Using seamless integration
User should be able to define a `predict` method that they can use in their batch inference as well as in kserve

### Describe alternatives you've considered 

You can do step 1 today using a simply python function. But, a native integration would simplify users lives vastly

###  Propose: Link/Inline OR Additional context 

Spec should be written first

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
Merging this with https://github.com/flyteorg/flyte/issues/2394
