### ISSUE TITLE
[Housekeeping] Configure grpc_health_prob in admin

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#1698]
### Describe the issue

Currently, flyteadmin doesn't have a health check prob in deployment. We need a health check prob for flyteadmin. We can use https://github.com/grpc-ecosystem/grpc-health-probe for running a health check

### What if we do not do this?

It's best practice

### Related component(s)

flyteadmin

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by EngHabu** [comment]
1. We have installed grpc healthcheck [in boilerplate Dockerfile template](https://github.com/flyteorg/boilerplate/blob/master/boilerplate/flyte/golang_dockerfile/Dockerfile.GoTemplate#L23-L27) but it hasn't been applied to [flyteadmin's Dockerfile](https://github.com/flyteorg/flyteadmin/blob/master/Dockerfile).

2. Docs for gRPC liveness probes: [this](https://cloud.google.com/blog/topics/developers-practitioners/health-checking-your-grpc-servers-gke) and [this](https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/).

3. We should also add healthchecks for the REST endpoint
