### ISSUE TITLE
[Docs] Update tuple output examples in flytesnacks/flytekit docs

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#1710]
### Description

currently our docs have output function sigs for tuples as
```python
def func() -> (int, str):
```
We added support for the correct syntax:
```python
def func() -> Tuple[int,str]:
```

The purpose of this issue is to update all instances of the former to the latter

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Qiwen-Yu** [comment]
@cosmicBboy Can I take this one?

**Comment by cosmicBboy** [comment]
@Qiwen-Yu yes! let me assign you. Also let me know if you need any help setting your repo up. Examples in both [flytekit](https://github.com/flyteorg/flytekit) and [flytesnacks](https://github.com/flyteorg/flytesnacks) probably need to be updated.

**Comment by Qiwen-Yu** [comment]
Correct me if I were wrong, the scope is to fix all `tuple` type hints to `Tuple[]` for files in https://github.com/flyteorg/flyte/tree/master/rsts, https://github.com/flyteorg/flytekit/tree/master/docs and https://github.com/flyteorg/flytesnacks/tree/master/cookbook, am I right?

**Comment by cosmicBboy** [comment]
yep, that's correct!

**Comment by samhita-alla** [comment]
@Qiwen-Yu, can you fill in this [form](https://tally.so/r/3qPO7m)?

**Comment by Qiwen-Yu** [comment]
> @Qiwen-Yu, can you fill in this [form](https://tally.so/r/3qPO7m)?

Hi, I have filled in this form. Thanks a lot!
