### ISSUE TITLE
[BUG] flytectl config init clobbers k3s.yaml

### ISSUE THREAD

**Issue by eapolinario** [flyteorg/flyte#1715]
### Describe the bug

Running `flytectl config init` clobbers a pre-existing `~/.flyte/k3s/k3s.yaml`, regardless of its content.

### Expected behavior

`flytectl config init` should not touch `k3s.yaml` files as that file should be generated by `flytectl sandbox` command.

### Additional context to reproduce

Run `flytectl config init` and verify that `~/.flyte/k3s/k3s.yaml` is an empty file.

flytectl version:
```
❯ flytectl version

 A new release of flytectl is available: 0.3.13 → v0.3.13

{
  "App": "flytectl",
  "Build": "e1a7534",
  "Version": "0.3.13",
  "BuildTime": "2021-10-19 14:13:25.759182675 -0700 PDT m=+0.015644128"
}{
  "App": "controlPlane",
  "Build": "e94ed6b",
  "Version": "v0.6.43",
  "BuildTime": "2021-10-19 20:59:12.752645466 +0000 UTC m=+0.022332281"
}%
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
@evalsocket / @pmahindrakar-oss I think this is a high pri bug. It is affecting usage of flytesandbox in flytesnacks
