### ISSUE TITLE
[Docs] Create documentation on how to inject nodes before and after a workflow

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#1725]
### Description

This documentation would show users how to customize their workflows by executing arbitrary tasks and workflows before and after the main workflow function body.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
cc @cosmicBboy I think this is done right?

**Comment by cosmicBboy** [comment]
fixed by #1724
