### ISSUE TITLE
Explicit Version API's and discovery

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#173]
As a user of Flyte and a system administrator, it should be easy to identify the versions of various components.

Proposal:
in the console, show Flyte console version and Admin service version
in FlyteCLI, show FlyteCLI version and admin service version
In flyte propeller show Flytepropeller version.

Eventually, we should be able to show `Flyte Platform version as well, which contains the version of all components`

Some of this can be auto injected using the version library in flytestdlib version package.

**Comment by evalsocket** [comment]
@kumare3 we don't have any grpc function for version in admin.

**Comment by kumare3** [comment]
> @kumare3 we don't have any grpc function for version in admin. 

@evalsocket what do you think about this one?

**Comment by evalsocket** [comment]
Yes you can assign to me

**Comment by evalsocket** [comment]
- [ ] in the console, show Flyte console version and Admin service version
- [ ] in FlyteCLI, show FlyteCLI version and admin service version
- [ ] in Flytectl, show Flytectl version and admin service version
- [ ] In flyte propeller show Flytepropeller version.

**Comment by kumare3** [comment]
Thank you @evalsocket for all the work!

**Comment by evalsocket** [comment]
@kumare3 Can we close this ? and create a new issue for flytecli and flyteconsole.

**Comment by kumare3** [comment]
I think that makes sense @evalsocket, let's close this and make one for flytecli and console
