### ISSUE TITLE
[Docs] Install instructions for flytekit-java

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1731]
### Description

I can't seem to find a doc that details how to get started with flytekit-java (how to install it,... etc.)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
@kumare3 @EngHabu is this issue high priority? Seems like since we don't own that repo (and we don't know how many users rely on it besides Spotify) we can ask them to add better installation instructions?

**Comment by kumare3** [comment]
The repo is part of flyteorg. But yes lower priority at the moment
