### ISSUE TITLE
[Docs] Document Flyte Resource Manager and its usage

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1763]
### Description

Flyte has a powerful feature called FlyteResourceManager, which can be used to globally throttle requests to any downstream service. This needs to be documented and configuration explained.

This is why the REDIS instance is used, and wihtout this documentation users have no idea how to best use the Redis.

Moreover, this documentation is extremely pertinent to Map/Array jobs.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by SmritiSatyanV** [comment]
[Discussion](https://unionai.slack.com/archives/C01H0FN1NJX/p1658766729399059)
