### ISSUE TITLE
[Housekeeping] Add example for Bigquery plugin in flytesnacks

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#1776]
### Describe the issue

Currently, we have README.md for Bigquery plugin, We need an example to test the plugin

- [ ] Flytesnacks Example
- [ ] Fix the Docs with correct example 

### What if we do not do this?

We need an example for the Bigquery plugin, It will help us in functional testing, it will also help us in plugin docs.

### Related component(s)

flytesnacks

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
@vglocus will you be able to do this as well?
