### ISSUE TITLE
Generate Java gPRC stub

### ISSUE THREAD

**Issue by honnix** [flyteorg/flyte#178]
Currently the docker image that is used to generate Java code from proto doesn't generate gPRC stub. 

This is easily solvable by installing one more binary and tweak it a bit. To do that we will need to open source the [image](https://github.com/lyft/flyteidl/blob/master/generate_protos.sh#L5).

**Comment by honnix** [comment]
@kumare3 wdyt?

**Comment by kumare3** [comment]
@honnix absolutely, we should be open sourcing it. I think I am also open to just starting a new repo outside and we can copy things over. Then use this open sourced alternative. Open sourcing sometimes can take too long.
@jonathanburns do you think it is worth open sourcing lyft/protocgenerator? Or should we just bootstrap a new project in flyteorg/...?

**Comment by kumare3** [comment]
I have moved it to milestone 3. I will work on this after tomorrow

**Comment by EngHabu** [comment]
@honnix Is this done as part of your https://github.com/spotify/flytekit-java OSS. Can we close this?

**Comment by honnix** [comment]
Yes it is done there. However it is still strange we don't generate stub here. flytekit-java as I remember doesn't distribute proto and rpc generated code. I will take a look at there first.

There is an ongoing PR in protocgenerator, and I think we could get Java fixed with little effort.

**Comment by kumare3** [comment]
@honnix let me know if we should start merging the PR

**Comment by kumare3** [comment]
This has been completed

**Comment by honnix** [comment]
Do we have the gRPC stubs generated for Java? I don't see them here https://github.com/flyteorg/flyte/tree/master/flyteidl/gen/pb-java/flyteidl/service. Also it would be nice to get those generated classes compiled, packed and uploaded to Maven central. Unlike Go, Java doesn't do source code distribution.
