### ISSUE TITLE
Documentation for tensorflow plugins and how to use/configure them

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#1785]

**Comment by charlie0220** [comment]
I would like to work on this issue, could anyone assign this issue to me, thanks.

**Comment by georgesnelling** [comment]
all yours Charlie.

**Comment by evalsocket** [comment]
@charlie0220 I just created a [pr](https://github.com/flyteorg/flyte/pull/1784) for tensorflow docs.....it's almost ready. We just need one tensorflow example for testing. If you are interested in writing one example then please create a pr https://github.com/flyteorg/flyte/issues/1757
