### ISSUE TITLE
[Plugin][flytekit] Support for Bash scripts using python tasks

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1788]
### Motivation: Why do you think this is important?

Today it is possible to use Raw container tasks to write bash scripts in Flyte tasks. But, raw container tasks should be used for IP restricted scenarios, where users cannot mutate the containers. In other cases, users may want to simply write the task using flytekit and it is possible to load flytekit into the task. This helps them manage the dependencies of the container and also use bash and python interchangeably

cc @palchicz

### Goal: What should the final outcome look like, ideally?

User should be able to declare BashTasks that can be run as a container, container on AWS Batch or, a Pod, with the pod and AWS batch allowing them to mount EFS volumes and other persistent volumes. The API should allow users to specify inputs and outputs and also allow chaining multiple bash commands. 
e.g.

```python
BashTask(
    task_config=Optional<Pod, Batch>,
    Inputs=...
    Outputs=...
    script_path=... OR raw_script=""" """,
    ... # retries, resources etc, container_image
)
```

### Describe alternatives you've considered 

Use RawContainerTask, but this is not the right usecase for it. Though it should continue to work.

###  Propose: Link/Inline OR Additional context 

NA

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by EngHabu** [comment]
Should we also support a list of commands like this? Which we can today just concat with `&&` but later can introduce intratask checkpointing?

```bash
BashTask(
    task_config=Optional<Pod, Batch>,
    Inputs=...
    Outputs=...
    commands=[
      "ls /dir",
      "rm -rf foo"
    ],
    ... # retries, resources etc, container_image
)
```
