### ISSUE TITLE
[Core feature] Add Raw AWS Batch Task

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1792]
### Motivation: Why do you think this is important?

Flyte supports targeting AWS Batch to run Map/Array tasks. So all the infrastructure to target Batch is in place. Batch does offer some customization to the task definition though that we should allow users to provide as a pass-thru. 

[Job Definition Docs](https://docs.aws.amazon.com/batch/latest/userguide/job-definition-template.html)

### Goal: What should the final outcome look like, ideally?

```python
@task(config=AWSBatch(<params similar to register_job_definition>))
def my_task(a: int, b: str) -> str:
  ...
```

We should be able to use this to customize a map task:

```python
@workflow
def my_wf(in_1: typing.List[str]):
  flyte.map(fn, in_1, config=AWSBatch(...))
```

[register_job_definition docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/batch.html#Batch.Client.register_job_definition).

### Describe alternatives you've considered 

N/A

###  Propose: Link/Inline OR Additional context 

Blocked by: https://github.com/flyteorg/flyte/issues/1791

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pingsutw** [comment]
sorry, I'm wrong. Flytekit and flytesnack PRs have not been merged. will get those PRs merged this week.
