### ISSUE TITLE
[Bug] Mention editing charts/flyte/values-eks.yaml in setup with Opta

### ISSUE THREAD

**Issue by RustamovAzer** [flyteorg/flyte#1827]
### Description

When I tried deploying without editing values-eks.yaml I got this error:
```
Failed to convert return value for var get_taxi_output for function myapp.workflows.queries_on_flyte.get_taxi_dataset_task with error <class 'flytekit.common.exceptions.user.FlyteAssertion'>: Failed to put data from /tmp/flytezd5ikpdu/local_flytekit/95adb1bdc4a4d9defb7ce5c82e67f871 to s3://<BUCKET_NAME>/dn/zsr5ihyt7h-n0-3/a6ed27d28f0cbb809555fdae65ee1041 (recursive=True).
```
When I changed `bucketName` under `userSettings` in `values-eks.yaml` from `<BUCKET_NAME>` to the name of my bucket (I also filled `accountNumber`, `accountRegion` and `logGroup`) I managed to run my workflow successfully.

I think it should be mentioned [here](https://docs.flyte.org/en/latest/deployment/aws/opta.html).

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
Thank you, what ll be part of our doc sprint

**Comment by evalsocket** [comment]
@kumare3 It's not the documentation issue, It's opta deployment bug, In set all these values from opta file and we are not override the propeller config for correct bucket name.
