### ISSUE TITLE
[BUG] Flyteadmin label validation is incorrect

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#1833]
### Describe the bug

A kubernetes label **key** can include a prefix followed by a `/` according to https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set

Flyteadmin requires an incorrect, stricter subset of chars when validating labels here: https://github.com/flyteorg/flyteadmin/blob/e94ed6b18112a0fa951b056644821be6276fb091/pkg/manager/impl/validation/validation.go#L65

This check should be updated so that the label **key** is more permissive to reflect the kubernetes standard

### Expected behavior

Valid kubernetes label keys should be accepted at registration time.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by katrogan** [comment]
cc @pmahindrakar-oss

**Comment by pradithya** [comment]
@pmahindrakar-oss @katrogan I am picking this one up.
