### ISSUE TITLE
[BUG] Flyte console does not display inputs & outputs

### ISSUE THREAD

**Issue by janwillemkl** [flyteorg/flyte#1841]
### Describe the bug

The inputs & outputs to workflows and tasks are not displayed in the Flyte console. Instead they show "_No data is available_".

### Expected behavior

Display the inputs & outputs for workflows and tasks in the Flyte console.

### Additional context to reproduce

**Correct:** Inputs & outputs are correctly displayed in previous versions. For example, for executions in a sandbox created with https://raw.githubusercontent.com/flyteorg/flyte/d151597f50212c6a0e1a7ecea753718d8291c768/deployment/sandbox/flyte_generated.yaml

**Missing inputs & outputs:** Executions in a sandbox created with https://raw.githubusercontent.com/flyteorg/flyte/master/deployment/sandbox/flyte_generated.yaml

### Screenshots

![old-flyte-sandbox](https://user-images.githubusercontent.com/26412002/142428095-237eab64-fbf9-4f85-9f4a-989d741bd822.png)

vs.

![new-flyte-sandbox](https://user-images.githubusercontent.com/26412002/142428146-f596fe2b-d51f-4a7c-a2c6-6d726765151c.png)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
Thank you for reporting this big, we released a patch for this, cc @jsonporter

**Comment by kumare3** [comment]
@janwillemkl so for some reason our release process broke, and we are trying to figure out why. Meanwhile i am creating a PR that should release the fix
