### ISSUE TITLE
[Docs] Provide examples for the remaining flyteremote API

### ISSUE THREAD

**Issue by eapolinario** [flyteorg/flyte#1844]
### Description

The current [flyteremote documentation](https://docs.flyte.org/projects/flytekit/en/latest/design/control_plane.html#design-control-plane) has examples for a portion of the API. 

We should have not only explore the rest of the API, but also provide code samples demonstrating the intended use of the API. 

Examples of missing documentation/examples:

1. Registration.
    i. This is the big feature missing documentation. We have the ability to register workflows and tasks programmatically, but no explanation for how to go about it yet.
2. List recent executions
3. List tasks by version
    i. List workflow ids, workflows, and launchplans are not currently exposed in flyteremote. 
4. Expand on how to inspect an execution (basically show examples of how to do this in https://docs.flyte.org/projects/flytekit/en/latest/design/control_plane.html#inspecting-execution-objects). 
5. Terminate executions
6. Explain why we need the `sync` call
7. Fetch an execution
8. Fetch outputs of an execution
9. Fetch outputs of a node within an execution
10. Dynamically create a workflow from fetched tasks

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
Hey @eapolinario. Are you working on this issue? @yongchand would like to contribute to the docs.

Also, we may have to include a FlyteFile example as mentioned in #1534:

Based on a Slack conversation with @cosmicBboy, I'd propose that the extended documentation addresses the use of FlyteFile with the Remote API. We've been able to figure out how to access and download FlyteFile output artifacts with his help, but some additional docs/examples would be great.

**Comment by eapolinario** [comment]
@samhita-alla , I'm not working on this at the moment. @yongchand , please, feel free to take over this ticket. This [file](https://github.com/flyteorg/flytekit/blob/master/docs/source/design/control_plane.rst) contains the current documentation for flyteremote, you can add the examples and explanations there.

**Comment by kumare3** [comment]
Examples

`Explain configuration and how it can be used`
```python
from flytekit.remote import FlyteRemote
from flytekit.configuration import Config

r = FlyteRemote(Config.for_endpoint("flyte.example.net"), default_project="flytesnacks", default_domain="development")
```

`Explain how to create a remote connection can be created for sandbox in oneline`

```python
r = FlyteRemote(Config.for_sandbox()...)
```

`Explain how you can retrieve an existing execution and get various contents`
```
exe = r.fetch_execution(project="flytelab",domain="development",name="fb22e306a0d91e1c6000")
# Get inputs and output keys for the top level execution (workflow itself)
print(exe.inputs.keys())
print(exe.outputs.keys())

# Fetch specific input
with open(exe.outputs['model']) as m:
     # use mode
      ...

# Sync nodes
exe = r2.sync(exe, sync_nodes=True)
print(exe.node_executions.keys())

# Get outputs from a node
m = exe.node_executions['n8'].outputs["model_file"]
```
`Explain how launchplans can be created dynamically for existing workflows`


`Explain create a workflow or task execution`
```python
# Note why execution_name can be provided and this is useful to de-dupe be idempotent
w = r.execute(wf|lp|task, inputs={}, execution_name="f75871bf818994bdc8ee", wait=True)
```

`Explain fetching tasks to execute or to create a workflow`
```python
from flytekit import workflow

tk = r.fetch_task(name="athena.workflows.example.say_hello")
tk2 = r.fetch_task(name="...", version="...", project="...", domain="...")

@workflow
def my_remote_wf(i: int) -> str:
    return tk(name=tk2(i=i))

from flytekit.configuration import SerializationSettings, ImageConfig

wf1 = r.register_workflow(my_local_remote_wf, serialization_settings=SerializationSettings(image_config=None), version="test")

# If you create a task locally and import it, you can use an existing image to register things
img = ImageConfig.from_images("docker.io/xyz:latest", {"spark": "docker.io/spark:latest"})
wf2 = r.register_workflow(my_local_remote_wf, serialization_settings=SerializationSettings(image_config=img), version="test")
```

**Comment by kumare3** [comment]
cc @samhita-alla / @eapolinario / @SmritiSatyanV
