### ISSUE TITLE
[BUG] GCP Logging

### ISSUE THREAD

**Issue by ckiosidis** [flyteorg/flyte#1852]
### Describe the bug

All golang logs written in stderr are being marked by default as ERROR logs in GCP.
this makes it difficult to debug and navigate the logs

### Expected behavior

Levels are being mapped to GCP Log Severity and logs are "compatible" with the platform

### Screenshots

<img width="526" alt="Screenshot 2021-11-22 at 16 54 36" src="https://user-images.githubusercontent.com/6562898/142883279-dc546881-07c3-4d57-b5ce-1f11fb2dd206.png">

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by EngHabu** [comment]
@ckiosidis 
You will also need to bump stdlib dependency version in plugins and propeller repos to pickup this change.

**Comment by ckiosidis** [comment]
I opened some PRs @EngHabu PTAL

**Comment by evalsocket** [comment]
@ckiosidis we also need to update flyteplugins and flytecopilot.

**Comment by ckiosidis** [comment]
PTAL @evalsocket
