### ISSUE TITLE
[BUG] Flyte Native Scheduler does not expose metrics server

### ISSUE THREAD

**Issue by pradithya** [flyteorg/flyte#1864]
### Describe the bug

Flyte scheduler deployment does not expose `/metrics` endpoint for prometheus scraping

### Expected behavior

Flyte scheduler deployment should expose `/metrics` endpoint and publish necessary metrics for monitoring its operation.
Currently the helm chart / deployment has following configuration

```
Name:         flytescheduler-6b986459fd-szfk7
Namespace:    flyte
Labels:       app.kubernetes.io/instance=flyte
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=flytescheduler
              helm.sh/chart=flyte-v0.18.1
              pod-template-hash=6b986459fd
Annotations:  configChecksum: a0c9f11fb2642375a4481c603a7c604c28e32728b175b768bee5b51ecee61b3
              prometheus.io/path: /metrics
              prometheus.io/port: 10254
              prometheus.io/scrape: true
```

Which expect the `:10254/metrics` to be accessible by prometheus, however it seems the port is not opened
```
curl: (52) Empty reply from server
```

Also from our prometheus 

<img width="1460" alt="Screenshot 2021-11-25 at 2 55 27 PM" src="https://user-images.githubusercontent.com/4023015/143394036-36b2d112-ece4-47a6-897e-fc00268237a9.png">

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
What I thought it did? This is a trivial change and important one. Cc @pmahindrakar-oss

**Comment by EngHabu** [comment]
We will need to either update the default value to 10254 or change the helm manifests for scheduler to the correct annotation.
