### ISSUE TITLE
[Housekeeping] Add `go generate ./...` && diff check CI for all repos

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1872]
### Describe the issue

Flyte relies on generating a lot of go code for various reasons (enums, pflags,... etc.). Sometimes developers forget to run go generate before pushing their code. We should have a guard against that to avoid having stale code pushed.

We should run, as part of CI, `make generate` and then check if `git diff` has any changes and fail the CI for it... developers will then have to run it locally and push the changes... this is similar to how we do `helm and diff` and `protobuf and diff` checks in flyte and flyteidl repos respectively.

### What if we do not do this?

Risk of stale code

### Related component(s)

- [ ] flyte 
- [ ] flyteidl 
- [x] flytestdlib  (https://github.com/flyteorg/flytestdlib/pull/111)
- [x] flyteplugins  (https://github.com/flyteorg/flyteplugins/pull/226)
- [x] flytepropeller (https://github.com/flyteorg/flytepropeller/pull/372)
- [x] flyteadmin (https://github.com/flyteorg/flytecopilot/pull/30)
- [x] flytecopilot (https://github.com/flyteorg/flytecopilot/pull/30)
- [x] flytectl (https://github.com/flyteorg/flytectl/pull/229)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
@EngHabu Do we need `go generate ./...` for `flyte` & `flyteidl` ?
