### ISSUE TITLE
[Housekeeping] use golang-ci-lint action instead of binary for all golang repos

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1874]
### Describe the issue

Currently we run the Linter CI for golang repos using the golang-ci-linter binary. But according to the documentation it is faster and better to use the github action. 
https://golangci-lint.run/usage/install/

The UX of all the error highlighting is also better.

### What if we do not do this?

Finding linter errors is troublesome as users have to parse through the console logs

### Related component(s)

flyteidl, flytepropeller, flyteplugins, flyteadmin, flytecopilot, flytectl, datacatalog

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by nishantwrp** [comment]
Hi @evalsocket, can I work on this issue?

**Comment by TheYk98** [comment]
I've  picked this  up as a starter for flyteidl

**Comment by evalsocket** [comment]
@TheYk98  Thanks for picking up, Now it's yours

**Comment by evalsocket** [comment]
@TheYk98 This issue doesn't add any value. I am closing this. 

cc: @EngHabu
