### ISSUE TITLE
feat: Node list view refresh

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyte#1910]
### Motivation: Why do you think this is important?

Update the node-list view on workflow details page.  These changes will add better readability to the list view as well as normalize the experience between graph and node-list views. 

- Replace current node-id with truncated task name
- Keep full task name, with same subtext styling under truncated task name (note: different from comps)
- Show node id as a new column
- re-order columns so that task type is before execution status

### Goal: What should the final outcome look like, ideally?

![Workflow-detail-page-refresh](https://user-images.githubusercontent.com/84735036/145081181-44dacaaa-b810-453a-befd-2dee5b9a5fcd.png)

New node-list view on workflow details page should match comps (with the exception that we will place the full task name under the truncated task name)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by anrusina** [comment]
Already fixed in flyteconsole v.0.43.0
