### ISSUE TITLE
[FlyteCTL Feature] Make version configurable from the terminal on create execution

### ISSUE THREAD

**Issue by ckiosidis** [flyteorg/flyte#1913]
### Describe the feature/command for FlyteCTL

The command currently looks like this

`flytectl create execution --execFile $PATH_TO_EXEC_FILE -p $PROJECT -d $DOMAIN`

the version of the task/workflow is not configurable from the terminal.
If no version is configured in the execFile, then the latest (i assume) will execute.

Making the version configurable from the terminal, will make it easier to execute and test various versions simultaneously (without the necessity to create/modify files), for example from different pull requests, and or automated systems running various executions. 

### Provide a possible output or UX example

`flytectl create execution --execFile $PATH_TO_EXEC_FILE -p $PROJECT -d $DOMAIN -v VERSION`

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pmahindrakar-oss** [comment]
Hi @ckiosidis , thanks for creating the feature request. This should be doable by adding a pflag for Version field https://github.com/flyteorg/flytectl/blob/aa48962103009d2ec045aef98e55438da5cdfdac/cmd/create/execution.go#L154
And then adding an override in this function
https://github.com/flyteorg/flytectl/blob/aa48962103009d2ec045aef98e55438da5cdfdac/cmd/create/execution_util.go#L168

**Comment by ckiosidis** [comment]
this is fix
