### ISSUE TITLE
[Docs] Add fully-specified config docs for flyte.config (needed e.g. FlyteRemote or pyflyte)

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#1917]
### Description

There's no canonical source for all the options for this config file. This leads to friction and digging into source code to figure out what all the valid options are.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
@cosmicBboy, is this still a valid issue?

**Comment by eapolinario** [comment]
We have https://docs.flyte.org/projects/flytekit/en/latest/configuration.html now, but I'm wondering if we should add a few examples.

**Comment by cosmicBboy** [comment]
I think we also need to figure out where in the docs user journey makes sense to link to the config docs.

First thought is perhaps a little note on getting started, the user guide environment setup page, and the deployment guides

**Comment by eapolinario** [comment]
@cosmicBboy , @samhita-alla , is this something that we can get prioritized this next sprint?

**Comment by samhita-alla** [comment]
@eapolinario, can I close this issue as it seems like this can be merged with https://github.com/flyteorg/flyte/issues/2257?

**Comment by eapolinario** [comment]
Sure thing, let's close this one.
