### ISSUE TITLE
[Housekeeping] Add pre check command in flyteadmin & datacatlog

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#1920]
### Describe the issue

Currently we are using postgres image for validating the postgres pod,  It is only used in sandbox.

Because we use flyte-core chart internally in sandbox chart that's why we need it in core but adding a precheck in all component will remove postgres image from flyte-core helm chart 

Currently flytescheduler has pre check for validating flyteadmin pod, we need similar solution for postgres 

### What if we do not do this?

It will reduce 33 security issue that flyte-core currently have 

### Related component(s)

flyteadmin
datacatalog

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
cc: @EngHabu @pmahindrakar-oss @katrogan

**Comment by katrogan** [comment]
related discussion? https://github.com/flyteorg/flyte/issues/1493

**Comment by evalsocket** [comment]
@katrogan it's different issue, In this issue we want to remove postgres image dependency from flyte core helm chart,
