### ISSUE TITLE
[Housekeeping] Move redoc container out of flyteadmin deployment

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#1921]
### Describe the issue

Currently flyteadmin has redoc container in it, Only used in sandbox. It can be moved in sandbox chart rather then flyte-core helm chart

### What if we do not do this?

Redoc contribute around 64 security issue in flyte-core helm chart

### Related component(s)

flyte

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
cc: @EngHabu

**Comment by EngHabu** [comment]
Done
