### ISSUE TITLE
[Core feature] Correctly handle cases when Workflow Executions land on multiple clusters

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#1929]
### Motivation: Why do you think this is important?

As it stands, if for some reason (perhaps a cluster failover/backup and restore) two clusters ended up with the same Flyte Workflow CRDs, propellers in both of these clusters will attempt to make progress to the same Workflow. This can lead to unexpected behavior and conflicting results...

### Goal: What should the final outcome look like, ideally?

flyteidl events already define a `producer_id` field [here](https://github.com/flyteorg/flyteidl/blob/master/protos/flyteidl/event/event.proto#L20), [here](https://github.com/flyteorg/flyteidl/blob/master/protos/flyteidl/event/event.proto#L46) and [here](https://github.com/flyteorg/flyteidl/blob/master/protos/flyteidl/event/event.proto#L145).

**Proposal**

- [ ] Propeller changes
  - [ ] FlytePropeller should start with a config/cmd line param to set that value (clusterName maybe)
  - [ ] Every event propeller sends should populate the `producer_id` field
  - [ ] If it fails to send the event with a particular status that admin will populate, it should not be considered a system failure but should rather quite trying to process this workflow. An MVP version of this is to let system failure handle such rejections and maybe only gracefully handle that error on terminate case to let the workflow CRD get deleted gracefully when encountering this error.

- [ ] Admin changes
  - [ ] On workflow Queued event, it should allow replacing the cluster_id assigned to the execution with the one coming in the event as producer_id. This allows executions to keep running if intentionally moved to a new cluster..
  - [ ] If the workflow moved on to running phase, it should reject any event with a different clusterName and it should respond with a clear error state to indicate the error

### Describe alternatives you've considered 

N/A

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by EngHabu** [comment]
CC @katrogan @mayitbeegh @kumare3

**Comment by kumare3** [comment]
> CC @katrogan @mayitbeegh @kumare3 

This should never happen? Unless we remove a cluster from the set?

**Comment by EngHabu** [comment]
Correct...

**Comment by kumare3** [comment]
` FlytePropeller should start with a config/cmd line param to set that value (clusterName maybe)` We may not need this right? A way could be that we could create logical clusters in FlyteAdmin and Admin can set the logical cluster in the CRD's meta part and Flytepropeller should send this back?

**Comment by EngHabu** [comment]
@kumare3 that would be a way yes.. What are the pros and cons of doing that vs propeller's config? Are there scenarios when the "clusterName" will change mid-way in propeller's operations? like some CRDs will have one value and others will have another? If the proposal is just to use the CRD as a config vehicle mechanism, I think that might not be the way to go... I would rather have it as a static config and when we are able to push configs from the server, this will just come through...
It can be created/generated the first time a deployment happens (through helm... etc.)... so I would like to understand more what you see as pros and cons...

**Comment by eapolinario** [comment]
@katrogan , can we close this issue?

**Comment by katrogan** [comment]
yup!
