### ISSUE TITLE
[Housekeeping] Remove flyte-cli footprint from the documentation

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#1949]
### Describe the issue

Currently in user guide we used `flyte-cli` for interacting with sandbox like https://docs.flyte.org/projects/cookbook/en/latest/auto/deployment/deploying_workflows.html#register-your-workflows-and-tasks
https://docs.flyte.org/projects/cookbook/en/latest/auto/deployment/fast_registration.html
https://docs.flyte.org/projects/cookbook/en/latest/auto/core/type_system/flyte_python_types.html

### What if we do not do this?

it's an old documentation  and flyte-cli is deprecated, It also confusing for new user  

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
cc: @samhita-alla

**Comment by samhita-alla** [comment]
Hey, @evalsocket. I'm assigning this issue to Alekhya as I think she can handle this. Hope you don't mind. :)
