### ISSUE TITLE
[Housekeeping] Use Gorm V2 connection pooling

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#1956]
### Describe the issue

With upgrade to gorm V2 , it supports connection pooling 
https://gorm.io/docs/generic_interface.html#Connection-Pool

In Gorm V1 , we had connection.Close() 
https://github.com/flyteorg/flyteadmin/blob/f60baa3c6c56b17c67d8c492188d56b390899d46/cmd/entrypoints/migrate.go#L51

But with Gorm V2 with connection pooling, Close is not supported explicitly.

### What if we do not do this?

Wont be utilize the performance benefits of using connection pooling

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
duplicate https://github.com/flyteorg/flyte/issues/881
