### ISSUE TITLE
[Docs] FlytePropeller Sharding Deployment

### ISSUE THREAD

**Issue by hamersaw** [flyteorg/flyte#1959]
### Description

Document deployment of FlytePropeller Manager [here](https://docs.flyte.org/en/latest/deployment/cluster_config/performance.html#scaling-out-flytepropeller) to provide a horizontally scaling FlytePropeller environment.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
@hamersaw do we need changes in helm to enable Sharding ?

**Comment by hamersaw** [comment]
> @hamersaw do we need changes in helm to enable Sharding ?

@evalsocket yes we will. I was planning on taking a look at it and opening up a small PR. It seems like a pretty simple update and a nice introduction to helm. Expect a review shortly and probably a few questions!
