### ISSUE TITLE
[Housekeeping] Copy common .github files to `.github` repository

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#1963]
### Describe the issue

We have `.github` directories across all repos under Flyte org. If we have a single [`.github`](https://github.com/flyteorg/.github) repo under flyteorg, we can have all the common `.github` files under one roof.

### What if we do not do this?

Maintenance

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
What does this mean? Can you explain a bit more in and description

**Comment by samhita-alla** [comment]
cc: @evalsocket
