### ISSUE TITLE
[Docs] Ideal flow for MLOps

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#1985]
### Description

Will have to include:
* DAG versioning through Git SHA
* Lyft's use case: Workflow registration on multiple domains when a PR gets merged (ref: https://docs.google.com/presentation/d/1kKGR67oKVPunwOj-qCCPyDlmeBSKFftBUG-VpnJXCyM/edit#slide=id.gfb06fbb202_0_69)
* Rapid iteration through fast-register

Discussion: https://flyte-org.slack.com/archives/CNMKCU6FR/p1636180897109900.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
@kumare3, anything more we have to include?

**Comment by kumare3** [comment]
@samhita-alla did you get a chance to do this?

**Comment by samhita-alla** [comment]
> @samhita-alla did you get a chance to do this?

I will work on this today.
