### ISSUE TITLE
[Docs] Create a separate repository for maintaining static assets

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1986]
### Description

Currently all static assets like images, gifs etc used in docs are stored in a separate untracked head branch in the flyte repo itself.
https://github.com/flyteorg/flyte/tree/static-resources

This is done to reduce the size of the repo, but storing binary assets separately. But, using an untracked branch is un-necessary. A better and simpler to use method can be to use a separate repo in the flyteorg project for managing the assets.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by AlekhyaSasi** [comment]
Created separate repository for static resources: [static-resources](https://github.com/flyteorg/static-resources)

**Comment by samhita-alla** [comment]
Merged all the relevant PRs. Closing this issue.
