### ISSUE TITLE
Resume the previous sandbox

### ISSUE THREAD

**Issue by khuyentran1401** [flyteorg/flyte#1994]
### Describe the feature/command for FlyteCTL

I created a sandbox using: `flytectl sandbox start --source`, and I can access Flyte UI. However, after stopping the container and starting the Docker container to resume the existing sandbox container, I can't access the Flyte UI. 

I could run `flytectl sandbox start --source` and rebuild the container again, but it often takes a long time to start a container. By resuming the container, I can start the container quickly and keep my previous experiments in flyte's sandbox. I wonder if there is any way you can add a feature that allows users to resume a sandbox container?

The command line can look something like this:
```bash
$ flytectl sandbox resume
```

### Provide a possible output or UX example

All of my previous activities in the sandbox are resume.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by EngHabu** [comment]
@jeevb @pmahindrakar-oss do you mind taking a look at this?

it seems that after hibernating and resuming the docker container, it comes up "fine" with ports and volumes mounted correctly. However, running `ps -ef` within the container we see our entrypoint and none of the k3s and other processes running...

**Comment by kumare3** [comment]
@jeevb we might need to make the flyte-entrypoint.sh `restartable` so that we can essentially restart all k3s and flyte services, but restore the state of db's

**Comment by khuyentran1401** [comment]
Here is the output when I run `ps -ef` in the docker container:

```bash
bash-5.1# ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 tini flyte-entrypoint.sh
    7 root      0:00 {flyte-entrypoin} /bin/sh /flyteorg/bin/flyte-entrypoint.sh
   10 root      0:00 sh -c until docker info &> /dev/null; do sleep 1; done
   12 root      0:00 timeout 600 sh -c until docker info &> /dev/null; do sleep 1; done
 1712 root      0:00 bash
 2167 root      0:00 sleep 1
 2168 root      0:00 ps -ef
```

**Comment by jeevb** [comment]
This is interesting. Looks like it is trying to restart since it is going through with the entrypoint again but is stuck on waiting for the docker-in-docker daemon.

**Comment by jeevb** [comment]
> @jeevb we might need to make the flyte-entrypoint.sh `restartable` so that we can essentially restart all k3s and flyte services, but restore the state of db's

I imagine we can do this by using a docker volume + hostpath volume for the postgres container.

**Comment by evalsocket** [comment]
@jeevb log of `/var/log/dockerd.log` 
```
failed to start daemon: pid file found, ensure docker is not running or delete /
var/run/docker.pid
```
I think we need a check for PID in entrypoint script.

**Comment by jeevb** [comment]
> @jeevb log of `/var/log/dockerd.log`
> 
> ```
> failed to start daemon: pid file found, ensure docker is not running or delete /
> var/run/docker.pid
> ```
> 
> I think we need a check for PID in entrypoint script.

Makes sense to skip starting dockerd and k3s if they are already up!

**Comment by evalsocket** [comment]
@jeevb @pmahindrakar-oss @EngHabu @ketan https://github.com/flyteorg/flyte/pull/1990
