### ISSUE TITLE
[Core feature] Project labels doesn't reflect on kubernetes namespace

### ISSUE THREAD

**Issue by yindia** [flyteorg/flyte#2050]
### Motivation: Why do you think this is important?

Currently if we create/update any project with labels then those labels only stay in flyte ecosystem, But it would be great if we can pass those labels in k8s namespaces. 

It's help full for management of different project in single cluster 

### Goal: What should the final outcome look like, ideally?

- Create project with labels 
- Project labels should reflect on Kubernetes namespace

### Describe alternatives you've considered 

NA

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
labels are passed to executions as projects and namespaces do not have a 1:1 mapping. there are many orgs that run fewer namespaces than projects.
