### ISSUE TITLE
Bug: Workflow versions error when filter is applied to executions list.

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyte#2065]
### Motivation: Why do you think this is important?

There is currently a bug in flyteconsole on the workflow detail page where applying a filter to the list of node executions breaks the workflow version section above.

Example of error:
![Screen Shot 2022-01-13 at 11 07 18 AM](https://user-images.githubusercontent.com/84735036/149393636-dd837530-91e8-4965-9df0-8f89be106bcb.png)

### Goal: What should the final outcome look like, ideally?

Selecting a filter on the list of executions should not break the versions section. 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by anrusina** [comment]
PR from Steven: https://github.com/flyteorg/flyteconsole/pull/264
