### ISSUE TITLE
[BUG] Flytectl shouldn't pull beta flytesnacks releases when registering examples

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#2066]
### Describe the bug

When calling `flytectl register examples` without specifying an explicit flytesnacks release, the latest release _even if it's a prerelease_ is used. We should not be using beta releases (e.g. v0.0.3b1) or pre-releases as the default.

### Expected behavior

Only the latest, production-worthy release of flytesnacks examples should be registered by default when calling `flytectl register examples`

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by katrogan** [comment]
cc @pmahindrakar-oss @evalsocket

**Comment by eapolinario** [comment]
in https://github.com/flyteorg/flytectl/blob/c29fbec0a39aa8be2d14d40f3e04139101f0a0e3/cmd/register/register_util.go#L551-L558 we should use https://github.com/google/go-github/blob/master/github/repos_releases.go#L117-L121 instead. The [documentation](https://docs.github.com/en/rest/reference/releases#get-the-latest-release) for that method mentions that it protects against non-prerelease releases.
