### ISSUE TITLE
[BUG] Flyte fails to build dynamic workflow with flytekit-k8s-pod plugin

### ISSUE THREAD

**Issue by ghtyrant** [flyteorg/flyte#2072]
### Describe the bug

We define the dynamic task `dynamic_task_with_pod_subtask`, which in turn calls the pod task `pod_task_with_resources`:
```python

REQUESTS_GPU = Resources(cpu="123m", mem="234Mi", ephemeral_storage="123M", gpu="1")
LIMITS_GPU = Resources(cpu="124M", mem="235Mi", ephemeral_storage="124M", gpu="1")


def get_minimal_pod_task_config() -> Pod:
    primary_container = V1Container(name="flytetask")
    pod_spec = V1PodSpec(containers=[primary_container])
    return Pod(pod_spec=pod_spec, primary_container_name="flytetask")


@task(
    task_config=get_minimal_pod_task_config(),
    requests=REQUESTS_GPU,
    limits=LIMITS_GPU,
)
def pod_task_with_resources(dummy_input: str) -> str:
    return dummy_input


@dynamic(requests=REQUESTS_GPU, limits=LIMITS_GPU)
def dynamic_task_with_pod_subtask(dummy_input: str) -> str:
    pod_task_with_resources(dummy_input=dummy_input)
    return dummy_input
```

Using fast-register, this causes flytekit to crash:

```
[3/3] currentAttempt done. Last Error: SYSTEM::Traceback (most recent call last):

      File "/usr/local/lib/python3.8/dist-packages/flytekit/common/exceptions/scopes.py", line 165, in system_entry_point
        return wrapped(*args, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/flytekit/core/base_task.py", line 468, in dispatch_execute
        raise e
      File "/usr/local/lib/python3.8/dist-packages/flytekit/core/base_task.py", line 465, in dispatch_execute
        native_outputs = self.execute(**native_inputs)
      File "/usr/local/lib/python3.8/dist-packages/flytekit/core/python_function_task.py", line 165, in execute
        return self.dynamic_execute(self._task_function, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/flytekit/core/python_function_task.py", line 300, in dynamic_execute
        return self.compile_into_workflow(ctx, task_function, **kwargs)
      File "/usr/local/lib/python3.8/dist-packages/flytekit/core/python_function_task.py", line 247, in compile_into_workflow
        for arg in task_template.container.args:

Message:

    'NoneType' object has no attribute 'args'
```
From what we found out debugging this, this only happens for fast-register, during sanitizing of container configuration. flytekit deserializes the task and then calls `get_container()` on it - which is overridden in flytekit-k8s-pod's class `PodFunctionTask` (https://github.com/flyteorg/flytekit/blob/master/plugins/flytekit-k8s-pod/flytekitplugins/pod/task.py#L116) to simply return `None`.

Call flow: `compile_into_workflow()` -> `get_serializable()` -> `get_serializable_task()` -> `entity.get_container()`

Versions:
- flyte 
- flytekit 0.26.0
- flyteidl 0.21.19

### Expected behavior

We expect flytekit to be able to handle pod tasks in dynamic workflows.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
This looks like a regression- ages is required.

Cc @hamersaw / @katrogan

**Comment by kumare3** [comment]
cc @wild-endeavor I think this is what you were talking about?

**Comment by jeevb** [comment]
We just ran into this issue today. Tagging @ggydush-fn too. We believe the issue is that sidecars use the k8s_pod attribute instead of container. We could try to mutate the appropriate args here: https://github.com/flyteorg/flytekit/blob/05653c889a0f8f96a4f2424f8d475b9c95e36d74/flytekit/core/python_function_task.py#L244.

**Comment by wild-endeavor** [comment]
i'll start taking a look at this tomorrow... sorry it's taken me this long.

**Comment by wild-endeavor** [comment]
sorry again... will look tomorrow.  had to debug something else today.
