### ISSUE TITLE
[Housekeeping] Supporting upgrade test earlier in pipeline

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#2077]
### Describe the issue

Currently there are no upgrade tests which create data in older version of flyte platform and upgrade to new version of flyte and perform the same operations.

Our clients perform upgrades regularly whenever a new release is out and fresh installations are only for new clients.
The pipelines catch issues with fresh installations earlier but not for upgrades

This issue tracks adding an upgrade scenario test in early stages of the development

* We deploy flyte using current version n
* Register and create executions on this version n
* upgrade flyte to n+1 
* Flyte deployment should be healthy
* Do basic Get /UPDATE/DELETE operations of older flyte entities
* Create new executions and perform the same GET/UPDATE/DELETE operations and additional CREATE too

### What if we do not do this?

Delays the release

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
@pmahindrakar-oss let's plan it after @eapolinario changes in functional test, He is planing to open source functional test.

**Comment by pmahindrakar-oss** [comment]
Any reason to wait till we open source. Since we faced this issue once during our last release, hence would be preferable to get this in sooner.
