### ISSUE TITLE
[Docs] How to display Flyte metrics stored in the admin DB

### ISSUE THREAD

**Issue by veggiemonk** [flyteorg/flyte#2079]
### Description

As we discussed with @kumare3, we were thinking about a way to extract metadata from the database. 
This could be useful for reporting and resources usage optimisation. 

Few things that we find cumbersome:

A) Getting the data. 
		Right now it leaves in the admin DB where production data are, and access control is more restricted.
B) The schema of the DB is not so obvious.
		Some column have a name that is not so self explanatory.
C) The queries are difficult to get right as they query a DAG.

* One possibility for us at Spotify is to sync the data from the DB to BigQuery and do the analytics there.
* Another possibility is to modify flyte-admin to add a command that can run a SQL query and expose the metrics to Prometheus.

As the reporting metrics are not needed in near real time, modifying flyte-admin is a bit of work but with proper guidance/documentation people could contribute their queries upstream.

Let me know what do you think?

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by veggiemonk** [comment]
Hey @kumare3 @EngHabu, this is the issue we discussed on our last call about reporting.

**Comment by kumare3** [comment]
this is not a supported feature. The DB schema should not be a direct dependency
