### ISSUE TITLE
[BUG] Scheduled job started early due to restart

### ISSUE THREAD

**Issue by pradithya** [flyteorg/flyte#2106]
### Describe the bug

We have GKE Node upgrade event in our cluster which cause all Flyte component to be restarted. 
Due to that, all of our scheduled workflow was started right away after Flyte scheduler starts even though it's not yet time.

 

### Expected behavior

Any flyte component restart should not impact scheduled job. 

### Additional context to reproduce

Trying to reproduce it by restarting all flyte component but with no success. 

### Screenshots

<img width="1057" alt="Screenshot 2022-01-28 at 11 57 33 AM" src="https://user-images.githubusercontent.com/4023015/151487083-a2d5b06c-3f4c-429c-9df8-226bc98c8ff9.png">

As shown above, the last execution happen outside of the schedule and in fact too early to happen

<img width="1413" alt="Screenshot 2022-01-28 at 12 28 46 PM" src="https://user-images.githubusercontent.com/4023015/151487510-c17b452f-4e74-4360-8cb5-7a453cff8ff2.png">
From the log above you can see that one workflow was started way before of its schedule. 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by EngHabu** [comment]
@pmahindrakar-oss can you take a look?

**Comment by EngHabu** [comment]
What is the Flyte version?
