### ISSUE TITLE
[BUG] Clean-up opta flyte.yaml

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#2116]
### Describe the bug

The Opta deployment flyte.yaml, contains some unnecessary sections like
setting up SQS / SNS, granting Cloudwatch eventss role. 
These can be found here - https://github.com/flyteorg/flyte/blob/master/opta/aws/flyte.yaml#L14-L39

### Expected behavior

Ideally the only things user should be expected to configure is
1. Setup EKS (or reuse an existing one)
2. Setup S3 (or reuse an existing one)
3. Setup Postgres
4. Setup role to access S3

This is all, but the current deployment seems to be more complicated than it needs to be.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by EngHabu** [comment]
Thanks to Austin Bennett for catching this. We seem to have lingering references to these module outputs in the opta file 
e.g. https://github.com/flyteorg/flyte/blob/master/opta/aws/flyte.yaml#L115

@evalsocket this file is now broken...
