### ISSUE TITLE
[BUG] `flytectl config init` creates config with incorrect dns

### ISSUE THREAD

**Issue by RustamovAzer** [flyteorg/flyte#2128]
### Describe the bug

```
flytectl config init --host=<FLYTEADMIN_URL>:81 --storage --insecure
```
creates config with line:
```
endpoint: dns://<FLYTEADMIN_URL>:81
```
**two slashes**
which returns an error when registering files:
```
Failed | Error registering file due to rpc error: code = |
| | | Unavailable desc = connection error: desc = |
| | | "transport: Error while dialing dial tcp: address |
| | | dns://<FLYTEADMIN_URL>:81: |
| | | too many colons in address"
```

### Expected behavior

If I change line in config to:
```
endpoint: dns:///<FLYTEADMIN_URL>:81
```
**three slashes**
I can register files without errors

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
Cc @evalsocket ?

**Comment by evalsocket** [comment]
@RustamovAzer what's your flytectl version ?

**Comment by RustamovAzer** [comment]
{
  "App": "flytectl",
  "Build": "07e64fd",
  "Version": "0.4.18",
  "BuildTime": "2022-02-01 13:29:06.37101982 +0000 UTC m=+0.017102336"
}

**Comment by kumare3** [comment]
I think this was just fixed. https://github.com/flyteorg/flytectl/pull/274

**Comment by evalsocket** [comment]
@RustamovAzer Try this `flytectl config init --host='<FLYTEADMIN_URL>:81' --storage --insecure`

**Comment by evalsocket** [comment]
I am not able to reproduce your error but we have proper validation for url

**Comment by RustamovAzer** [comment]
Thanks, fixed!
