### ISSUE TITLE
[BUG] Sandbox Logs URL link is broken

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#2135]
### Describe the bug

It seems K8s console updated the log link. 
Previously:
http://localhost:30082/#!/log/flytesnacks-development/bj6r0l60e4-n0-0/pod?namespace=flytesnacks-development
New link:
http://localhost:30082/#/pod/flytesnacks-development/bj6r0l60e4-n0-0?namespace=flytesnacks-development

### Expected behavior

The default log for k8s dashboard should show up correctly

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
@kumare3 where did you get new URL ? For me sandbox logs URL is working fine and it's old one `http://localhost:30082/#/log/flytesnacks-development/nuv4t4dgyz-n0-0/pod?namespace=flytesnacks-development&container=nuv4t4dgyz-n0-0`

**Comment by evalsocket** [comment]
@kumare3 New URL is not working with k8s dashboard, I didn't find any issue with our current URL. Can you explain what needs to be done in this?
