### ISSUE TITLE
[FlyteCTL Feature] Add `flytectl compile` command

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#2141]
### Describe the feature/command for FlyteCTL

Related to https://github.com/flyteorg/flyte/issues/2140. 
Validating compilation currently requires a full registration step (standing up a sandbox cluster... etc. etc.)

### Provide a possible output or UX example

`pyflyte package ...`
`flytectl compile --f archive.tar`

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by EngHabu** [comment]
CC @kumare3

**Comment by kumare3** [comment]
cc @EngHabu did you have an api idea in mind?

**Comment by flixr** [comment]
Seems this can be closed as it's already implemented...
