### ISSUE TITLE
[Core feature] [flyteadmin] Support max connections param

### ISSUE THREAD

**Issue by lupasarin** [flyteorg/flyte#2171]
### Motivation: Why do you think this is important?

We had issues related to too many database connections. And we noticed that [GORM library](https://gorm.io/docs/generic_interface.html) has unlimited connections as a default value (source [here](https://github.com/golang/go/blob/master/src/database/sql/sql.go#L992-L993)). Therefore, we would like to be able to customize this value by exposing it as part of flyteadmin config.

### Goal: What should the final outcome look like, ideally?

A new maxConnections field in [flyteadmin config](https://github.com/flyteorg/flyteadmin/blob/master/pkg/repositories/config/database.go#L10) to be taken by [OpenDbConnection](https://github.com/flyteorg/flyteadmin/blob/master/pkg/repositories/config/postgres.go#L69) and used to configure the new connection being opened.

We can actually provide a config for all of these options if needed:
```
// SetMaxIdleConns sets the maximum number of connections in the idle connection pool.
sqlDB.SetMaxIdleConns(10)

// SetMaxOpenConns sets the maximum number of open connections to the database.
sqlDB.SetMaxOpenConns(100)

// SetConnMaxLifetime sets the maximum amount of time a connection may be reused.
sqlDB.SetConnMaxLifetime(time.Hour)
```

### Describe alternatives you've considered 

We considered customizing cloudsql proxy, by selecting some connection pooling option instead. But we asked Google and they said they don't support it. [Here](https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/88) is an issue explaining it too.

We also considered [pgbouncer](https://www.pgbouncer.org/) as an alternative, but it sounded simpler to do connection pooling in the application rather than to setup another proxy. Especially considering that the GORM library already provides this functionality.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
Cc @katrogan

**Comment by sonjaer** [comment]
Hi @kumare3 @katrogan, do you think this is a good way forward or do you recommend going with something else?

**Comment by katrogan** [comment]
This sounds good! cc @kumare3

**Comment by kumare3** [comment]
@katrogan can we merge you or for config change first

**Comment by kumare3** [comment]
@sonjaer nm, I realized it's already merged. The change should be simple

**Comment by kumare3** [comment]
Cc @pmahindrakar-oss - related to https://github.com/flyteorg/flyteadmin/pull/358

**Comment by kumare3** [comment]
Related to #1956
