### ISSUE TITLE
[Docs] Home page Community tab

### ISSUE THREAD

**Issue by SandraGH5** [flyteorg/flyte#2176]
### Description

The following are a few suggestions for the Community tab on the home page flyte.org:

- To maintain consistency across all pages and announcements, Community Calls could be renamed "OSS Sync Up", or "Open Source Community Sync". Whereas Community Calls is a cooler name, those familiar with OSS Sync Up may not recognize it, and it may be confused with Office Hours (where you can call someone from the community).
I personally prefer "Open Source Community Sync" and if chosen will slowly migrate OSS Sync Up to that name.
  
-  I suggest adding to the Community Tab a link to the Community Page (https://docs.flyte.org/en/latest/community/index.html), and naming it "Community Channels" for example. That page has all channels in one place.

Thoughts?

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
my preference: Open source community Sync. This is also referred to as Townhall, but sounds too bureaucratic

**Comment by SandraGH5** [comment]
Agree, since we also have the UX/UI TownHall.

**Comment by SandraGH5** [comment]
Could we please also rearrange the footer to be the same order as the top tabs: Docs, Resources, then Community (reading from left to right).
And under the "Stay Connected" section we have Slack, GitHub and Email. The URL for email leads back to flyte.org, which is basically the same page. Can we change that to https://groups.google.com/u/0/a/flyte.org/g/users?

**Comment by samhita-alla** [comment]
@SandraGH5, closing this issue. Do let me know if there's anything that still needs to be worked on.
