### ISSUE TITLE
[Docs] How to get to "What is Flyte" from flyte.org?

### ISSUE THREAD

**Issue by SandraGH5** [flyteorg/flyte#2179]
### Description

How do new users find the "What is Flyte" page (https://docs.flyte.org/en/latest/index.html) when they are on https://flyte.org/?

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
@SandraGH5, the GitHub README won't suffice?

**Comment by samhita-alla** [comment]
@SandraGH5 ^^^

**Comment by SandraGH5** [comment]
I guess now they can click on "Learn More" to get there. We can close this, thanks.
