### ISSUE TITLE
[BUG] Incorrect message on flytectl version command when already on latest

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#2183]
### Describe the bug

Despite the installed version being up-to-date, the message A new release of Flytectl is available is being shown. Looks like its a string match issue ( 0.5.1 vs v0.5.1).Looks like its a string match issue ( 0.5.1 vs v0.5.1).

![image (2)](https://user-images.githubusercontent.com/77798312/154517935-c88e188b-adb7-4bae-87f3-a6542a3f4323.png)

### Expected behavior

`A new release of Flytectl is available` should be shown only when the existing binary is not at latest version

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pmahindrakar-oss** [comment]
cc : @AlekhyaSasi @evalsocket

**Comment by evalsocket** [comment]
cc: @TheYk98

**Comment by samhita-alla** [comment]
@pmahindrakar-oss @evalsocket, is this issue resolved?

**Comment by pmahindrakar-oss** [comment]
Dont see this issue anymore . Closing it
```
➜  cloud git:(main) bin/flytectl version
INFO[0000] [0] Couldn't find a config file []. Relying on env vars and pflags. 
{
  "App": "flytectl",
  "Build": "5a331a4",
  "Version": "0.6.14",
  "BuildTime": "2022-09-26 16:02:50.941169 +0530 IST m=+0.019604624"
}%                                                                                                                                                                                                    ➜  cloud git:(main) bin/flytectl upgrade
INFO[0000] [0] Couldn't find a config file []. Relying on env vars and pflags. 
You already have the latest version of Flytectl
```
