### ISSUE TITLE
[BUG] flytectl sandbox failed to start 

### ISSUE THREAD

**Issue by fanqiehc** [flyteorg/flyte#2197]
### Describe the bug

```
🧑‍🏭 Bootstrapping a brand new flyte cluster... 🔨 🔧
delete existing sandbox cluster [y/n]: y
🐋 Running Flyte v0.19.2 release
🐋 pulling docker image for release cr.flyte.org/flyteorg/flyte-sandbox:dind-cb382d0f85cc9e2dc52e6e96dd7a6ae79801eb39
{"status":"Pulling from flyteorg/flyte-sandbox","id":"dind-cb382d0f85cc9e2dc52e6e96dd7a6ae79801eb39"}
{"status":"Digest: sha256:9d61423ca947b53669410bc003debc814feac72d48a5a0e70efdc4c7d6cdb80f"}
{"status":"Status: Image is up to date for cr.flyte.org/flyteorg/flyte-sandbox:dind-cb382d0f85cc9e2dc52e6e96dd7a6ae79801eb39"}
🧑‍🏭 booting Flyte-sandbox container
92022-02-22T10:55:08.360985868Z Starting Docker daemon...
%2022-02-22T10:55:09.426768152Z Done.
72022-02-22T10:55:09.426802741Z Starting k3s cluster...

....

+---------------------------------------------+-----------+-----------+
|                   SERVICE                   |  STATUS   | NAMESPACE |
+---------------------------------------------+-----------+-----------+
| flyte-contour-contour-7cfc9f6fb5-qjg59      | Running   | flyte     |
+---------------------------------------------+-----------+-----------+
| flyte-contour-envoy-tn7jb                   | Running   | flyte     |
+---------------------------------------------+-----------+-----------+
| minio-7749dfc49d-q4sl7                      | Running   | flyte     |
+---------------------------------------------+-----------+-----------+
| flyteconsole-6dd485d769-jxk4z               | Running   | flyte     |
+---------------------------------------------+-----------+-----------+
| flytepropeller-6f5c985cd4-fj2ts             | Running   | flyte     |
+---------------------------------------------+-----------+-----------+
| postgres-8664477894-jb2ww                   | Running   | flyte     |
+---------------------------------------------+-----------+-----------+
| datacatalog-6c5b75c485-bss8r                | Pending   | flyte     |
+---------------------------------------------+-----------+-----------+
| flyte-pod-webhook-5f5d86c46d-5k8nd          | Running   | flyte     |
+---------------------------------------------+-----------+-----------+
| syncresources-27425413-rv6f6                | Pending   | flyte     |
+---------------------------------------------+-----------+-----------+
| flyte-kubernetes-dashboard-7fd989b99d-mf6ht | Running   | flyte     |
+---------------------------------------------+-----------+-----------+
| syncresources-27425414-c54kr                | Pending   | flyte     |
+---------------------------------------------+-----------+-----------+
| syncresources-27425412-t2kxb                | Succeeded | flyte     |
+---------------------------------------------+-----------+-----------+
| flyteadmin-84bb997f9b-m52vj                 | Pending   | flyte     |
+---------------------------------------------+-----------+-----------+
| syncresources-27425411-nhf46                | Succeeded | flyte     |
+---------------------------------------------+-----------+-----------+
| syncresources-27425415-cfpnb                | Succeeded | flyte     |
+---------------------------------------------+-----------+-----------+
| flytescheduler-9d5f844cc-ld9s9              | Pending   | flyte     |
+---------------------------------------------+-----------+-----------+
Error: Get "https://127.0.0.1:30086/api/v1/nodes": dial tcp 127.0.0.1:30086: connect: connection refused
```

### Expected behavior

sandbox should just works.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
@fanqiehc Can you add more details about your env/os ? Please join slack and start a thread there

**Comment by EngHabu** [comment]
Triage:
@evalsocket we can support an optional `--timeout` flag to allow more time for the sandbox to start up (download images... etc.)

**Comment by evalsocket** [comment]
@XiangyangHe Most probably your internet is slow, Flyte sandbox download all the images of flyte that take time, In sandbox we have a 600s timeout. After that we just kill the sandbox container.

**Comment by Abdullahi-Ahmed** [comment]
I had the same issue;
since I was using vm thus my machine was slow that kills the request with short timeout kicks. Also sometimes i forget to turn my docker daemon on, this is important because flyte sandbox runs locally in a docker container. restarting my vm solved for me.

**Comment by kumare3** [comment]
Thank you all for the patience. We are working to reduce the download size and thus make the startup way more snappy

**Comment by fanqiehc** [comment]
It should be a slow network issue.
After several tries, I found that the sandbox container was not killed after the `flytectl` command timeout. About one hour later, all docker images were downloaded, and the cluster started running.
For this issue, I'd like to have a command used to list all necessary docker images, and an option to let me choose a different docker registry when bootstrapping the cluster. It seems non-sandbox ways already have.
@evalsocket @kumare3 , thank you.

**Comment by kumare3** [comment]
Ya the goal of sandbox was to minimize effort for users to try things and in that asking them to change images would be crazy 😰

**Comment by fanqiehc** [comment]
> Ya the goal of sandbox was to minimize effort for users to try things and in that asking them to change images would be crazy 😰

Definitely, it's great to make the sandbox as simple as it should be.
I'm trying to say, the other deployment methods already have the feature I want, my problem is solved.
Thank you again.

**Comment by evalsocket** [comment]
Flyte will downloading all docker images of it's component… this can be slow depending on your network bandwidth and geographical location

Please make sure the docker daemon has enough resources (say 8Gb mem), We are working on reducing the package size to speed up this process for first time users… stay tuned! 

To know what’s happening with these, you can do this:
```bash
flytectl sandbox exec -- kubectl describe pod -n flyte 
```

Finally note that if it remains Pending for long, the operation will timeout and you will get a failure. You can increase the timeout by running:

```bash
flytectl sandbox start --env FLYTE_TIMEOUT=1800
```
To allow it to wait up to 30mins…
