### ISSUE TITLE
[FlyteCTL Feature] Support get execution --launch_spec flag 

### ISSUE THREAD

**Issue by ckiosidis** [flyteorg/flyte#2213]
### Describe the feature/command for FlyteCTL

Users should be able to extract the Launch Spec in a way that is usable from the create execution command.

```
flytectl get execution xyz --launch_spec -p projectabc -d production > exec.yaml
flytectl create execution -p projectabc -d DEVELOPMENT --execFile exec.yaml
```

### Provide a possible output or UX example

The launch spec in a way that is readable and understandable by the `flytectl create execution ...`

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
Cc @pmahindrakar-oss

**Comment by kumare3** [comment]
this will need a join. For now we will close this, if anyone still wants this please re-open
