### ISSUE TITLE
[Docs] flytectl create project documentation doesn't include --project flag, but requires it

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#2231]
### Description

The `flytectl create project` requires the `--project` flag but the documentation doesn't include this:

```
❯ flytectl create project intelligent-moles-17 --name intelligent-moles-17 --id intelligent-moles-17 --description "Hackathon - intelligent-moles-17 team" --labels app=flyte -c ~/.flyte/unionplayground-config.yaml
Error: Project not passed
```

Documentation: https://docs.flyte.org/projects/flytectl/en/latest/gen/flytectl_create_project.html

The purpose of this task is to:
- identify other instances of flytectl commands where `--project` is actually required but doesn't include it in the documentation
- fix those instances

@AlekhyaSasi @SmritiSatyanV 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
Cc @AlekhyaSasi

**Comment by evalsocket** [comment]
@cosmicBboy can you confirm the flytectl version, I fixed a bug earlier, I think you can upgrade the flytectl version

**Comment by samhita-alla** [comment]
> @cosmicBboy can you confirm the flytectl version, I fixed a bug earlier, I think you can upgrade the flytectl version

@cosmicBboy, can you run the command with the latest flytectl version?

**Comment by cosmicBboy** [comment]
upgrading to flytectl 0.5.6 addresses this issue. closing now
