### ISSUE TITLE
[Core feature] Quick Start flow in flytekit (aka script mode)

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#2241]
# Script Mode

To support a lighter-weight flow in the documentation, and for faster deployment in general, we should add a script-mode feature to flytekit/pyflyte.

## Experience
The steps required to get started should be something like this

1. `pip install flytekit`
1. `brew install flytectl`
1. Possibly start sandbox, if not configure flytectl to point to an existing Flyte deployment (if existing, make sure that the s3/gs permissions are set correctly).
   * The sandbox image should be using the new single binary, so it should be much faster to download/run. Other than this, the experience should be identical to today.
1. (These next two steps are up for some debate - Eduardo will think about this a bit more)  User to click on a snippet of code that shows a hello world task and workflow. Clicking should copy the snippet.
1. User `cat > main.py` then paste the snippet.
1. Get the user to run locally so they can see it works locally.  Maybe a `python` command snippet to copy.
1. Another snippet to copy and run `pyflyte run main:tk`
   * The full command for this is `pyflyte run main:wf --image ghcr.io/flyteorg/flytekit_py39:v1.0.0` but the image arg will somehow default to the latest image.
   * `pyflyte run` will perform a fast-register, picking up the storage settings in the flytectl config (which is why they had to be set correctly), and store main.py in s3
   * The image will be a default base image that we start building with every flytekit release (Dockerfile to be in flytekit - we already have one, just confirm it works, maybe add some dependencies).
1. The run will dump out to stdout a FlyteRemote snippet.  User to install ipython or jupyter, open up an interactive session, and copy/paste snippet.

### questions
* There already is an image in the flytekit repo (one for each Python version).  These images are used for the SQL Alchemy/SQLite TaskTemplate task I think.  Is this same image usable?  It should be.  If there are missing common dependencies we should just add them.
* How are inputs handled to `pyflyte run`.  In the past we had code that would fetch the interface from Admin, and then dynamically add click options to the click command, but it was pretty wacky and didn't necessarily improve the user experience.
* Where will the `main.py` be downloaded to?  Probably just current `WORKDIR` of the image until we figure out a more comprehensive interactive experience.

## Other Issues
https://github.com/flyteorg/flyte/issues/1035

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
@cosmicBboy - just fyi, we discussed this briefly yesterday.  A couple of things

* The cookie-cutter thing you and eduardo mentioned - so points 4 and 5 might be replaced with a pyflyte init command of some kind.
* Instead of writing directly to minio, we'll add a new endpoint to Admin from which we can request a signed URL to write to.  It'll always just be https regardless of the backend so that should simplify configuration further.
* We should still make the change for pyflyte to read flytectl config because we can detect the admin endpoint from there.
* We're going to try to resurrect the feature where we iterate through the interface of a workflow and present `--argname` for each input. We don't have to go to Admin for this, we can just parse the workflow/task in question.

Whatever we end up doing for script mode should also work out of the box or nearly out of the box for the existing flytesnacks examples - `pyflyte run core/flyte_basics/whatever.py:my_wf`.

**Comment by wild-endeavor** [comment]
Oh @cosmicBboy we also decided that the run command should just print a flyte remote snippet to stdout.  so like when you do `pyflyte run blah:my_wf` you get a snippet like
```
from flytekit import FlyteRemote, Config
remote = FlyteRemote(config=Config.auto(), project="some project", domain="development")
exec = remote.fetch_workflow_execution(name="abc123")
remote.sync(exec)
print(exec.outputs)
```
or something like that.  The pyflyte run command should be able to capture the execution id and fill that into the snippet.

Not sure what we do about project/domain - @kumare3 @eapolinario did we consider that?

**Comment by eapolinario** [comment]
Good question, we didn't really touch on how to specify project and domain. IMO we should just assume default values for both. 

How about we default to `project="quick-start"` and `domain="development"` ?

**Comment by wild-endeavor** [comment]
can we default to "flytesnacks"?  One less thing to change in the sandbox setup.
