### ISSUE TITLE
[Core feature] Include Intratask Checkpoints in `Recovery` Mode

### ISSUE THREAD

**Issue by sbrunk** [flyteorg/flyte#2254]
### Motivation: Why do you think this is important?

[Intratrask-checkpointing](https://github.com/flyteorg/flyte/issues/709) is a very useful feature for fast recovery if long running tasks such as model training runs fail.

However, intratrask-checkpoints only work within the same execution, i.e. when a pod fails and is retried. If the complete execution fails, and we rerun it in [`Recovery mode`](https://github.com/flyteorg/flyte/issues/1151), intratask checkpoints are not used by the new execution.

### Goal: What should the final outcome look like, ideally?

If a task fails, and  we run it again in `Recovery` mode, flyte should look for checkpoints in the original execution, and make them available to the recovered execution.

In addition, we should also provide checkpoints as task meta output in order to let the user resume from a previously failed execution even from a different workflow version. This is mostly to support fast iteration during development, i.e. when the execution has failed due to a bug in user code. The user could then optionally provide the checkpoint path as task input to speed up a new training run.

By providing the checkpoint url via API during execution we could also better support use-cases like experiment tracking. I.e. we could save the `TensorBoard` run directory on each checkpoint, and then serve it directly from the bucket location of the checkpoint during training.

### Describe alternatives you've considered 

An explicit `Recover from` to recover from a different version, but this is considered too error prone due to versioning issues.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by andrewwdye** [comment]
I'm tackling the first part of this feature request -- passing the previous checkpoint to a recovered execution (like we do for retried tasks). I intend to include the path in the node execution closure and store in the admin DB. This will require changes in both propeller and admin.

I will defer treating checkpoints as meta outputs and optionally passing them as meta inputs to a separate workflow for future work, as this has much larger implications.

**Comment by hamersaw** [comment]
Using intra-task checkpointing across workflow executions could be very dangerous.
