### ISSUE TITLE
[Docs] Improve FlyteKit configuration documentation

### ISSUE THREAD

**Issue by AlekhyaSasi** [flyteorg/flyte#2257]
### Description

We need to include detailed documentation for all the configuration options available for flytekit.

https://docs.flyte.org/projects/flytekit/en/latest/configuration.html

[Slack archives](https://unionai.slack.com/archives/C01HA7KQP7X/p1646945388578159)

__Edit__:

The original intent of this issue is to better document how to write flyte.config toml files (see [flytekit unit tests](https://github.com/flyteorg/flytekit/blob/master/tests/flytekit/unit/configuration/configs/good.config)), as there's no place in the flytesnacks/flytekit API reference that shows what all the valid values are.

The purpose of this issue is to create a page or pages on what the different configuration options are.
 
### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
Hey @AlekhyaSasi! Can you give a detailed description of the issue? If this seems like a good first issue, @marc-union could take it up, maybe?

**Comment by AlekhyaSasi** [comment]
@marc-union added the relevant slack archive link in the description.
