### ISSUE TITLE
[Core feature] Replace free cache with bigcache

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/flyte#2259]
### Motivation: Why do you think this is important?

Writes and reads in [bigcache](https://github.com/allegro/bigcache) are faster than in `freecache`. 
Flyte can have better performance by leveraging with `bigcache`.

### Goal: What should the final outcome look like, ideally?

Replace `freecache` with `bigcache` in FlyteAdmin and FlytePlugin

### Describe alternatives you've considered 

N/A

###  Propose: Link/Inline OR Additional context 

Benchmark tests: https://gist.github.com/janisz/53e487224ed9bad0d06a
https://github.com/allegro/bigcache#benchmarks

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by brucearctor** [comment]
This was closed as completed -- where is the link with the associated PR?
