### ISSUE TITLE
Cleanup Flytekit dynamic jobs and metaclasses

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#226]
**Motivation: Why do you think this is important?**
In adding SDK support for dynamic launch plans and sub workflows, the flytekit code has become a bit messy.  We need to clean it up.  Also, there is now no consistency between the SDK launch plan, task and workflow objects.  There are no "Runnable" workflows for instance.  All three Flyte entities should ideally follow the same pattern.

**Goal: What should the final outcome look like, ideally?**
Users should be able to clearly understand the various Sdk classes meant to represent Flyte entities, and all the code around dynamic job handling.

**Describe alternatives you've considered**
N/A

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Additional context**
N/A

**Is this a blocker for you to adopt Flyte**
N/A

**Comment by kumare3** [comment]
this has already been complete. We do not use metaclasses anywhere
