### ISSUE TITLE
[BUG] [flytekit] Using enum as parameter doesn't work with flyte-remote 

### ISSUE THREAD

**Issue by zm8597** [flyteorg/flyte#2278]
### Describe the bug

When using enum as parameter for flyte workflow in Flyte Console everything works fine, but it doesn't with flyte-remote.

### How to reproduce:
Create a dummy workflow with enum as parameter and register it.

```python
class TestEnum(Enum):
    A = "a"
    B = "b"

@task
def test_enum_as_parameter_task(enum_parameter: TestEnum) -> None:
    print(enum_parameter.value)

@workflow
def test_enum_as_parameter_workflow(enum_parameter: TestEnum) -> None:
    test_enum_as_parameter_task(enum_parameter=enum_parameter)
``` 

Create another workflow that uses previous one with referencing.
```python
remote = FlyteRemote(
        flyte_admin_url="example_admin_url",
        insecure=False,
        default_project="example_project",
        default_domain="development",
    )
test_remote_workflow = remote.fetch_workflow(
    name="example.test_enum_as_parameter_workflow",
    version="example_version",
)

@workflow
def test_workflow(enum_parameter: TestEnum) -> None:
    test_remote_workflow(enum_parameter=enum_parameter)
``` 

Try to register it and registering will fail with error message:
![image](https://user-images.githubusercontent.com/67868248/158978646-9d38395e-32e7-44a5-8fa0-8bf75b65e8dd.png)

### Expected behavior

Enums as parameters in remote workflows work.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
@zm8597 huge updates are coming for flyteremote- cc @wild-endeavor

**Comment by pingsutw** [comment]
@zm8597 which version of flytekit are you using? how did you register the workflow? pyflyte register or pyflyte run?

it works for me.
<img width="1830" alt="image" src="https://user-images.githubusercontent.com/37936015/197892348-38f4c950-ebd0-4a47-a31b-cf31dfddd2c7.png">

**Comment by zm8597** [comment]
Hey, this got fixed with new versions. I don't know what version we were using at the time we raised this issue. Thank you for your response! :smiley:
