### ISSUE TITLE
[Core feature] Flytepropeller should send IsDynamic and IsParent

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#2282]
### Motivation: Why do you think this is important?

It's already been established that [IsDynamic is a useful flag to have](https://github.com/flyteorg/flyte/issues/2132). The [current implementation](https://github.com/flyteorg/flyteadmin/blob/560d784da6d26334716bb3e1b2ab43b5fb2a173e/pkg/repositories/transformers/node_execution.go#L241,L246) for determining that bool and/or `IsParent` is **incredibly expensive**.

It requires joining every node execution fetched in a `get` or `list` call against the node executions table to preload child node executions. In the case of a subworkflow with thousands of nodes, we're fetching a massive amount of node executions to essentially determine whether or not any child node executions exist.

### Goal: What should the final outcome look like, ideally?

Flytepropeller already handles dynamic and subworkflow nodes. Events sent for dynamic node executions should include a flag for is_dynamic and is_parent. This can be persisted in flyteadmin and obviate the expensive join described above to propagate these bits back to api callers.

### Describe alternatives you've considered 

The current, very non-performant implementation.

Alternatively flytekit could also capture the is_dynamic bit at workflow serialization time, but if we are concerned with the distinction between a node execution producing child nodes to be considered dynamic, this becomes a runtime-only computable value. 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by katrogan** [comment]
cc @EngHabu @pmahindrakar-oss @kumare3

**Comment by kumare3** [comment]
@katrogan this is not only for isDynamic right this is also for isParent?

**Comment by katrogan** [comment]
@kumare3 yeah it's in the issue title, but updated the description some more
