### ISSUE TITLE
[Core feature] Allow to choose Spot Instances at workflow start time

### ISSUE THREAD

**Issue by Antaxify** [flyteorg/flyte#2284]
### Motivation: Why do you think this is important?

At this point, we can set `interruptible=true` either at task or workflow level. I would be great if we could set this flag when we **start a workflow**, similiar to `max parallism`.  This would allow to use the very same workflow as follows:

- during development / testing, run with `interruptible=false` to get feedback asap
- for big production runs where cost efficiency is more important, run with `interruptible=true`
- for time critical executions (e.g. an approaching deadline) , run with `interruptible=false` 

This would be a very helpful addition to Flyte. :)

### Goal: What should the final outcome look like, ideally?

- `interruptible` can be set at workflow start, similar to `max parallism`
- can be set when a workflow ist started using flytectl, console, flyte_remove, or api

### Describe alternatives you've considered 

Registering the same workflow twice, once with `interruptible` set to true, once set to false

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
Cc @pmahindrakar-oss / @EngHabu

**Comment by katrogan** [comment]
this could be a great candidate for the newly [expanded execution config](https://github.com/flyteorg/flyteidl/pull/253/files#diff-6c101b93284e15aa7ab1060e7cab2d403065a1b27529d01e0540092bcaa23139R104) as a matchable resource too

**Comment by MorpheusXAUT** [comment]
Hi!
As briefly mentioned on Slack, I'd be willing to look into this, feel free to assign the issue to me :smile:

**Comment by kumare3** [comment]
Assigned
