### ISSUE TITLE
[Core feature] Report complete subtask metadata from map tasks

### ISSUE THREAD

**Issue by hamersaw** [flyteorg/flyte#2288]
### Motivation: Why do you think this is important?

Currently, map tasks (from both `aws_batch` and `k8s-array` plugins) report incomplete subtask metadata. This manifests as:
(1) Not reporting subtasks until they have started
(2) Not reported subtasks that were successfully read from cache, or reporting cache status of completed subtasks
(3) Not enabling mapping of log links to specific subtasks

### Goal: What should the final outcome look like, ideally?

To effectively track map task execution in the UI and various cli mechanisms map tasks need to report more complete sub task metadata.

### Describe alternatives you've considered 

Leaving it as is results in a poor map task experience.

###  Propose: Link/Inline OR Additional context 

We plan on adding fields to the [ExternalResource proto](https://github.com/flyteorg/flyteidl/blob/7c724bded6a30a90f86499fc35d17c8c8f481e82/protos/flyteidl/event/event.proto#L191-L207) for subtask specific metadata. In addition to the already added `index`, `retry_attempt`, and `phase` fields we propose two additional fields: `log` which will be analogous to the [logs field](https://github.com/flyteorg/flyteidl/blob/7c724bded6a30a90f86499fc35d17c8c8f481e82/protos/flyteidl/event/event.proto#L148) from the [TaskExecutionEvent proto](https://github.com/flyteorg/flyteidl/blob/7c724bded6a30a90f86499fc35d17c8c8f481e82/protos/flyteidl/event/event.proto#L129) and `cache_status` which is analogous to the [similarly named field](https://github.com/flyteorg/flyteidl/blob/7c724bded6a30a90f86499fc35d17c8c8f481e82/protos/flyteidl/event/event.proto#L99) on the [TaskNodeMetadata proto](https://github.com/flyteorg/flyteidl/blob/7c724bded6a30a90f86499fc35d17c8c8f481e82/protos/flyteidl/event/event.proto#L97).

This additional data is included in each [TaskExecutionEvent](https://github.com/flyteorg/flyteidl/blob/7c724bded6a30a90f86499fc35d17c8c8f481e82/protos/flyteidl/event/event.proto#L129) for map task execution. On the FlyteAdmin side, with [this PR](https://github.com/flyteorg/flyteadmin/pull/375/files) we will populate the [metadata field](https://github.com/flyteorg/flyteidl/blob/7c724bded6a30a90f86499fc35d17c8c8f481e82/protos/flyteidl/admin/task_execution.proto#L119) on the [TaskExecutionClosure proto](https://github.com/flyteorg/flyteidl/blob/7c724bded6a30a90f86499fc35d17c8c8f481e82/protos/flyteidl/admin/task_execution.proto#L77). So for map tasks this data will be available through something like `taskExecution.closure.metadata.externalResources`.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pmahindrakar-oss** [comment]
So only the tree view for the node execution details would be impacted by this change over here https://github.com/flyteorg/flytectl/blob/ffc9f8b5b3a7e0b88f3f4e825b09d5e0307992ad/cmd/get/node_execution.go#L225

But the regular yaml or json view should work automatically once the new field is available for the external resource.
If its a new field , then just updating the idl in flytectl should do for this view.
