### ISSUE TITLE
[Docs] Flytekit.extend types shows Schema instead of StructuredDataSet

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#2290]
### Description

StructuredDataset is the preferred type now and all new extensions should use it instead of Schema

This link should be updated - https://docs.flyte.org/projects/flytekit/en/latest/types.extend.html#extend-type-system

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
@AlekhyaSasi, could this be made a part of the [generation of Flytekit plugins API issue](https://github.com/flyteorg/flyte/issues/1279) you're working on?
