### ISSUE TITLE
[BUG] [flytekit] Issues with StructuredDataset

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#2312]
### Describe the bug

* Since we use typing.Annotated to specify things like format and columns, at instantiation time, we don't know what the correct format is.  This leads to incorrect literals if the user does not manually override.
* Also noticed that the default protocol for pandas DataFrame is gs.  It shouldn't matter but if we have one i feel like it should be s3.  Let's go through the code and make sure that everywhere we need it, it's been specified correctly (i.e., when we're about to encode, we're detecting the raw output prefix setting, getting the right location, and setting the right protocol from that.

### Expected behavior

Fix the bug.

### Additional context to reproduce

https://github.com/flyteorg/flytekit/pull/909

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pingsutw** [comment]
Fixed it. https://github.com/flyteorg/flytekit/pull/909
