### ISSUE TITLE
[Core Feature] Add project level API to return the global settings

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#2322]
### Describe the issue

With this issue https://github.com/flyteorg/flyte/issues/2070
Project domain settings have been added for execution config and which will be shown in the UI on the domain landing page.

We also need Project level global settings which the user can view

### What if we do not do this?

User wont be aware of  global config which can get used in the absence of project-domain settings

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by katrogan** [comment]
hey @pmahindrakar-oss can you expand on what is a project-level global setting? do you mean the default settings at the per-domain level in the config?

**Comment by pmahindrakar-oss** [comment]
Hi @katrogan 
So if you check the UX here https://www.figma.com/file/s06CbgfgMMJjeDPxORhOJU/Flyte-Console we have a domain setting global which is nothing but project level default settings  that get applied to all domains. 

project-domain through matchable attributes provides an override for this behavior which we now have in flyteadmin.
This ticket is track the project level default settings. 

Let me know if that makes senses

**Comment by katrogan** [comment]
yeah thanks for clarifying, i think i got thrown off b/c the hierarchy is domain -> domain/project -> ... but I see this is just a way to expose the default/domain settings, makes sense!

**Comment by pmahindrakar-oss** [comment]
https://docs.google.com/document/d/1Ju74RnljISh2Hg4PD_2B5FDw8IKooVjOV1ZidAthmF0/edit#heading=h.xlbmxx7jayoi

**Comment by pmahindrakar-oss** [comment]
Problem statement  for review : https://docs.google.com/document/d/17yP8r2BOcBAAsVOAbTPYmrIAE2BC_XGCVJ6v2fcdJzk/edit?usp=sharing

**Comment by jsonporter** [comment]
https://github.com/flyteorg/flyteconsole/pull/689
