### ISSUE TITLE
[Feature] Abstraction and standardization of query tasks

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#238]
**Motivation: Why do you think this is important?**
Now that we have a Presto task and a Hive task in Flytekit, we should consider abstracting them both behind a more general Flytekit query task.

We should also change the way Hive queries currently run (as de facto dynamic tasks), and follow the pattern established by the new Presto plugin.  It may not be possible to do this in a backwards compatible way however, especially considering legacy code at Lyft, so the development of a general query task that supports Hive may be independent from the existing Hive task.

**Goal: What should the final outcome look like, ideally?**
Flytekit tasks that are more general.

**Describe alternatives you've considered**
None.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [x] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Additional context**
Original Presto task issue: https://github.com/lyft/flyte/issues/203

**Comment by wild-endeavor** [comment]
cc @lu4nm3 @kumare3

**Comment by kumare3** [comment]
I think this should be done by elevating SQL as an alternative to container in the task spec. IMO task spec contains a reference to the portable code, for which container is a great proxy. In case of queries you don’t need a container as the code itself is portable. And so we could capture the code inline

**Comment by kumare3** [comment]
this has been already done. Flyte TaskTemplates can have queries in them
