### ISSUE TITLE
[Housekeeping] flytectl unit tests should not make api calls

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#2384]
### Describe the issue

Currently flytectl unit tests make request calls to fetch release versions, start sandbox docker containers, and more without mocking out external network dependencies. 

By definition these aren't unit tests and tying a dependency to a live service should be mocked out of tests.

### What if we do not do this?

Hammer github and get rate limited.

### Related component(s)

flytectl

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pmahindrakar-oss** [comment]
Hi @katrogan we have an existing issue which was reported earlier https://github.com/flyteorg/flyte/issues/2173
Closing this one as a dup
