### ISSUE TITLE
[Docs] Flytesnacks examples have pyflyte run and FlyteRemote code snippets (with tests)

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#2387]
### Description

To make UX better, have code snippets at the bottom of each example showing how to run it using `pyflyte run` and `FlyteRemote`

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
https://github.com/flyteorg/flytesnacks/pull/736
