### ISSUE TITLE
[Docs] Port the Documentation Standards Guide to a Flytesnacks contributing page

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#2388]
### Description

Move the content in https://docs.google.com/document/d/1rhEZqd3Ae8Y9HUxg7yF6LarHrfIHKnPyeke8aMSPgis/edit#heading=h.au3aq9ubs9hf

Into a dedicated "Style Guide" page in the Community section of the docs: https://docs.flyte.org/en/latest/community/index.html#

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by mkubdev** [comment]
Hi, can I be assigned to this issue, please?

**Comment by Rutam21** [comment]
#self-assign

**Comment by aniketh-varma** [comment]
#self-assign

**Comment by trishitapingolia** [comment]
I have already started working on this issue, please assign me to it.

**Comment by trishitapingolia** [comment]
Let me know if i should continue this.

**Comment by samhita-alla** [comment]
@trishitapingolia, thanks for creating the PR. Will review it shortly.
