### ISSUE TITLE
[Feature] Finish Presto open-source client

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#239]
**Motivation: Why do you think this is important?**
Internally a Presto client has already been developed and is in use at Lyft (because the Presto platform at Lyft has a unique API) and the open-source Presto client remains incomplete.  We should finish it.

**Goal: What should the final outcome look like, ideally?**
A open-source Presto client in place of the no-op client in the code today, that works with something like an [Amazon Athena](https://aws.amazon.com/athena/).

**Describe alternatives you've considered**
None.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [x] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Additional context**
Original Presto task issue: https://github.com/lyft/flyte/issues/203

**Comment by wild-endeavor** [comment]
cc @lu4nm3 @kumare3

**Comment by kumare3** [comment]
again defer to agent
