### ISSUE TITLE
[Housekeeping] Flytesnacks: add pre-commit linter (flake8, black, etc) for example .py files

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#2401]
### Describe the issue

Right now flytesnacks examples are not linted, which leads to inconsistent formatting.

### What if we do not do this?

The examples continue to have inconsistent formatting, which may put off users, but mainly it makes reading the examples harder. It also incurs additional burden on OSS reviewers.

### Related component(s)

flytesnacks

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by SmritiSatyanV** [comment]
http://localhost:30080/console/projects/flytesnacks/domains/development/executions/fcd7c907e539f422cbe9?duration=all
