### ISSUE TITLE
[BUG] gRPC error codes are not correctly parsed when retrieving launchplan

### ISSUE THREAD

**Issue by hamersaw** [flyteorg/flyte#2404]
### Describe the bug

This was identified because a dynamic task requested a launchplan that does not exist. Propeller attempts to identify the [cause of the detected error](https://github.com/flyteorg/flytepropeller/blob/d3bef3c3c01127b9321e075ae84c2b27d598cd8a/pkg/controller/nodes/dynamic/dynamic_workflow.go#L349) so that it can label the failure as either a system or a user failure. In this case, a user failure will automatically fail the node (because it is unrecoverable). However, it is wrongly labeled as a system failure. Therefore, propeller continually attempts to execute the node with backoff and it results in the node taking a long time to properly fail (ex. >1hour).

I believe this is caused by the [GetErrorCode](https://github.com/flyteorg/flytestdlib/blob/6185cd0d84cc1e0eaf3af1ed7ef42c144d2f6165/errors/error.go#L73) function using the coder interface, whereas gRPC errors require the [status.Code](https://pkg.go.dev/google.golang.org/grpc@v1.46.0/status#Code) function. This should be tested extensively.

### Expected behavior

Propeller should detect the missing launchplan as a user error and fail immediately.

### Additional context to reproduce

Create a dynamic task which requests a launchplan that does not exist.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
This is a very good find @hamersaw. I think the interface is very close and so probably very hard to identify (unit32 vs string)
Does this affect all other error codes from admin? I have seen other error codes identified

**Comment by hamersaw** [comment]
@wild-endeavor actually discovered the repetitive system retries. It should affect everywhere the [GetErrorCode](https://github.com/flyteorg/flytestdlib/blob/6185cd0d84cc1e0eaf3af1ed7ef42c144d2f6165/errors/error.go#L73) which seems to be the [Is}(https://github.com/flyteorg/flytestdlib/blob/6185cd0d84cc1e0eaf3af1ed7ef42c144d2f6165/errors/error.go#L26) and [IsCausedBy](https://github.com/flyteorg/flytestdlib/blob/6185cd0d84cc1e0eaf3af1ed7ef42c144d2f6165/errors/error.go#L87) functions in flytestdlib. So everywhere we use those to find the error code of a gRPC error (which may be frequent).

I think the example you linked works because we [parse the error](https://github.com/flyteorg/flytepropeller/blob/d3bef3c3c01127b9321e075ae84c2b27d598cd8a/events/errors/errors.go#L58) with `status.FromError` first. For example:
```
type ErrorCode = string
type coder interface {
	Code() ErrorCode
}

func main() {
	var e error
	e = status.Error(codes.NotFound, "entity is not found")

	if er, ok := e.(coder); ok {
		fmt.Printf("coder code: %v\n", er.Code())
	}

	if er, ok := status.FromError(e); ok {
		fmt.Printf("status code: %v\n", er.Code())
	}
}
```
prints `status code: NotFound`.

This should be a quick fix, but it is important.

**Comment by hamersaw** [comment]
This seems to be a localized issue with [retrieving launch plans](https://github.com/flyteorg/flytepropeller/blob/24e93cd9e7930bac95968f46c0d6b6fc46bad3e3/pkg/controller/nodes/subworkflow/launchplan/admin.go#L145). In [other locations](https://github.com/flyteorg/flytepropeller/blob/24e93cd9e7930bac95968f46c0d6b6fc46bad3e3/pkg/controller/nodes/subworkflow/launchplan/admin.go#L212-L213) the gRPC error code is parsed and the error is wrapped with [RemoteErrorNotFound](https://github.com/flyteorg/flytepropeller/blob/24e93cd9e7930bac95968f46c0d6b6fc46bad3e3/pkg/controller/nodes/subworkflow/launchplan/errors.go#L11).
