### ISSUE TITLE
[Docs] Create Deployment Guide Docs ( based on Terraform )

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#2419]
### Description

Documentation of Deployment on AWS has problems.  

After creating/fixing the [terraform] code to make the user experience easier, create the documentation.  

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by brucearctor** [comment]
Blocked by https://github.com/flyteorg/flyte/issues/2410

**Comment by wild-endeavor** [comment]
We're removing opta entirely because it's no longer being supported.  We'll slowly transition to terraform, but also push more of the deployment responsibility to the user.

**Comment by brucearctor** [comment]
@wild-endeavor  -- check updated title/description.  Suggested for this issue to remain/re-open, to address [ using terraform and docs, rather than opta.  As discussed, Opta was more of a bandaid and distraction rather than a good idea over the non-immidiate term ]

**Comment by brucearctor** [comment]
Do share more about 'push more of the deployment responsibility to the user'?  That seems something an open source project would want to make really easy for the user?

**Comment by wild-endeavor** [comment]
This issue is kinda broad though... we know we have to move to TF, so if this issue is meant to encapsulate that whole project, I guess that's fine.  But like, "improve documentation" isn't really actionable. What specifically do you think should be improved and what is the metric for success/acceptance criteria?

**Comment by brucearctor** [comment]
Blocked by: https://github.com/flyteorg/flyte/issues/2421

**Comment by brucearctor** [comment]
Relies on https://github.com/flyteorg/flyte/issues/2420

**Comment by brucearctor** [comment]
changed to 'create' not improve'.  There is no deployment guide for relying on terraform - which is finally going to be the go-to for Flyte?  Also, why terraform ( as I hear that was decided), and not pulumi or other?  Where did that discussion happen [ I missed the discussion, can I see that ] -- was that an OSS community decision?  I'm not advocating for a different decision, but am advocating for transparent decision making as it relates to OSS project

**Comment by brucearctor** [comment]
Also, @wild-endeavor Also, why was terraform ( as I hear that was decided) the choice, and not pulumi or other?  Where did that discussion happen [ I missed the discussion, can I see that ] -- was that an OSS community decision?  I'm not advocating for a different decision, but am advocating for transparent decision making as it relates to OSS project

**Comment by eapolinario** [comment]
We have published a terraform-only reference implementation. This is no longer applicable.
