### ISSUE TITLE
[Feature] Deprecate Travis, or GitHub Workflows

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#242]
**Motivation: Why do you think this is important?**
Some of our repos use Travis CI, some of them use GitHub actions.  We should pick one and move everything over to it.  (I feel like we should pick GH, but that's mostly personal preference).

**Goal: What should the final outcome look like, ideally?**
Seamless testing, package and docker image hosting and publishing, all done somewhere.

**Describe alternatives you've considered**
None.

**Flyte component**
- [x] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Comment by wild-endeavor** [comment]
cc @jonathanburns

**Comment by mweagle** [comment]
+1 to GH Actions

**Comment by kumare3** [comment]
We have deprecated Travis CI complete, I will close this out.
