### ISSUE TITLE
[Core feature] Test Deployments 

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#2420]
### Motivation: Why do you think this is important?

Needing to ensure Flyte does not lose users due to code/docs not being followable and/or having problems

### Goal: What should the final outcome look like, ideally?

If the relevant terraform files are tested ( ex: nightly ) we will notice if anything breaks them and able to more readily respond/fix.  And get these recipes/modules to live somewhere like github/flyteorg/<$DEPLOYMENT_MODULES$> ( maybe in flyteorg/flyte in folder OK, or perhaps new repo ... not 100% sure where best at this time

### Describe alternatives you've considered 

Condidered testing individual separately, but arrived at a nice pattern that looks to address in a way that also does the 'regular' nightly testing, and in a way that minimizes resource utilization ( cloud spend ).  

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by brucearctor** [comment]
blocked by https://github.com/flyteorg/flyte/issues/2410

**Comment by brucearctor** [comment]
blocked by https://github.com/flyteorg/flyte/issues/2410

**Comment by brucearctor** [comment]
`E0707 19:22:34.207197000 4303029632 ssl_transport_security.cc:1495]    Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.` ...  After trying to connect via:  `from flytekit.remote import FlyteRemote
from flytekit.configuration import Config

remote = FlyteRemote(
    config=Config.for_endpoint(endpoint="<<ELB_DNS>>"),
    default_project="flytesnacks",
    default_domain="development",
    insecure=False,
    insecure_skip_verify=True
)`

**Comment by brucearctor** [comment]
```
from flytekit.remote import FlyteRemote
from flytekit.configuration import Config

FlyteRemote(config=Config.auto())  
```

Yields [ assuming the yaml config in the default location ]:  

```
E0707 19:43:41.203977000 4309828992 hpack_parser.cc:1234]              Error parsing metadata: error=invalid value key=content-type value=text/html
E0707 19:43:41.290353000 4309828992 hpack_parser.cc:1234]              Error parsing metadata: error=invalid value key=content-type value=text/html
```

**Comment by brucearctor** [comment]
New Error -- moving along!  


`	debug_error_string = "{"created":"@1657773189.919078432","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3260,"referenced_errors":[{"created":"@1657773189.919077232","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":167,"grpc_status":14}]}"
`
From:  https://github.com/flyteorg/flyte/runs/7333590845?check_suite_focus=true

**Comment by evalsocket** [comment]
@brucearctor bad news we are moving to terraform from opta. Opta just close an acquisition deal and they will not support the open source going forward.

**Comment by brucearctor** [comment]
that's ultimately better

**Comment by brucearctor** [comment]
I would have preferred Terraform from the start, a shame I bothered learning opta to help you guys in the first place

**Comment by brucearctor** [comment]
terraform WAY better [ I have used extensively ].  Opta was more trouble than it was worth

**Comment by evalsocket** [comment]
@brucearctor I am with you, terraform is pretty simple and used widely. Most of the developers are aware of it, But we should accept that production-grade TF is hard and it takes time that's where opta fits in the stack but defiantly it has a lot of limitations and a learning curve, and users don't want to learn a new tech just for flyte deployment.

**Comment by brucearctor** [comment]
Agreed, that production-grade-anything requires attention to detail.  

But, otherwise, I don't think I understand your point

**Comment by evalsocket** [comment]
I agree with you, It's not hard just needs proper attention.

**Comment by evalsocket** [comment]
@brucearctor I Just published some terraform modules under unionai-oss, You can use them for flyte deployment, They are created from opta and now going forward we will maintain them. https://registry.terraform.io/modules/unionai-oss/opta/unionai/0.0.4

**Comment by evalsocket** [comment]
@brucearctor we have one problem with opta, Going forward they will not support anything, Meaning we need to maintain them, But we think It's not Flyte relevant that's why we are using `unionai-oss`, And Flyte can re-use them

But the thing is not decided yet, We are in early discussion and all feedback would be appreciated

**Comment by brucearctor** [comment]
Suggesting:  https://github.com/flyteorg/flyte/issues/2751 

and, that eventually, with that setup, that there be terraform modules within flyte github repo/organization for the flyte deployment guides, etc

**Comment by evalsocket** [comment]
cc: @wild-endeavor

**Comment by eapolinario** [comment]
We're taking the investments in testing in a different route (essentially running in private clusters).
