### ISSUE TITLE
[Core feature] Nightly testing -- optimize resource utilization

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#2421]
### Motivation: Why do you think this is important?

The project wastes compute ( $$$, Energy, etc ) by leaving a cluster running 24x7, though very sporatically used ( ex: nightly and releases ).  

It would be better for bank account, and environment to have testing be ephemeral ( create/start/stop/delete - on demand ).  

**That also helps work towards more testing, more often, with fewer conflicts ( if spinning up in very separate environments because that infra automation has been well worked out ).**  

### Goal: What should the final outcome look like, ideally?

Proper workflows to address the goal.

### Describe alternatives you've considered 

Leaving as is :-/ 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
We're taking the investments in testing in a different route (essentially running in private clusters).
