### ISSUE TITLE
[BUG] Workflow Failed --  github-project-issue-to-sheets workflow run ... Rate Limiting ... 

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#2422]
### Describe the bug

<img width="832" alt="fail" src="https://user-images.githubusercontent.com/5032356/166873108-ba247a30-e8f2-4240-8517-a77fc52d6d0b.png">

Consistently getting errors when creating issues about rate-limiting, and something about sheets.

1) Help this error go away
2) Why are sheets involved?  Perhaps improve docs to help explain this.

I'm happy to dig in, but don't believe I have the permissions to see/understand/address.  

### Expected behavior

Error free issue creation

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
@EngHabu i think action is broken. https://github.com/EngHabu/github-project-issue-to-sheets/blob/92c859986a697873dcc3e00ca169d3a6defe22a1/Importer.ts#L25 it's wrong for auth you need to pass token like this https://github.com/octokit/octokit.js#octokit-api-client

**Comment by evalsocket** [comment]
cc: @TheYk98, What do you think about this issue ?

**Comment by EngHabu** [comment]
Can we delete this WF, @evalsocket ?
We created it to try to work through issues in Google sheets but we ended up not using that process.

**Comment by brucearctor** [comment]
👍 -- esp. if not being used, it is silly to leave things around with failing tests.
