### ISSUE TITLE
[Housekeeping]  Auto-Update Website Header on New Version Release

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#2432]
### Describe the issue

https://github.com/flyteorg/flyteorg.github.io/blob/development/_includes/navbar.html

Is not automatically updated on new release -- therefore gets out-of-date.  

Suggesting to add a GH Workflow to update https://github.com/flyteorg/flyteorg.github.io/blob/development/_includes/navbar.html#L10
and
https://github.com/flyteorg/flyteorg.github.io/blob/development/_includes/navbar.html#L14

when new release is available ( https://github.com/flyteorg/flyte/releases/tag/ ...  )

### What if we do not do this?

Stale/old-info header on website.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by brucearctor** [comment]
@samhita-alla -- why wait/delay to run a schedule -->

https://github.com/flyteorg/flyteorg.github.io/blob/development/.github/workflows/update_release.yml#L3-L4

Instead of auto-triggering when there is a new release?

**Comment by samhita-alla** [comment]
@brucearctor, we can surely add that functionality. I just wanted to get the PR merged ASAP, hence I've included cron, but let me create a repository dispatch event from flyte repo.

**Comment by brucearctor** [comment]
[re-]Opening ... so that the auto-update task is tracked.

We can create a different ticket for 'batch'/cron, if we want to track completing some form of a task.
