### ISSUE TITLE
[BUG] With GRPC v1.46.0 non-ascii chars are not permitted in grpc metadata

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#2444]
### Describe the bug

With this change https://github.com/grpc/grpc-go/issues/468

The data populated in metadata has to be ascii data 
https://github.com/flyteorg/flyteadmin/blob/6591fa2a6303ee5dc6f47db9c9725cf72c0db99a/auth/handlers.go#L326

Hence umlaut chars used by the User in there IDP provider would fail in admin and throw 

```
Request failed with status code 500 header key "userinfo" contains value with non-printable ASCII characters
```

### Expected behavior

The request shouldn't fail .

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pmahindrakar-oss** [comment]
cc : @katrogan @EngHabu @sbrunk

**Comment by bimtauer** [comment]
Hi we're using OpenID connect with Google and are having a lot of problems with this since many of our colleagues have non-ascii conforming names 😅 🇫🇮 We solved this now by downgrading flyteadmin, but a quick fix would help us a lot 🙌🏼
