### ISSUE TITLE
[Housekeeping] Coherent organizations for OSS?

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#2450]
### Describe the issue

Unclear what belongs in flyteorg, vs unionai vs unionai-oss, vs ???

Ex: [unionai/flyte-register-action](https://github.com/unionai/flyte-register-action) and [unionai-oss/flytectl-setup-action](https://github.com/unionai/flyte-register-action) ... seems like would want those as part of the same GH Org?

Suggesting to use flyteorg for most, since these things are all in support of flyte?  And, if not, perhaps unionai-oss?  

This issue is meant to be 2-fold:
* get `flyte-register-action` and `flytectl-setup-action` in the same gh organization.
* Create documentation to live ??? with guidelines on what organization which type of project should use.

If only the first of the above is addressed, then please writeup a new issue for the second.  I'd do the first, but don't think I have permissions [ someone advise if I am mistaken ].  And, since representing open source, not sure I'd be dictating repos use in a company repository, so that should go to someone else.  

### What if we do not do this?

Usability low.  Potential future change/cleanup/migration needed.  Unclear how to keep things tidy.  Confusion.  Etc.  

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pingsutw** [comment]
cc @evalsocket should we move `flyte-register-action` and `flytectl-setup-action` to flyteorg?

**Comment by evalsocket** [comment]
cc: @kumare3 @EngHabu

**Comment by kumare3** [comment]
@brucearctor these are not relevant to flyteorg. We have kept them deliberately in unionai. We may donate them to flyteorg, once we fee
They are mature enough. That being said they are open sourced and this should not matter right. Can I understand your confusion

**Comment by evalsocket** [comment]
@kumare3 we need to transfer the ownership of https://github.com/unionai/flyte-register-action to union-oss

**Comment by brucearctor** [comment]
1) You'll see I never proposed flyteorg...  but why is one in `unionai`, and one in `unionai-oss` ... unclear the strategy for having things across multiple GH organizations.

**Comment by brucearctor** [comment]
Exactly, @evalsocket -- getting things to the same makes sense... wherever it might be.

**Comment by brucearctor** [comment]
That said ...

@kumare3 -- I am writing some testing workflows that are to be part of flyte ( already walked @EngHabu  through the design ) that will have those as dependencies ...  

Whether or not those live in flyteorg is a different.  But, still would like some docs/clarity around why one GH org used rather than another.  Rather than temperment/convenience at any given moment.  Ex: Housekeeping category :-)

**Comment by kumare3** [comment]
This is fair, we created unionai-oss recently. Let us move it asap

**Comment by brucearctor** [comment]
🧹

**Comment by evalsocket** [comment]
@brucearctor it's done
