### ISSUE TITLE
[Docs] Missing info on using custom images in sandbox

### ISSUE THREAD

**Issue by marc-union** [flyteorg/flyte#2466]
### Description

From Matheus, a user on the Slack Flyte #general channel: 

> I'm kinda confused on how to use custom images on a sandbox with Flyte 1.x.x. At first I thought the sandbox would pull the image from my local repository, but this doesn't seem to be the case, since I'm receiving the error containers with unready status: [ash8dlh4m294mnd9psbs-f62iya2y-0]|Back-off pulling image "flyte-example:1.0" when trying to execute a workflow, even though I have the flyte-example:1.0 image on my local repo. But, at the same time, it doesn't seem like I should have to build the image inside the sandbox container, right? The container from flytectl demo start doesn't even mount the working directory into /root.
> I can't find anything in the documentation that says how to do this... 

More comments from Matheus in the same thread:

> this section specifically is kinda ambiguous. it says that local images will be available for the cluster without specifying that they have to be build inside the cluster container https://docs.flyte.org/projects/cookbook/en/latest/auto/deployment/deploying_workflows.html#building-images

> I think this should be explained in more detail. the new "Getting Started" is very good, but I think it should mention this (or at least link to another part of the documentation)

Full details: 

https://flyte-org.slack.com/archives/CNMKCU6FR/p1651867300490069

https://unionai.slack.com/archives/C01HA7KQP7X/p1651868240760509

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by SmritiSatyanV** [comment]
flyteorg/flytesnacks#750
