### ISSUE TITLE
[Housekeeping] Refactor flytectl sandbox & demo command

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#2472]
### Describe the issue

Currently In flytectl we have redundant code for sandbox & demo command, Idea is to convert sandbox re use able code into a package. 

Sandbox command: https://github.com/TheYk98/flytectl/tree/81b2fe9fbe660804f65e26c8b61c5ba561f4dcc5/cmd/sandbox
Demo command: https://github.com/TheYk98/flytectl/tree/81b2fe9fbe660804f65e26c8b61c5ba561f4dcc5/cmd/demo

### What if we do not do this?

We need to manage duplicate code for both the command 

### Related component(s)

flytectl

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
cc: @TheYk98

**Comment by pmahindrakar-oss** [comment]
This PR took care of the issue https://github.com/flyteorg/flytectl/pull/326

**Comment by evalsocket** [comment]
`teardown` & `status` is not done yet. https://github.com/flyteorg/flytectl/pull/326 PR only take care of start command.

**Comment by DarthBenro008** [comment]
I think this issue is already resolved under https://github.com/flyteorg/flytectl/pull/329 . Is there any other action item for this issue that's pending?

**Comment by daniel-shuy** [comment]
Added a PR (flyteorg/flytectl#364) to refactor the remaining `start` command

**Comment by wild-endeavor** [comment]
@evalsocket can we close this ticket?

**Comment by evalsocket** [comment]
Yes
