### ISSUE TITLE
[Docs] Update subworkflows with chain workflows 

### ISSUE THREAD

**Issue by AlekhyaSasi** [flyteorg/flyte#2475]
### Description

[Slack archive](https://flyte-org.slack.com/archives/CNMKCU6FR/p1652231602845379)

Include subworkflows in the existing example or at least, have a note saying it’s possible to chain sub workflows.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by SmritiSatyanV** [comment]
https://github.com/flyteorg/flytesnacks/pull/824
