### ISSUE TITLE
[BUG]  Dot separated python packages does not work for pyflyte

### ISSUE THREAD

**Issue by sonjaer** [flyteorg/flyte#2476]
### Describe the bug

 Dot separated python packages does not work for pyflyte.

This doesn't work:
```
pyflyte --pkgs flyte_python_pipeline_sonjae.flyte_python_pipeline_sonjae_2 serialize workflows
```
but this does:
```
pyflyte --pkgs flyte_python_pipeline_sonjae --pkgs flyte_python_pipeline_sonjae_2 serialize workflows
```

```
@click.group("pyflyte", invoke_without_command=True)
@click.option(
    "-k",
    "--pkgs",
    required=False,
    multiple=True,
    callback=validate_package,
    help="Dot separated python packages to operate on.  Multiple may be specified  Please note that this "
    "option will override the option specified in the configuration file, or environment variable",
)
```

https://github.com/flyteorg/flytekit/blob/c011ef7cf47ac8ffc06c48e000cb309d9df99969/flytekit/clis/sdk_in_container/pyflyte.py#L29

### Expected behavior

You should be able to pass 

```
pyflyte --pkgs flyte_python_pipeline_sonjae,flyte_python_pipeline_sonjae_2
```

### Additional context to reproduce

flytekit v1.0.1

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
python package yes.  dot-deliminated.  so like `a/b/c` would be represented as `a.b.c` from the folder that a/ lives in.  (and there would have to be init files in a, b, and c

**Comment by seunggs** [comment]
Ah ok - got it. Thank you!
