### ISSUE TITLE
[Docs] Improve Docs on how to login docker registry in flyte to download private image.

### ISSUE THREAD

**Issue by AlekhyaSasi** [flyteorg/flyte#2499]
### Description

[Slack archives](https://flyte-org.slack.com/archives/CP2HDHKE1/p1652408181368079)
[K8s doc](https://flyte-org.slack.com/archives/CP2HDHKE1/p1652409599342919?thread_ts=1652408181.368079&cid=CP2HDHKE1)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
@SmritiSatyanV, has this issue been resolved?
