### ISSUE TITLE
[Docs] What is the distinction between flytectl sandbox and flytectl demo

### ISSUE THREAD

**Issue by SmritiSatyanV** [flyteorg/flyte#2503]
### Description

As seen https://docs.flyte.org/projects/flytectl/en/latest/gen/flytectl.html#id1, there are two ``sandbox`` nouns. What is the difference between ``flytectl sandbox`` and ``flytectl demo``? 
According to the discussion: demo is for beginners, and sandbox is for advanced users who wish to update certain attributes, perform end to end testing and gain better control over it.

Goal: We need to provide clear distinction between ``flytectl sandbox`` and ``flytectl demo`` , or delete one of them.

Marc: We need a clarification of the differences between demo and sandbox to help the user choose the best

What are each best for? When should the user choose one or the other?
What is included in each one? What is missing?
Proposed places to add this content:

https://docs.flyte.org/projects/cookbook/en/latest/userguide_setup.html#create-a-local-demo-flyte-cluster

https://docs.flyte.org/projects/flytectl/en/latest/sandbox.html

https://docs.flyte.org/projects/flytectl/en/latest/demo.html

See also

https://flyte-org.slack.com/archives/CP2HDHKE1/p1655871238925919

**Comment by flixr** [comment]
Yes, please clarify this... What is different between them? And when should I choose which?

**Comment by SmritiSatyanV** [comment]
Hi @flixr 

``flytectl sandbox``
* Uses all Flyte released images in addition to postgres and minio
* May glitch incase of bad network
* Uses port 30081
* Up-to-date with production environment setup, hence recommended


``flytectl demo``
* Uses single binary to bundle all the Flyte components thereby reducing the time to spin up the cluster because it has lesser dependencies to download
* Other dependencies include postgres and minio
* Uses port 30080

If you are looking to play around or you are a beginner, start with ``demo``, else use ``sandbox``.
Hope this answers your question.
We have a comprehensive document on all the differences between ``sandbox`` and ``demo`` coming soon.

**Comment by rupurt** [comment]
Any chance there are updates on this? I can only start the demo. I can't start the sandbox as it doesn't have the k3s file that is symlinked `/var/lib/flyte/config/kubeconfig`

**Comment by jeevb** [comment]
@eapolinario: Please confirm, but I believe that the goal is to drop the current implementation of `flytectl sandbox` completely, move `flytectl demo` to `flytectl sandbox` and just add `demo` as an alias of `sandbox` for backward compatibility.

**Comment by rupurt** [comment]
Is there a way to remove the default project from the `demo`?

**Comment by rupurt** [comment]
@jeevb sweet. That worked. Thank you :pray:

**Comment by jeevb** [comment]
> @jeevb sweet. That worked. Thank you 🙏
> 
> Is it possible to make that file come from somewhere local to the repository?

Not atm, afaik. But we should make the config directory configurable for sure.

**Comment by kumare3** [comment]
there is no difference any more
