### ISSUE TITLE
[Housekeeping] Loadbalancing grpc clients

### ISSUE THREAD

**Issue by ckiosidis** [flyteorg/flyte#2510]
### Describe the issue

currently grpc clients are not using the load balancing feature instead the code suggests to place flyteadmin behind a proxy
https://github.com/flyteorg/flyteidl/blob/master/clients/go/admin/config.go#L1-L4

### What if we do not do this?

most likely platform administrators will not notice the comments in the code and will discover this behaviour through maintaining the system, which is not the best experience

### Related component(s)

flyteidl

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by honnix** [comment]
It's a feature request maybe. :)

**Comment by honnix** [comment]
Not exactly sure, but https://github.com/flyteorg/flytepropeller/blob/25802b017dcd50d6cfd1b37b1bbb11a910c31506/pkg/controller/nodes/task/catalog/datacatalog/datacatalog.go#L390 might also need the change.

**Comment by EngHabu** [comment]
This is pretty cool... we briefly look at this when gRPC Client Side Load Balancing blog came out a while ago but it didn't seem mature enough to adopt... maybe things have moved on?

Are you planning to implement gRPC client side load balancing all the way? https://grpc.io/blog/grpc-load-balancing/

**Comment by honnix** [comment]
> This is pretty cool... we briefly look at this when gRPC Client Side Load Balancing blog came out a while ago but it didn't seem mature enough to adopt... maybe things have moved on?
> 
> Are you planning to implement gRPC client side load balancing all the way? https://grpc.io/blog/grpc-load-balancing/

That is unfortunately not the plan. Internally we use DNS for service discovery and customized resolver plugged into gRPC. Together with load balancing strategy, we distribute calls to multiple instances.

I think standard gRPC libraries already provide read-to-use resolver and load balancing policies for the thick client approach https://grpc.io/blog/grpc-load-balancing/#thick-client.
