### ISSUE TITLE
[BUG] Order of keys from DictTransformer is non-deterministic

### ISSUE THREAD

**Issue by ggydush-fn** [flyteorg/flyte#2515]
### Describe the bug

When using a dictionary with Flyte, the order of the keys is not deterministic. Python dictionary ordering is something that would be awesome to guarantee, as it was surprising to me when the order or the keys changed on Flyte.

### Expected behavior

Maintain order of keys when using dictionaries on Flyte.

### Additional context to reproduce

This example will fail. The `lit` and `transformed_lit` variables look identical, but are not after converting to Python value.
```python
import string
from flytekit.core.context_manager import FlyteContext
from flytekit.core.type_engine import DictTransformer, TypeEngine
from flytekit.models import literals

def simulate_dict_transform(data: dict, python_type: type) -> dict:
    t = DictTransformer()
    ctx = FlyteContext.current_context()
    lit = t.to_literal(ctx, data, python_type, TypeEngine.to_literal_type(python_type))
    transformed_lit = literals.Literal.from_flyte_idl(lit.to_flyte_idl())
    return t.to_python_value(ctx, transformed_lit, python_type)

data = {k: v for v, k in enumerate(string.ascii_lowercase)}
transformed = simulate_dict_transform(data, dict[str, int])
print(data.keys())
print(transformed.keys())
assert list(data.keys()) == list(transformed.keys())
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
maybe it's my jet lag, but doesn't [this](https://stackoverflow.com/questions/60507076/the-order-of-elements-in-a-protobuf-map-field) imply we can't guarantee it?  since we just use [map](https://github.com/flyteorg/flyteidl/blob/654427ef4027c6b48d997abe8770c2e8b915e84a/protos/flyteidl/core/literals.proto#L120).  the only way may be to store the order explicitly in another field?

**Comment by eapolinario** [comment]
> maybe it's my jet lag, but doesn't [this](https://stackoverflow.com/questions/60507076/the-order-of-elements-in-a-protobuf-map-field) imply we can't guarantee it? since we just use [map](https://github.com/flyteorg/flyteidl/blob/654427ef4027c6b48d997abe8770c2e8b915e84a/protos/flyteidl/core/literals.proto#L120). the only way may be to store the order explicitly in another field?

This is correct. Python guarantees insertion order since python 3.7, but we don't get that guarantee from [protobuf](https://protobuf.dev/programming-guides/proto3/#maps):
```
Wire format ordering and map iteration ordering of map values are undefined, so you cannot rely on your map items being in a particular order.
```
