### ISSUE TITLE
[Core feature] Expose task execution ids to client SDKs

### ISSUE THREAD

**Issue by eapolinario** [flyteorg/flyte#2558]
### Motivation: Why do you think this is important?

We should expose unique task execution names. There are some use cases that would benefit from uniquely identifying a specific task execution, including the possibility of using such unique ids to link external objects to specific task executions.

### Goal: What should the final outcome look like, ideally?

The unique task id should be exposed to clients as an environment variable and each client sdk would access it at runtime similarly to how we expose the workflow execution id.

The unique guarantees of such ids would follow the same as the workflow execution ids, in other words, they would be guaranteed to be unique in the context of a project and domain.

### Describe alternatives you've considered 

We could not do this and instead ask users to leverage other source of entropy to guarantee unique ids per task ids.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
closing as subset of https://github.com/flyteorg/flyte/issues/4400
