### ISSUE TITLE
[BUG] flyteadmin should not interfere with the format of client secrets

### ISSUE THREAD

**Issue by eapolinario** [flyteorg/flyte#2559]
### Describe the bug

Currently flyteadmin [removes newlines](https://github.com/flyteorg/flyteadmin/blob/master/auth/auth_context.go#L203) from user-provided secrets. 

### Expected behavior

flyteadmin should load the contents of the secret file as it's provided, as having this extra cleaning step introduces potential divergences in how client secrets are used in other parts of the system, including client SDKs.

At the very least we should detect the presence of trailing newlines and warn the user that having such characters there might indicate that this is not what they wanted in the first place. 

### Additional context to reproduce

Any client secret that contains a trailing newline triggers this behavior.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by mao3267** [comment]
#take

**Comment by mao3267** [comment]
#take

**Comment by mao3267** [comment]
@eapolinario It seems that Flytekit handles secrets with trailing newlines in the same way—by removing the newlines.
Are there any other reasons why we expect FlyteAdmin not to automatically remove trailing newlines?
https://github.com/flyteorg/flytekit/blob/1b67f16ce768225f034fe4698a43e30047817fab/flytekit/core/context_manager.py#L383

**Comment by eapolinario** [comment]
I left a comment in [slack](https://flyte-org.slack.com/archives/CP2HDHKE1/p1728314545057569?thread_ts=1728287604.799599&cid=CP2HDHKE1), but just to document it here also. I'm fine closing this issue as `Won't fix`, unless there's a clear use case.

**Comment by eapolinario** [comment]
Closing this as the benefits of fixing this do not outweigh the risks of breaking existing Flyte users who might depend on this behavior.
