### ISSUE TITLE
[Housekeeping] Sync Boilerplate in flyteorg/flyte

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#2561]
### Describe the issue

https://github.com/flyteorg/flyte/tree/master/boilerplate

is not staying in sync with 

https://github.com/flyteorg/boilerplate/tree/master/boilerplate

Create CD to ensure that when things are updated in source ( https://github.com/flyteorg/boilerplate/tree/master/boilerplate ) they get updated to destinations ( I imagine boilerplate needs to also make it elsewhere ). 

If not CD, a using git submodule *might* be appropriate?  https://git-scm.com/book/en/v2/Git-Tools-Submodules ??

### What if we do not do this?

Out of sync/stale.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by brucearctor** [comment]
setup a GH Action on a schedule to pull/sync relative boilerplate ( by running `make sync_boilerplate`

**Comment by evalsocket** [comment]
@brucearctor nice catch, We are not syncing flyte boilerplate https://github.com/flyteorg/boilerplate/actions/runs/2423287649, We can add flyte repository here https://github.com/flyteorg/boilerplate/blob/master/.github/workflows/master.yaml#L14

In flyte we have a workflow for automation https://github.com/flyteorg/flyte/blob/master/.github/workflows/upgrade_automation.yml, Adding flyte repository in boilerplate WF will fix the issue.

**Comment by brucearctor** [comment]
Cool -- sounds like that might be worth [ at least eventually] updating.  

Related:  even though this is sorta a push mechanism --> go to XX repo and sync from boilerplate, which 'features' are included is a function of what is in each repo.  Do I understand correctly that:  There is no knowledge of where all each feature has a dependency/is-used [ and there isn't a logging/trace/etc mechanism currently in place ]?

**Comment by evalsocket** [comment]
No Actually whenever you merge anything in boilerplate, We trigger a GHWF https://github.com/flyteorg/boilerplate/blob/156fbc19864056fd0949389a8cd1cafaed4cabc2/.github/workflows/master.yaml#L4. This workflow will trigger the remote workflow and these remote workflow can be custom, You can add extra steps in a specific repo.

**Comment by evalsocket** [comment]
One more thing, Each repo has one Upgrade Boilerplate WF that we can trigger from any branch and it will automatically sync the boilerplate repo in flyte repository.

**Comment by brucearctor** [comment]
👍
