### ISSUE TITLE
[BUG] flytectl delete help doesn't match the actual functionality

### ISSUE THREAD

**Issue by honnix** [flyteorg/flyte#2563]
### Describe the bug

`delete      Terminates/deletes various Flyte resources such as tasks, workflows, launch plans, executions, and projects.`

But
```
Usage:
  flytectl delete [command]

Available Commands:
  cluster-resource-attribute Deletes matchable resources of cluster attributes.
  execution                  Terminates/deletes execution resources.
  execution-cluster-label    Deletes matchable resources of execution cluster label.
  execution-queue-attribute  Deletes matchable resources of execution queue attributes.
  plugin-override            Deletes matchable resources of plugin overrides.
  task-resource-attribute    Deletes matchable resources of task attributes.
  workflow-execution-config  Deletes matchable resources of workflow execution config.
```

For example projects cannot be deleted but archived/activated.

It was mentioned in https://github.com/flyteorg/flyte/issues/1619 as doc bug but not fixed yet.

### Expected behavior

A more accurate `delete` command help message.

### Additional context to reproduce

1. flytectl
2. flytectl delete --help

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by nmichlo** [comment]
Took me a while to figure out this functionality, came across https://github.com/flyteorg/flyte/issues/1619 too.

Archiving instead of deleting, by adding `--archive` to the update command for a project was a little unintuitive.
