### ISSUE TITLE
[Plugin] TypeTransformer for TensorFlow model

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#2570]
We need to support `tf.keras.Model` as a native Flyte type.

Reference doc for serialization and deserialization of models: https://www.tensorflow.org/guide/keras/save_and_serialize

More on TypeTransfomers can be found [here](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/extend_flyte/custom_types.html).

Related PR that adds PyTorch tensor and module as Flyte types: https://github.com/flyteorg/flytekit/pull/1032

**Comment by techytushar** [comment]
Hey @samhita-alla ,
Is someone working on this, can I pick this up?

**Comment by samhita-alla** [comment]
@techytushar, absolutely! Assigned the issue to you.
