### ISSUE TITLE
[Plugin] TypeTransformer for TensorFlow TFRecord

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#2571]
We need to support writing to and reading from TFRecord format.

Reference doc: https://www.tensorflow.org/tutorials/load_data/tfrecord

More on TypeTransfomers can be found [here](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/extend_flyte/custom_types.html).

Related PR that adds PyTorch tensor and module as Flyte types: https://github.com/flyteorg/flytekit/pull/1032

**Comment by ryankarlos** [comment]
@samhita-alla  ill pick this up

**Comment by ryankarlos** [comment]
@samhita-alla  Ive had a go at the PR
