### ISSUE TITLE
[Docs] Add notes for Requirements and Installation 

### ISSUE THREAD

**Issue by drleowang** [flyteorg/flyte#2584]
For get start Docs: https://docs.flyte.org/en/latest/getting_started/index.html

I think we should add these steps:

1. Requirements part: add python 64 bit.
2. Installation part: add after install flytekit, please add flytekit path to environment path, eg, export PATH="/home/osboxes/.local/bin:$PATH"
3.  Add run " pyflyte  init myproject" to set a new project. Then we can create example.py in the myproject directory.

Thanks

Leo

**Comment by eapolinario** [comment]
The getting started guide is supposed to be slim. The instructions you're proposing are already part of one of the user guides: https://docs.flyte.org/projects/cookbook/en/latest/auto/larger_apps/index.html.
