### ISSUE TITLE
[Feature] Pass extra configs to raw storage clients

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#261]
**Motivation: Why do you think this is important?**
We have a scenario were we need to set the bucket-owner-full-control ACL on all objects created through Flyte. The storage config doesn't expose that and the underlying store (Stow) doesn't expose it neither.

**Goal: What should the final outcome look like, ideally?**
Be able to set this up.
"x-amz-acl": "bucket-owner-full-control"

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [X] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Comment by kumare3** [comment]
this has already been completed
