### ISSUE TITLE
[Docs] Document How to make custom Flyte Deck renderers

### ISSUE THREAD

**Issue by marc-union** [flyteorg/flyte#2618]
There are new features for Flyte Deck that need documentation.

@cosmicbboy proposes this:

> There are a couple of levels here:
> * using Flyte decks (probably something in flytesnacks)
> * extending/creating your own Flyte decks (probably also flytesnacks?)
> * API reference for flyte deck parent classes? (maybe [here](https://docs.flyte.org/projects/flytekit/en/latest/plugins/deck.html)?)

**Comment by cosmicBboy** [comment]
- https://github.com/flyteorg/flytesnacks/pull/735
- extending guide: probably somewhere [here](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/extend_flyte/index.html)
