### ISSUE TITLE
[Docs] [flytekit] pyflyte run - image & dependency customization

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#2639]
### Description

Pyflyte run works well with the default image, but we should include instructions on how to change the pip dependencies (like explain/link to the whole image building concepts).

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
There's a section on how to set the `--image` flag [here](https://docs.flyte.org/en/latest/getting_started/index.html#executing-workflows-on-a-flyte-cluster) in _How to handle custom dependencies? Meet the `--image` flag_ dropdown. Should we elaborate more on this?
