### ISSUE TITLE
[Core feature] Easily see all workflow using a particular task

### ISSUE THREAD

**Issue by sonjaer** [flyteorg/flyte#2646]
### Motivation: Why do you think this is important?

[Nothing super important for us or a big use case yet, so feel free to ignore if you don't think it is valuable]

It would be nice to see what workflows are using a particular task.  Today we rewrote a task to replace an old task and wanted to remove the old task code completely. Before we wanted to verify if any workflows were using this task remotely. If that was the case, we might have asked the owners of the workflows to migrate to the new one or we would have kept the code in case there were any future changes needed.

### Goal: What should the final outcome look like, ideally?

This or similar type of data could probably be useful for different use-cases, but I am not entirely sure what would be a final outcome. 

### Describe alternatives you've considered 

I could get this probably by making different API calls

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
Closing as not planned at this time. Please feel free to reopen if you feel strongly about it.
