### ISSUE TITLE
[Docs] [flytekit] FlyteRemote docs

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#2648]
### Description

We need to write documentation detailing usage of FlyteRemote.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
Hey @wild-endeavor! The documentation's already available [here](https://docs.flyte.org/projects/flytekit/en/latest/design/control_plane.html). Do we need to add anything to it?

**Comment by wild-endeavor** [comment]
oh no, i had no idea this was here.  Thanks!
