### ISSUE TITLE
[Docs] Docs on how Propeller ensures a task is executed exactly once

### ISSUE THREAD

**Issue by sonjaer** [flyteorg/flyte#2652]
### Description

I was curious how Propeller ensures a task is executed exactly once? I was curious since we have non idempotent tasks that we wouldn't want to run twice. 
Is there any instance when this could not be true? When deploying a new Propeller or error writing to etcd? 
Is this something that could be added to the Propeller Architecture [docs](https://docs.flyte.org/en/latest/concepts/component_architecture/flytepropeller_architecture.html#id1) here 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
Calling Flyte's model exactly once is not correct. Flyte does in fact a lot of heavy lifting to ensure that resources are not wasted and for a given execution inputs and outputs are never overwritten.
