### ISSUE TITLE
[BUG] flytekit union type can't distinguish list and str from command 

### ISSUE THREAD

**Issue by eugenejahn** [flyteorg/flyte#2655]
### Describe the bug

flytekit versions I used
Version: 1.1.0b7

union type with str example: 
`Union[bool,int, str]`

union type with list example: 
`Union[bool,int, list[int]]`

both Union type will take the argument of this ` '[1, 1 ,1 , 1, 1]'`  as an argument from command.  

however, if we have a union type like this:
 `Union[bool,int, str, list[int]]`
flytekit can't tell whether is list or string. 

### Expected behavior

should have a way to distinguish list and str from command. so union type can support both list and str in the same time can distinguish whether or not the argument is list or str.  

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
This is for pyflyte run command line right. This is a hard one

**Comment by eugenejahn** [comment]
yep for pyflyte run command line. talked with @wild-endeavor and we noticed `str` type will take any input from command line 

ex.  all the below example will be considered as `str`
`
0 
-1 
[1,2]
'[1,2]'
'12313'
`

so it can be confused not only for `list` and `str`, but `str` for any types..

**Comment by wild-endeavor** [comment]
this is hard to resolve... closing until there's a clear path forward.
