### ISSUE TITLE
[Docs] Document how to log with CloudWatch and Fluentd

### ISSUE THREAD

**Issue by marc-union** [flyteorg/flyte#2660]
We need better coverage of connecting Flyte logging with [AWS CloudWatch](https://aws.amazon.com/cloudwatch/) and [Fluentd](https://www.fluentd.org/)

Potential location for this new content is in this page or a sibling page:

https://docs.flyte.org/projects/cookbook/en/latest/auto/deployment/configure_logging_links.html

**Related:**

Slack conversation: https://flyte-org.slack.com/archives/C01P3B761A6/p1656366983976689

Issue: https://github.com/flyteorg/flyte/issues/2635

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs-FluentBit.html

https://docs.flyte.org/en/latest/deployment/cluster_config/flytepropeller_config.html

**Comment by Smartmind12** [comment]
@marc-union Can you assign this issue to me as i would like to work on it...Thanks!
