### ISSUE TITLE
[Docs] Verify doc consistency for cron scheduling for launch plans

### ISSUE THREAD

**Issue by marc-union** [flyteorg/flyte#2662]
Doc for cron scheduling for launch plans might not be consistent in these pages:

https://docs.flyte.org/projects/flytekit/en/latest/generated/flytekit.CronSchedule.html#flytekit-cronschedule

https://docs.flyte.org/projects/flytekit/en/latest/_modules/flytekit/core/schedule.html#CronSchedule

https://docs.flyte.org/projects/cookbook/en/latest/auto/core/scheduled_workflows/lp_schedules.html#cron-schedules

**See also**

https://flyte-org.slack.com/archives/CNMKCU6FR/p1655976105257199

https://github.com/flyteorg/flytekit/pull/1081/files

**Comment by samhita-alla** [comment]
@SmritiSatyanV, any idea what this means?

**Comment by SmritiSatyanV** [comment]
https://docs.flyte.org/projects/flytekit/en/latest/_modules/flytekit/core/schedule.html#CronSchedule isn't rendered correctly.
This could be something I recently saw on Slack. This PR: https://github.com/flyteorg/flyte/pull/2900

**Comment by samhita-alla** [comment]
If you think the issue's resolved, can we close it?

**Comment by SmritiSatyanV** [comment]
Yep
