### ISSUE TITLE
Aks deployment Issue

### ISSUE THREAD

**Issue by maheswaraiahp** [flyteorg/flyte#2672]
Basically, we used a single node AKS cluster in which we deployed one Deployment with Three Replicas. But I check the pod's Status one pod running and the remaining pods are pending state and also CSI-Blob deployment is also pending state. 
So please help me to fix the issue
![image003](https://user-images.githubusercontent.com/97515976/177531605-ffc62688-2798-4a87-9890-4bd604ed5098.png)
![image002](https://user-images.githubusercontent.com/97515976/177531614-4e93813b-0269-4057-aae9-694db3531345.png)
![image001](https://user-images.githubusercontent.com/97515976/177531619-17fe781c-acfc-46ee-80f1-d14a1e0f0d55.png)
![image](https://user-images.githubusercontent.com/97515976/177531625-390b79e1-18af-4f91-ba3f-13330f11caa3.png)

**Comment by joaolgn1985** [comment]
hey @maheswaraiahp you can help me with how I can deploy on cluster aks, I did see nothing about installing on AKS, only GCP and EKS.
I need help if you have a step of step this installation, please?

thank you so much.
