### ISSUE TITLE
[Docs] Add a tutorial that uses Flyte with NLP

### ISSUE THREAD

**Issue by SmritiSatyanV** [flyteorg/flyte#2676]
### Description

Create a tutorial that uses Flyte to implement a Natural Language Processing project.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by ryankarlos** [comment]
Hi @samhita-alla can this be assigned to me please

**Comment by mertbozkir** [comment]
Hello @ryankarlos, 

Are you still working on this issue? If not I would like to take over on it. 🙃 I want to contribute Flyte😅

**Comment by ryankarlos** [comment]
@mertbozkir yes I am, i will be making  a PR today or tomorrow.

**Comment by ryankarlos** [comment]
@samhita-alla  added a PR now, any initial comments would be helpful before i progress further
