### ISSUE TITLE
[Docs] Guide on how to write Flytekit shim plugins for Backend plugins

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#2679]
### Description

Currently, we have docs for how to write [backend plugins](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/extend_flyte/backend_plugins.html) but don't have any guides for how to write a flytekit shim plugin that allows flytekit task authors to use that backend plugin.

An example of this is the [Sagemaker Training](https://docs.flyte.org/projects/cookbook/en/latest/auto/integrations/aws/sagemaker_training/index.html) plugin, which requires both.

This issue breaks up the tasks described in https://github.com/flyteorg/flyte/issues/1541

Context: https://www.youtube.com/watch?v=59w9HYOcJJ8&t=1282s

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
[Flyte agents](https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/development_lifecycle/agent_service.html#extend-agent-service) are the blessed way of extending Flyte.
