### ISSUE TITLE
[Docs] Guide on how to write data persistence plugins

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#2681]
### Description

We currently support S3, GCS, and Local FS data persistence for when Flyte has to serialize data that's passed from one task to another, we should write a guide on how to write additional ones for e.g. Azure's blob store, etc.

This issue breaks up the tasks described in https://github.com/flyteorg/flyte/issues/1541

Example: https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-data-fsspec

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
We have added support for other blob stores (including Azure). We don't need a specific guide on how to extend the data persistence layer as we have multiple examples at this point.
