### ISSUE TITLE
Automated end-to-end testing using opta and cookbook examples

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#2690]
WIP

**Comment by brucearctor** [comment]
lol

**Comment by wild-endeavor** [comment]
haha - let me fill this in with details.

**Comment by brucearctor** [comment]
I think this is covered by: https://github.com/flyteorg/flyte/issues/2419 and https://github.com/flyteorg/flyte/issues/2420 ?

**Comment by wild-endeavor** [comment]
oops
