### ISSUE TITLE
[Docs] Publish Code Style Guide

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#2694]
### Description

It is great for a project to have consistent code formatting/style.  This is often accomplished by a linting, and as part of pre-commit tests.  But, it would also be helpful if a styleguide were published to make the choices/opinions explicit.  

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
@SmritiSatyanV, could you link the google doc we have? Should we have the page in the community tab of our docs?

The task here is to convert the google doc to a flyte doc page.

**Comment by SmritiSatyanV** [comment]
https://docs.google.com/document/d/1rhEZqd3Ae8Y9HUxg7yF6LarHrfIHKnPyeke8aMSPgis/edit?usp=sharing - here's the google doc

**Comment by SmritiSatyanV** [comment]
The user specifies code guide here. What we have is a documentation style guide. I think we need to have a separate code style guide..

**Comment by samhita-alla** [comment]
Oh, okay. Do we have an issue for porting the doc style guide to our docs?

**Comment by akarsh-jain-790** [comment]
Hey, I would like to work on this issue.

**Comment by akarsh-jain-790** [comment]
> https://docs.google.com/document/d/1rhEZqd3Ae8Y9HUxg7yF6LarHrfIHKnPyeke8aMSPgis/edit?usp=sharing - here's the google doc

If I'm right I just have to convert the google doc to a flyte doc page ?
