### ISSUE TITLE
Get the id of a sub workflow from the parent workflow SdkWorkflowExecution object

### ISSUE THREAD

**Issue by generalzhou** [flyteorg/flyte#270]
**Motivation: Why do you think this is important?**
Need to be able to navigate to subworkflow from parent workflow via the API. We want to be able to do this in a programmatic way. 

**Goal: What should the final outcome look like, ideally?**
For this workflow : priceoptimizeroffline-production/f0d3bef933e314c89936
I want to get the id of the subworkflow from task ss-wait. However, I just see this:
```
wf.node_executions['ss-wait'] -> 
id {
  node_id: "ss-wait"
  execution_id {
    project: "priceoptimizeroffline"
    domain: "production"
    name: "f0d3bef933e314c89936"  # this is the id of the parent, not the subworkflow
  }
}
```

Either the `id` field should have the id of the subworkflow, or another id field should contain this. 

**Describe alternatives you've considered**
Can query the http api that drives the UI directly, but this is probably not a good idea. 

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [X] FlyteIDL (Flyte specification language)
- [X] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Comment by anandswaminathan** [comment]
@wild-endeavor I believe flytekit supports it right?

**Comment by kumare3** [comment]
Resolved
