### ISSUE TITLE
[Core feature] Speed up Deployment of a cluster - esp. for getting started or testing

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#2707]
### Motivation: Why do you think this is important?

Takes ~30 minutes to go through the various stages.  Explore, and ideally find ways, to get that time much less.  

### Goal: What should the final outcome look like, ideally?

Faster cluster [ EKS ] and Flyte specific starting times.  

### Describe alternatives you've considered 

Not doing anything.  

###  Propose: Link/Inline OR Additional context 

Imagining this will either involve finding opta optimizations, or dropping into Terraform to reduce the number of stages, while being explicit about `depends_on`.  

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
Between single-binary, all the other perf improvements, and the improvements to the different helm charts we've done over the last 1.5 years I don't see initialization/installation as being this slow or problematic.
