### ISSUE TITLE
[Core feature] SECRET FOR BUCKET NAME

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#2708]
### Motivation: Why do you think this is important?

To address: https://github.com/flyteorg/flyte/issues/2421 , https://github.com/flyteorg/flyte/issues/2420 , etc...  It would be prudent to have a Bucket which name is not pubilcly viewable.  Having a GH SECRET in the repo with the bucket name would be most ideal.  Naturally, this means it is not obvious where/when there is an AWS Bucket [ whether or not permissions set accordingly, better to 'hide' things ].  

### Goal: What should the final outcome look like, ideally?

A GH SECRET which can be used for bucket name.

### Describe alternatives you've considered 

Not having a Secret/Variable.  

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
We're taking the investments in testing in a different route (essentially running in private clusters).
