### ISSUE TITLE
GCP Opta Deployment needs updating [ not to reference AWS instance type ]

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#2714]
I'm interested in trying out Flyte on GCP with tasks that vary in CPU, memory, and GPU usage. I noticed [this tutorial](https://docs.flyte.org/en/latest/deployment/gcp/opta.html#deployment-gcp-opta) provides a deployment from Opta. 

However, I saw in the yaml [here](https://github.com/flyteorg/flyte/blob/master/opta/gcp/env.yaml#L12-L15) it provides an autoscaling (3-6 node) e2-medium node pool for the cluster. 

```
  - type: k8s-cluster
    min_nodes: 3
    max_nodes: 6
    node_instance_type: e2-medium
```

How does one modify this configuration to provide the ability to use GPU enabled machines from a separate node pool? I saw [these taint/tolerations directions](https://docs.flyte.org/projects/cookbook/en/latest/auto/deployment/configure_use_gpus.html#sphx-glr-auto-deployment-configure-use-gpus-py), but was a little confused on how to tie it all together.

_Originally posted by @tszumowski in https://github.com/flyteorg/flyte/discussions/2713_

**Comment by tszumowski** [comment]
@brucearctor I believe the e2-medium is a valid instance type. I was able to deploy the cluster with this config (details [here](https://flyte-org.slack.com/archives/C01P3B761A6/p1658974292802369)). Suggest closing issue.

**Comment by brucearctor** [comment]
@tszumowski --> This was your issue: https://github.com/flyteorg/flyte/discussions/2713 so if solved, no reason for it to be open.
