### ISSUE TITLE
[Core feature] Create github.com/flyteorg/gh-badges repository

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#2725]
### Motivation: Why do you think this is important?

While creating OSS testing, it is important for badges to live somewhere.  I would imagine that should be in the flyteorg GH organization.  And, a good repo for badges would be something like 'gh-badges' ( other names are OK too, ex 'flyte-badges', or ??? ).  

### Goal: What should the final outcome look like, ideally?

A repo existing that can be used for badges in the flyteorg

### Describe alternatives you've considered 

Not having a new/discrete repository.  Ex: using a non-flyte repo.  Or, using an existing one.  Seems safer to have one just used for this.  

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
@eapolinario should we create a repository in flyteorg?

**Comment by evalsocket** [comment]
@brucearctor It's done https://github.com/flyteorg/gh-badges
