### ISSUE TITLE
[BUG] GCP Opta Deployment does not set roles and permissions

### ISSUE THREAD

**Issue by tszumowski** [flyteorg/flyte#2727]
### Describe the bug

When I run the opta GCP deployment steps, everything gets deployed including the service accounts. However, it did not apply the Roles or Permissions described [here](https://docs.flyte.org/en/latest/deployment/gcp/manual.html#permissions). I needed to manually follow those directions after running the Opta deployment in order for Flyte to work. 

### Expected behavior

Created GCP Service Accounts should have the permissions required to read/write from buckets as well as have the FlyteAdmin role should have the iam.serviceAccounts.signBlob applied. 
All permissions defined in [the manual instructions](https://docs.flyte.org/en/latest/deployment/gcp/manual.html#permissions) should be in the deployment. 

### Additional context to reproduce

See [this thread](https://flyte-org.slack.com/archives/C01P3B761A6/p1658974292802369) for details. To reproduce, deploy the Opta GCP configuration and check the service account permissions for FlyteAdmin. It should have signBlob shown above.

I attached the logs from my run. 

[opta_gcp_deploy_logs.txt](https://github.com/flyteorg/flyte/files/9222436/opta_gcp_deploy_logs.txt)

 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
This has been fixed in the latest gcp helm charts.
