### ISSUE TITLE
[BUG] `with_overrides` is failing in `dynamic` steps

### ISSUE THREAD

**Issue by rahul-theorem** [flyteorg/flyte#2730]
### Describe the bug

Currently Flyte supports overriding resources & other configurations at runtime with the `with_overrides` construct, ie. as described [here](https://docs.flyte.org/projects/cookbook/en/latest/auto/deployment/customizing_resources.html#using-with-overrides). However, it doesn't appear to be possible to specify overrides using arguments in a step decorated with `@flytekit.dynamic`.

### Expected behavior

`@flytekit.dynamic` steps can use user-specified arugments arguments to set overrides (ie. for resource limits/requests)

### Additional context to reproduce

Reproduced on a sandbox EKS cluster w/ the flyte-sandbox chart deployed w/ flytekit 1.0.3;

```python
import flytekit


@flytekit.task()
def my_task() -> str:
    return "foo"


@flytekit.dynamic()
def dynamic_with_resources(cpu: str, mem: str) -> str:
    return my_task().with_overrides(limits=flytekit.Resources(cpu=cpu, mem=mem))


@flytekit.workflow()
def my_workflow(cpu: str, mem: str) -> str:
    return dynamic_with_resources(cpu=cpu, mem=mem)
```

Attempting to run this workflow multiple times led to either 1) the workflow stalling after the first pod succeeded or 2) the following exception;
```
'Promise' object has no attribute 'with_overrides'
```

See https://flyte-org.slack.com/archives/CREL4QVAQ/p1659056459202059 & https://flyte-org.slack.com/archives/CP2HDHKE1/p1655135984234209 for additional context.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by rahul-theorem** [comment]
This was resolved after upgrading our sandbox EKS cluster to the most recent version of the flyte helm chart.

**Comment by kumare3** [comment]
> This was resolved after upgrading our sandbox EKS cluster to the most recent version of the flyte helm chart.

I am not sure how platform upgrade fixed it?
