### ISSUE TITLE
[BUG] [flyteconsole] Dynamic task information not fully parsed

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#2731]
# Describe the bug
When running a dynamic task like so
![image](https://user-images.githubusercontent.com/2896568/181854083-c3940b81-2ae0-4722-bb15-d9da4f557883.png)

clicking on the underlying generated task (n0-0-dn0), the pane that comes up on the right is for the parent dynamic task, not the underlying child task.

The frontend renders the graph correctly though
![image](https://user-images.githubusercontent.com/2896568/181854179-03c18e72-8b4b-415b-a880-4e39bc739804.png)
and when you click on `my_task` here, the pane that comes up
![image](https://user-images.githubusercontent.com/2896568/181854222-f18ffd4c-16ef-4417-a519-757b3e35a311.png)
is
* missing the Task tab
* missing name and type and you just the the gray updating bar

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
No longer repros.
