### ISSUE TITLE
[BUG] Flyte Logo not showing up in repository README

### ISSUE THREAD

**Issue by shivaylamba** [flyteorg/flyte#2733]
### Describe the bug

 Flyte Logo is not showing up in repository README. Currently showing the following error:  Error 503 Backend is unhealthy

### Expected behavior

Logo should show up correctly

### Screenshots

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/19529592/181917034-2815874a-12aa-4ee8-9118-443c7b850060.png">

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
@shivaylamba, I see the logo. Could you clear your cache or open the README in incognito?

<img width="927" alt="image" src="https://user-images.githubusercontent.com/27777173/182014167-3c0fe1b6-b23a-47f5-952f-46a6fe566924.png">

**Comment by shivaylamba** [comment]
Thanks it did show up after clearing the cache. For some reason earlier, it didn't even open in incognito.
