### ISSUE TITLE
[Docs] Add a note in opta deployment for depreciation 

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#2740]
### Description

<img width="1536" alt="Screenshot 2022-08-08 at 8 59 30 AM" src="https://user-images.githubusercontent.com/10830562/183332776-04724342-2a05-4eb5-80d4-01db2c8b7cd3.png">

We should add a note on the aws/GCP opta deployment page, Please also mention the opta migration guide https://docs.opta.dev/features/terraform/#migrate-from-opta-to-terraform

For the short term, users can generate terraform code from the opta file using the above guide, We just need to refactor our docs that will describe opta to terraform generation(terraform init/apply/destroy) rather than opta apply. 

Add docs that describe how to migrate from opta to terraform on Flyte

**Comment by evalsocket** [comment]
cc: @samhita-alla @SmritiSatyanV @wild-endeavor

**Comment by samhita-alla** [comment]
@SmritiSatyanV, do you mind adding the note/warning?

**Comment by SmritiSatyanV** [comment]
Sure @samhita-alla , I will do that
