### ISSUE TITLE
[Core feature] Support passing client secret credentials as an env var 

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#2744]
### Motivation: Why do you think this is important?

Currently the only way to use client secret credentials authentication is by passing the client secret by file path location.

### Goal: What should the final outcome look like, ideally?

We should permit specifying the client secret as an environment variable

### Describe alternatives you've considered 

Current implementation which limits the ways we can pass secrets

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
Can this issue be closed?

**Comment by katrogan** [comment]
not until the flytectl change is in
