### ISSUE TITLE
[Core feature] Create OSS Cloud Environments

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#2751]
### Motivation: Why do you think this is important?

Community/Project could use Cloud Resources, currently - as I understand - these things are all Union-internal.  

### Goal: What should the final outcome look like, ideally?

things running in flyte/open-source environments with permissions to condoned community members

### Describe alternatives you've considered 

keeping things the way they are.  

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
We're taking the investments in testing in a different route (essentially running in private clusters).
