### ISSUE TITLE
[Plugin] Sklearn integration

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#2752]
Flyte is an ML- and data- aware orchestrator, it would make sense to support the most popular ML frameworks as first-class citizen types in the Flyte type system.

For `sklearn`, there's really only one base class, which is the [BaseEstimator](https://scikit-learn.org/stable/modules/generated/sklearn.base.BaseEstimator.html#sklearn.base.BaseEstimator).

We'll need to follow the conventions set in the [`flytekit.extras.pytorch`](https://github.com/flyteorg/flytekit/tree/master/flytekit/extras/pytorch) module, by doing the following:

1. the `__init__.py` file should handle the case where the user doesn't have `sklearn` and `joblib` installed.
2. implement a `TypeTransformer` for the `BaseEstimator` class:
   - flyte docs: https://docs.flyte.org/projects/cookbook/en/latest/auto/core/extend_flyte/custom_types.html
   - numpy type transformer: https://github.com/flyteorg/flytekit/blob/master/flytekit/types/numpy/ndarray.py
3. add tests here: https://github.com/flyteorg/flytekit/tree/master/tests/flytekit/unit/extras. Test out:
   - `BaseEstimators`
   - `Transformers` (e.g. https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html?highlight=standardscaler#sklearn.preprocessing.StandardScaler)
   - `sklearn.pipeline.Pipeline`

### Resources 

- serialize/deserialize sklearn estimators: https://scikit-learn.org/stable/model_persistence.html
- joblib docs: https://joblib.readthedocs.io/en/latest/

### Open Questions

- joblib/sklearn will complain if the an estimator is serialized in some version `x` and deserialized in another version `y`, but this is just a user warning... how do we handle this?

**Comment by SmritiSatyanV** [comment]
Is this something I can take up? @cosmicBboy

**Comment by kumare3** [comment]
@cosmicBboy can we add a more detailed description- I think this is a great good first issue for open source contributors?

**Comment by cosmicBboy** [comment]
assigned @SmritiSatyanV to this, gonna fill out https://github.com/flyteorg/flyte/issues/2759 and https://github.com/flyteorg/flyte/issues/2753 for others to pick up.

@kumare3 as a side note, I think we should host OSS planning meetings (similar to UnionML) so that we can get better involvement.

**Comment by techytushar** [comment]
I can pick this up, I have already worked on adding TypeTransformer for Tensorflow Models here: https://github.com/flyteorg/flytekit/pull/1241
this seems to be very similar to it
