### ISSUE TITLE
[BUG] `--details` flag in flytectl command is erroring out

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#2757]
### Describe the bug

When appending the `--details` flag to flytectl command, it throws a StructuredDataset error as follows:

```
flytectl get execution  -p flytesnacks -d development a47w6dwnr454vzzgqhxj -o yaml  --details
```

Error:
```
Error: unsupported literal scalar type *core.Scalar_StructuredDataset
```

### Expected behavior

The command should work.

### Additional context to reproduce

Run `flytectl get execution  -p flytesnacks -d development <execution-id> -o yaml  --details`

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
cc: @pmahindrakar-oss @wild-endeavor

**Comment by mounesi** [comment]
I have face the same error also. The error message "unsupported literal scalar type *core.Scalar_StructuredDataset" indicates that the output data type of your Flyte workflow contains a structured dataset, which is not supported by the flytectl get execution command. 

Also calling the --nodeID n0 throws the same error.
