### ISSUE TITLE
[Plugin] Tensorflow types integration

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#2760]
Add support for Tensorflow model/tensor types

**Comment by samhita-alla** [comment]
Hey @cosmicBboy! I've already created issues for TensorFlow: https://github.com/flyteorg/flyte/issues/2569, https://github.com/flyteorg/flyte/issues/2570, and https://github.com/flyteorg/flyte/issues/2571.

**Comment by cosmicBboy** [comment]
ah! nice didn't catch those. closing this.
