### ISSUE TITLE
[Housekeeping] Helm doesn't like our notification config

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#2761]
### Describe the issue

In Helm chart we are substituting the `[userSettings](https://github.com/flyteorg/flyte/blob/c56a1a4df382b0213ee587746a5da0619b87cc99/charts/flyte-core/values-eks.yaml#L309-L326)` and we have `[tpl](https://github.com/flyteorg/flyte/blob/master/charts/flyte-core/templates/admin/configmap.yaml#L46)` function inside our template. 

If we enable the notification then helm will through the error because of `{{ workflow.project }}`, https://github.com/flyteorg/flyte/blob/c56a1a4df382b0213ee587746a5da0619b87cc99/charts/flyte-core/values-eks.yaml#L324

error
```
function "workflow" not defined
```

### What if we do not do this?

- Users will not able to enable notification with helm chart

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
Hey @evalsocket! How quickly can we resolve this issue? One other user encountered the same issue: https://flyte-org.slack.com/archives/CNMKCU6FR/p1660629648020239.
