### ISSUE TITLE
Issue running container tasks in imperative workflows locally

### ISSUE THREAD

**Issue by thoughtworks-tom** [flyteorg/flyte#2766]
Container tasks run via imperative workflows locally seems to return None value outputs for all container tasks.

```python
# Create an imperative workflow
workflow = ImperativeWorkflow(name=name)

# Create standard inputs for calculate ellipse example 
workflow.add_workflow_input("a", float)
workflow.add_workflow_input("b", float)

# Create a container task using calculate ellipse script example
container_task = ContainerTask(
    name=task_name,
    input_data_dir="/var/inputs",
    output_data_dir="/var/outputs",
    inputs=kwtypes(a=float, b=float),
    outputs=kwtypes(area=float, metadata=str),
    image="ghcr.io/flyteorg/rawcontainers-python:v1",
    command=[
        "python",
        "calculate-ellipse-area.py",
        "/var/inputs",
        "/var/outputs",
    ],
)

# Add task to workflow
node = workflow.add_entity(task, a=workflow.inputs["a"], b=workflow.inputs["b"])

# Define output from workflow
workflow.add_workflow_output(
    "output_list",
    [node.output["area"]],
    python_type=typing.List[float],
)

# Try to run workflow locally, tasks always return None
print(workflow(a=1.0, b=3.0))

```
Returns 

> TypeError: Failed to convert return value for var area for function model_a with error <class 'flytekit.core.type_engine.TypeTransformerFailedError'>: Python value cannot be None, expected <class 'float'>/simple: FLOAT

Is there an issue for running container tasks locally in imperative workflows? Above is an example of how to reproduce the issue. This makes use of the caclulate-ellipse-area.py script from the [docs](https://docs.flyte.org/projects/cookbook/en/stable/auto/core/containerization/raw_container.html). I would appreciate any help. I have been running into this quite a bit while testing and cannot seem to get around it.

**Comment by kumare3** [comment]
@thoughtworks-tom today raw containers do not have a local execution implications https://github.com/flyteorg/flytekit/blob/73eaad121df796ba4490b8af0706b4391ae8b28e/flytekit/core/container_task.py#L72

**Comment by kumare3** [comment]
@thoughtworks-tom btw, we are getting imperative workflows in pyflyte run ^
