### ISSUE TITLE
[Docs] FlyteRemote code snippets need to be added to the remote access section

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#2769]
### Description

The "Remote Access" [section](https://docs.flyte.org/projects/cookbook/en/latest/auto/remote_access/remote_workflow.html) currently has `flytectl` commands to register and run flyte entities. FlyteRemote examples need to be appended to each of the doc pages to showcase accessing the backend programmatically through an API.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Alcadeus0** [comment]
Hello, can i work on this :)

**Comment by Alcadeus0** [comment]
@jerempy yeah i'm on it

**Comment by jerempy** [comment]
ok coolio. @samhita-alla can you re-assign when you get a chance?

**Comment by jerempy** [comment]
@samhita-alla thanks for assign. PR up to add the requested snippets to docs: https://github.com/flyteorg/flytesnacks/pull/910 😎
