### ISSUE TITLE
[UI Feature] Make Flyte Deck modal expandable

### ISSUE THREAD

**Issue by hankfanchiu** [flyteorg/flyte#2774]
### Motivation: Why do you think this is important?

We're using Flyte Deck to render static Jupyter notebooks serving as data reports. Given the current size of the Flyte Deck modal, some long notebook paragraphs are difficult to view.

### Goal: What should the final outcome look like, ideally?

The Flyte Deck modal should be enlarged, perhaps scaled based on the viewport size while having the existing dimensions as the minimum.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
cc @jsonporter
