### ISSUE TITLE
[Docs] Activate launch plan docs are missing --version flag

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#2776]
### Description

https://docs.flyte.org/projects/cookbook/en/latest/auto/core/scheduled_workflows/lp_schedules.html#activating-a-schedule Only a specific version of a launch plan can be activated
the docs should update the sample command to include `--version <foo>`

cc @SmritiSatyanV 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by katrogan** [comment]
We should also update the docs to specify that a launch plan can be deactivated with the `--archive` flag

**Comment by SmritiSatyanV** [comment]
https://github.com/flyteorg/flytesnacks/pull/853
