### ISSUE TITLE
[Docs] `make` is resulting in an error when trying to build the flytesnacks docs

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#2783]
### Description

There shouldn't be any errors. Will have to fix indentations, broken links, and RST styles.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by techytushar** [comment]
Hi @samhita-alla ,
Please can you give some more info on how to reproduce this, from which folder do we need to run the `make` command.
I ran the `make rsts` and `make html` command from `cookbook/docs` folder and it worked without any errors (it did throw some warnings though)

**Comment by samhita-alla** [comment]
@techytushar, yeah, we'll need to fix the warnings. Try running `make linkcheck` and you'll see some errors. We'll also need to fix the broken links.

**Comment by Azanul** [comment]
@techytushar Are you looking into it or can I give it a go?

**Comment by Azanul** [comment]
Taking this up as it seems stale

**Comment by Azanul** [comment]
#take

**Comment by Azanul** [comment]
@samhita-alla I don't know how to fix this 
```
(auto/deployment/customizing_resources: line   47) broken    https://github.com/flyteorg/flytepropeller/blob/v0.10.5/config.yaml#L51,L56 - Anchor 'L51,L56' not found
```

**Comment by samhita-alla** [comment]
Um I'm not sure if there's a way to fix them. For now, please ignore the anchor not found warnings.

**Comment by samhita-alla** [comment]
@Azanul when can you create a PR?

**Comment by Azanul** [comment]
@samhita-alla I'll try by tonight.

**Comment by Azanul** [comment]
`/workspaces/flytesnacks/cookbook/docs/auto/core/control_flow/subworkflows.rst:175: WARNING: undefined label: 'using multiple kubernetes clusters'
/workspaces/flytesnacks/cookbook/docs/auto/core/type_system/structured_dataset.rst:86: WARNING: py:class reference target not found: flytekit.types.schema.FlyteSchema
/workspaces/flytesnacks/cookbook/docs/auto/core/type_system/typed_schema.rst:62: WARNING: py:meth reference target not found: flytekit.types.schema.FlyteSchema.open
/workspaces/flytesnacks/cookbook/docs/auto/core/type_system/typed_schema.rst:84: WARNING: py:meth reference target not found: flytekit.types.schema.FlyteSchema.open
/workspaces/flytesnacks/cookbook/docs/auto/integrations/flytekit_plugins/greatexpectations/index.rst:25: WARNING: py:class reference target not found: flytekit.types.schema.FlyteSchema
/workspaces/flytesnacks/cookbook/docs/auto/integrations/flytekit_plugins/sql/sql_alchemy.rst:58: WARNING: py:class reference target not found: flytekit.types.schema.FlyteSchema`

@samhita-alla, I've fixed many but these still remain

**Comment by samhita-alla** [comment]
Have you created a PR?

**Comment by Azanul** [comment]
> @Azanul Have you created a PR?

Yes, but in draft

**Comment by Azanul** [comment]
@samhita-alla just wasted my work.

**Comment by samhita-alla** [comment]
@Azanul, you haven't linked any PR, so I assumed you haven't worked on it.

**Comment by Azanul** [comment]
@samhita-alla 
![flyte_ss](https://user-images.githubusercontent.com/42029519/202093898-6116c5a4-b1dd-40b6-ba10-993bd1b23838.png)

**Comment by samhita-alla** [comment]
Oh, I'm sorry. I missed it somehow. I saw your message and thought you haven't linked it yet. Sorry!
