### ISSUE TITLE
[FlyteCTL Feature] Flytectl needs to log the url and a config to skip browser opening while authenticating through Pkce

### ISSUE THREAD

**Issue by shahwar9** [flyteorg/flyte#2787]
### Describe the feature/command for FlyteCTL

When `flytectl` is used inside a container it tries to open a browser with `xdg-open`. This fails. 

Ideally flytectl would have an option to only print the URI and not try to open it.
flytectl running in containers would really benefit from this by mounting a browser port onto the container and opening the URL by just copying and pasting the URL. 

Various CLI browsers have been tried and they are not really handy when using for Auth or filling out an Authentication form. A URL in the console would let people open the Auth UI in their favourite browsers through port mounts.

### Provide a possible output or UX example

Something like this would work:

Please open the following URL and authenticate yourself:

<URL>

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@pmahindrakar-oss , can we close this?

**Comment by pmahindrakar-oss** [comment]
yes closing this. One issue is pending with [PR](https://github.com/flyteorg/flyteidl/pull/314)  which is tracked [separately](https://github.com/flyteorg/flyte/issues/2862)  . Also  we didn't implement logging of the URL as mentioned in the main title but instead settled on implementing the Device flow of Oauth2.0. If needed we can change the title and description or leave it as it is
