### ISSUE TITLE
[Docs] Docs on how to assign project-domain-specific permissions

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#2790]
### Description

We need docs on how to define a service account at the project-domain level and annotate it with an env-user-role.

Reference Slack thread: https://discuss.flyte.org/t/2404214/yes-but-i-don-t-think-it-works-across-accounts-i-e-eks-is-de

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
cc: @pmahindrakar-oss

**Comment by 26tanishabanik** [comment]
@samhita-alla , I have gone through the discussion, but not able to figure out, where from should I refer for the documentation, also, I am not able to join the slack community

**Comment by samhita-alla** [comment]
@26tanishabanik, you can join our Slack using [this](https://slack.flyte.org/) link. 

@pmahindrakar-oss, what's the best place to document the above discussion -- which section in https://docs.flyte.org/en/latest/deployment/aws/manual.html page precisely? I'm confused between (4) in https://docs.flyte.org/en/latest/deployment/aws/manual.html#installing-flyte and https://docs.flyte.org/en/latest/deployment/aws/manual.html#flyte-user-role.

**Comment by Thusal06** [comment]
Can you assign me? @samhita-alla

**Comment by samhita-alla** [comment]
@Thusal06, please go ahead and create a PR. It's first-come, first-serve.

**Comment by pmahindrakar-oss** [comment]
@samhita-alla this should go in the manual installation doc where we specify creating only one flyte-user-role across environments currently. For GCP we create each one separate https://docs.flyte.org/en/latest/deployment/gcp/manual.html#time-for-helm
