### ISSUE TITLE
[BUG] In some cases Flyte Admin not respecting terminate call 

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#280]
**Describe the bug**
A user reported an issue where clicking the Terminate button in the UI did not terminate a workflow.

**Expected behavior**
User expected the UI to show the state of the workflow as Terminated instead of Running.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [x] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
Have not been able to reproduce.

**Screenshots**
N/A

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [x] AWS
     * [x] GCP
     * [x] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**
Have confirmed in logs the receipt of the `TerminateExecution` call, and the Aborted event that propeller sends back to Admin.

**Comment by kumare3** [comment]
I agree, either should terminated (terminating) or return an error!

**Comment by anandswaminathan** [comment]
+1 on Terminating state. We are seeing more issues/cases where Propeller is missing to send the event. Remember this should be a blocking Admin call from Propeller. cc @katrogan @kumare3

**Comment by kumare3** [comment]
I have been able to consistently reproduce this. Its for cases in which the workflows are extremely large. Flyteadmin does respect the terminate call, but it does not update the state. so UI will get updated eventually when propeller updates the state. This is especially a problem when we have system errors and propeller is backing off

**Comment by kumare3** [comment]
@katrogan / @anandswaminathan can one of you help with this issue?
cc @jeevb

**Comment by EngHabu** [comment]
Not enough information to go on. Please reopen if it's persistently happening... and we can jump on slack to debug it..
