### ISSUE TITLE
[Docs] Broken image for external authorization server

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#2804]
### Description

Following page https://docs.flyte.org/en/latest/deployment/cluster_config/auth_appendix.html#service-authentication-using-oauth2 has broken image 
<img width="1318" alt="Screenshot 2022-08-24 at 5 21 43 PM" src="https://user-images.githubusercontent.com/77798312/186411643-e405bd41-f243-4a9c-9117-c0138a705469.png">

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pmahindrakar-oss** [comment]
cc : @hampusrosvall

**Comment by Smartmind12** [comment]
I wanted to work on this issue so i have pushed a PR for the same!
