### ISSUE TITLE
[BUG] By default, FlyteDirectory is empty when executing workflow on Flyte cluster

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#2806]
### Describe the bug

To reproduce, register and run these tasks and workflows on a local `flytectl demo` cluster:

```python
from pathlib import Path
from typing import List

from flytekit import task, workflow
from flytekit.types.directory import FlyteDirectory


@task
def create_directory() -> FlyteDirectory:
    path = Path("/tmp/flytekit-testing")
    path.mkdir(exist_ok=True, parents=True)
    for file in ["file1.txt", "file2.txt"]:
        with (path / file).open("w") as f:
            f.write("hey\n")
    return FlyteDirectory(path=str(path))


@task
def downstream_task(directory: FlyteDirectory) -> List[str]:
    output = []
    for file in Path(directory.path).glob("*"):
        output.append(str(file))
        print(file)
    return output


@workflow
def wf() -> List[str]:
    return downstream_task(bento_model=create_directory())


if __name__ == "__main__":
    wf()

```

You'll find that the output of the `downstream_task` contains no filepath strings:
![image](https://user-images.githubusercontent.com/2816689/186533247-18d668a3-fa20-4cd6-a5dd-15b616aff85f.png)

### Expected behavior

I would expect the files to be in the `directory.path`. Instead, I need to explicitly call `directory.download()` to get those files there.

Why is this a problem? Because the local and remote experiences are divergent: if I just run the tasks above with `python`, the files are there. But when executing remotely, now I need to change my code to `.download()` the files.

## Potential Solutions

1. automatically download the files
2. raise an exception if the `directory.path` is invoked but `directory.downloaded == False`
3. make the local python experience equivalent to the remote one: force the user to invoke `download()`.
4. others?

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pingsutw** [comment]
@cosmicBboy, It can be fixed by replacing `Path(directory.path)` with `Path(directory)`. 

[Fspath](https://github.com/flyteorg/flytekit/blob/df6a949cb99169c7bc612cac593b46bc4a7586dc/flytekit/types/directory/types.py#L131-L139) will be invoked when we call Path(directory), which will trigger downloader to download the files

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/37936015/186632560-34e5ab0b-4157-4f45-9b16-2c174e5a7768.png">

**Comment by cosmicBboy** [comment]
ah, nice! could we also maybe make `path` a private variable `self._path`, and make a property that does the same thing?

```python
@property
def path(self):
    self.__fspath__()
    return self._path
```

This will reduce confusion and make the behavior more consistent.

**Comment by cosmicBboy** [comment]
an alternative: don't expose a `path` property at all... this adds a possible execution path that does the wrong thing.

**Comment by eapolinario** [comment]
no longer reproes.
