### ISSUE TITLE
[Docs] Add docs on how to handle a large response when using `FlyteRemote.sync`

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#2809]
### Description

Slack thread: https://discuss.flyte.org/t/2423924/k-edit-cm-flyte-admin-base-config-n-flyte-server-grpcport-80

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Ln11211** [comment]
Hey there,
@samhita-alla
I went through the thread and I understood that updating/increasing the `maxMessageSizeBytes` was the fix to Anna's problem, but I wanted to know more about the problem and wonder how the fix works, so I checked for documentation and files about `FlyteRemote.sync` and couldn't find any.. So, should I just reference Anna's problem in the documentation ?

Are there other documentation files that I can use for boilerplate/ as a template?

I might be interested in writing the documentation for this fix, can't promise though :)

**Comment by Ln11211** [comment]
#self-assign

**Comment by samhita-alla** [comment]
@Ln11211, thanks for assigning yourself to the issue. Here's the documentation on sync: https://docs.flyte.org/projects/flytekit/en/latest/design/control_plane.html#retrieving-inspecting-executions. Please add the fix to this page and the [troubleshooting guide](https://docs.flyte.org/en/latest/community/troubleshoot.html#troubleshoot) as well.
