### ISSUE TITLE
[BUG] flyteadmin make generate has different results between go 1.18 and 1.19

### ISSUE THREAD

**Issue by andrewwdye** [flyteorg/flyte#2814]
### Describe the bug

Running `make generate` on a clean flyteadmin repo produces different results between go versions 1.18 and 1.19. This causes the Check Go Generate checker to fail and prevents using the latest version of go for development.

Looks like this is related to `enumer` and https://github.com/alvaroloes/enumer/issues/68.

### Expected behavior

Running `make generate` on a clean flyteadmin repo with the latest version of go produces the same output as Check Go Generate.

### Additional context to reproduce

1. Install latest version of go (1.19)
2. From a clean flyteadmin repo, run `make generate`
3. Run `git diff`

```
diff --git a/auth/config/authorizationservertype_enumer.go b/auth/config/authorizationservertype_enumer.go
index a5c7dc2..f6e89a6 100644
--- a/auth/config/authorizationservertype_enumer.go
+++ b/auth/config/authorizationservertype_enumer.go
@@ -1,6 +1,5 @@
 // Code generated by "enumer --type=AuthorizationServerType --trimprefix=AuthorizationServerType -json"; DO NOT EDIT.

-//
 package config

 import (
diff --git a/auth/config/samesite_enumer.go b/auth/config/samesite_enumer.go
index af9bfdf..e42e58f 100644
--- a/auth/config/samesite_enumer.go
+++ b/auth/config/samesite_enumer.go
@@ -1,6 +1,5 @@
 // Code generated by "enumer --type=SameSite --trimprefix=SameSite -json"; DO NOT EDIT.

-//
 package config

 import (
diff --git a/pkg/runtime/interfaces/inlineeventdatapolicy_enumer.go b/pkg/runtime/interfaces/inlineeventdatapolicy_enumer.go
index 63ff94e..7c3895b 100644
--- a/pkg/runtime/interfaces/inlineeventdatapolicy_enumer.go
+++ b/pkg/runtime/interfaces/inlineeventdatapolicy_enumer.go
@@ -1,6 +1,5 @@
 // Code generated by "enumer -type=InlineEventDataPolicy -trimprefix=InlineEventDataPolicy"; DO NOT EDIT.

-//
 package interfaces

 import (
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
closing as all OSS flyte components on 1.19.
