### ISSUE TITLE
[Docs] Use different regex when deploying using helm to define logs

### ISSUE THREAD

**Issue by SmritiSatyanV** [flyteorg/flyte#2820]
### Description

While configuring logging link for Splunk, set up a template URI like: ```https://splunk.something.com/en-US/app/search/search?q=search%20index%3Dmy_index%20kubernetes.namespace_name%3D{{ "{{" }}.namespace{{ "}}" }}%20kubernetes.container_name%3D{{ "{{" }}.containerName{{ "}}" }}%20kubernetes.pod_name%3D{{ "{{" }}.podName{{ "}}" }}&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=-72h&latest=now```
 
It is deployed using helm. 
Local config: 
```plugins:
  logs:
    templates:
      - displayName: splunk
        templateUris:
          - "https://splunk.something.com/en-US/app/search/search?q=search%20index%3Dmy_index%20kubernetes.namespace_name%3D{{.namespace}}%20kubernetes.container_name%3D{{.containerName}}%20kubernetes.pod_name%3D{{.podName}}&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=-72h&latest=now"
 ```

Use different regex ids (ex. {{ .foo }}) that helm uses to define these logs.

[Thread](https://discuss.flyte.org/t/2429565)

**Comment by samhita-alla** [comment]
@SmritiSatyanV, what should be done exactly? Is there a slack thread?

**Comment by SmritiSatyanV** [comment]
The contents of slack thread is the description of the issue. Added the link to slack convo @samhita-alla

**Comment by samhita-alla** [comment]
Could you please link the discuss.flyte.org thread?
