### ISSUE TITLE
[Docs] An example showing AWS EFS volume in eks cluster for ``ReadWriteMany``

### ISSUE THREAD

**Issue by SmritiSatyanV** [flyteorg/flyte#2821]
### Description

Provide an example that illustrates how EFS volume can be used in eks cluster.

Ketan:  I think we should have an example of using Efs
[Reference](https://flyte-org.slack.com/archives/CP2HDHKE1/p1660138337197199?thread_ts=1660068983.300349&cid=CP2HDHKE1)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by CAG07** [comment]
Has this been assigned or can I work on it @eapolinario ?
