### ISSUE TITLE
[Housekeeping] [polish] Secrets handling

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#2822]
# Secrets Related Cleanup
### Single-Binary working
Checked out yes.

### Missing secret
If a secret is missing, handling is ungraceful.  The pod is stuck on container creating (tested on flytectl demo)

```bash
ab4xnx6g9xbf7mxfltrb-n1-0   0/1     ContainerCreating   0          17m
```

```
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    13m                  default-scheduler  Successfully assigned flytesnacks-development/ab4xnx6g9xbf7mxfltrb-n1-0 to 82c4e8393be0
  Warning  FailedMount  2m30s (x3 over 11m)  kubelet            Unable to attach or mount volumes: unmounted volumes=[ovzwk3rnnfxgm216], unattached volumes=[ovzwk3rnnfxgm216 kube-api-access-p58zr]: timed out waiting for the condition
  Warning  FailedMount  77s (x14 over 13m)   kubelet            MountVolume.SetUp failed for volume "ovzwk3rnnfxgm216" : references non-existent secret key: username
  Warning  FailedMount  13s (x3 over 9m13s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[ovzwk3rnnfxgm216], unattached volumes=[kube-api-access-p58zr ovzwk3rnnfxgm216]: timed out waiting for the condition
```

### Webhook Confusion
https://flyte-org.slack.com/archives/CP2HDHKE1/p1660840108152709?thread_ts=1660338586.829659&cid=CP2HDHKE1
[discuss](https://discuss.flyte.org/t/2236280/nice-i-ve-been-through-the-docs-and-hitting-some-speed-bumps)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
@wild-endeavor I have a PR open adding optional flags on k8s secrets for file mounts and env vars. This works when I manually create Pods for both, for example:
```
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: busybox
    args:
      - /bin/sh
      - -c
      - sleep 10; touch /tmp/healthy; sleep 30000
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
    - name: foo
      secret:
        secretName: mysecret
```
I can see /tmp/healthy exists after 10 seconds but the secret is not mounted. This should allow flytekit to execute in the container and fail when the secret is missing. (this works similarly for env vars). However, when I tested this locally (by replacing the pod-webhook image in sandbox) the container started (without the secret) and then flytekit ran and was ultimately OOM killed. So this is not working as expected, ie. flytekit not finding the secret and throwing "secret x:y not found" error. Is there something I'm missing in how flytekit retrieves secrets?

**Comment by hamersaw** [comment]
@wild-endeavor pinging again on this. With the aforementioned PR, we can successfully create and start Pods with missing secrets (both file and env mounted) - but the Pods just hang and do not do anything. I tried to manually execute the `pyflyte execute` command in the Pod container to see if there was any output and there was nothing. After about 90s the Pods fail with "Matplotlib is building the font cache; this may take a moment." for the flytesnacks `core.containerization.use_secrets.user_info_task` example.
