### ISSUE TITLE
[Docs] Exploring tasks beyond Python: Using Spark based Tasks

### ISSUE THREAD

**Issue by shivaylamba** [flyteorg/flyte#2826]
### Description

There should be a separate section inside getting started guide for explaining users how to use tasks that might not be Python based, for example: Spark based tasks. 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
invalid
