### ISSUE TITLE
[Docs] Getting Started Guide section on Scaling a project to a repository

### ISSUE THREAD

**Issue by shivaylamba** [flyteorg/flyte#2828]
### Description

There should be a separate section inside getting started guide for on scaling a project to a repository using flyte register.  In this section we will teach the user how to work with and structure their code in a whole repo.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
invalid
