### ISSUE TITLE
[Docs] Change limit set in the platform configuration [1Gi] for memory in sandbox

### ISSUE THREAD

**Issue by SmritiSatyanV** [flyteorg/flyte#2842]
### Description

You can change the set limit using the below commands:

```
$ k edit cm flyte-admin-config

  task_resource_defaults.yaml: |
    task_resources:
      defaults:
        cpu: 100m
        memory: 500Mi
        storage: 500Mi
      limits:
        cpu: 2
        gpu: 1
        memory: 1Gi <- change this value
        storage: 20Mi
```

Add it in the environment guide setup or troubleshooting guide. The above config works for sandbox.

For demo cluster, you can't change config at runtime. Hence, change the config and build a custom image. 
```
$ git clone git@github.com:flyteorg/flyte.git
$ cd flyte
$ vim flyte.yaml (update config)
$ docker build -t user_name/sandbox-lite-test -f docker/sandbox-lite/Dockerfile . # Build image
$ docker push user_name/sandbox-lite-test
$ flytectl demo start --image user_name/sandbox-lite-test
```

**OR**

``docker exec`` into the cluster and modify the flyte.yaml file. 
``docker run -v my_flyte.yaml:flyte.yaml …``
``docker restart flyte-sandbox``

**Comment by wild-endeavor** [comment]
hey @SmritiSatyanV let's hold off on making this change.  we are making some changes to the way flytectl brings up the demo cluster that will change the steps here.  let's circle back to this in six weeks or so?

**Comment by SmritiSatyanV** [comment]
Absolutely @wild-endeavor , thank you for the update..

**Comment by wild-endeavor** [comment]
not needed anymore
