### ISSUE TITLE
[Docs] Unable to view pod logs from console, elaborate how to use logging link

### ISSUE THREAD

**Issue by SmritiSatyanV** [flyteorg/flyte#2846]
### Description

``User: we configured own domain name and able to access the flyte console after running workflow. jobs are getting succeed but unable to view the pod logs from the console. link is pointing to http://localhost:30082/  like below but our flyte url is https://dev-flyte.example.com/.
please let me know anything need to be updated. also we dont see any logs are pushed to cloudwatch after completion of job.
[http://localhost:30082/#!/log/cloudops-max-flyte-demo-development/f82ed701fa1f04c489[…]0-0-driver/pod?namespace=cloudops-max-flyte-demo-development](http://localhost:30082/#!/log/cloudops-max-flyte-demo-development/f82ed701fa1f04c4896d-n0-0-driver/pod?namespace=cloudops-max-flyte-demo-development)``
Configure [logging links](https://github.com/flyteorg/flyte/blob/cc127265aec490ad9537d29bd7baff828043c6f5/charts/flyte-core/values-eks.yaml#L304-L317) and refer to [this](https://docs.flyte.org/projects/cookbook/en/stable/auto/deployment/configure_logging_links.html)

[Slack conversation](https://flyte-org.slack.com/archives/CP2HDHKE1/p1661450232630339)

**Comment by eapolinario** [comment]
@SmritiSatyanV , can you add more context? Link to the slack thread at the very least.

**Comment by SmritiSatyanV** [comment]
The conversation I have mentioned above is the only context in slack.. @eapolinario
