### ISSUE TITLE
[Core feature] Use https://github.com/Textualize/rich for pyflyte commands to help build great UX

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#2863]
### Motivation: Why do you think this is important?

Sometimes errors are not easy to understand, sometimes stack traces are raised. Also tables and other things can be rendered much better with rich

### Goal: What should the final outcome look like, ideally?

Beautiful rendering of the CLI

### Describe alternatives you've considered 

NA

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
We've been happy users of rich for a while.
