### ISSUE TITLE
[Core feature] Add support for duckdb with structured dataset

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/flyte#2865]
### Motivation: Why do you think this is important?

[duckdb](https://github.com/velascoluis/serverless-duckdb) is a serverless DB deployed at GCP. we could integrate it with Flyte, and write task output, like `pandas.DataFrame` or `arrow.Tables`, to duckdb transparently.

```python
@task
def t1() -> Annotated[StructuredDataset, kwtypes(len=int)]:
    df = pd.DataFrame({"name": ["dylan", "steve"],"age": [33, 32]})
    return StructuredDataset(df, uri=duckdb_uri) # flytekit will write pandas dataframe to duckdb
```

### Goal: What should the final outcome look like, ideally?

Add a duckDB plugin in flytekit, and add a structured dataset encoder and decoder. 
Here is an [example](https://github.com/flyteorg/flytekit/blob/master/plugins/flytekit-polars/flytekitplugins/polars/sd_transformers.py) to add custom encoder/decoder in flytekit-plugin

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by rajagurunath** [comment]
Hi Team, I was new to Flyte, Shall I take this task and try this integration of flytekit and DuckDB?
(if no one was working on this issue !) 

Thanks in Advance

**Comment by samhita-alla** [comment]
@rajagurunath, please go ahead! Do you want me to assign the issue to you?

**Comment by rajagurunath** [comment]
Thanks a lot, @samhita-alla, please assign this issue to me!

**Comment by samhita-alla** [comment]
@rajagurunath, hey I'm going to unassign you as my team will work on this issue. I hope you haven't started working on it. Sorry!

**Comment by shivaylamba** [comment]
Hi @samhita-alla I would like to take up the issue

**Comment by rajagurunath** [comment]
sure No problem @samhita-alla Thanks, yeah kind of started with an initial exploration of the code base and saving the data frame to duckdb, etc, will have a look at the list and pick other issues. 

Please let me know @shivaylamba, for any help needed from my side!
