### ISSUE TITLE
[Docs] API reference for pyflyte

### ISSUE THREAD

**Issue by SmritiSatyanV** [flyteorg/flyte#2888]
### Description

Need API references for ``pyflyte`` init, local-cache, package, register, run, and serialize

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
Use [sphinx click](https://sphinx-click.readthedocs.io/en/latest/) to generate CLI reference docs

See [here](https://github.com/unionai-oss/unionml/blob/main/docs/source/cli_reference.rst) for example usage

**Comment by sanjus-robotic-studio** [comment]
#self-assign

**Comment by sanjus-robotic-studio** [comment]
Hey can you Assign this issue to me?

**Comment by rithvikshetty** [comment]
#self-assign

**Comment by rithvikshetty** [comment]
I'm a first time contributor, is this a good first issue?
@cosmicBboy

**Comment by adicoder95** [comment]
I am willing to work on this issue as Hacktoberfest participant.
can you assign to me

**Comment by Devolta05** [comment]
Hello I want to contribute to this issue. I am having a lot of troubles, the documentation doesn't make it clear where & how to run the workflow of documentation building (to my knowledge, please reference it) locally, neither does it give specific locations for API reference to `pyflyte` & conflicts with `flytectl`. It is very confusing with respect to the flow of documentation & code. Kindly allow for more information. Thank you

**Comment by Azanul** [comment]
@adicoder95 Are you working on it?

**Comment by adicoder95** [comment]
@Azanul yes, but facing lots of trouble. That's why taking time.

**Comment by Azanul** [comment]
@adicoder95 In which parts are you facing issues? I might be able to help

**Comment by samhita-alla** [comment]
The changes need to be made in the flytekit directory. The API docs should be rendered [here](https://docs.flyte.org/projects/flytekit/en/latest/).
