### ISSUE TITLE
[Docs] Flyte Tensorflow cookbook example doesn't work on Macbooks with Silicon Chip

### ISSUE THREAD

**Issue by jevers-bc** [flyteorg/flyte#2896]
### Description

Trying to run the Tensorflow example from the Flyte cookbook results in an error for users with the Mac silicon chip. 

Tutorial - [link](https://github.com/flyteorg/flytesnacks/tree/master/cookbook/integrations/kubernetes/kftensorflow)

Tensorflow can be installed on a user's local machine via `pip install tensorflow-macos`, but using base image for the tutorial (`tensorflow/tensorflow:latest-gpu` or `tensorflow/tensorflow:latest`) causes the following error when a workflow execution is attempted in a sandbox deployment:

```
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
qemu: uncaught target signal 6 (Aborted) - core dumped
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
Tensorflow has been running ok on Macs for a bit. Closing this.
