### ISSUE TITLE
[BUG] Cached task is oblivious to the code changes

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#2899]
### Describe the bug

New code changes aren't getting picked up when the task is cached.

### Expected behavior

Cached outputs need to be discarded when code changes are introduced in the cached task.

### Additional context to reproduce

```python
from flytekit import task, workflow


@task(cache=True, cache_version="1.0")
def t1() -> int:
    return 2


@workflow
def wf() -> int:
    return t1()


if __name__ == "__main__":
    wf()
```

1. Register the workflow
2. Run the workflow
3. Change the output to 3
4. Re-register the workflow
5. The output of t1 is still 2 (fetch from cache)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
@samhita-alla did you increment the `cache_version`? Cache keys are determined by the task id, cache version, and input values. There is currently no mechanism in Flyte to configure caching based on internal code changes.

**Comment by samhita-alla** [comment]
@hamersaw, oh okay. @pingsutw said this is a valid issue, though: https://flyte-org.slack.com/archives/CP2HDHKE1/p1663345443691509?thread_ts=1663234563.754209&cid=CP2HDHKE1.

I'll close the issue.
