### ISSUE TITLE
[Deployment] Flyte on k3s.

### ISSUE THREAD

**Issue by ChenpiDog** [flyteorg/flyte#2903]
### Description

Provide the deployment guidance of flyte on k3s, as detailed as possible, thank you.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@ChenpiDog , we support a [number of deployments](https://docs.flyte.org/en/latest/deployment/index.html) in our docs and it'd be unwieldy if we decided to officially support yet another deployment strategy. Unfortunately we don't have the capacity to maintain yet another deployment story. 

Having said that, the sandbox development environment uses k3s under the covers. You can read about it [here](https://docs.flyte.org/en/latest/deployment/sandbox.html#deployment-sandbox).

Contributions are welcome!

**Comment by rupurt** [comment]
It would be really awesome to be able to deploy this to k3s locally with a similar setup to the cloud deployments. Currently there are a lot of limitations and rough edges while starting out try to deploy the sandbox. For example it's not very easy to override the seed projects.

https://github.com/flyteorg/flyte/issues/2503#issuecomment-1570863885
