### ISSUE TITLE
Deploy Flyte Sandbox to a Cloud Kubernetes Cluster doc is missing a command

### ISSUE THREAD

**Issue by sanjaychouhan-adf** [flyteorg/flyte#2918]
### Description

The doc https://docs.flyte.org/en/latest/deployment/sandbox.html#deploy-flyte-sandbox-to-a-cloud-kubernetes-cluster need one more step to configure the minio url in configmap of flyteadmin.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by evalsocket** [comment]
User need minio access at 30084, So they need to run `kubectl port-forward --address 0.0.0.0 svc/postgres 30084:9000 -n flyte` in the background,


@eapolinario I faced this issue with a few on-prem user before also, They want to configure signed URL from helm so they don't need to port forward, But our helm chart only support sandbox(local) https://github.com/flyteorg/flyte/blob/master/charts/flyte-core/templates/_helpers.tpl#L180, It's hardcoded

**Comment by eapolinario** [comment]
Just linking https://github.com/flyteorg/flyte/issues/2868 as that is the exact same issue.
