### ISSUE TITLE
[Core feature] Support mapping `principal` to Kubernetes namespace

### ISSUE THREAD

**Issue by hankfanchiu** [flyteorg/flyte#2927]
### Motivation: Why do you think this is important?

At Stripe, Flyte users will be able to register and then launch workflows on an ad hoc basis, without second party review. Within these workflows, some tasks may access sensitive data. From a security perspective, we must be able to thread the identity of a Flyte user through Flyte Admin and Kubernetes to downstream, internal services or resources.

To do so for any task execution, we must be able to run a Kubernetes workload in a Kubernetes namespace that is scoped to the user. Then, within this task that makes the outbound request to an internal service or resource, we would first extract the username/principal from the namespace, and then propagate this identity encoded in an access token.

### Goal: What should the final outcome look like, ideally?

In [Flyte Admin's `namespace_mapping` configuration](https://docs.flyte.org/en/latest/deployment/cluster_config/flyteadmin_config.html#section-namespace-mapping), add support for `{{ principal }}` in the template.

Then, an example scenario would be as such, given this Flyte Admin configuration:

```yaml
namespace_mapping:
  template: "{{ principal }}"
```

When the user `hankfanchiu` triggers a task execution, the Kubernetes workload would run in the `hankfanchiu` namespace.

### Describe alternatives you've considered 

None

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by EngHabu** [comment]
@hankfanchiu thank you for filing the issue...

There are two parts to this change:
1. The cluster resource sync (that attempts to create/update K8s resources for each project/domain): you will have to disable that because there is no realistic way for it to pickup the principals. Is that your expectation as well? the provisioning of namespaces/service accounts... etc. will happen out of band?
2. At execution time, to run these executions on the desired namespace... for that you can look at [this line](https://github.com/flyteorg/flyteadmin/blob/master/pkg/manager/impl/execution_manager.go#L620). This is the function that takes in the template and, as of now, the project and domain and does the substitution. I imagine this needs to change to also use [this function](https://github.com/flyteorg/flyteadmin/blob/master/pkg/manager/impl/execution_manager.go#L113) to retrieve the principal to substitute with.

Please let me know if you have any questions!

**Comment by hankfanchiu** [comment]
> The cluster resource sync (that attempts to create/update K8s resources for each project/domain): you will have to disable that because there is no realistic way for it to pickup the principals. Is that your expectation as well? the provisioning of namespaces/service accounts... etc. will happen out of band?

Yes, that is our expectation -- we will manage the principal-based namespaces and service accounts out of band.

> At execution time, to run these executions on the desired namespace... for that you can look at [this line](https://github.com/flyteorg/flyteadmin/blob/master/pkg/manager/impl/execution_manager.go#L620). This is the function that takes in the template and, as of now, the project and domain and does the substitution. I imagine this needs to change to also use [this function](https://github.com/flyteorg/flyteadmin/blob/master/pkg/manager/impl/execution_manager.go#L113) to retrieve the principal to substitute with.

Looks straightforward enough. Thank you for the guidance, @EngHabu!

**Comment by hankfanchiu** [comment]
Within `clusterresource.controller.Sync()`, how should we handle not having a principal to pass to `common.GetNamespaceName()`?

https://github.com/flyteorg/flyteadmin/blob/281172edf55fe6800959238fc128964ead6d9101/pkg/clusterresource/controller.go#L580

**Comment by hankfanchiu** [comment]
> Within `clusterresource.controller.Sync()`, how should we handle not having a principal to pass to `common.GetNamespaceName()`?

@katrogan, what do you think?

**Comment by katrogan** [comment]
hey @hankfanchiu do you plan on running cluster resource controller to provision user-based namespaces?

**Comment by hankfanchiu** [comment]
> do you plan on running cluster resource controller to provision user-based namespaces?

No, we will separately create user/principal-based namespaces with our own cron job that syncs with an LDAP group's membership list.

**Comment by wild-endeavor** [comment]
Can we close this @hankfanchiu ?

**Comment by hankfanchiu** [comment]
> we must be able to run a Kubernetes workload in a Kubernetes namespace that is scoped to the user.

We switched to using user-scoped Kubernetes service accounts instead.

With an ingress proxy, we identify the caller through an access token, and then set (or override) the `ExecutionCreateRequest.ExecutionSpec.SecurityContext.RunAs.K8SServiceAccount` field before forwarding the request to Flyte Admin.
