### ISSUE TITLE
[Docs] Getting started - installing flytectl more securely

### ISSUE THREAD

**Issue by hajapy** [flyteorg/flyte#2934]
### Description

In the getting started guide, the process to [install flytectl for other operating systems suggests](https://github.com/flyteorg/flyte/blob/v1.2.0-b3/rsts/getting_started/index.rst#creating-a-demo-flyte-cluster):

```bash
curl -sL https://ctl.flyte.org/install | sudo bash -s -- -b /usr/local/bin # You can change path from /usr/local/bin to any file system path
```

Passing in an arbitrary script to bash with sudo privileges is a recipe for bad things to happen (eg. codecov incident). 

Given that installing flytectl can be achieved by simply downloading a pre-built binary directly from github releases, my suggestion would be to [point users to those artifacts](https://github.com/flyteorg/flytectl/releases/latest) instead of using this approach. 

Alternatively, I'd use the [direct github url for the script](https://raw.githubusercontent.com/flyteorg/flytectl/HEAD/install.sh) in the docs instead of the redirect (which could be a hijack point), and remove the need for sudo.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Smartmind12** [comment]
@hajapy Could you assign this issue to me so that i can work on it ...Thanks!

**Comment by Smartmind12** [comment]
@cosmicBboy @eapolinario @hajapy Kindly review the PR and recommend any changes if need be...Thanks!!

**Comment by samhita-alla** [comment]
@pmahindrakar-oss, is this a valid issue? If so, can you review the PR?
