### ISSUE TITLE
[Feature] Support cloud vendor specific configuration

### ISSUE THREAD

**Issue by honnix** [flyteorg/flyte#294]
**Motivation: Why do you think this is important?**

Different cloud vendors have different terminology and required configuration, such as region (aws) vs project (gcp) in [this case](https://github.com/lyft/flyteadmin/pull/90).

It is clearer both for users and Flyte contributors if those configuration items are grouped into vendor specific section.

**Goal: What should the final outcome look like, ideally?**

As an example, all AWS specific configuration is grouped as `AWSConfig`.

**Describe alternatives you've considered**

Alternatively, those configuration items can all be optional and sit side by side.

**Flyte component**
- [x] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**

An example implementation is done as https://github.com/lyft/flyteadmin/pull/90/files#diff-2cd697d44b48c0070c8e0756ed47b382R51. However that PR didn't cover everything in flyteadmin. Also if this becomes a shared thing among all components, we might want to lift it up to flytestdlib.

**Additional context**

**Is this a blocker for you to adopt Flyte**
No.

**Comment by kumare3** [comment]
Thank you for the Issue @honnix, lets see if we can prioritize it for the 0.4.0

**Comment by EngHabu** [comment]
I think it should be done per config section. This is an example for a relatively weakly typed config: https://github.com/lyft/flytestdlib/blob/master/storage/config.go#L46

I do like the one you added that's strongly typed. Generally speaking, we tried to push all "vendor"-specific code into flytestdlib to begin with. I would like us to move gizmo and others there...
