### ISSUE TITLE
[Core feature] CI/CD for Flyte binary image

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#2952]
# Flyte Binary CI/CD
## Background
The Flyte binary combines the Flyte components together into one executable. Something is already updating the relevant go-based components (like how Admin gets bumped [here](https://github.com/flyteorg/flyte/pull/2944/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R7) in the Flyte release).  But there is no CI/CD to build the image.  Let's get this added.

## Request
We'd like to:
* Make sure a docker image is built for the Flyte binary and pushed properly with every merge to master/release of the Flyte repo.
  * This is the [dockerfile](https://github.com/jeevb/flyte-deployment-sandbox/blob/main/images/flyte/Dockerfile) that's being used to create the image today.
* The Docker image relies on the latest Flyte console but it should really pick up a constant version of console, specified... somehow.
* The `flyte` binary should probably be built and released somewhere as well.  Would be nice to be able to `brew install` it.

Related to https://github.com/flyteorg/flyte/issues/2993

**Comment by falconcode16** [comment]
Hello, I cannot find the dockerfile that you have attached here. I think its an invalid link.
