### ISSUE TITLE
[UI Feature] Relaunch/recover execution with same clusterPool as original execution

### ISSUE THREAD

**Issue by iaroslav-ciupin** [flyteorg/flyte#2960]
### Motivation: Why do you think this is important?

flyteidl was recently updated to support specifying cluster pool when creating new execution. We need to make sure when we recover/relaunch execution, same cluster pool is sent in CreateExecution request.

### Goal: What should the final outcome look like, ideally?

On hitting relaunch/recover button, new CreateExecution request must take same cluster pool as original execution.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
Can you open this issue in the [flyteconsole repo](https://github.com/flyteorg/flyteconsole/issues)?

**Comment by iaroslav-ciupin** [comment]
@eapolinario https://github.com/flyteorg/flyteconsole/issues/618 done
