### ISSUE TITLE
[Docs] Add DBT plugin API reference

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#2966]
### Description

Need to update the flytekit repo with API reference to the new DBT plugin:
https://docs.flyte.org/projects/flytekit/en/latest/plugins/index.html

Update the plugin docs https://github.com/flyteorg/flytekit/tree/master/docs/source/plugins to include the dbt plugin module.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by arpitbhardwaj** [comment]
Let me know if i can pick it up.
