### ISSUE TITLE
[BUG] Dashboard components overlap with each other when user goes back to dashboard after terminating a workflow

### ISSUE THREAD

**Issue by aliabbasjaffri** [flyteorg/flyte#2990]
### Describe the bug

I was running flytesnacks, and wanted to terminate a workflow. After i clicked terminate, and then went back to the dashboard using the `<-` button, the UI of some components appears to be overlapping with each other.

### Expected behavior

The UI should remain consistent. After user refreshes the page, the UI gets consistent again.

### Screenshots

![Screenshot 2022-10-14 at 10 31 23](https://user-images.githubusercontent.com/4748985/196112605-fb7b8299-c3df-4241-b1cc-4f521a2aa161.png)
UI with overlapping components

![Screenshot 2022-10-14 at 10 31 36](https://user-images.githubusercontent.com/4748985/196112848-ebc62b05-269a-42bf-9424-71967bad9b47.png)
UI after i refreshed the page.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
this has been resolved
