### ISSUE TITLE
[Housekeeping] Flyte Deployment journey and documentation

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#2993]
# Revamp Flyte Deployment
This ticket encompasses all the work for revamping the Flyte deployment journey.  Specifically this covers

* Updates to the flyte sandbox-lite image
* Changes to flytectl
* Documentation updates
* Helm chart updates

More information to follow.

## Flyte Local Demo Experience
* Persist state to user's local workstation
* Run a registry so we can deprecate the --source flag
* Preload images

### New local demo sandbox
After this [PR](https://github.com/flyteorg/flyte/pull/3066/files) is merged, we will have the following structure.

#### Helm
* A Helm chart just for the Flyte single binary.
* A Helm chart for the sandbox that uses the Flyte single binary Helm chart and pulls in the open source Helm charts for dependencies (like minio/postgres)

#### Images
* New [bundled image](https://github.com/flyteorg/flyte/tree/master/docker/sandbox-bundled) will be created.  This is the core of the new experience.  It will contain
  * predownloaded images for all the dependencies including the flyte binary itself.
  * a registry so that the `--source` flag in flytectl is no longer necessary.

## Flytectl
* Allow users to start with an external flyte config
* Allow users to modify a config and reload
* Print current state of cluster

## Docs
Implement the new user journey, moving the more difficult error prone things like auth and ingress to later stages.

## Helm
Refactor and introduce new Helm charts that use the single binary.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
fixed by #3116
