### ISSUE TITLE
[Core feature] GCS-enabled sandbox deployment

### ISSUE THREAD

**Issue by eapolinario** [flyteorg/flyte#3000]
### Motivation: Why do you think this is important?

The current sandbox deployment relies on minio as the blob storage, this forces users to install `awscli` in their images so that flytekit can interact with the blob storage. 

This arrangement excludes users who:
1. have Flyte deployments on GCP 
2. want to use sandbox for local deployment and want to share the dockerfiles between development and production (in other words, they don't want to have both `awscli` and `gsutil` present in their images)

### Goal: What should the final outcome look like, ideally?

We would have a gcs-enabled sandbox deployment. 

This would involve require some investigation to find an equivalent blob storage that is gcs-compliant and could be installed in the sandbox cluster. An alternative could be to somehow still use minio as the blob store but use `gsutil` to talk to it.

### Describe alternatives you've considered 

None

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
Supporting a gcs-enabled sandbox deployment would be a heavy lift for the core team at this time. This use case would be fulfilled by using a GCS as a blob store and a GCP-hosted Flyte cluster. We'll close this issue for now, and potentially revisit it if the stated alternative is inadequate.
