### ISSUE TITLE
[Core feature] Add type transformer for datetime.date

### ISSUE THREAD

**Issue by dennisobrien** [flyteorg/flyte#3026]
### Motivation: Why do you think this is important?

Flyte currently does not support the `datetime.date` object for passing to or from tasks.

```
ValueError: Type <class 'datetime.date'> not supported currently in Flytekit. Please register a new transformer
```

In `flytekit/core/type_engine.py` there are transformers for `datetime.datetime` and `datetime.timedelta`, but not for `datetime.date`.

### Goal: What should the final outcome look like, ideally?

Flyte tasks should be able to accept and return `datetime.date` objects.

### Describe alternatives you've considered 

The workaround is to use a `datetime.datetime` or to use a string of the form "YYYY-MM-DD".

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
@eapolinario

**Comment by eapolinario** [comment]
This is a good first issue as it'll touch a few of the components, at least `flyteidl` (to add the new field) and `flytekit`.

**Comment by troychiu** [comment]
Hi @eapolinario,
 I am interested in this issue. If you think it still needs to be fixed, feel free to assign it to me.

**Comment by pingsutw** [comment]
@dennisobrien FYI. The PR has been merged.
