### ISSUE TITLE
[Docs] Add steps for configuring self auth server

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#3029]
### Description

Current docs for authentication https://docs.flyte.org/en/latest/deployment/cluster_config/auth_setup.html for flyte don't mention how to setup self Auth server and related config changes.

Add a section where we details steps for these for setting up auth for 
* user auth using flyteconsole
* app auth for flytescheduler, flytepropeller

https://flyte-org.slack.com/archives/CP2HDHKE1/p1666278679120739

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
Here's a link to the security advisory: https://github.com/flyteorg/flyteadmin/security/advisories/GHSA-67x4-qr35-qvrm

And a slack thread where we shared a python one-liner to produce a secret: https://flyte-org.slack.com/archives/CP2HDHKE1/p1666196304611219?thread_ts=1666169843.332409&cid=CP2HDHKE1
