### ISSUE TITLE
[Docs] Add Flyte's architecture diagram

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/flyte#3035]
### Description

Currently, docs have a [`Component Architecture`](https://docs.flyte.org/en/latest/concepts/architecture.html) section is mainly text with the only diagram being the one for `FlytePropeller`

A high-level diagram describing Flyte's architecture and the role of each component would be a good starting point to understand the inner mechanisms of the project.

This issue is related to #1586 but with a broader scope and an atomic goal.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
Present in https://docs.flyte.org/en/latest/concepts/architecture.html#divedeep-architecture-overview
