### ISSUE TITLE
[Housekeeping]  Inconsistent naming on the storage buckets

### ISSUE THREAD

**Issue by andrusha** [flyteorg/flyte#3039]
### Describe the issue

A good security practice is to give each workflow only access rights required to perform its function. The naming scheme for the bucket is currently inconsistent, which makes it complicated to create a policy per workflow.

Eg on S3 we're currently getting files like this:
```
0p/project-x/development/QMAM74EECKTJ4JDNWMCVXHEAH4======/fast91686145481555fce72a2a47137a26f2.tar.gz
0z/project-x/development/ZDWLO6645EE73ENUB4I2U4C764======/fastdb6e0c43aec1ae7b60cdd14797da2f54.tar.gz
1l/project-x/development/TVHEJEB5H3KG2FRKQ43IYHCKJI======/fast0400dadb6f2dac21d77422b62926eb19.tar.gz
...
metadata/admin/project-x/development/.flytegen.workflow.say_hello/v1
...
metadata/project-x/development/a2lg56hwv25rbxbg5v4x/inputs
metadata/project-x/development/a2lg56hwv25rbxbg5v4x/user_inputs
...
metadata/propeller/project-x-development-a2lg56hwv25rbxbg5v4x/start-node/data/0/outputs.pb
metadata/propeller/project-x-development-a2qqvz6lbcdd6pmngzwd/n0/data/inputs.pb
...
```

Having consistent names would allow to give access to `<bucket>/<project>/<env>/*` instead of `bucket/*/<project>/<env>/*, bucket/*/<project>-<env>/*`. It's also unclear which directories should have write access from the runtime role and which ones can be read-only.

The project might benefit from making those naming schemes consistent and explicit in documentation.

### What if we do not do this?

Bugs in workflows with high-permission roles might lead to the data corruption affecting other workflows in odd ways, which is hard to debug.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
This is related to https://github.com/flyteorg/flyte/issues/2545 and https://github.com/flyteorg/flyteadmin/pull/489.

This will address this problem right?

**Comment by andrusha** [comment]
@wild-endeavor it only changes where the prefix is set, it doesn't address the order of other parameters. I think the domain/project should go first, and then shard, since otherwise it's hard to create meaningful policy

**Comment by wild-endeavor** [comment]
Please see comments on the PR linked above.

**Comment by wild-endeavor** [comment]
We agree with you - just removing the entire shard is better for now.

I know when we talked on slack i said something about the raw output prefix setting that's associated (or can be associated) with each project/project-domain combination.  Please ignore that - that is not a good idea.  If we were to do that, the guarantee you'd have to make is - whenever you upload via data proxy on projA/domainD, all calls to download it will have access to the that project/domain's raw output location.  When uploading code, this would imply that all tasks will have access to that raw output location prefix, which is a guarantee we don't think we should add.  This also conflates data proxy with user data, which is not good.  Sorry for the misdirection.

**Comment by wild-endeavor** [comment]
Gonna close this... will be in the next release.
