### ISSUE TITLE
[Docs] Added my Blog Post

### ISSUE THREAD

**Issue by hridaya423** [flyteorg/flyte#3040]
### Description

I created a Blog Post: https://dev.to/learnearnfun/quickstart-to-flyte-39ml

Please review and add!

Please add the hacktoberfest labels too!

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hridaya423** [comment]
@samhita-alla Could you please review my blog?

**Comment by samhita-alla** [comment]
Um sorry, I'll have to not consider this as a hacktoberfest contribution as it's a repetition of the getting started guide.

**Comment by hridaya423** [comment]
It also explains about flyte

**Comment by hridaya423** [comment]
Ok, If i make a video version, does that work?

**Comment by samhita-alla** [comment]
I guess no because we aren't accepting videos as part of hacktoberfest. Sorry again!

**Comment by hridaya423** [comment]
ok
