### ISSUE TITLE
[Core feature] Podman support for `flytectl sandbox/demo`

### ISSUE THREAD

**Issue by ryaminal** [flyteorg/flyte#3041]
### Motivation: Why do you think this is important?

Currently I'm unable to start a sandbox or demo instance, easily, because I don't use Docker.

### Goal: What should the final outcome look like, ideally?

Preferably `flytectl sandbox --engine podman` would work properly and setup an environment. Or, for those of us that use a wrapper that turns `docker` commands in to `podman`, then perhaps the `--engine` flag isn't required.

Looking through the code, it looks like the go code around Docker is pretty locked in to using Docker. This makes me wonder if a different "engine" is ideal.

### Describe alternatives you've considered 

Considered installing Docker, but it's bloated and I don't think it should be necessary for flyte.

I've tried searching around. Found a super old conversation on discuss.flyte.org but there didn't appear to be a resolution.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
@ryaminal this is absolutely right. Infact the underlying command can simply be exposed as all of Flyte is packaged as a simple docker image and flytectl simply just starts it 

What if we have a command like
'Flytectl demo print-command'?

**Comment by ryaminal** [comment]
@kumare3 I think a `print-command` subcommand for demo/sandbox would be great.
I looked around flytectl a bit, I imagine the change would be somewhere around https://github.com/flyteorg/flytectl/blob/939df7392e44b57505cc2e6e7dbe441d3a7b3c74/pkg/docker/docker_util.go#L173 ?

**Comment by pmahindrakar-oss** [comment]
@ryaminal let us know if the solution works for you and if yes we can close this ticket

**Comment by ryaminal** [comment]
Works for me. Unfortunate that we have to run it with `--privileged`, but that is a conversation for another time, perhaps.

**Comment by pmahindrakar-oss** [comment]
The following script requires the privileged access cgroup-v2-hack.sh . 
Adding  @eapolinario @wild-endeavor for more info regarding this script due to which we need the privileged access
