### ISSUE TITLE
[BUG] Flyte protobuf registration should explicitly have a type information

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#3042]
### Describe the bug

Flyte protobuf serialization produces the following type of objects and written to files
* [admin.LaunchPlan](https://github.com/flyteorg/flyteidl/blob/master/protos/flyteidl/admin/launch_plan.proto#L45)
* [admin.WorkflowSpec](https://github.com/flyteorg/flyteidl/blob/master/protos/flyteidl/admin/workflow.proto#L50)
* [admin.TaskSpec](https://github.com/flyteorg/flyteidl/blob/master/protos/flyteidl/admin/task.proto#L51)

Currently flytectl, flytekit and other SDK's  use customized mechanism to determine how to Unrmarshal the object written in these files and which type the object has to be unmarshalled into and sent to admin for registration

eg : in case of flytectl following code determines how the unrmarshalling happens https://github.com/flyteorg/flytectl/blob/master/cmd/register/register_util.go#L95-L125

This is not deterministic and it's possible that proto unmarshaller is able to unmarshal a file into multiple types which would be an incorrect behavior.

Proposed solutions from Haytham.

* Change the naming of these files to include a prefix informing flytectl/pyflyte register about how to parse these (e.g. 1_tsk_blast… 2_wf_blast… etc.).. This change will need to happen in all SDKs (python, java, scala)… the register behavior will need to be backward compatible…
* Create an envelope message for the data serialized in these files… something like below. And update the registration logic to always only unmarshal into that envelope type.
message RegistrationEntity {
  oneof item {
    TaskTemplate task = 1;
    WorkflowTemplate workflow = 2;
...
  }
}
There is no way around backward compatibility ugliness here, we will have to fallback to existing logic. Both options require changes in flytekit. I do think the second option a tad better since it doesn’t rely on string comparisons and doesn’t assume the existence of “files” to begin with (this logic works just fine with REST APIs and programmatic APIs)…
If we don’t have one already, we should file an issue on this and list these (and other?) options considered and maybe move the discussion there..

### Expected behavior

Provide a deterministic solution to register the serialized proto files with admin

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pmahindrakar-oss** [comment]
cc : @wild-endeavor @EngHabu @eapolinario

**Comment by honnix** [comment]
Thank you for this issue!

Can we get this prioritized? We hit this very issue when `flytectl` mistakenly parsed a default launch plan proto into task and tried to register an ill formatted task. As a workaround, we tried renaming the workflow to create a binary that failed to be parsed as task, and that worked for us. But this is not ideal.

**Comment by kumare3** [comment]
Interesting- cc @pmahindrakar-oss what are the options - cc @wild-endeavor

**Comment by honnix** [comment]
Maybe there could be a third option: flytekit generates a manifest file recording the type of each proto file, and flytectl can read the manifest and make the correct decision, with fallback to guessing as it is today.

**Comment by honnix** [comment]
It turns out we types are already encoded in file names: https://github.com/flyteorg/flytekit/blob/b0cf91818c16867c6ba6d3a052c259771617ca1d/flytekit/tools/serialize_helpers.py#L85-L93. So I guess flytectl can first try to look at the file name and do things properly, and if it cannot find expected file name, it makes a guess.

**Comment by honnix** [comment]
I guess they are intentionally named to match this?
```protobuf
enum ResourceType {
  UNSPECIFIED        = 0;
  TASK               = 1;
  WORKFLOW           = 2;
  LAUNCH_PLAN        = 3;
  // A dataset represents an entity modeled in Flyte DataCatalog. A Dataset is also a versioned entity and can be a compilation of multiple individual objects.
  // Eventually all Catalog objects should be modeled similar to Flyte Objects. The Dataset entities makes it possible for the UI  and CLI to act on the objects 
  // in a similar manner to other Flyte objects
  DATASET            = 4;
}
```

**Comment by honnix** [comment]
Note that in flytekit-java we don't register things in this way, but directly sending protos to admin, so there is nothing to worry about there.

**Comment by honnix** [comment]
I can take a stab to propose something in flytectl.
