### ISSUE TITLE
[UI Feature] Distinguish between task and workflow executions in the UI

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#3048]
### Motivation: Why do you think this is important?

In the list executions view it would be useful to differentiate whether an execution belongs to a single task or workflow.

### Goal: What should the final outcome look like, ideally?

Clear to pinpoint the original type of entity used to launch an execution.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@katrogan , can you say a bit more about this? Are you talking about an icon in the list of executions?

**Comment by katrogan** [comment]
yes or some kind of tag in the row

**Comment by wild-endeavor** [comment]
@katrogan is this still relevant?  i don't think @jsonporter looks at these issues, they use the flyteconsole repo

**Comment by katrogan** [comment]
I think it's still relevant, yes. I can move the issue over.
