### ISSUE TITLE
[Core feature] support pod plugin for ContainerTasks

### ISSUE THREAD

**Issue by flixr** [flyteorg/flyte#3055]
### Motivation: Why do you think this is important?

ContainerTasks currently don't support the [pod plugin](https://docs.flyte.org/projects/cookbook/en/latest/auto/integrations/kubernetes/pod/pod.html) so we can't use it to control the pod and e.g. mount additional volumes or inject env vars and secrets.

### Goal: What should the final outcome look like, ideally?

ContainerTask supports specifying pod spec.

### Describe alternatives you've considered 

Not using flyte...

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
To add a little more context here - this issue is very similar to the existing request to add [Pod configuration to python tasks](https://github.com/flyteorg/flyte/issues/2255). However, this should apply specifically to the `ContainerTask`, so something like:
```
calculate_ellipse_area_shell = ContainerTask(
    name="ellipse-area-metadata-shell",
    ...
    pod=PodConfig(),
)
```

**Comment by flixr** [comment]
Actually I think this should be labeled as a bug not a feature...
Here is a simple repro:

Run this workflow and check the logs which should print the `POD_SPEC_VAR` env var:
```
from flytekit import workflow, ContainerTask
from flytekitplugins.pod import Pod
from kubernetes.client.models import V1Container, V1PodSpec, V1EnvVar

def gen_pod():
    pod_spec_var = V1EnvVar(name="POD_SPEC_VAR", value="yay")
    primary_container = V1Container(name="primary", env=[pod_spec_var])
    pod_spec = V1PodSpec(containers=[primary_container])
    return Pod(pod_spec=pod_spec, primary_container_name="primary")

print_env = ContainerTask(
    name="container_env_test",
    image="ubuntu:22.04",
    task_config=gen_pod(),
    command=["env"]
)

@workflow
def wf():
    print_env()
```

**Comment by hamersaw** [comment]
Closing as completed in [this PR](https://github.com/flyteorg/flyteidl/pull/358).
