### ISSUE TITLE
[BUG] Environment variables in PodTask primary container are erased

### ISSUE THREAD

**Issue by hamersaw** [flyteorg/flyte#3059]
### Describe the bug

When using the pod plugin, if you set environment variable on the primary container they are dropped when compiling the PodSpec. This means that they will not exist on the actual created Pod. However, variables set on any container that is not the primary are correctly maintained.

Presumably [this line](https://github.com/flyteorg/flytekit/blob/3b5d15acb5389d99b86ba342a77e1cab5ce8546d/plugins/flytekit-k8s-pod/flytekitplugins/pod/task.py#L111) is the culprit, but more investigation should be done to ensure correctness. Additionally, we should make sure that maintaining these variables is the right thing to do.

### Expected behavior

Users should be able to manually define environment variables on the primary container in the Pod plugin.

### Additional context to reproduce

Execute the following workflow and you can see the environment variable `POD_SPEC_VAR` is set on the secondary container but not the primary in k8s.

```
import os

from flytekit import workflow, task
from flytekitplugins.pod import Pod
from kubernetes.client.models import V1Container, V1PodSpec, V1EnvVar

_SHARED_DATA_PATH = "/data/message.txt"

def gen_pod():
    pod_spec_var = V1EnvVar(name="POD_SPEC_VAR", value="yay")
    primary_container = V1Container(name="primary", env=[pod_spec_var])

    secondary_container = V1Container(
        name="secondary",
        image="alpine",
        env=[pod_spec_var],
    )
    secondary_container.command = ["/bin/sh"]
    secondary_container.args = [
        "-c",
        "echo hi pod world > {}".format(_SHARED_DATA_PATH),
    ]

    pod_spec = V1PodSpec(containers=[primary_container, secondary_container])
    return Pod(pod_spec=pod_spec, primary_container_name="primary")

@task(task_config=gen_pod())
def secret_env_task() -> str:
    return os.environ.get("POD_SPEC_VAR", "nay")

@workflow
def wf() -> str:
    return secret_env_task()
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by flixr** [comment]
Fix works and is released, this can be closed...
