### ISSUE TITLE
[BUG] Dictionary key is unintentionally modified by Flyte when using custom python objects to configure tasks

### ISSUE THREAD

**Issue by fg91** [flyteorg/flyte#3068]
### Describe the bug

When [configuring Flyte tasks with Python dataclasses](https://docs.flyte.org/projects/cookbook/en/stable/auto/core/type_system/custom_objects.html) and when using dictionaries within those dataclasses, flyte, under certain circumstances, replaces the name of the key with the name of the dictionary.

### Expected behavior

Flyte should not modify the arguments.

### Additional context to reproduce

Let's create a custom python dataclass to configure our task/workflow:

```python
@dataclass_json
@dataclass
class Hyperparams(object):
    param_dict: Dict[str, str]  # Used e.g. to pass additional kwargs
    # ... more hyper parameters
```

```python
@task
def train(
    hparams: Hyperparams,
) -> str:
    print(hparams)


@workflow
def workflow(
    hparams: Hyperparams = Hyperparams(
        param_dict={"foo": "bar"}
    ),

) -> None:
    train(
        hparams=hparams,
    )
```

### Screenshots

In the Flyteconsole, the name of the dict is displayed instead of the key:

<img width="589" alt="Screenshot 2022-11-14 at 16 48 34" src="https://user-images.githubusercontent.com/36511035/201706730-3699ecad-a29e-49e0-9509-033ffa4e9c1d.png">

The workflow is started with the correct arguments  ...

<img width="272" alt="Screenshot 2022-11-14 at 16 49 03" src="https://user-images.githubusercontent.com/36511035/201706837-78dcd786-8bda-4d69-97eb-e4812f2319ec.png">

... unless, in Flyteconsole, one puts the cursor into the `param_dict (string)` field:

<img width="572" alt="Screenshot 2022-11-14 at 16 49 18" src="https://user-images.githubusercontent.com/36511035/201707036-75dfe308-4540-4185-9870-1765f3791fc5.png">

<img width="301" alt="Screenshot 2022-11-14 at 16 49 39" src="https://user-images.githubusercontent.com/36511035/201707076-bf56da72-98f2-4886-9f4a-f3379eb0fa19.png">

I used `image: cr.flyte.org/flyteorg/flyteconsole-release:v1.2.0`.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
@jsonporter could you take a look at this please?  it looks to be localized to the UI.

**Comment by jsonporter** [comment]
Closed with https://github.com/flyteorg/flyteconsole/pull/692
