### ISSUE TITLE
[Housekeeping] flyte.org, image incubation project => gratuated project

### ISSUE THREAD

**Issue by andife** [flyteorg/flyte#3090]
### Describe the issue

Flyte seems to be a "gratuated project" at lfaidata. The landing page flyte.org still has an image with incubation project.

### What if we do not do this?

webpage might be a bit longer outdated 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
@andife, not sure what you're referring to. Could you be more specific?

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/27777173/202969587-f07e365d-e698-4480-8d12-37094063bf6d.png">

**Comment by andife** [comment]
![grafik](https://user-images.githubusercontent.com/20612932/202974032-1632930f-68e6-4648-a303-ac8d7b5d822b.png)

**Comment by andife** [comment]
![image](https://user-images.githubusercontent.com/20612932/204327000-f7753746-2e86-45fd-94dd-2c8435cb6df7.png)

**Comment by cosmicBboy** [comment]
@kumare3 @EngHabu hey can one of you update the header on the flyteorg github page? It should be "Graduated Project" instead of "Incubating project"

https://github.com/flyteorg

**Comment by wild-endeavor** [comment]
tagging @samhita-alla since you're working on the new page right?

**Comment by samhita-alla** [comment]
Yeah. Closing this issue as there will be a total revamp. @wild-endeavor, if you have access to change the repo description, could you do that?

> ![image](https://user-images.githubusercontent.com/20612932/204327000-f7753746-2e86-45fd-94dd-2c8435cb6df7.png)
