### ISSUE TITLE
[Core feature] Support overriding node name

### ISSUE THREAD

**Issue by honnix** [flyteorg/flyte#3092]
### Motivation: Why do you think this is important?

When composing a workflow out of tasks, it is not always good enough to use the task name as is (Python function name) for node name, and sometimes it is better give a more meaningful node name. This is currently not supported by flytekit.

### Goal: What should the final outcome look like, ideally?

Users can override node name using `with_overrides(name="A better Task Name")` in flytekit.

### Describe alternatives you've considered 

There is no alternative can achieve this.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by honnix** [comment]
Note that this issue is not fully addressed because of https://github.com/flyteorg/flyte/issues/3092

**Comment by jsonporter** [comment]
Closing as dupe of #3470
