### ISSUE TITLE
[BUG] flyteadmin returns inaccurate gRPC error code

### ISSUE THREAD

**Issue by honnix** [flyteorg/flyte#3115]
### Describe the bug

When submitting an invalid workflow, e.g. referencing to a remote task with wrong variable name, flyteadmin returns `INTERNAL` error code (see https://github.com/flyteorg/flyteadmin/blob/1817f38b977e9e821f732fb439cdd2f0acaead21/pkg/manager/impl/workflow_manager.go#L149). This complicates client side retry because in many cases an `INTERNAL` error is considered to be retryable. However in this case, retry doesn't make sense because it is client fault.

### Expected behavior

`INVALID_ARGUMENT` is returned instead of `INTERNAL`.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
@honnix is it just this one line change?  would you mind putting it in?

**Comment by honnix** [comment]
> @honnix is it just this one line change? would you mind putting it in?

@wild-endeavor It can be a simple change if we are fine breaking backward compatibility. There are likely another couple of exception sites having similar issue.

**Comment by luckyarthur** [comment]
#take

**Comment by luckyarthur** [comment]
https://github.com/flyteorg/flyte/blob/be67457271a841db9095a7ce0a81c892c138375d/flyteadmin/pkg/manager/impl/workflow_manager.go#L149

checked on the master branch, the issue has already been fixed, this link shows the current source code

**Comment by troychiu** [comment]
@luckyarthur thank you for taking a look at it!
