### ISSUE TITLE
[Core feature] Map tasks with default arguments

### ISSUE THREAD

**Issue by klekass** [flyteorg/flyte#3120]
### Motivation: Why do you think this is important?

Currently map_tasks does not provide an option to pass default arguments to the mapped function. The [documentation](https://docs.flyte.org/projects/cookbook/en/stable/auto/core/control_flow/map_task.html) suggests to create an additional input preparation task, to prepare parallelized input and default inputs in a single paralellizable list, which adds unnecessary complexity to the workflow execution graph.

The idea is, to add an option to pass default arguments to the map_task wrapper, similar to the functools.partial() method.

### Goal: What should the final outcome look like, ideally?

The first task in the following example workflow uses the currently implemented map_task function, to parallelize the 'parallel_task' over a list of inputs.

The second task in the workflow is an example of how the map_task could be used with default arguments. The idea is, to parallelize the `parallel_task_with_default` over a list of inputs, where each element is passed to `inp1`. `inp2` should be a default input, equal for all parallel calls of the task.

```
@task
def parallel_task(inp: int) -> int:
    return inp ** 2


@task
def parallel_task_with_default(inp1: int, inp2: int) -> int:
    return inp1 ** 2 + inp2


@workflow
def square_workflow(inp1: List[int], inp2: int) -> None:
    # Supported
    out1 = map_task(parallel_task)(inp=inp1)

    # Not supported!
    out2 = map_task(parallel_task_with_default, inp2=inp2)(inp1=inp1)
```

### Describe alternatives you've considered 

A potential workaround is explained in the [documentation](https://docs.flyte.org/projects/cookbook/en/stable/auto/core/control_flow/map_task.html#map-a-task-with-multiple-inputs).

### Are you sure this issue hasn't been raised already?

- [x] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by LukasBommes** [comment]
This would be a very useful feature for which we also have a need.

**Comment by JakubWaikat** [comment]
IMO this would improve the workflow a lot! Would be very graceful for this feature to be implemented.

**Comment by hamersaw** [comment]
This functionality is not available by using [partials in tandem with maptasks](https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/control_flow/map_task.html#map-a-task-with-multiple-inputs).

**Comment by Vervious** [comment]
Is there anywhere else that this is documented? The link is down.

**Comment by kumare3** [comment]
Cc @nelsonjr

**Comment by kumare3** [comment]
Also @Vervious we are working on something new. Would you be open to having a chat where we can share and get feedback (join slack)
