### ISSUE TITLE
[BUG] Flytekit doesn't preview "successful Login" message after authentication is completed

### ISSUE THREAD

**Issue by mounesi** [flyteorg/flyte#3122]
### Describe the bug

running `pyflyte run --remote` initiate a login URI for authentication process. After logging in successfully the page is just blank without any message on it.

### Expected behavior

The expected behavior is to see the message "Logged in successfully" or similar message.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
not planned.
