### ISSUE TITLE
[Core feature] Add PodTemplate configuration to flytekit task definitions

### ISSUE THREAD

**Issue by hamersaw** [flyteorg/flyte#3123]
### Motivation: Why do you think this is important?

Many users require more complex k8s configuration within the Flyte ecosystem. This may include specifying task-specific tolerations, volume mounts, etc. Currently this is unsupported within flytekit, where the API favors ergonomics in abstracting away the complexities of k8s configuration from end-users. However, some use-cases require this complex configuration and striking a balance is very difficult.

### Goal: What should the final outcome look like, ideally?

Users should be able to configure every aspect of the k8s Pod that Flyte creates without bloating the task definition.

One solution is to add a PodTemplate configuration to every flytekit task definition. This would work similarly to the [default PodTemplate](https://docs.flyte.org/en/latest/deployment/cluster_config/general.html#using-default-k8s-podtemplates) scheme where this PodTemplate definition serves as the base in creating the k8s Pod. By default this will be empty and therefore not applied, but if it is specified it will serve as the base for Pod configuration. This API could look something like:
```
@task(
    request=Resources(),
    pod_template=V1PodTemplate{
        spec=V1PodSpec{
            tolerations=[
                V1Toleration{
                    key= "num-gpus"
                    operator= "Equal"
                    value= 1
                    effect= "NoSchedule"
                },
            ]
        }
    }
)
```

### Describe alternatives you've considered 

Currently, proposals often include one-off configuration updates that solve a specific use-case but are not applicable in generalized terms. This approach was used in the k8s plugin and has proved unmaintainable in that every option requires code changes which may change between k8s versions.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by fg91** [comment]
I really like this proposal since it would solve a problem I currently face:

Our ML engineers would like to have the ability to switch between T4, A100, and V100 GPUs. The resource name is the same for every GPU type on GKE. Instead, GKE adds a label to the nodes. One could use a Pod task configured with a node selector. However, this only works as a replacement for Python tasks whereas we need this to work for Pytorch tasks.

I had the idea to expose not the pod template but the name of the pod template in the task decorator:

```python
@task(
    request=Resources(),
    pod_template_name="v100_pod_template",
)
```

I feel this would align well with Flyte's current approach where 

> the API favors ergonomics in abstracting away the complexities of k8s configuration from end-users.

Non ops-savvy ML engineers might not like the UX of having to specify a complete pod template. As the MLOps engineer (or a K8s savvy ML engineer) who runs the platform for them, however, I don't mind maintaining a set of pod templates for them that are managed with the rest of the infrastructure as IaC.

This would also bloat the task definition less.

**Comment by flixr** [comment]
I need the same (especially `runtimeClassName` and `affinity`), but mostly for ContainerTask (see #3055).
Volumes and mounts from secrets I worked around using the pod spec template.
Also already discussed this with @eapolinario

**Comment by fg91** [comment]
About exposing pod template or pod template *name* in the task decorator: of course only one would be enough. Exposing only the name bloats the decorator less in my opinion but in case the other solution is preferred by others, I'm just as happy about this one!

**Comment by flixr** [comment]
I vote for exposing the pod spec directly, otherwise it always needs an admin to create an appropriate pod template in the cluster first and the users cannot easily inspect those.
We e.g. want to use affinity to select nodes with GPUs larger than certain amount of GPU memory (nodes are tagged using the nvidia device plugin with GPU feature discovery, so we can easily match on those per task).

**Comment by hamersaw** [comment]
We had a chance to discuss this at some length today and decided to move forward **supporting both approaches**. So the configuration value can be either a `PodTemplate` or a `PodTemplate` name. A few things to highlight on this:
1. The `PodTemplate` will be applied rather than the [default PodTemplate](https://docs.flyte.org/en/latest/deployment/cluster_config/general.html#using-default-k8s-podtemplates) but in the same way, namely serving as the base for `Pod` configuration. In some scenarios this will require some duplication of configuration, but we feel it provides the best balance of flexibility and understandability.
2. This can replace the current [Pod Task](https://docs.flyte.org/projects/cookbook/en/latest/auto/integrations/kubernetes/pod/pod.html#sphx-glr-auto-integrations-kubernetes-pod-pod-py) implementation. We will begin by making an update in flytekit to convert the existing `Pod` definition into a `PodTemplate` to unify the APIs. This change will be transparent to users, so the Pod Task will continue working identically but we can unify the APIs in the backend. Moving forward, since all `Pod` configuration will also be available in the Python Task / Container Task these should be preferred for future implementation.

**Comment by fg91** [comment]
> 1. The `PodTemplate` will be applied rather than the [default PodTemplate](https://docs.flyte.org/en/latest/deployment/cluster_config/general.html#using-default-k8s-podtemplates) but in the same way, namely serving as the base for `Pod` configuration. In some scenarios this will require some duplication of configuration

This is perfect, thanks 🙏 

Since in [this](https://github.com/flyteorg/flyteplugins/pull/297) PR we apply the Pod template to kf operator task pods, will the pod template exposed in the task decorator also work for those task types since it will be a replacement for the default pod template? (Our ML engineers cannot choose the GPU type for Pytorch tasks currently since they cannot configure a node selector. For Python tasks we work around this with Pod tasks.)

**Comment by hamersaw** [comment]
> Since in [this](https://github.com/flyteorg/flyteplugins/pull/297) PR we apply the Pod template to kf operator task pods, will the pod template exposed in the task decorator also work for those task types since it will be a replacement for the default pod template? (Our ML engineers cannot choose the GPU type for Pytorch tasks currently since they cannot configure a node selector. For Python tasks we work around this with Pod tasks.)

Absolutely, I have not had a chance yet to figure out how this will work in the backend, but presumably we can overload the[ LoadOrDefault](https://github.com/flyteorg/flyteplugins/blob/d5295d284c028be2b6d3c7ba9d6888e616d31551/go/tasks/pluginmachinery/flytek8s/pod_template_store.go#L26) with some task metadata (containing the PodTemplate from flytekit) which will then return the correct. So hopefully this doesn't even require changes anywhere else.

**Comment by flixr** [comment]
@hamersaw any updates here?

**Comment by hamersaw** [comment]
@flixr thanks for checking in on this! Sorry for slow response, as you might imagine many of us took some time to unwind over the holidays. We just discussed our Q1 plan and this is a very high priority item. I'm expecting to address this in the next few weeks.

**Comment by flixr** [comment]
:+1:  let me know if I can help out with testing or so...

**Comment by xshen8888** [comment]
Is this issue related to https://github.com/flyteorg/flyte/issues/3241 ?

**Comment by davidmirror-ops** [comment]
By exposing the complete PodSpec, user would have control over (for example) the container name for a particular task?

By reading [the docs](https://docs.flyte.org/en/latest/deployment/cluster_config/general.html#using-default-k8s-podtemplates) I understand that the container name in the PodTemplate will be overridden by Flyte.

This is in regards to @stephen37's question [here](https://flyte-org.slack.com/archives/CP2HDHKE1/p1673261121648239)

**Comment by kumare3** [comment]
@xshen8888 this is indeed related and will address your problem. Though passing in the CLI is still hard. I have an eventual goal of making the entire configuration externally configurable at pyflyte run time - maybe some brave soul can help :D

**Comment by ByronHsu** [comment]
I will work on the flytekit part. Thank @wild-endeavor for offering this chance.

**Comment by cosmicBboy** [comment]
@eapolinario to write "proto-docs" for this feature in flytesnacks somewhere

**Comment by cosmicBboy** [comment]
@cosmicBboy to make issues for Spark, Ray, Dask issues

**Comment by lynxoid** [comment]
Do `ShellTasks` now support `pod_template`?

**Comment by hamersaw** [comment]
> Do `ShellTasks` now support `pod_template`?

I do not believe so, but adding support should be a trivial add to flytekit since shell tasks are [basically a lighweight wrapper](https://github.com/flyteorg/flytekit/blob/master/flytekit/extras/tasks/shell.py). cc @wild-endeavor @eapolinario can you confirm this? If so, it would be a great contribution!

**Comment by ByronHsu** [comment]
@hamersaw ShellTasks inherits from PythonInstanceTask, and then PythonAutoContainerTask. `pod_template` is on PythonAutoContainerTask's constructor, so users should be able to pass `pod_template` to ShellTask to use. Correct me if I am wrong

**Comment by eapolinario** [comment]
This feature has been integrated into the SDK and backend. To simplify support going forward, let's get bugs and feature requests as separate github issues.

**Comment by hamersaw** [comment]
This issue is not yet fully complete. Waiting on final [integration into the dask plugin](https://github.com/flyteorg/flyteplugins/pull/374)
