### ISSUE TITLE
[Docs] A one-pager on logger configuration

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#3126]
### Description

We need a dedicated one-pager showcasing how to configure a flytekit logger.

https://discuss.flyte.org/t/1019/of-course-thank-you-for-digging-into-this-and-using-force-is

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
@wild-endeavor, if that's the case, shall I close this issue?

**Comment by cosmicBboy** [comment]
Going to close this issue, in favor of overhauling the logging story more systematically
