### ISSUE TITLE
[Docs] How to verify that the GRPC service of flyteadmin works as expected

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#3163]
### Description

Add a section to the troubleshooting guide: https://discuss.flyte.org/t/8152768/Hi-Community-is-there-any-simple-approach-to-verify-the-GRPC.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by popojk** [comment]
#take
