### ISSUE TITLE
[Housekeeping] Remove deprecated numpy aliases

### ISSUE THREAD

**Issue by eapolinario** [flyteorg/flyte#3166]
### Describe the issue

A few aliases defined in `numpy` were deprecated in v1.20.0 and finally removed in `v1.24.0` (check Deprecations in https://github.com/numpy/numpy/releases/tag/v1.20.0).

We should remove the mentions to those deprecated aliases from the [FlyteSchemaTransformer](https://github.com/flyteorg/flytekit/blob/master/flytekit/types/schema/types.py#L316-L333).

### What if we do not do this?

Users who install `numpy>=1.24.0` will see this error in flytekit:

```
/tmp/tmp.pgqfAvNZOC/venv/lib/python3.10/site-packages/flytekit/types/schema/types.py:324: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  _np.bool: SchemaType.SchemaColumn.SchemaColumnType.BOOLEAN,  # type: ignore
Traceback (most recent call last):
  File "/tmp/tmp.pgqfAvNZOC/venv/bin/pyflyte", line 5, in <module>
    from flytekit.clis.sdk_in_container.pyflyte import main
  File "/tmp/tmp.pgqfAvNZOC/venv/lib/python3.10/site-packages/flytekit/__init__.py", line 195, in <module>
    from flytekit.types import directory, file, numpy, schema
  File "/tmp/tmp.pgqfAvNZOC/venv/lib/python3.10/site-packages/flytekit/types/schema/__init__.py", line 1, in <module>
    from .types import (
  File "/tmp/tmp.pgqfAvNZOC/venv/lib/python3.10/site-packages/flytekit/types/schema/types.py", line 314, in <module>
    class FlyteSchemaTransformer(TypeTransformer[FlyteSchema]):
  File "/tmp/tmp.pgqfAvNZOC/venv/lib/python3.10/site-packages/flytekit/types/schema/types.py", line 324, in FlyteSchemaTransformer
    _np.bool: SchemaType.SchemaColumn.SchemaColumnType.BOOLEAN,  # type: ignore
  File "/tmp/tmp.pgqfAvNZOC/venv/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'. Did you mean: 'bool_'?
```

### Related component(s)

flytekit

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by dennisobrien** [comment]
It looks like one of these changes has already been made in the PR [flytekit#1557](https://github.com/flyteorg/flytekit/pull/1557)

```
-        _np.bool: SchemaType.SchemaColumn.SchemaColumnType.BOOLEAN,  # type: ignore
+        _np.bool_: SchemaType.SchemaColumn.SchemaColumnType.BOOLEAN,  # type: ignore
```

I've verified that all the `numpy` types referenced in `FlyteSchemaTransformer` are valid for `numpy` version 1.26.4.  So maybe the only work that needs to be done here is to relax the version constraint on `numpy`?

**Comment by eapolinario** [comment]
Fixed by https://github.com/flyteorg/flytekit/pull/2483.
