### ISSUE TITLE
[Core feature] [flytekit] Using remote.fetch_task causes network calls - potentially on module load

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#3176]
### Motivation: Why do you think this is important?

There are 2 ways today in which users can use remote tasks in flyte.
1. @reference_task/workflow - [docs](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/flyte_basics/reference_task.html#sphx-glr-auto-core-flyte-basics-reference-task-py)
2. remote.fetch_task / fetch_workflow

Reference tasks are neverloaded till registration time and are nicer to work with.
but, often times it is desirable to simply construct a workflow by loading remote tasks. this can be done so

```python

remote = FlyteRemote(...)
t1 = remote.fetch_task(...)
...
@workflow
def foo():
   t1(...)
```

The problem with this approach is that this will cause the t1 to be loaded a module load time.

### Goal: What should the final outcome look like, ideally?

it should be possible to lazy load tasks from remote.

```python
t1 = remote.fetch_task_lazy(....)
...
```

this should automatically load the task when used in a workflow at registration or local execution time.

### Describe alternatives you've considered 

NA

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
hey @kumare3 can we close this?
