### ISSUE TITLE
[BUG] Getting Started - Creating a Demo Flyte Cluster and Executing Workflows on a Flyte Cluster

### ISSUE THREAD

**Issue by PulkitMishra** [flyteorg/flyte#3177]
### Describe the bug

Following [this](https://docs.flyte.org/en/latest/getting_started/index.html), steps before `flytectl demo start` work as expected but on running `flytectl demo start` I get 

> 👨‍💻 Flyte is ready! Flyte UI is available at http://localhost:30080/console 🚀 🚀 🎉 
> ❇️ Run the following command to export sandbox environment variables for accessing flytectl
>         export FLYTECTL_CONFIG=/Users/pulkit.mishra/.flyte/config-sandbox.yaml 
> 🐋 Flyte sandbox ships with a Docker registry. Tag and push custom workflow images to localhost:30000
> 📂 The Minio API is hosted on localhost:30002. Use http://localhost:30080/minio/login for Minio console

This provides `FLYTECTL_CONFIG` and the <basepath>/.flyte/config-sandbox.yaml  is also present where it should be, but there is no `KUBECONFIG` as specified in the docs

I set environment variable `FLYTECTL_CONFIG` but am unable to set `KUBECONFIG` because of the above reasons

After this when I run `pyflyte run --remote example.py wf --n 500 --mean 42 --sigma 2` I get the error

>     raise _InactiveRpcError(state)
> grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
>         status = StatusCode.UNAVAILABLE
>         details = "failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused"
>         debug_error_string = "UNKNOWN:Failed to pick subchannel {created_time:"2022-12-21T17:37:15.06631+05:30", children:[UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused {grpc_status:14, created_time:"2022-12-21T17:37:15.066302+05:30"}]}"

### Expected behavior

After running `flytectl demo start`, I should get `KUBECONFIG` just like I get `FLYTECTL_CONFIG`
and `pyflyte run --remote example.py wf --n 500 --mean 42 --sigma 2` should run without the error

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
Hi @PulkitMishra I'm unable to reproduce this error: would you mind copy-pasting the output of
```
flytectl version
pip list | grep flytekit
```

Also, as a side note we're going to update the expected output in the docs, we recently made changes to the output of `flytectl demo start`.

**Comment by cosmicBboy** [comment]
also, what do you see when you go to http://localhost:30080/console?

**Comment by wild-endeavor** [comment]
hey @PulkitMishra thanks for the report!  Could you also help us by telling us what OS you're on?  

The kubeconfig should be in `~/.flyte/state/kubeconfig` and it should have been copied to `~/.kube/config`.  Are any of these files there?  What does your `~/.kube` directory look like?  And does `echo $KUBECONFIG` produce anything?

Thanks.

**Comment by PulkitMishra** [comment]
@cosmicBboy `flytectl version`

> INFO[0000] [0] Couldn't find a config file []. Relying on env vars and pflags. 
> {
>   "App": "flytectl",
>   "Build": "4c68e63",
>   "Version": "0.6.25",
>   "BuildTime": "2022-12-22 12:03:12.718774 +0530 IST m=+0.103588901"
> }

`pip list | grep flytekit`

> flytekit                                        1.2.7

Screenshot of http://localhost:30080/console attached

<img width="1788" alt="Screenshot 2022-12-22 at 12 05 38 PM" src="https://user-images.githubusercontent.com/31157487/209072546-e1cf14ff-c22b-41be-9672-f4b96af69637.png">

**Comment by PulkitMishra** [comment]
ok nvm its fixed now. My bad, I had set the `export FLYTECTL_CONFIG=/Users/pulkit.mishra/.flyte/config-sandbox.yaml` in one terminal but was running `pyflyte run --remote example.py wf --n 500 --mean 42 --sigma 2` in other terminal. Apologies for the trouble

**Comment by cosmicBboy** [comment]
@wild-endeavor @eapolinario even though this issue is closed, can we be proactive here? E.g. can we check in `pyflyte run` to make sure the `FLYTECTL_CONFIG` is set, and if not raise an error or warning?
