### ISSUE TITLE
[Core feature] `pyflyte run` should avoid `_InactiveRpcError(state)` error if `FLYTECTL_CONFIG` env var is not set

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3182]
### Motivation: Why do you think this is important?

When invoking `pyflyte run` without `FLYTECTL_CONFIG` set to some valid flyte config, users get a fairly cryptic error message, see https://github.com/flyteorg/flyte/issues/3177. This throws off new users especially, with no clear recourse or suggestion on how to address the issue.

### Goal: What should the final outcome look like, ideally?

When a user invoked `pyflyte run` without `FLYTECTL_CONFIG` set, it should either produce a more informative error so that they know how to fix it.

_edit: we can also consider changing the default value of `insecure` to True [here](https://github.com/flyteorg/flytekit/blob/master/flytekit/configuration/__init__.py#L314)_

### Describe alternatives you've considered 

A heavier lift would be for pyflyte run to expose a flag or argument that allows users to explicitly pass in a config file.

###  Propose: Link/Inline OR Additional context 

https://github.com/flyteorg/flyte/issues/3177

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by jpvotta** [comment]
@cosmicBboy noting that I also fell into this trap when running through the getting started docs just now. 

Spent about 30 mins googling around looking at similar issues, and was about to post about it, but then found this [old issue](https://github.com/flyteorg/flyte/issues/3177) and realized I hadn't run the `export FLYTECTL_CONFIG=/Users/jv/.flyte/config-sandbox.yaml ` command.

Note that I had run multiple `flytectl demo start` and `flytectl demo teardown` commands in the past, which might be a different usage pattern than others.

**Comment by cosmicBboy** [comment]
@jpvotta which guide were you following? I think we call this out explicitly here: https://docs.flyte.org/projects/cookbook/en/latest/index.html#running-workflows-in-a-flyte-cluster

**Comment by jpvotta** [comment]
I was looking at: https://docs.flyte.org/projects/cookbook/en/latest/userguide_setup.html :)
