### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by GuptaShitul** [flyteorg/flyte#3208]
### Describe the bug

I am trying to create a workflow whenever a release is published but it is not triggering , below code snippet -

**_name: action on release
on:
 release:
    types: [published]_**

all the other triggers work fine indicating that the configuration is fine , only this release is problematic.

### Expected behavior

It should trigger as soon as a release is published

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by GuptaShitul** [comment]
Just to add I have tried using my PAT in place of GITHUB_TOKEN but that also does not help.

**Comment by kumare3** [comment]
Is this using the flytectl action

**Comment by wild-endeavor** [comment]
Hey @GuptaShitul we're not experts on github workflows either, but take a look at some of the ones we use https://github.com/flyteorg/flytekit/blob/master/.github/workflows/pythonpublish.yml.

Maybe check the indentation?

**Comment by eapolinario** [comment]
This doesn't seem Flyte-related (from the details you provided this is github actions misuse or bug). If you feel otherwise, please, re-open the bug with more details and we'll be more than happy to help.
