### ISSUE TITLE
[BUG] Misleading/erroneous `Caching was disabled for this execution.` for tasks with cache enabled

### ISSUE THREAD

**Issue by fg91** [flyteorg/flyte#3218]
### Describe the bug

When a Python task - which has the cache enabled - fails, the flyte console displays an erroneous and misleading warning that `Caching was disabled for this execution.`

I have also seen this warning for **successful* tasks (see screenshot) even though I unfortunately cannot come up with a minimal example to consistently reproduce this.

### Expected behavior

This warning should not be shown.

### Additional context to reproduce

```python
from flytekit import task, workflow


@task(
    cache=True,
    cache_version="1.0",
)
def fail() -> None:
    raise Exception()

@workflow
def workflow():
    fail()
```

### Screenshots

<img width="252" alt="Screenshot 2023-01-09 at 16 24 40" src="https://user-images.githubusercontent.com/36511035/211344301-8fdb16f9-dd2a-4f6e-8c9a-2ef1ef2f4f83.png">
<img width="276" alt="Screenshot 2023-01-09 at 16 24 45" src="https://user-images.githubusercontent.com/36511035/211344348-92fc7616-f272-468c-a3ea-ed5a995bc6b9.png">

Erroneous warning for a **successful task** with *cache enabled*:
<img width="387" alt="Screenshot 2023-01-09 at 17 20 56" src="https://user-images.githubusercontent.com/36511035/211358445-94f739bb-23e8-4243-be6f-7f88360b647f.png">

<img width="663" alt="Screenshot 2023-01-10 at 10 00 53" src="https://user-images.githubusercontent.com/36511035/211507365-5ca4a583-0453-418a-a32b-a7ac32694e01.png">

I downloaded the tarball containing the code in order to make sure that for the respective version the cache is in fact enabled:

<img width="411" alt="Screenshot 2023-01-10 at 12 05 56" src="https://user-images.githubusercontent.com/36511035/211535669-a778da02-9421-4759-9df8-26664d24c086.png">

<img width="398" alt="Screenshot 2023-01-10 at 12 05 35" src="https://user-images.githubusercontent.com/36511035/211535716-d6cc8239-f858-4c8a-a958-5759f9e61e79.png">

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
cc: @jsonporter

**Comment by fg91** [comment]
> I have also seen this warning for *successful tasks (see screenshot) even though I unfortunately cannot come up with a minimal example to consistently reproduce this.

@jsonporter We have identified that the cache errors *for successful tasks* are likely caused by envoy proxies in istio side-cars in the Pods in the flyte namespaces of our deployment that have a default timeout of 1h for dropping inactive TCP connections - in this case between `datacatalog` and the database. This appears to have caused the failed cache writes. See [this](https://flyte-org.slack.com/archives/CP2HDHKE1/p1673533588312959) Slack thread.

This means in my eyes this issue can be closed.
