### ISSUE TITLE
[Core feature] Pass inputs inline with execution event data

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#3232]
### Motivation: Why do you think this is important?

Follow-up to https://github.com/flyteorg/flyte/issues/1327. For a distributed propeller deployment it's useful to pass executions inputs inline rather than as an offloaded URI.

### Goal: What should the final outcome look like, ideally?

Raw inputs should be (configurably) sent inline in execution events

### Describe alternatives you've considered 

Current implementation

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@katrogan , can you expand a bit on the usecase for this?

**Comment by katrogan** [comment]
This is just to keep in feature parity with the inline output passing for eventing. We should be consistent for deployments with inline data policies

**Comment by katrogan** [comment]
Changes are all fully merged
