### ISSUE TITLE
[Docs] flytectl demo start does not work with ZFS

### ISSUE THREAD

**Issue by mficek** [flyteorg/flyte#3235]
### Description

I had troubles running `flytectl demo start`: it hung during initialization of k8s cluster, without any message. After examination of docker logs I realized there is an issue with k8s when running on ZFS file system. 

My setup is Ubuntu 22.04 with the whole hard drive partition being created as ZFS. After re-installing my system to run on ext4, everything works smoothly.

It might be useful to stress this somewhere in the documentation: ZFS is not a friend the demo cluster (sandbox cluster is the same).

Thanks!

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
Hey @mficek, just wanted to add some additional context to this issue. My system is installed on bytes subvolumes and there are similar issues. To fix this, I was able to create a 60G file, format it as ext4, and mount it as a loop back device to '/var/lib/docker', then docker can use the overlay fs driver. I think this approach should work with zfs as well, but have not tested.

**Comment by mficek** [comment]
@hamersaw Thanks for your input, the hardest was to figure out what is happening. In such a complex setup a Flyte has, it's quite hard for newbies to start and if things do not go as planned or described, it's easy to get disappointed and chicken out ;) I think Flyte guys did an amazing job in preparing all the setup and demo and sandbox cluster, no doubts, just this minor issue I didn't find documented anywhere and moreover, the k8s cluster initialization hung silently without any output, which made the problem source detection a bit harder.

**Comment by eapolinario** [comment]
This is caused by the lack of support for ZFS in k3s (as per https://github.com/k3s-io/k3s/discussions/3980). Thankfully a change is being upstreamed and will hit linux distros shortly. In the meantime we should probably leave a note pointing to https://github.com/k3s-io/k3s/discussions/3980#discussioncomment-1299250.

**Comment by mficek** [comment]
@kumare3 Sure thing. 
In Section [Create a Local Demo Flyte Cluster](https://docs.flyte.org/projects/cookbook/en/latest/userguide_setup.html#create-a-local-demo-flyte-cluster) I'd add a simple note: "Please note that local demo Flyte cluster setup does not support a ZFS file system." Maybe?

**Comment by kumare3** [comment]
exclusions are actually harder to know. We should probably write that it has been tested on X? Wdyt?

**Comment by mficek** [comment]
well, I'd be worried about OS versions, python version, etc. etc. I think that a simple note about what we do not know might be more helpful.

**Comment by kumare3** [comment]
I think this works now? wdyt?

**Comment by mficek** [comment]
I do not have options/setup to try now, honestly, sorry. We can close the issue if ZFS support has been either added or documented.
