### ISSUE TITLE
[Docs] De-emphasize Docker. Explain that any OCI container daemon will work.

### ISSUE THREAD

**Issue by ppiegaze** [flyteorg/flyte#3243]
### Description

Currently in the docs we specify that users should install Docker to enable deploying Flyte workflows on a local cluster. In fact any OCI-compatible container engine will do (options include Podman,  RKT and LXD, there are others).

While most user will, in fact, use Docker, we should be accurate and explain that other engines will also work.
We should rewrite the sections that mention Docker. The Getting Started section should tell the whole story in detail, while saying "for example, Docker". Other mentions of Docker can be adjusted slightly. Some thing like "container engine (e.g., Docker)"

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by neverett** [comment]
Addressing this in https://github.com/flyteorg/flytesnacks/pull/1266
