### ISSUE TITLE
[Feature] Add freeform task execution metadata to task executions table

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#325]
**Motivation: Why do you think this is important?**
Allow additional data to be passed as task execution metadata. It's unclear how useful each of these pieces is at the moment but surfacing them might be a good way to figure that out.

**Goal: What should the final outcome look like, ideally?**
Add execution metadata to task execution events.
An example of this task metadata could be - nodeId for a pod where the node was executed
Cluster id for the hive cluster etc
Qubole Command ID
Resource Token that was associated
podID 
AWS Batch Job ID
Spark application id
etc
	Thoughts: A simple Map<string,string> called executionMetadata, which we can show as tabular information in the UI
For node name it is part of the podspec - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#pod-v1-core

**Flyte component**
- [X] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Comment by kumare3** [comment]
This has to be done in two parts
PART 1: Event has to be updated to add this metadata
PART 2: Update admin to add it to the table and expose it in the API

**Comment by katrogan** [comment]
@EngHabu we already do have https://github.com/flyteorg/flyteidl/blob/da3f0f7695147f79a65f0348ba0f626f054ad28e/protos/flyteidl/event/event.proto#L147 although it is a struct rather than map. this is accessible for calls to get and list task executions https://github.com/flyteorg/flyteidl/blob/master/protos/flyteidl/admin/task_execution.proto#L98
