### ISSUE TITLE
[flytekit-java] Change SdkBindingData to be typed

### ISSUE THREAD

**Issue by andresgomezfrr** [flyteorg/flyte#3250]
### Motivation: Why do you think this is important?

After evaluating the current development experience using flytekit-java with some of our users. We've detected some improvements that could help to do the development experience more smooth. One of them is the difficulty that the users have to know what is the specific type of SdkBindingData when working with remote tasks. Currently, the user needs to jump into the remote code to check the input/output classes to know what is the specific type of each attribute. It could be very tedious because you need to find the repository of this remote task or jump using the IDE and check the input.

### Goal: What should the final outcome look like, ideally?

The final outcome is that we want to change the `SdkBindingData` to a typed version `SdkBindingData<?>`. This new version allows the user to know the inner type during the normal development and also helps to ensure that you are setting the current input to a task because if not you get a type mismatch error at compile time.

### Describe alternatives you've considered 

no alternatives

###  Propose: Link/Inline OR Additional context 

https://github.com/flyteorg/flytekit-java/pull/164

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by narape** [comment]
https://github.com/flyteorg/flytekit-java/pull/164
