### ISSUE TITLE
[BUG] copilot uploader sidecar is started even if no outputs are defined

### ISSUE THREAD

**Issue by flixr** [flyteorg/flyte#3254]
### Describe the bug

I have ContainerTasks without any outputs, but it still creates the copilot uploader sidecar, which then exits immediately marking the pod as not ready...

There is a check in [copilot plugin](https://github.com/flyteorg/flyteplugins/blob/b8d3ea9f7396af0c9264e4f946549c1a788c75f0/go/tasks/pluginmachinery/flytek8s/copilot.go#L243) but it doesn't cover this case properly, since outputs is set to empty map in [flytekit core interface](https://github.com/flyteorg/flytekit/blob/5dd887cf5cbe817a35d682a32886f304a97fc910/flytekit/core/interface.py#L53)

So in the copilot plugin it should not just check for nil (None), but also for empty...

### Expected behavior

copilot uploader sidecar is not started

### Additional context to reproduce

simple example:

```python
from flytekit import ContainerTask, kwtypes, workflow

hello_task = ContainerTask(
    name="hello",
    image="ubuntu:20.04",
    inputs=kwtypes(name=str),
    command=["echo", "hello {{.inputs.name}}"]
)

@workflow
def say_hello(name: str):
    hello_task(name=name)
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
@flixr is this something you may be able to contribute? I can offer a fast review.

**Comment by flixr** [comment]
I'm not fluent in go, just fixed some minor things here and there... and mostly I don't really know how I would build and test all this locally..
Also I'm not quite sure if outputs is really an empty map, from what I can see in flyteconsole task definition it seems to have an empty `variables` map inside...

**Comment by kumare3** [comment]
@hamersaw are you tackling this one?
