### ISSUE TITLE
[Core feature] Create reference implementation for Flyte deployments

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3283]
### Motivation: Why do you think this is important?

The purpose if this issue is to create reference implementations of terraform for deploying Flyte on AWS and GCP (eventually we may have community contributions for other cloud platforms like Azure). This reference implementation will be a useful starting point for Flyte administrators to start their production Flyte journey.

### Goal: What should the final outcome look like, ideally?

By the end of this, we should have
- terraform artifacts for deploying a Flyte cluster to AWS/GCP
- documentation in the [Deployment Guides](https://docs.flyte.org/en/latest/deployment/deployment/index.html) that describe and take users through how to set it up.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
should we close this since we won't be open sourcing it here?
