### ISSUE TITLE
[Housekeeping] Improve the way requirements are regenerated

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3284]
### Describe the issue

TODO

regenerating requirements:
- 1 requirements files per python version?
- tox?
- dockerize?
- how to manage plugins requirements?

### What if we do not do this?

TODO

### Related component(s)

flytekit

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
We might need to revisit this in the future, but the current solution of not forcing multiple requirements files.
