### ISSUE TITLE
[FlyteCTL Feature] flytectl not recognized as a valid command on Windows

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/flyte#3290]
### Describe the feature/command for FlyteCTL

After following the [documented instructions](https://docs.flyte.org/projects/flytectl/en/latest/index.html#flytectl-the-official-flyte-command-line-interface) to install flytectl on Windows, the process completes successfully but, when the command is invoked, it returns an error:

`flytectl' is not recognized as an internal or external command, operable program or batch file`

Alternatives tried with no success:

1. Invoking the command using the full path (`C:\Users\<user>\bin\flytectl version` or `./bin/flytectl version`)

**Environment**
Windows 10 Pro, Dev version, ARM-64 arch, WSL2 with Ubuntu distro

### Provide a possible output or UX example

![image (1)](https://user-images.githubusercontent.com/82604841/215156985-b82e2ccc-d7b4-4494-9f29-d5549fadf34d.png)
![image (2)](https://user-images.githubusercontent.com/82604841/215157002-acbc9ff4-7403-402f-8970-d644c4b9988a.png)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
@davidmirror-ops, take a look at https://github.com/flyteorg/flyte/issues/1561 issue. https://github.com/flyteorg/flyte/issues/1561#issuecomment-939034681 is where flytectl testing was captured.

**Comment by eapolinario** [comment]
@davidmirror-ops , if you look at the screenshot you'll notice that we're installing the linux x86 version of flytectl, which is not correct as the environment is windows + arm.

**Comment by eapolinario** [comment]
@davidmirror-ops , while we investigate a proper fix, can you ask the user to download the right binary (e.g. https://github.com/flyteorg/flytectl/releases/download/v0.6.27/flytectl_Windows_arm64.zip)?
