### ISSUE TITLE
[BUG] Tasks called within tasks should error out when run remotely

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3299]
### Describe the bug

Currently, tasks within tasks will return a promise, while the same setup on a remote Flyte cluster will invoke the inner task as a plain python function. Consider the following:

```python
@task
def test(x: int) -> int:
    return x + 1

@task
def echo_integer(value: int) -> int:
    logging.error(f"I've got value {value}")
    return test(x=value + 5) + 1

@workflow
def wf(
    value: int,
):
    return echo_integer(value=value)
```

### Expected behavior

The above code should work when run locally

*edit: flytekit should also log a warning saying that the inner task is executed as a function and not an atomic entity*

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
Just to comment on the decision for this. We're going to log a warning in the remote case where a task is invoked within another task.

**Comment by eapolinario** [comment]
Starting on the next release (flytekit 1.9.0), we're going to throw a warning in case of nested tasks (courtesy of https://github.com/flyteorg/flytekit/pull/1727).
