### ISSUE TITLE
[BUG] OneHotEncoder type not supported as task input when None is supplied as input value.

### ISSUE THREAD

**Issue by xshen8888** [flyteorg/flyte#3319]
### Describe the bug

The task’s input is of type sklearn.preprocessing.OneHotEncoder. It is either supplied by the caller or None if user doesn’t have a encoder instance as input (in which case the task code will get it from an offline storage location).
I tried both, with or without Optional.

```python
@task
def transform(encoder: Optional[OneHotEncoder] = None, ...)
def transform(encoder: OneHotEncoder = None, ...)
When caller do transform(encoder=None, ...), the task will work successfully with pyflyte run (locally).
However, if I bake the module containing the task estimate() into an image and refer to it in a pyflyte remote run, no mater what I do, I keep getting at the terminal (before pyflyte submit the code to remote flyte server):
flytekit/core/type_engine.py", line 1060, in to_literal
    raise TypeError("Ambiguous choice of variant for union type")
...
flytekit/core/promise.py", line 937, in create_and_link_node
    raise AssertionError(f"Failed to Bind variable {k} for function {entity.name}.") from e
AssertionError: Failed to Bind variable **_encoder_** for function dai_mle_models.onehotenc.simple_onehotenc. transform.
```

### Expected behavior

The task should run remotely just like when None is supplied to pandas.DataFrame as task input value (which I have verified working).
e.g.

```python
@task
def sometask(test_data: pd.DataFrame = None, ...)
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
@xshen8888 can you add a TypeTransformer for this type? https://docs.flyte.org/projects/flytekit/en/latest/types.extend.html#custom-types

**Comment by xshen8888** [comment]
It can be done.
However, there are numerous custom types.
This should not be an efficient way to deal with them.
Image what the effort will be for anyone new to Flyte to implement this.

**Comment by kumare3** [comment]
@xshen8888 this does not need to be done for every type. Default is to use pickle as the transport. Just that pickle is brittle. 
now that i see it correctly, it seems the union type has an issue. This is because optional is represented as union. 
You are right, this is a bug, we will fix this soon
