### ISSUE TITLE
[Docs] Explain how the type system and data passing works in Flyte Fundamentals

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3322]
### Description

Currently the **Flyte Fundamentals** don't cover the flyte type system of how data passing works between tasks and workflows. The purpose of this issue is to create a new docs page (probably under "Tasks, Workflows and LaunchPlans") that provides an overview of:

- the flyte type system: how it works, when to use it, how the type engine works, limitations
- data passing: provide a clear mental model of how data is handled in a workflow execution

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by 10sharmashivam** [comment]
Hey, I’d like to take this issue and start working on adding new docs page about how data passing works between tasks and workflows.. #take

**Comment by davidmirror-ops** [comment]
Completed as a blog post: https://flyte.org/blog/so-you-think-you-can-type-how-flytes-type-system-works
