### ISSUE TITLE
[Docs] Explicitly note that nested dataclasses are not supported in the type system

### ISSUE THREAD

**Issue by alex-dr** [flyteorg/flyte#3328]
### Description

In https://github.com/flyteorg/flyte/issues/3110 it was noted that nested dataclasses are not actually supported, and the docs are not very explicit about that.

Given I've gone down a couple rabbit holes related to this (another one related to enum types in doubly-nested dataclasses...), it would be worth making the docs more clear.

In my case, it would have helped to update the comment in [this table](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/type_system/flyte_python_types.html#id1) to mention that nested dataclasses (and I'm not sure what else) are not supported.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
Note: a nuance here is the the Flytekit SDK supports nested dataclasses, but the FlyteIDL type system will lose all the type information in the nested dataclasses, only preserving the types of the top-most dataclass.

**Comment by neverett** [comment]
Added to planned work for docs team.

**Comment by eapolinario** [comment]
After the Flyte 1.14 release, this is no longer the case.
