### ISSUE TITLE
[Docs] Add Deployment Docs for Azure

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3335]
### Description

The purpose of this issue is to add deployment instructions for Flyte on Azure: https://docs.flyte.org/en/latest/deployment/deployment/index.html#deployment-deployment

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
@MorpheusXAUT and many others have done this.

**Comment by davidmirror-ops** [comment]
This is still needed

**Comment by davidmirror-ops** [comment]
A reference Flyte implementation for Azure is maintained here: https://github.com/unionai-oss/deploy-flyte/tree/main/environments/azure/flyte-core
