### ISSUE TITLE
[BUG] Request failed with status code 429 grpc: received message larger than max when opening Flyte Console

### ISSUE THREAD

**Issue by pradithya** [flyteorg/flyte#3337]
### Describe the bug

Opening workflow execution page is failing with error "Request failed with status code 429 grpc: received message larger than max when opening"

<img width="2677" alt="Screenshot 2023-02-14 at 2 51 25 PM" src="https://user-images.githubusercontent.com/4023015/218660954-fd85363e-29f4-4535-92ca-49bf6d487d3c.png">

### Expected behavior

Flyte console should shows workflows execution properly

### Additional context to reproduce

The issue seems to happen due to `/api/v1/executions/` API response returning an execution object that has a huge `closure.error.message` payload.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
cc @ursucarina / @jsonporter

**Comment by pingsutw** [comment]
@katrogan has fixed it
