### ISSUE TITLE
[UI Feature] Add support for ApprovedCondition for GateNodes

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3346]
### Motivation: Why do you think this is important?

Signal UX needs to add support for a third type of gate node - `ApproveCondition`.  ApprovedCondition only accepts `true` (boolean) as an input and should be presented to the user as displaying the incoming input and the simply allowing them to click on 'resume' in the Signal Form. Currently, these nodes (correctly) show the incoming inputs but the resume button is greyed out.

Note: the shape of ApprovedCondition gate nodes is a little different in the `CompiledWorkflowClosure` -- look for `gateNode` and `approve`. Here is an example from [core.control_flow.human_in_the_loop.mainwf](https://localhost.development.uniondemo.run:3000/console/projects/flytesnacks/domains/development/workflows/core.control_flow.human_in_the_loop.mainwf?duration=all)

```
// Example of ApprovedCondition
{
    "gateNode": {
        "approve": {
            "signalId": "approvalfory"
        }
    }
}
```

IDL: [Link to ApprovedCondition in IDL](https://github.com/flyteorg/flyteidl/blob/master/protos/flyteidl/core/workflow.proto#L100)

### Goal: What should the final outcome look like, ideally?

Acceptance Criteria:
- Renders incoming inputs (this currently works just make sure the fix doesn't break it)
- Allows user to click "resume" (this is currently greyed out)
- Sends `true` as value

### Propose: Link/Inline OR Additional context 

This was ported over from this other board: https://github.com/unionai/cloud/issues/1518

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
The condition accepts a Boolean value. So true means that the input values are approved and the mode succeeds. If a user passes false, then the input values are rejected and the node fails. So there should be two buttons - namely "Approve" and "Reject".

**Comment by james-union** [comment]
> Can we rename "Resume" to "Approve"?

@cosmicBboy Sure. And do you want the Reject button to be red or remaining as blue?

**Comment by jsonporter** [comment]
Okay yeah I like that in principle but let me engage the design team to see if they have thoughts

**Comment by jsonporter** [comment]
Sync with design we're going to:
 - Rename "resume" to "approve"
 - Make the "reject" white background (secondary) button
 - Swap the placement/order to cancel -> reject -> approve.

**Comment by tsheiner** [comment]
> thanks! I think it would make sense to have the "Reject" button be red and the "Approve" be green, unless that messes with our current style convention @jsonporter

I am not yet up to speed on our style conventions. However, I would say that in general I am biased towards all modals following the same appearance conventions and not defining special appearance cases for particular use cases.

That said, there can be exceptions, however, I'm just not clear if this case really should rise to that level.

**Comment by cosmicBboy** [comment]
👍
