### ISSUE TITLE
[FlyteCTL Feature] Hide global flags when printing help

### ISSUE THREAD

**Issue by eapolinario** [flyteorg/flyte#3352]
### Describe the feature/command for FlyteCTL

The output of `flytectl <command> --help` includes all global flags, which ends up pushing the useful info about the command too far up in the screen.

### Provide a possible output or UX example

Global flags should be hidden and only the available flags for a particular command should show up, including all flags in case we run `flytectl --help`.

This is possible to be done if we override cobra's usage template. 

https://github.com/unionai/cloud/pull/1818 is an implementation of this idea for Cloud.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Kota-Karthik** [comment]
Hello @samhita-alla 
I am interested in doing this issue 
so kindly assign me this
Thank You : )

**Comment by soumya-dash3** [comment]
Hello @samhita-alla , can this issue be assigned to me please?

**Comment by samhita-alla** [comment]
We'll consider whoever creates a PR first.

**Comment by chaohengstudent** [comment]
Hi @samhita-alla , I have created an PR for this issue.
Wonder if is possible to assigned this me, thanks a lot!
