### ISSUE TITLE
[BUG] [CONSOLE] gate node in dynamic task

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#3354]
### Describe the bug

Gate nodes inside of dynamic tasks don't behave the same.  This workflow https://github.com/flyteorg/flytesnacks/blob/cecf8b1c98b784da3f15c1ab04624619890d1d16/cookbook/core/control_flow/human_in_the_loop.py#L82 is functionally the same as the `mainwf` that we've been testing on, except that it happens inside a dynamic task instead of the top level workflow.

However when run inside a dynamic workflow, things don't look the same.  None of the gate node stuff is there and the approval node only shows Running not Paused.

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/2896568/219818062-c971c10f-f9b1-499e-af5e-02021b92f2e5.png">

### Expected behavior

Things should look the same as the non-dynamic case. This includes all views (node-list, graph, timeline) 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
@jsonporter just assigned @james-union to work on this for the 1.5.0 release.

**Comment by cosmicBboy** [comment]
@jsonporter @james-union this PR: https://github.com/flyteorg/flytesnacks/pull/968 contains code that you can use to work on this issue (basically the `dyn` `@dynamic` workflow)
