### ISSUE TITLE
[Docs] Find a place to document applying changes via helm chart across all namespaces and projects

### ISSUE THREAD

**Issue by ppiegaze** [flyteorg/flyte#3356]
### Description

The discussion begins [here](https://flyte-org.slack.com/archives/CP2HDHKE1/p1676554000073849)

Need to sort through this thread and figure out where to document the essential points.

Among other issues:
The rbac given in [values.yaml](https://github.com/flyteorg/flyte/blob/master/charts/flyte-binary/values.yaml)  is wrong and had to be replaced with the rbac given in [eks-production.yaml](https://github.com/flyteorg/flyte/blob/master/charts/flyte-binary/eks-production.yaml)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by davidmirror-ops** [comment]
`flyte-the-hard-way` is a first attempt to document the necessary fields in `values` and how to use it in a production EKS env. A reference implementation will also be provided with documentation.
