### ISSUE TITLE
[Feature] Flyteadmin should impose limits on stored, free-form strings

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#336]
**Motivation: Why do you think this is important?**
Admin currently accepts string fields that it saves to the database in a variety of different object attributes: error messages, project descriptions, etc. Ideally there should be a limit to ensure the size of the objects stored in the database isn't huge.

**Goal: What should the final outcome look like, ideally?**
Admin should reject write requests that attempt to save large blobs to the datastore **or** handle offloading those values outside the database.

**Describe alternatives you've considered**
See above.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [x] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
Admin should reject write requests (create, update) with too large attribute payload.

**Additional context**
Large string message attributes cause admin to fail list requests. The message payload in list requests can exceed the default gRPC response size resulting in a 429 for end users.

**Is this a blocker for you to adopt Flyte**
nope

**Comment by kumare3** [comment]
@narape any updates on this, should we close this out?

**Comment by evalsocket** [comment]
@kumare3  can this assign to me ? if @narape is not working on this issue

**Comment by kumare3** [comment]
Sure - @narape / @katrogan do we know what remains?

**Comment by katrogan** [comment]
This is done for project descriptions I believe but not _all_ freeform strings

**Comment by EngHabu** [comment]
You got it, @evalsocket ! thank you

**Comment by EngHabu** [comment]
@evalsocket is this something you can do in April?

**Comment by evalsocket** [comment]
Yes
