### ISSUE TITLE
[Core feature] Use mashumaro to serialize/deserialize dataclass

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/flyte#3364]
### Motivation: Why do you think this is important?

[mashumaro](https://github.com/Fatal1ty/mashumaro) has better performance than [marshmallow](https://github.com/marshmallow-code/marshmallow) we use now. we should be able to replace it with marshmallow in flytekit.

![image](https://user-images.githubusercontent.com/37936015/220773538-95fd0880-7254-468a-a6b5-fd4bc9008329.png)

### Goal: What should the final outcome look like, ideally?

1. Reduce overhead while serialize/deserialize dataclass.
2. Should not break existing users

### Describe alternatives you've considered 

NA

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hajapy** [comment]
Another bonus beside speed is it should eliminate the many marshmallow deprecation warnings we see with the current ser/de for dataclasses.

**Comment by hhcs9527** [comment]
Hi Community,
Here is the related [PR](https://github.com/flyteorg/flytekit/pull/1735), please take a look!
Thanks.

**Comment by hhcs9527** [comment]
Hi @eapolinario @pingsutw please check [PR](https://github.com/flyteorg/flytekit/pull/1735) for this issue.
Thanks.
