### ISSUE TITLE
[Docs] Document how to run Flyte deployment via Unionoss-maintained terraform files

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3373]
### Description

See: https://github.com/flyteorg/flyte/issues/3283

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
After some deliberation we decided not to open-source the terraform files.

**Comment by jacksonwb** [comment]
😢
