### ISSUE TITLE
[BUG] FE: Structured data sets not working from launch form

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyte#3395]
### Describe the bug

Users reported that launching a workflow does not work when using structured data sets. This feature was initially implemented in [https://github.com/flyteorg/flyte/issues/405](405) but is no longer working. 

Acceptance Criteria:
- users can launch workflows using structured data sets.

### Expected behavior

- users can launch workflows using structured data sets.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@jsonporter , the linked issue is for FlyteSchema not StructuredDataset. https://github.com/flyteorg/flyteconsole/issues/414 is an issue to support it in the Task tab, but not in the launch form?
