### ISSUE TITLE
[UI Feature] Flyte runtime metrics UI

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3405]
### Motivation: Why do you think this is important?

https://github.com/flyteorg/flyte/issues/3272

#### UPDATE: New
There have been some changes from the original spec/comps.

1. We will no longer use color/opacity values. Instead, simply render the lines between spans. Users can hover over a span to see which `operationId` it represents.
2. We will fetch all execution spans using `depth=0` and will revisit this to better optimize performance in later versions if this feature starts gaining traction.
3. The hover tool-tip will be handled in a separate ticket. 

--- The following is out of date in the listed cases ---

The new UI will be controlled by a toggle ("View Details") and will break up the graph into sections. The colors for these new buckets should be opacity values on black/white overlayed over the existing phase color. Crucially, these overlayed values should be consistent across events (eg, the overlay treatment applied to "plugin" durations should be the same regardless of phase) 

![Image](https://user-images.githubusercontent.com/84735036/231818536-0f03e468-d96c-43d4-8567-d1fae13f8f55.png)

![Image](https://user-images.githubusercontent.com/84735036/231818563-eff07f7c-e628-4cc4-ab65-15488a43c5ca.png)

![Image](https://user-images.githubusercontent.com/84735036/231818571-6d5755bb-ba3d-43e4-b04f-3f9e42ce9298.png)

### Propose: Link/Inline OR Additional context 

See high-level proposal [here](https://github.com/flyteorg/flyte/discussions/3429)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
@jsonporter we need to come up with a few mockups of how this looks. Open questions include:
- how to visualize the different buckets?
- color scheme? legend? tooltip?

**Comment by tsheiner** [comment]
@cosmicBboy I am wondering why the 'view details' toggle ?

do we incur a performance hit to bring the additional details to the UI? 

I am, in general, in favor of "opt-in to complexity" but with this design I don't see the details being visually overwhelming and rather think the toggle introduces unnecessary clutter and cognitive load.

Put another way, why would I not want the sectioned display?

**Comment by cosmicBboy** [comment]
@tsheiner we should discuss further with @jsonporter, I'm agnostic to what approach we take here, but he may have more context on this decision.

**Comment by cosmicBboy** [comment]
@jsonporter @tsheiner let's update the comps so that the new runtime metrics view is the default, no need for the toggle button.

- if the performance hit is too much for large dynamic nodes, for example, we can revisit the toggle button UI.

**Comment by tsheiner** [comment]
Updated design:

<img width="1440" alt="default state" src="https://user-images.githubusercontent.com/839128/232549404-962df4a6-f83b-4065-a196-8b9dc7682143.png">
<img width="1440" alt="hover over state" src="https://user-images.githubusercontent.com/839128/232549408-f9781ab3-7c97-4f2a-bc87-c2607d6dc2ac.png">

**Comment by tsheiner** [comment]
@4nalog updated comps ^^^

**Comment by flixr** [comment]
The design looks nice, I would even prefer to highlight the actual runtime even more than the other phases.

@jsonporter This is marked as done in the roadmap, but I only see basic hover tooltips in 1.6...
Is there a follow up planned for 1.7?

**Comment by hamersaw** [comment]
closing as completed
