### ISSUE TITLE
[Docs] Explain that .gitignore and .dockerignore are used by fast registration to ignore files

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3407]
### Description

In the [registering workflows] Flyte Fundamentals page, add a subheading to explain that fast registration takes into consideration the `.gitignore` and `.dockerignore` files to ignore certain file patterns when packaging up user-defined code.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
@eapolinario could not find any documentation on this, will add it to 1.5.0 release

**Comment by eapolinario** [comment]
Indeed. That said, the original [PR](https://github.com/flyteorg/flytekit/pull/899) has a great description of this feature that we could use.
