### ISSUE TITLE
[Core feature] Spark, Ray, Dask plugins should support `pod_template` and `pod_template_name` arguments

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3414]
### Motivation: Why do you think this is important?

Similar to https://github.com/flyteorg/flytekit/pull/1515, we want to add support for the new pod template configuration for the spark, ray, and dask plugins:

- [ ] spark plugin code changes: https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-spark
- [ ] spark plugin flytesnacks docs: https://github.com/flyteorg/flytesnacks/tree/master/cookbook/integrations/kubernetes/k8s_spark
- [ ] ray plugin code changes: https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-ray
- [ ] ray plugin flytesnacks docs: https://github.com/flyteorg/flytesnacks/tree/master/cookbook/integrations/kubernetes/ray_example
- [ ] dask plugin code changes: https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-dask
- [ ] dask plugin flytesnacks docs: https://github.com/flyteorg/flytesnacks/tree/master/cookbook/integrations/kubernetes/k8s_dask

### Goal: What should the final outcome look like, ideally?

Each of the plugins mentioned above needs to accept `pod_template` and `pod_template_name` arguments, like the [ContainerTask PR](https://github.com/flyteorg/flytekit/pull/1515/files#diff-640c26a7a46d424fc3097a9af00d8b97c4efbbea249800c30b8784ec93b2186f), with documentation updates in the Spark, Ray, and Dask integration examples.

### Describe alternatives you've considered 

NA

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
@cosmicBboy we should close this issue, or at least reword it significantly because it is very misleading. There does not need to be any changes to flytekit for any of these plugins to support the new `PodTemplate` work. In addition, it is not clear that this is useful with Spark.

**Comment by cosmicBboy** [comment]
cool, closing this now. @hamersaw would you mind creating a new issue with the correct scope?
