### ISSUE TITLE
Docstring not supported on flyteconsole

### ISSUE THREAD

**Issue by ByronHsu** [flyteorg/flyte#3416]
1. docstring is already stored in database but not exposed to UI
2. My idea is to add a docstring column and provide an doc icon to hover. When users hover on the icon, they can see the doc
<img width="961" alt="image" src="https://user-images.githubusercontent.com/24364830/223212575-0735cb82-0dac-4ee0-88b3-818fac1e6ccb.png">

**Comment by pingsutw** [comment]
pr is merged in v1.6.0. https://github.com/flyteorg/flyteconsole/pull/735
