### ISSUE TITLE
[BUG] ARM64 Docker Images contains x86_64 binaries (helm)

### ISSUE THREAD

**Issue by qbx2** [flyteorg/flyte#3423]
### Describe the bug

I am not able to run the arm64 docker images on aws graviton instances because arm64 docker images are built in incorrect way.

To check:
```
$ docker run -it --platform linux/arm64 -u root cr.flyte.org/flyteorg/flyteadmin-release:latest sh

/ # apk add file

/ # file bin/flyteadmin
bin/flyteadmin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=pwwxVfCtJjTsZm9XA0ED/BJdCEuBm0QjhMujOZ7E7/a_vHl8mBZ4xrHPFYqAdf/on6kzeFZfsYdRjhPjzhK, stripped
```

Other images also have this issue, for example:
```
$ docker run -it --platform linux/arm64 -u root cr.flyte.org/flyteorg/datacatalog:latest sh

/ # apk add file

/ # file bin/datacatalog
bin/datacatalog: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=YBzDJD8nguzh9dRW4GPp/iKNJqrMQzbqKL7lVR_L0/_wLIwVTI2EO3sXJO2Sup/5m-2xGfqxh4rTZlXehX4, not stripped
```

I did not check every images, but I'm pretty sure that most images have the issue.

### Expected behavior

ARM64 Docker Images should not contain x86_64 binaries. They should contain arm64 binaries instead. Graviton instances should be able to run flyte using docker.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by jeevb** [comment]
This has to do with the `make linux-compile` target. It doesn’t respect the env vars set in the Dockerfile.

**Comment by eapolinario** [comment]
Fixed by https://github.com/flyteorg/flytepropeller/pull/552, https://github.com/flyteorg/flyteadmin/pull/550, and https://github.com/flyteorg/datacatalog/pull/103.

**Comment by qbx2** [comment]
@eapolinario Thank you for the fix, could you please tell when is the fix going to be released?

**Comment by eapolinario** [comment]
@qbx2 , we have a monthly release cadence (unless we have a high pri / security issue). The current expectation is to have 1.6 out by the beginning of May.
