### ISSUE TITLE
Differentiate between cache disabled and cache put failure

### ISSUE THREAD

**Issue by hamersaw** [flyteorg/flyte#3430]
A user has a cache put failure which we can confirm is set in the admin DB as the [correct code](https://github.com/flyteorg/flyteidl/blob/9fbac98b2d173fe1b30f18ac0487ff35b9627e3b/protos/flyteidl/core/catalog.proto#L9-L25). However, when it is displayed in the UI, the icon is the same as the "cache disabled" icon and hovering displays as such. It would be useful if there were visual differentiation between these two status'.

**Comment by james-union** [comment]
![image](https://user-images.githubusercontent.com/105876962/224357868-848eaa56-e163-409f-aa24-5d354c51d74b.png)
@jsonporter @hamersaw Does this look good?
