### ISSUE TITLE
Bug: certain actions on workflow pages create "Unexpected Error"

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyte#3437]
Users reported that certain actions on the workflow details page create an error "Cannot read property of undefined". To repo, open a workflow execution, click on the task to open the side panel and then click on a second task while the panel is open. The bug was reported in `v1.1.6`
![image (9)](https://user-images.githubusercontent.com/84735036/185468712-911181f9-dfec-4fab-9b2e-7628ee2c9b9e.png)

**Comment by cosmicBboy** [comment]
https://github.com/flyteorg/flyteconsole/pull/715 should have been the fix for this, will close this for now. If this comes up again users should be able to open up a new issue.
