### ISSUE TITLE
[BUG] pyflyte run fails on Windows

### ISSUE THREAD

**Issue by jboutwell-rva** [flyteorg/flyte#3451]
Running the following in the command prompt fails:
`pyflyte run --remote example.py training_workflow --hyperparameters "{\"C\": 0.1}"`

Error:
`{"asctime": "2023-03-11 11:32:20,895", "name": "flytekit", "levelname": "WARNING", "message": "FlyteSchema is deprecated, use Structured Dataset instead."}
Failed with Exception: Reason: SYSTEM:Unknown
Underlying Exception: cannot find context for 'fork'`

The example is taken from https://docs.flyte.org/projects/cookbook/en/latest/index.html.

The error appears to be caused by this line:
https://github.com/flyteorg/flytekit/blob/master/flytekit/clients/auth/auth_client.py#L308

The python multiprocessing docs indicate only "spawn" is supported on Windows, and as of 3.8 is also recommended for macOS.

Version Info
Windows 10
Python 3.10.10
flytekit-1.4.1

The same example works for me on macOS.

**Comment by eapolinario** [comment]
https://github.com/flyteorg/flytekit/pull/2626 is going to fix this.
