### ISSUE TITLE
[BUG] Java AutoValue Inputs/Outputs can't extend from other classes.

### ISSUE THREAD

**Issue by andresgomezfrr** [flyteorg/flyte#3453]
### Describe the bug

If I have an AutoValue Input/Output and it extends from another class which adds more fields to this input/output, the `JacksonSdkType.of(Input.class)` doesn't get the fields from the parent class properly.that

### Expected behavior

```java
 @AutoValue
  public abstract static class Input extends ParentInput {
    abstract SdkBindingData<String> c();

    public static Input create(
        SdkBindingData<String> a,
        SdkBindingData<String> b,
        SdkBindingData<String> c) {
      return new AutoValue_Input(a, b, c);
    }
  }
  ```
  
  ```java
  public abstract static class Input extends ParentInput {
    abstract SdkBindingData<String> a();

    abstract SdkBindingData<String> b();
  }
  ```
  
  This autovalue class is generated well but the `JacksonSdkType.of(Input.class)` only identifies the `c` as a field. It must identify `a`, `b` & `c`.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pingsutw** [comment]
FYI @honnix

**Comment by honnix** [comment]
I assume it was:
```java
public abstract static class ParentInput {
  abstract SdkBindingData<String> a();

  abstract SdkBindingData<String> b();
}
```

It is not possible to safely infer the getter methods from parent by only looking at `Input` and `ParentInput`. This is a limitation, and to work around:

```java
public abstract static class ParentInput {
  @JsonProperty("a")
  abstract SdkBindingData<String> a();

  @JsonProperty("b")
  abstract SdkBindingData<String> b();
}
```

**Comment by honnix** [comment]
I suggest we close this.  Wdyt @andresgomezfrr ?

**Comment by andresgomezfrr** [comment]
Sounds good to me!
