### ISSUE TITLE
[BUG] FlyteConsole: execution detail panel task template dynamic executions

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyte#3455]
### Describe the bug

User reported inconsistent behavior when dealing with dynamic executions in the detail panel (right slide-out).  The first issue is that sometimes the task tab doesn't show up (it should) and then sometimes the detail are incorrect.

Dynamic tasks should always have a task template and this template should be pulled from the closure (in the case of dynamics this should be the dynamic's closure)

### Expected behavior

1. All tasks (dynamic included) should show a task tab in the execution details panel
2. The values displayed in this the task tab should always from the execution closure.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by nicklofaso** [comment]
We are experiencing this issue (missing Task tab), thanks for opening/addressing. Happy to be a guinea pig of a beta release if it would be helpful. We use dynamic tasks pretty heavily.
