### ISSUE TITLE
[BUG] [UI] gate node "signal input" form should display the expected type

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3456]
### Describe the bug

The `wait_for_input` gate node has an `expected_type` type that indicates the type that needs to be provided when setting the signal value (either on the UI or FlyteRemote).

Currently, the gate node modal form doesn't show the expected type:
![image](https://user-images.githubusercontent.com/2816689/224797602-d81412f6-5f64-43b7-abf6-e5cfcf84438a.png)

### Expected behavior

The purpose of this ticket is to update the gate node modal form for `wait_for_input` nodes so that it displays the expected type of the input, similar to the regular launchform:
![image](https://user-images.githubusercontent.com/2816689/224797689-0936a314-0e20-4522-bafd-257e8ee0eb1a.png)

### Additional context to reproduce

See this workflow to reproduce:
https://development.uniondemo.run/console/projects/flytesnacks/domains/development/workflows/core.control_flow.waiting_for_external_inputs.reporting_wf?duration=all

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
this is supported now. the ux can still be improved but closing it for now
