### ISSUE TITLE
[housekeeping] Include default MinIO credentials in sandbox console readout

### ISSUE THREAD

**Issue by jpvotta** [flyteorg/flyte#3458]
### Motivation: Why do you think this is important?

When following the [steps](https://docs.flyte.org/en/latest/deployment/deployment/sandbox.html#start-the-sandbox) to setup Flyte on a demo sandbox, the console reports that `📂 The Minio API is hosted on localhost:30002. Use http://localhost:30080/minio/login for Minio console`. However, in order to view the obect store, you need to use the default credentials for MinIO, which are: 
 - username: `minio`
 - password: `miniostorage `

### Goal: What should the final outcome look like, ideally?

It would be great to include this information in:
 - The docs ([sandbox deployment](https://docs.flyte.org/en/latest/deployment/deployment/sandbox.html#sandbox-deployment) article)
 - The console readout upon successful install (part of the `Flyte is ready!` message)

### Describe alternatives you've considered 

N/A

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by davidmirror-ops** [comment]
@GRomR1 that's great!

would you be up to submitting a PR?
