### ISSUE TITLE
Cost Optimizations: Create Resource Request CRD before launching pod

### ISSUE THREAD

**Issue by migueltol22** [flyteorg/flyte#346]
**Motivation: Why do you think this is important?**
motivation can be found at https://github.com/lyft/flyte/issues/342.

**Goal: What should the final outcome look like, ideally?**
Prior to launching a pod a Resource Request CRD should be created containing queuing_budget for the given node. This will be used as part of the scheduler extender to decide when to schedule the pod.

**Describe alternatives you've considered**

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [x ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Additional context**

**Is this a blocker for you to adopt Flyte**
Please let us know if this makes it impossible to adopt Flyte

**Comment by kumare3** [comment]
the project has been abandoned for better alternatives
