### ISSUE TITLE
[FlyteCTL Feature] Add `--force` flag to `flytectl config init`

### ISSUE THREAD

**Issue by eapolinario** [flyteorg/flyte#3469]
### Describe the feature/command for FlyteCTL

Config files are usually setup in CI, but this is hard in the case of `flytectl config init` because it [expects user input](https://github.com/flyteorg/flytectl/blob/master/cmd/configuration/configuration.go#L112-L116) in case there's an existing file.

### Provide a possible output or UX example

We should be able to run `flytectl config init --force` to force an update to the config file.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Future-Outlier** [comment]
@eapolinario, I've completed the feature implementation.
Please feel free to assign yourself, review the changes, and close the pull request (PR) if everything looks good. Thank you

**Comment by pingsutw** [comment]
done
