### ISSUE TITLE
[BUG] Flyteconsole: mapped tasks in execution detail panel tabs not updating to correct node

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyte#3499]
### Describe the bug

When viewing a mapped task's execution detail panel, clicking on one of the mapped tasks should update the context of the panel to that specific execution. However, the details within the tabs (Inputs, Outputs, Tasks) still display the details from the parent execution.

### Expected behavior

When a user is viewing a mapped task in the execution detail panel and clicks into one of the sub/mapped tasks, the context for all of the details in the panel should be set to that mapped tasks execution. 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by jsonporter** [comment]
Fixed with https://github.com/flyteorg/flyteconsole/pull/727 and https://github.com/flyteorg/flyteconsole/pull/725

**Comment by nicklofaso** [comment]
Hi @jsonporter  I upgraded from flyte v1.3.0 to v1.4.3 yesterday and noticed the "task" tab is now gone for my dynamic tasks. Does this issue resolve that? See attached screenshots. In v1.3.0 i had a "task" tab

<img width="1429" alt="Missing Task Tab on Dynamic" src="https://user-images.githubusercontent.com/25391173/227728077-e2cdc9a2-5df4-4533-b377-e8dd5f278c21.png">
<img width="1419" alt="Task Tab Present" src="https://user-images.githubusercontent.com/25391173/227728079-bc380b93-7552-4622-a00a-db775b284a8c.png">
