### ISSUE TITLE
[Docs] Mention need to create an initial git commit

### ISSUE THREAD

**Issue by tsheiner** [flyteorg/flyte#3520]
### Description

Minor issue.

At [this point](https://docs.flyte.org/projects/cookbook/en/latest/getting_started/package_register.html#containerizing-your-project) in Getting Started, you'll get an error unless you've created at least one git commit, which the narrative never explicitly tells you to do.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
hi @tsheiner, the referenced guide has a Prerequisites admonition that assumes that the user has following the [previous guide](https://docs.flyte.org/projects/cookbook/en/latest/getting_started/creating_flyte_project.html#creating-a-flyte-project) on creating a flyte project, which does tell the user to initialize a git repository: 

<img width="848" alt="image" src="https://user-images.githubusercontent.com/2816689/227052839-14426da8-3bbc-4f71-b41d-758520c56245.png">

Feel free to suggest a way that this can be made clearer!

**Comment by tsheiner** [comment]
Yes, understood. I believe the issue is not about init'ing a repo in the directory but that the user must _also_ do at least one commit. Sounds obvious in retrospect but I missed it and as a result had trouble figuring out why I was getting an error when trying to follow the instructions to register my project:

```
(my_project) ➜  my_project git:(main) ✗ flytectl register files \
    --project flytesnacks \
    --domain development \
    --archive flyte-package.tgz \
    --version "$(git rev-parse HEAD)"
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
INFO[0000] [0] Couldn't find a config file []. Relying on env vars and pflags. 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105df4a64]
```

**Comment by neverett** [comment]
Addressing this in https://github.com/flyteorg/flytesnacks/pull/1266
