### ISSUE TITLE
[Docs] No instruction to install flytekitplugins

### ISSUE THREAD

**Issue by tsheiner** [flyteorg/flyte#3521]
### Description

Following getting started, [at this point in docs](https://docs.flyte.org/projects/cookbook/en/latest/getting_started/visualizing_artifacts.html#rendering-in-line-decks) syntax given will create a pylance problem for the file because was no previous instruction to install flytekitplugins module. 

Need to add `flytekitplugins-deck-standard` to installation command [here](https://docs.flyte.org/projects/cookbook/en/latest/index.html#installation) 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
cc @davidmirror-ops
