### ISSUE TITLE
[UI] Show more information for Branch nodes

### ISSUE THREAD

**Issue by schottra** [flyteorg/flyte#3529]
The UI will currently only show minimal information about a branch node in the list of NodeExecutions. This could be enhanced to show things such as the if/else condition and maybe which branch was taken at runtime.

**Flyte component**
- [x] FlyteConsole (UI)

**Comment by cosmicBboy** [comment]
Note: this is something we want to do eventually, we have comps for this, but not prioritized in the roadmap at the moment

**Comment by kumare3** [comment]
this is indeed supported. closing
