### ISSUE TITLE
nginx 404 after install via Opta

### ISSUE THREAD

**Issue by SamJBentley** [flyteorg/flyte#3535]
I followed the instructions to install with Opta into AWS. When I go to the URL in Chrome, I get 404. Can anyone help with this please?[](url)
![Flyte 404](https://user-images.githubusercontent.com/19324577/227903242-3d20f838-3c75-45f7-8e27-a27739494678.png)

**Comment by davidmirror-ops** [comment]
Opta is deprecated now
