### ISSUE TITLE
[BUG] Flyteconsole: Validation causes infinite loop when trying to delete existing value

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyte#3543]
### Describe the bug

When re-launching a workflow if the a user tries to delete a value from a text input the browser freezes. 

Steps to repo:
- find a workflow with launch plan that has a text input (eg, `flytesnacks/development/human_in_the_loop.wf_dy`)
- relaunch a previous execution 
- In the launch form, delete the text value (note: the bug only happens when a user hits backspace/delete; simply highlighting and over-typing a new value seems to work)

### Expected behavior

Users should be able to delete a previous value and the validation message should appear... but the browser should not freeze.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
@jsonporter will let you triage this.

**Comment by jsonporter** [comment]
Transient error; cannot repo. Closing.
