### ISSUE TITLE
[Feature][Discussion needed] CRD validation in Flyte Deployment Pipeline: approaches

### ISSUE THREAD

**Issue by bnsblue** [flyteorg/flyte#355]
**Motivation: Why do you think this is important?**
We are adding CRD Validation for Flyteworkflow CRD. One question that needs to be discussed is how we integrate the validation generation into Flyte's deployment pipeline given that we have multiple repos and deployments do not always cover all of the relevant repos.

**Goal: What should the final outcome look like, ideally?**
Currently the implementation of the command that generates the validation for CRDs lives in `flytepropeller`. Whenever there's changes around the Flyteworkflow CRDs we have to make sure the developer remembers to generate the new validation spec for the changes. 

However, the changes in CRD and the validation spec also needs to be recognized in `flyte` repo so that any new deployments of `flyte` doesn't revert the changes.

**Describe alternatives you've considered**

### **A. Using initContainer of K8s**
- Description:
Create a initContainer within flytepropeller pod and let that container generate the validation spec everytime a propeller got spins up. This can be considered as an on-line approach.

Whenever there's changes in CRDs, developers need to 
1. in `flytepropeller`, generate the new openapi definition
2. Build and push a new `flytepropeller` image to dockerhub
3. in `flyte`, pull the `flytepropeller` image and generate the new crd which contains the new validation spec and put the spec to the right place

- Pros: 
  1. Highly automated

- Cons: 
  1. Leaving the initContainer idle for the rest of the time and takes resource
  2. ...

### **B. Pulling `flytepropeller` images from within `flyte` repo and do integration similar to `kustomize`**
- Description:
This is an offline approach. This approach creates a script inside flyte and a corresponding make target. The developer needs to execute that make target to generate the latest validation spec. This approach is pretty similar to `make kustomize` but it has to pull the latest image of flytepropeller everytime. 

Whenever there's changes in CRDs, developers need to 
1. in `flytepropeller`, generate the new openapi definition
2. Build and push a new `flytepropeller` image to dockerhub
3. in `flyte`, pull the `flytepropeller` image and generate the new crd which contains the new validation spec and put the spec to the right place
4. `k apply -f` the new CRD in all the clusters

- Pros:
  1. No resource wasted
  2. Simple enough and verifiable offline

- Cons:
  1. More manual steps. 
  2. The order of the keys in the generated validation spec is randomized somehow. It is difficult to verify whether the validation spec is up-to-date when we execute kustomize.

**Flyte component**
- [ ] Overall
- [x] Flyte Setup and Installation scripts
- [x] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [x] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Additional context**

**Is this a blocker for you to adopt Flyte**
Please let us know if this makes it impossible to adopt Flyte

**Comment by EngHabu** [comment]
This PR will add the empty schema: https://github.com/flyteorg/flyte/pull/1805 I'm inclined to close this issue... 
thank you for the work you did so far!
