### ISSUE TITLE
[Docs] Copy code button puts too much html in buffer

### ISSUE THREAD

**Issue by tsheiner** [flyteorg/flyte#3551]
### Description

As example, just after [this point](https://docs.flyte.org/projects/cookbook/en/latest/userguide_setup.html#repo-setup) in docs there is a code block with copy code button. If you press button and then paste you get this output:

```

span.prompt1:before {
  content: "$ ";
}
git clone https://github.com/flyteorg/flytesnacks
cd flytesnacks/cookbook
pip install -r core/requirements.txt
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
@cosmicBboy is this something you know anything about?

**Comment by cosmicBboy** [comment]
weird, lemme look
