### ISSUE TITLE
[UI Feature] Detailed schedule information in workflow page

### ISSUE THREAD

**Issue by pradithya** [flyteorg/flyte#3554]
### Motivation: Why do you think this is important?

When multiple scheduled launch plans are bound to a single workflow the information on the workflow page is lacking. The schedules section in the workflow page currently only shows the list of schedules and no further information about the corresponding launch plan. 

![Screenshot 2023-03-30 at 5 12 12 PM](https://user-images.githubusercontent.com/4023015/228788392-cc863053-d7a4-4cfd-9e4d-b2bac0ea71d7.png)

### Goal: What should the final outcome look like, ideally?

Ideally, in addition to the schedule, the launch plan name and a link that points to the corresponding launch plan page should be visible on the workflow page.

![Screenshot 2023-03-30 at 5 19 27 PM](https://user-images.githubusercontent.com/4023015/228790338-c449a1a2-e110-4a0a-9f0f-96a383f5127b.png)

### Propose: Link/Inline OR Additional context 

Add the launch plan name and link to the launch plan page next to the schedule in the workflow page.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
cc @tsheiner

**Comment by kumare3** [comment]
cc @jsonporter
