### ISSUE TITLE
[BUG] Unnecessary warning in response to every pyflyte command

### ISSUE THREAD

**Issue by tsheiner** [flyteorg/flyte#3557]
### Describe the bug

1. execute any valid pyflyte command
2. see in response the following warning `{"asctime": "2023-03-30 10:54:22,803", "name": "flytekit", "levelname": "WARNING", "message": "FlyteSchema is deprecated, use Structured Dataset instead."}`

### Expected behavior

That I only get this warning if I am doing something that involves FlyteSchema

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pingsutw** [comment]
we have fixed it [here](https://github.com/flyteorg/flytekit/commit/de2878903b594069f1629d7ee11bf59ab04b59f2). Try to install latest version of flytekit.

**Comment by tsheiner** [comment]
Yup, validated in 1.5.
