### ISSUE TITLE
[BUG] ShellTask error is recognize as system failure

### ISSUE THREAD

**Issue by pradithya** [flyteorg/flyte#3559]
### Describe the bug

Error while executing script within a ShellTask is recognize as system error

<img width="843" alt="Screenshot 2023-03-31 at 3 31 06 PM" src="https://user-images.githubusercontent.com/4023015/229053651-6427eb54-e750-48a8-883d-435ce9a0ac2d.png">

### Expected behavior

Error while executing script in ShellTask should be classified as non-system error

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
what type of exception do you think this should raise?  Should it be automatically retried or not?

**Comment by wild-endeavor** [comment]
https://github.com/flyteorg/flytekit/pull/1580

**Comment by pradithya** [comment]
Fixed in #1732
