### ISSUE TITLE
[Core feature] Add user id to security context

### ISSUE THREAD

**Issue by ByronHsu** [flyteorg/flyte#3566]
### Motivation: Why do you think this is important?

Currently, we do not have user id in the security context. Therefore, the developers are unable to decorate the task with user id on flytepropeller side.

### Goal: What should the final outcome look like, ideally?

Add userid to security context protobuf and change related repo accordingly.

### Describe alternatives you've considered 

None

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by ByronHsu** [comment]
@mick will be collaborating on this issue. We will provide a configurable way to map securityContext.Identity to pod label.

Implementation:
1. Use `taskCtx.TaskExecutionMetadata().GetSecurityContext()` to extract `securityContext` from `taskCtx` ([line](https://github.com/flyteorg/flyteplugins/blob/master/go/tasks/plugins/k8s/pod/plugin.go#L51))
2. Inject identity to `objectMeta`'s label with customKey Name ([line](https://github.com/flyteorg/flyteplugins/blob/master/go/tasks/plugins/k8s/pod/plugin.go#L60))

Config:
1. Developers should be able to config (maybe use configmap) which fields of `securityContext.Identity`  to map to pod labels

**Comment by pingsutw** [comment]
@ByronHsu could we close this issue?

**Comment by mickjermsurawong-stripe** [comment]
Yup Kevin! Thanks for revisiting here
