### ISSUE TITLE
Correctly render static sub-workflow nodes

### ISSUE THREAD

**Issue by schottra** [flyteorg/flyte#357]
There are two issues:
1. In the Nodes view, we do not correctly show the nesting relationship of nodes that are executed as part of static sub-workflows. This is because there is no information available only in NodeExecutions which can be used to determine this relationship. The nesting structure only exists in the workflow closure.
2. In the graph view, we don't show any nodes inside of static sub-workflows. We only show the workflow node itself. This is despite having the connection information available in the static closure.

Two changes would help this:
1. Update the Nodes tab to render the nodes in the static graph, decorating with execution information, instead of the other way around. This would require some special handling for dynamic nodes (synthesizing and inserting connections for child nodes)
2. Update the graph preparation code to also extract connections in sub-workflows. This will take special handling for wiring the end-node of the sub-workflow to the downstream nodes of the workflow node itself.

![image](https://user-images.githubusercontent.com/1815175/85439028-67f78d80-b541-11ea-9255-c32d15ff18d8.png)

![image](https://user-images.githubusercontent.com/1815175/85439072-747be600-b541-11ea-88ea-db50c48f857d.png)

**Comment by kumare3** [comment]
This was resolved in Jan using Node-node relationship

**Comment by kanterov** [comment]
@kumare3 I don't think the second part was resolved, was it?

> In the graph view, we don't show any nodes inside of static sub-workflows. We only show the workflow node itself. This is despite having the connection information available in the static closure.

**Comment by kumare3** [comment]
@kanterov you are right, but we are completely redoing graph view. I'll open one ticket. Also for now look at https://github.com/flyteorg/flytectl/pull/75.

I will create a new issue for all graphview problems
