### ISSUE TITLE
[BUG] Wrong primary container name when using pod template breaks PytorchJob

### ISSUE THREAD

**Issue by fg91** [flyteorg/flyte#3590]
### Describe the bug

When creating a task with such a pod template passed to `@task`...

```python
PodTemplate(
    pod_spec = V1PodSpec(
        containers=[],
        tolerations=[
            V1Toleration(<some toleration>)
        ],
        node_selector=<some nodeselector>
    )
)
```

... such a Pod is created:

```yaml
apiVersion: v1
kind: Pod
...
spec:
  containers:
  - image: ...
    name: primary
  nodeSelector:
    <some nodeselector>
  tolerations:
  - <some toleration>
```

The nodeselector and toleration is applied correctly but the primary container name is `primary` instead of the typical task id.

For a normal task running in a single Pod, the container name doesn't really matter. However, this leads to problems e.g. with PytorchJobs for which the primary container name is expected to be `pytorch`.

[Here](https://github.com/flyteorg/flyteplugins/blob/4f02c2ca8d461538e43a1cd6250bcfd23cd448c4/go/tasks/plugins/k8s/kfoperators/common/common_operator.go#L169), a typical task id-based container name would be replaced with `pytorch`, the string `primary` is not.

### Expected behavior

[Here](https://github.com/flyteorg/flyteplugins/blob/4f02c2ca8d461538e43a1cd6250bcfd23cd448c4/go/tasks/pluginmachinery/flytek8s/pod_helper.go#L155), the container name in `target.K8SPod.PodSpec` should not be `primary`.

If this were the case, it would correctly be replaced with `pytorch` [here](https://github.com/flyteorg/flyteplugins/blob/4f02c2ca8d461538e43a1cd6250bcfd23cd448c4/go/tasks/plugins/k8s/kfoperators/pytorch/pytorch.go#L69).

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
fixed by https://github.com/flyteorg/flyteplugins/pull/340
