### ISSUE TITLE
[BUG] Megabyte sized log lines

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#360]
**Describe the bug**
There are some very large log lines in propeller that look like this

```
{"json":{"exec_id":"mj9w6zkj55","ns":"asdf-development","res_ver":"300754394","routine":"worker-409","src":"executor.go:146","wf":"asdf:development:workflows.raw_data_wf.asdfWorkflow"},"level":"info","msg":"Workflow has failed. Error [code:\"USER:Unknown\" message:\"Traceback (most recent call last):\\n\\n      File \\\"/srv/service/venv/lib/python3.6/site-packages/flytekit/common/exceptions/scopes.py\\\", line 206, in user_entry_point\\n        return wrapped(*args, **kwargs)\\n      File \\\"/srv/service/current/workflows/......
```

which seems to be a repeat of another log line

```
Workflow has failed. Error [code:"USER:Unknown" message:"Traceback (most recent call last):\n\n      File \"/srv/service/venv/lib/python3.6/site-packages/flytekit/common/exceptions/scopes.py\", .......
```

These two log lines can get very big.  I think they both come from `pkg/controller/workflow/executor.go:146`.  I don't know why Kibana is repeating them but fixing this line will probably fix both.

**Expected behavior**
Human readable logs.

Should we add a limit to the logger itself?

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [x] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
1. Use Spark
2. When you inevitably make a mistake, look at the logs.

**Screenshots**
Internal data - no screenshot.

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**
NA

**Comment by EngHabu** [comment]
Adding the limit in the logger actually make sense... should it limit and fail the logger call? or truncate? truncate from the end or from the end or from the start?

**Comment by wild-endeavor** [comment]
truncate from the middle i think.  what should the limit be?  128KB?

**Comment by EngHabu** [comment]
128KB sounds so generous already... but yeah, let's go with that..

**Comment by kumare3** [comment]
we should also remove the print statement

**Comment by EngHabu** [comment]
Triage: Won't fix
