### ISSUE TITLE
[Docs] Add documentation for partial task support

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3604]
### Description

Flytekit 1.5.0 added support for using `partial` to provide default arguments to tasks. The flytesnacks documentation should be updated with this information in the [basics](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/flyte_basics/index.html) section and maybe also the [Flyte Fundamentals](https://docs.flyte.org/projects/cookbook/en/latest/getting_started/tasks_and_workflows.html) section

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
@samhita-alla we should hold off on merging any more PRs until we merge https://github.com/flyteorg/flytesnacks/pull/1011. All these files will be removed/deleted and will need help migrating these changes over to the new structure and file format

**Comment by samhita-alla** [comment]
Ah, my bad. Will not merge PRs.
