### ISSUE TITLE
[BUG] Workflow page doesn't display correctly

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/flyte#3611]
### Describe the bug

it happens when I click previous page button

<img width="1867" alt="image" src="https://user-images.githubusercontent.com/37936015/233511389-3efc11f9-22bc-43f7-b92f-b8a03eeaf25b.png">

<img width="811" alt="image" src="https://user-images.githubusercontent.com/37936015/233511766-580c1231-79fc-4ef3-8a6e-3389bafca8a5.png">

### Expected behavior

go to the workflow page

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
cc @jsonporter

**Comment by eapolinario** [comment]
@pingsutw , can you confirm which version of Flyte you're running? This used to be a problem in one of the 1.4.x releases, but was supposed to be fixed in 1.5. I can't repro on the dev cluster nor on the latest sandbox.

**Comment by pingsutw** [comment]
I used flyteconsole v1.4.3. I just tested it with v1.6.2, and it's working fine. Thanks @eapolinario

**Comment by pingsutw** [comment]
fixed in v1.4.3
