### ISSUE TITLE
[BUG] Setting service_account_name in task PodTemplate does not work

### ISSUE THREAD

**Issue by hamersaw** [flyteorg/flyte#3613]
### Describe the bug

Creating a task with the definition:
```
    @task(
        pod_template=PodTemplate(
            pod_spec=V1PodSpec(
                service_account_name="trainer-service",
                containers=[],
    )
```
attempts to manually set the service account of the k8s `Pod` to `trainer-service`. However, the result is that Flyte overrides this variable, setting the service account to 'default' (by default).

This seems to be because the `PodPlugin` always overrides the `ServiceAccount` [in this logic](https://github.com/flyteorg/flyteplugins/blob/46796b6666281cf3ebbef6fbf41f49f7da3cfe58/go/tasks/plugins/k8s/pod/plugin.go#L131). However, previous implementation first checked if the `ServiceAccount` [was empty first](https://github.com/flyteorg/flyteplugins/blob/46796b6666281cf3ebbef6fbf41f49f7da3cfe58/go/tasks/pluginmachinery/flytek8s/pod_helper.go#L87-L89). The latter seems to be the correct implementation.

### Expected behavior

Users should be able to override the k8s `Pod` service account using the `PodTemplate`.

### Additional context to reproduce

Create a task with a service account, run it, and note the manually set service account is overridden.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Kota-Karthik** [comment]
Hello @samhita-alla 
I want to solve this issue
so kindly assign me this!!

**Comment by Vishalk91-4** [comment]
@samhita-alla, can you please assign this issue to me

**Comment by samhita-alla** [comment]
Are any of working on creating a PR for this issue? @Kota-Karthik @Vishalk91-4

**Comment by samhita-alla** [comment]
hey @hampusrosvall, please feel free to work on it. i'm gonna assign it to you. :)
