### ISSUE TITLE
[BUG] Failing to write to etcd (large object sizes) leaves workflow in non-terminal phase

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#363]
**Describe the bug**
When seeing this in propeller logs

```
msg:Failed to update workflow. Error [etcdserver: request is too large]
```

and looking at Flyte console, it seems that the workflow is left in a Failing state.

**Expected behavior**
The workflow should be in a failed state, not failing.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [x] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
1. Create a workflow that has a dynamic task.
2. Generate lots of tasks in your dynamic task, with each subtask taking primitive input values that are enormous, like 1MB each.
3. Look at propeller logs.

**Screenshots**

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [x] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**
NA

**Comment by kumare3** [comment]
This has been tested and will be merged soon
