### ISSUE TITLE
[BUG] Launch plan icon doesn't display correctly

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/flyte#3641]
### Describe the bug

I use latest flyteConsole
To reproduce, go to execution detail page, and click previous page button. 

<img width="239" alt="image" src="https://user-images.githubusercontent.com/37936015/236353303-1fa90200-a7bd-4075-a5aa-b498e8186ac4.png">
<img width="220" alt="image" src="https://user-images.githubusercontent.com/37936015/236353370-e0c7bb23-4fe5-4d6b-b680-366e4cf50faf.png">

correct one:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/37936015/236353676-d59b0d74-fd37-4839-943a-c384d2e1e2f0.png">

### Expected behavior

display correctly

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by jsonporter** [comment]
fixed with https://github.com/flyteorg/flyteconsole/pull/734
