### ISSUE TITLE
[BUG] Single task executions should not default to a node execution deadline of 24 hours

### ISSUE THREAD

**Issue by jeevb** [flyteorg/flyte#3642]
### Describe the bug

It is not clear if this is a bug, or is intended for a good reason. Currently, single task executions receive a default hard coded timeout of 24 hours: https://github.com/flyteorg/flyteadmin/blob/950ad1522aa8697777b86bb39e5df73eaf64e530/pkg/manager/impl/util/single_task_execution.go#L29

As such, they do not respect the default deadlines specified at the platform level, or the timeout specified at the task level in Flytekit.

### Expected behavior

Single task executions do not timeout by default at 24 hours, and respect the task's timeout or the platform node execution deadline.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
ohh this is not intended and seems to be a complete miss, unless cc @katrogan / @EngHabu do you folks know?
