### ISSUE TITLE
[BUG] No kubeconfig for flytectl demo cluster

### ISSUE THREAD

**Issue by tekumara** [flyteorg/flyte#3645]
### Describe the bug

```
❯ flytectl demo start 
INFO[0000] [0] Couldn't find a config file []. Relying on env vars and pflags. 
W0507 10:37:51.431316   66838 loader.go:221] Config not found: /home/compute/.flyte/k3s/k3s.yaml
🧑‍🏭 Bootstrapping a brand new flyte cluster... 🔨 🔧
🐋 Going to use Flyte v1.5.0 release with image cr.flyte.org/flyteorg/flyte-sandbox-bundled:sha-bc521dac6f0dc6e1942efa6447611cd3354540c4 
🐋 pulling docker image for release cr.flyte.org/flyteorg/flyte-sandbox-bundled:sha-bc521dac6f0dc6e1942efa6447611cd3354540c4
🧑‍🏭 booting Flyte-sandbox container
Waiting for cluster to come up...
Waiting for cluster to come up...
Waiting for cluster to come up...
Waiting for cluster to come up...
Waiting for cluster to come up...
Waiting for cluster to come up...
Waiting for cluster to come up...
W0507 10:38:10.078019   66838 loader.go:221] Config not found: /home/compute/.flyte/k3s/k3s.yaml
W0507 10:38:10.078495   66838 loader.go:221] Config not found: /home/compute/.flyte/k3s/k3s.yaml
Error: open /home/compute/.flyte/k3s/k3s.yaml.lock: permission denied
{"json":{},"level":"error","msg":"open /home/compute/.flyte/k3s/k3s.yaml.lock: permission denied","ts":"2023-05-07T10:38:10Z"}
```

```
❯ cat ~/.flyte/k3s/k3s.yaml
cat: /home/compute/.flyte/k3s/k3s.yaml: No such file or directory

❯ ll ~/.flyte/k3s/
total 0
lrwxrwxrwx 1 root root 32 May  7 10:38 k3s.yaml -> /var/lib/flyte/config/kubeconfig
```

### Expected behavior

_~/.flyte/k3s/k3s.yaml_ is created by `flytectl demo start`

### Additional context to reproduce

The host is ubuntu linux

```
❯ flytectl version
{
  "App": "flytectl",
  "Build": "bd6b856",
  "Version": "0.6.36",
  "BuildTime": "2023-05-07 10:43:00.839982826 +0000 UTC m=+0.029162480"
}%       
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by tekumara** [comment]
So it turns out I had `KUBECONFIG=/home/compute/.flyte/k3s/k3s.yaml` set when running `flytectl demo start` ... and unsetting this worked ...  🤔

**Comment by tekumara** [comment]
Even when it succeeds, `~/.flyte/k3s/` is owned by root, and `~/.flyte/k3s/k3s.yaml` is an invalid symlink (see the issue description).

**Comment by tekumara** [comment]
So it turns out I had `KUBECONFIG=/home/compute/.flyte/k3s/k3s.yaml` set when running `flytectl demo start` ... and unsetting this at least means the cluster starts ... 

However, `~/.flyte/k3s/` is owned by root, and `~/.flyte/k3s/k3s.yaml` is an invalid symlink (see the issue description).  So I don't have a valid kubeconfig I can use to hit the cluster from the host.

**Comment by eapolinario** [comment]
@tekumara , can you use the kubeconfig file under `~/.flyte/sandbox/kubeconfig`?

**Comment by tekumara** [comment]
Thanks @eapolinario that works!

Any reason why ~/.flyte/k3s/k3s.yaml is being created as an invalid symlink?

**Comment by eapolinario** [comment]
@tekumara , as you can probably guess, under the covers the flyte demo cluster runs k3s in a container. As part of its installation process, k3s writes a kubeconfig file somewhere, it's just in our case, instead of using the [default](https://docs.k3s.io/cluster-access) we [chose](https://github.com/flyteorg/flytectl/blob/bd6b85605f49ff4877484edd69942ca72f4e19dd/pkg/sandbox/start.go#L426C1-L428) a different path.

If you exec into the docker container you'll see that it is valid, e.g.:
```
❯ docker exec -it flyte-sandbox cat /var/lib/flyte/config/kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: ...
    client-key-data: ...
```

**Comment by tekumara** [comment]
Oh I see, I was only expecting to see a single kubeconfig file created on the host (ie: `~/.flyte/sandbox/kubeconfig`) rather than two (one of which, `~/.flyte/k3s/k3s.yaml` doesn't work on the host so isn't useful).

**Comment by eapolinario** [comment]
got it. Unfortunately, this file is required by k3s.

**Comment by eapolinario** [comment]
Closing this for now. Let us know if you need any more help or clarification related to this.
