### ISSUE TITLE
[Plugin] Remove print in SQLAlchemyTaskExecutor

### ISSUE THREAD

**Issue by sofianelounici** [flyteorg/flyte#3651]
## Problem

When using a SQLAlchemyTask, there are two prints which are annoying (especially when running multiple queries and we want light logging):

https://github.com/flyteorg/flytekit/blob/db7d1eb480cea24504d94419981859bfc9ef6c62/plugins/flytekit-sqlalchemy/flytekitplugins/sqlalchemy/task.py#L129

https://github.com/flyteorg/flytekit/blob/db7d1eb480cea24504d94419981859bfc9ef6c62/plugins/flytekit-sqlalchemy/flytekitplugins/sqlalchemy/task.py#L132

## Solution

Possibility to remove them ? Are they useful ?

**Comment by eapolinario** [comment]
@sofianelounici , feel free to submit a PR, this seems like an oversight in the original work. If anything these log messages should use the default logger (and possibly be an `info`).

**Comment by wirthual** [comment]
Hi,
I try to help out with this issue.

With the default logger, do you mean the root logger?

**Comment by eapolinario** [comment]
@wirthual , thanks for the PR. I meant flytekit's [root logger](https://github.com/flyteorg/flytekit/blob/06fffc786edfe9d4cbb891d6c0e14181a5823998/flytekit/loggers.py#L18).

**Comment by wirthual** [comment]
I see, so should I do a 

```python
from flytekit.loggers import logger
```

or simply a
```python
logger = logging.getLogger("flytekit")
```

**Comment by eapolinario** [comment]
The former, please.

**Comment by wirthual** [comment]
Pushed the changes just now

**Comment by cosmicBboy** [comment]
fixes https://github.com/flyteorg/flytekit/pull/1651
