### ISSUE TITLE
[BUG] error: unknown command "kubectl" for "kubectl"

### ISSUE THREAD

**Issue by tekumara** [flyteorg/flyte#3653]
### Describe the bug

```
❯ flytectl demo exec -- k3s kubectl
error: unknown command "kubectl" for "kubectl"
```

### Expected behavior

No error

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@tekumara , this seems to be a k3s bug (e.g.) https://github.com/k3s-io/k3s/issues/231 and https://github.com/k3s-io/k3s/issues/1349.

Can you expand on your use case?

**Comment by tekumara** [comment]
Hi @eapolinario I wanted to inspect the pods on the cluster during `flytectl demo start`, but Yee pointed out I can do this from the host, so happy to close this. Thanks!
