### ISSUE TITLE
Provide ability to set a max limit on number of executors that can be set by user.

### ISSUE THREAD

**Issue by migueltol22** [flyteorg/flyte#366]
**Motivation: Why do you think this is important?**
A user can specify an arbitrarily high number of executors in spark task. From the maintainer perspective it should be possible to add safeguards to avoid a user setting a very large number of executors.

**Goal: What should the final outcome look like, ideally?**
Configuration option to specify max limit of executors in spark plugin. 

**Describe alternatives you've considered**

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [x] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Additional context**

**Is this a blocker for you to adopt Flyte**
Please let us know if this makes it impossible to adopt Flyte

**Comment by kumare3** [comment]
@migueltol22 it seems you have a PR in progress here, any updates?

**Comment by hamersaw** [comment]
closing as unplanned.
