### ISSUE TITLE
[flytekit feature] Support Pandas 2 

### ISSUE THREAD

**Issue by tekumara** [flyteorg/flyte#3680]
### Motivation: Why do you think this is important?

I'd like to use Pandas 2 in my tasks because it has a lot of [performance improvements](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html#performance-improvements).

But I'm limited to <2 because Flytekit pins to [pandas>=1.0.0,<2.0.0](https://github.com/flyteorg/flytekit/blob/35e52ef/setup.py#L34).

### Goal: What should the final outcome look like, ideally?

I can use Pandas 2 in my tasks.

### Describe alternatives you've considered 

Not using Pandas 2.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
I agree with this, but I think we should take this opportunity to remove a direct dependency on pandas itself

**Comment by pingsutw** [comment]
fixed it here. https://github.com/flyteorg/flytekit/pull/1818
