### ISSUE TITLE
[Housekeeping] go-gormigrate/gormigrate is abandoned

### ISSUE THREAD

**Issue by honnix** [flyteorg/flyte#3684]
### Describe the issue

flyteadmin uses https://github.com/go-gormigrate/gormigrate for database migration, and unfortunately this repo has been abandoned by the author (see https://github.com/go-gormigrate/gormigrate/issues/180#issuecomment-1530375183 for the reason).

We might want to take some action to mitigate this.

### What if we do not do this?

It is probably OK for now because the features we use in flyteadmin should be minimum and there doesn't seem to be any urgent bug fixes, etc. But in the long run, it is not sustainable to depend on an unmaintained lib for critical things like DB migration.

### Related component(s)

flyteadmin

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by avakarev** [comment]
Hi @honnix,
JFYI gormigrate is not abandoned, it has active maintainers now.

**Comment by honnix** [comment]
@avakarev That is really good to know. Thank you so much for taking over the maintenance!
