### ISSUE TITLE
Support latest vaex-core

### ISSUE THREAD

**Issue by tekumara** [flyteorg/flyte#3685]
### Motivation: Why do you think this is important?

To support efficient installation in python 3.10.

flytekitplugins-vaex pins to [vaex-core>=4.13.0,<4.14](https://github.com/flyteorg/flytekit/blob/45c0110/plugins/flytekit-vaex/setup.py) which doesn't have [wheels for python 3.10](https://pypi.org/project/vaex-core/4.13.0/#files).

This means we need to build wheels ourselves to use flytekitplugins-vaex on python 3.10.

vaex-core 4.16.1 [has wheels](https://pypi.org/project/vaex-core/4.16.1/#files) for python 3.10

### Goal: What should the final outcome look like, ideally?

flytekitplugins-vaex installs from wheels.

### Describe alternatives you've considered 

Building our own wheels.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pingsutw** [comment]
@tekumara Feel free to open a pr

**Comment by TechWizard9999** [comment]
😊 "I'd be delighted to work on this issue, @tekumara ! Could you please assign it to me?"

**Comment by pingsutw** [comment]
Assigned to you, thanks!

**Comment by samhita-alla** [comment]
@TechWizard9999, are you working on creating a PR for this issue?

**Comment by davidmirror-ops** [comment]
So is this fixed with [#1942](https://github.com/flyteorg/flytekit/pull/1942)?
