### ISSUE TITLE
[BUG] Mapped task overwrite the parent map task startedAt timestamp

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#3702]
### Describe the bug

For map task  the startedAt timestamp is getting overwritten for each mappedTask
We get startedEvent for each mapped task https://github.com/flyteorg/flyteadmin/blob/master/pkg/repositories/transformers/task_execution.go#L44
and hence we overwrite the task startedAt time

### Expected behavior

startedAt timestamp shouldnot change 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pmahindrakar-oss** [comment]
@hamersaw  I was [testing my changes](https://github.com/flyteorg/flyteadmin/pull/567/files) and couldn’t reproduce and hence dug deeper into this
https://github.com/flyteorg/flyteadmin/blob/master/pkg/repositories/transformers/task_execution.go#L401-L406
This code assumes that once a task is in RUNNING state it remains in RUNNING state or ends up in  one of TERMINAL states

>These cases shouldn't be exhibiting different behavior than any regular task.
Correct

But there are cases where  it can happen that the task is RUNNING state for some time and then goes to WAITING_FOR_RESOURCES and back to RUNNING. This cases causes the above code to overwrite the startedAt timestamp due to the peculiar state check.
My PR adds nil check on the startedAt to avoid this overwrite.
Let me know what you think

**Comment by hamersaw** [comment]
Oh sure, the `WAITING_FOR_RESOURCES` phase is set if any of the subtasks are waiting for resources. Thanks for the clarification!
