### ISSUE TITLE
[BUG] Parent dynamic task registered in non-fast mode, child subtask registered in fast mode. Child subtask executes in non-fast mode.

### ISSUE THREAD

**Issue by redartera** [flyteorg/flyte#3703]
### Describe the bug

The task `foo` is registered in fast mode, while `bar` is registered in non-fast mode.
The subtask `foo` is executed with `pyflyte-execute` rather than `pyflyte-fast-execute` when called from within `bar`, causing `ModuleNotFoundError`.

```python
# a.py
@task
def foo(x: int) -> int:
  return x

# This task foo was registered in fast registration
 
# b.py

@reference_task(
  project="flytesnacks",
  domain="development",
  name="a.foo",
  version="v0.1.0",
)
def foo(x: int) -> int:
  ...

@dynamic(image="...")
def bar(x: int) -> int:
  for i in range(10):
   foo(x)

# This task bar was registered in non-fast mode
```

### Expected behavior

`foo` should be executed with `pyflyte-fast-execute`.

### Additional context to reproduce

flytekit==1.4.2 and using `flyte-binary`

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
cc @wild-endeavor this should not be happening right?

**Comment by eapolinario** [comment]
Currently reference tasks cannot be used in `@dynamic`.  

In fact, you should be seeing [this message](https://github.com/flyteorg/flytekit/blob/d7060cc13be711ea37773435abcc7fbca6c3e4df/flytekit/core/python_function_task.py#L223-L227) in the logs of the dynamic task if you try to execute a reference task inside a dynamic task.

**Comment by eapolinario** [comment]
@redartera , can you expand on the example you're using to repro this issue?

**Comment by redartera** [comment]
> Currently reference tasks cannot be used in `@dynamic`.
> 
> In fact, you should be seeing [this message](https://github.com/flyteorg/flytekit/blob/d7060cc13be711ea37773435abcc7fbca6c3e4df/flytekit/core/python_function_task.py#L223-L227) in the logs of the dynamic task if you try to execute a reference task inside a dynamic task.

@eapolinario I have been getting this error message this morning when adding `container_image=` to the `@task` decorator for `foo` in an attempt to get rid of `ModuleNotFoundError`.

Let me expand and update you on this

**Comment by redartera** [comment]
I tried to reproduce this locally multiple ways against the flytectl sandbox, but I have been getting the expected error
`Reference tasks are currently unsupported within dynamic tasks`, please disregard this, I was likely having a different issue.
