### ISSUE TITLE
[UI Feature] Domain tabs do not persist 

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyte#3706]
### Motivation: Why do you think this is important?

Users reported that when switching between nav items (workflows, tasks, launchplans, etc) the domain state is not persisted. 

### Goal: What should the final outcome look like, ideally?

That the current selected domain is persisted when users interact with the nav.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by bstadlbauer** [comment]
We would really appreciate this! Have heard this from a lot of our users :-)

**Comment by jsonporter** [comment]
@bstadlbauer - we're picking it up this sprint 👍
