### ISSUE TITLE
[Housekeeping] Remove `storage` from `flytekit` and helm values

### ISSUE THREAD

**Issue by fg91** [flyteorg/flyte#3728]
### Describe the issue

* In [`flytekit.Resources`](https://github.com/flyteorg/flytekit/blob/eafcc820303367749e63edc62190b9153fd6be5e/flytekit/core/resources.py#L32) one can request `storage` which, however, doesn't have any effect.

    This is also acknowledged in the docstring:
    
       .. note::

        Persistent storage is not currently supported on the Flyte backend.
        
        
* The task default resource and limits [also allow setting `storage`](https://github.com/flyteorg/flyte/blob/0cd5ec1b7d6b04211b3ff6d59e717c8536556891/charts/flyte-core/values.yaml#L565) which doesn't have an effect either. Ephemeral storage defaults which would work cannot be configured on the platform side.

The `storage` arg should be deprecated from `flytekit.Resources` and from the helm values. Ephemeral storage defaults and limits should be configurable in the helm values.

See [discussion in slack](https://flyte-org.slack.com/archives/C04NJPLRWUX/p1684153008272579).

### What if we do not do this?

Users might try requesting storage and would then wonder why there is no effect.

### Related component(s)

flytekit, helm chart

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by fg91** [comment]
@Future-Outlier I saw that you tackled part of this in https://github.com/flyteorg/flytekit/pull/2078, thanks a lot! 🙏 
Would you be willing to also take a look at the helm chart so that we can close this issue? No problem if not!

**Comment by Future-Outlier** [comment]
> @Future-Outlier I saw that you tackled part of this in https://github.com/flyteorg/flytekit/pull/2078, thanks a lot! 🙏 
> 
> Would you be willing to also take a look at the helm chart so that we can close this issue? No problem if not!

I can try to take a look, thank you for giving me this chance, will let you know if I face problems!

**Comment by Future-Outlier** [comment]
I think it is right to delete the `storage` arg in the helm chart.
We can see it here to prove that the place you mention is correct.
https://pkg.go.dev/github.com/lyft/flyteadmin@v0.3.37/pkg/runtime/interfaces#TaskResourceConfiguration
Thank you!
