### ISSUE TITLE
[Housekeeping] flytekit to support generic collections in 3.9+

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#3745]
## Support builtins generics

Implement https://peps.python.org/pep-0585/ basically, so that in python 3.9+ users don't have to do `typing.List` and can just use `list`

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
Closing this issue for two reasons: (1) this already works correctly in pyton 3.9+, and (2) the error being bubbled up is easily resolved with a google search.
