### ISSUE TITLE
[Core feature] Wrap ImageSpec packages in quotes

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3761]
### Motivation: Why do you think this is important?

When using `ImageSpec` and `pyflyte build`, specifying packages like `transformers[torch,deepspeed]>=4.28.1,<5` will fail during the build step will fail and to fix it, the user needs to wrap the package dep in quotes `'transformers[torch,deepspeed]>=4.28.1,<5'`.

### Goal: What should the final outcome look like, ideally?

To improve the ergonomics of this feature, packages deps should automatically be wrapped in quotes by flytekit.

### Describe alternatives you've considered 

Keeping the status quo, which would be inconvenient for end users.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by mao3267** [comment]
Hi, @cosmicBboy. I tried the code below by `pyflyte run --remote`, and it successfully built an image and completed the workflow. Has this issue already been resolved? 
```py
from flytekit import ImageSpec, task, workflow
import transformers
from transformers import pipeline
from typing import NamedTuple

imagespec = ImageSpec(
    name="my_image",
    packages=["transformers[torch,deepspeed]>=4.28.1,<5"],
    registry="localhost:30000",
).force_push()

test_output = NamedTuple("test_output", [("output", str), ("version", str)])


@task(container_image=imagespec)
def text_generation_test() -> test_output:
    pipe = pipeline("text-generation", model="gpt2")
    return test_output(
        output=pipe("Hello, What's your name?")[0]["generated_text"],
        version=transformers.__version__,
    )


@workflow
def wf():
    text_generation_test()
```
