### ISSUE TITLE
[Core feature] Support configuring pip index url with the image spec feature

### ISSUE THREAD

**Issue by mucahitkantepe** [flyteorg/flyte#3765]
### Motivation: Why do you think this is important?

We have some private common libraries that we want to access in our Flyte workflows using image spec feature. To be able to use imageSpec feature that was highlighted with Flyte 1.6 release, we need image spec feature to support configuring pip index url. envd does support this, and it should be fairly small change. 

### Goal: What should the final outcome look like, ideally?

```python
image_spec=ImageSpec(
    base_image="some-base-image:latest
     packages=["a-private-library==1.6.0"
     pip_index="https://private-pip-index/simple"
)

```

and the generated build.envd file would look like this

```python

# syntax=v1

def build():
...
    config.pip_index(url = "https://private-pip-index/simple")
...
```

### Describe alternatives you've considered 

I think it's pretty straightforward.

###  Propose: Link/Inline OR Additional context 

envd has built-in support for this, as shown in the main example in their readme

https://github.com/tensorchord/envd#create-an-envd-environment

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@mucahitkantepe , this is a great idea and looks simple enough to warrant a first contribution! Feel free to open the PR and tag me or someone on the core team to review it.

**Comment by Future-Outlier** [comment]
I am interested at it, if possible, please assign to me, thank you.
