### ISSUE TITLE
[UI Feature] Extra lines in Graph View ?

### ISSUE THREAD

**Issue by tsheiner** [flyteorg/flyte#3767]
### Motivation: Why do you think this is important?

This is reported by [Felix Ruess in Flyte Slack](https://flyte-org.slack.com/archives/CP2HDHKE1/p1686301605941289).

Felix Ruess
Does anyone know why Flyte workflows always seem to have unnecessary connections between tasks?
Like A -> B -> C, but also A -> C

Dan Rammer (hamersaw)
can you elaborate? maybe a code example, i'm really not following. this is just the transitive property, if c depends on b and b depends on a then c will always execute after a right?

Felix Ruess
Yes, it is just a bit annoying to see that extra line in the DAG visualization...
Would look much cleaner if the transitive dependency would not be shown

Dan Rammer (hamersaw)
oh sure, my understanding is that the UI displays the exact task-level dependencies. for example:
```@task
def task_a() -> (int, int):
    # ...

@task
def task_b(m: int) -> int:
    # ...

@task
def task_c(n: int, l: int) -> int:
    # ...

@workflow
def wf() -> int:
    x, y = task_a()
    z = task_b(m=x)
    return task_c(n=y, l=z)
```

would create exactly what you mentioned. is that not the case? or do you want to UI to automatically remove the a->c line because it's redundant?

Felix Ruess
yeah, would be nice if the UI would not show the redundant lines...
not sure if they are needed in the backend...

Ketan (kumare3)
Why is it redundant

Ketan (kumare3)
I guess the lines are showing where data feeds from

Ketan (kumare3)
Cc 
[@Tim Sheiner](https://flyte-org.slack.com/team/U04UC024F3Q)

Dan Rammer (hamersaw)
IMO it would be more confusing to remove the line.

Felix Ruess
simple example where the extra lines are a bit confusing:

![train_workflow](https://github.com/flyteorg/flyte/assets/839128/1c641c03-6955-4caf-b661-6b92b5869cc5)

Tim Sheiner
[@Felix Ruess](https://flyte-org.slack.com/team/U03N8LN2SHX)
 have I correctly labeled the 'extra' lines in your example?
![extraLines](https://github.com/flyteorg/flyte/assets/839128/f3eaa842-31d2-40e5-bbd5-692c494fd679)

Felix Ruess
yes

### Goal: What should the final outcome look like, ideally?

TBD, this ticket is about investigating if diagram view could use refinement, understanding why Felix thinks lines are extra, but Dan thinks they are helpful. 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
closing as externally discussed that his most accurately reflects task dependencies.
