### ISSUE TITLE
[Core feature] Configuration containing secrets should use Opaque Secrets over ConfigMaps

### ISSUE THREAD

**Issue by EternalDeiwos** [flyteorg/flyte#3769]
### Motivation: Why do you think this is important?

The way secrets are handled in deployment cause several headaches:

1. Secrets are supplied in plain text in Helm configuration; this is a problem when deployments and Helm `values.yaml` contents are stored in a git repository and deployed using an external tool.
1. There are no existing configuration to pull configuration and/or secrets from existing configmaps or secrets; this makes it difficult inject secrets and configuration from a central vault (e.g. Hashicorp Vault).
1. Potentially long-lived secrets are being kept in ConfigMaps instead of Opaque Secrets; this is generally not idiomatic even if the security of the two option were roughly equivalent.

This is creating a significant barrier to me deploying a _test_ instance in our environment (bare metal K8s).

### Goal: What should the final outcome look like, ideally?

I would like to supply names of existing secrets to the Helm chart and/or Kustomization without directly exposing secrets in configuration files or Helm values. This will allow incremental improvement of my deployment configuration without needing to expose secrets directly as part of the deployment.

### Describe alternatives you've considered 

I've been working on a Kustomization with significant patching to move existing configmaps into secrets... however I am considering a completely parallel deployment because writing the patches takes more time than editing the original files.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by jeevb** [comment]
@EternalDeiwos: Do you already have a list of long-lived secrets are incorrectly stored in a configmap right now?

**Comment by EternalDeiwos** [comment]
@jeevb the ones that come to mind based on my currently limited experimentation are:

- `client_id` and `client_secret` for OIDC.
- S3 credentials
- Postgres credentials &mdash; this is already read from a mounted secret, which is ideal, however this could use some better documentation for providing that secret externally.

Other than that, the same would apply to literally anything in the configuration that constitutes a secret or externally issued credential.  One would need to scan through all existing deployment configuration to check that.

Also, another caveat is that I have been looking at the Kustomize scripts not necessarily the Helm chart output &mdash; which I understand the project is moving away from? Unsure of the precise state of the Helm charts but based on conversations on Slack it is clearly different to what I understood.

Will provide further feedback as soon as I can get back to this.

**Comment by jeevb** [comment]
The linked draft [PR](https://github.com/flyteorg/flyte/pull/3807) should cover most of the use cases you have outlined, with the exception of `clientId`. Can you take a look?

**Comment by EternalDeiwos** [comment]
Thanks @jeevb, I can confirm that this is working like it should. The way you've implemented it means that anything important is in a secret and the existing stuff (defaults etc.) can be in a CM.
