### ISSUE TITLE
[Feature] UI Waterfall / Timeline view

### ISSUE THREAD

**Issue by schottra** [flyteorg/flyte#377]
[Spec and UI Mocks](https://docs.google.com/document/d/1m2hh9xSiwezqM5IBgusj6gunjuWIAm-1e5ICAsFuFjY/edit?usp=sharing)

While optimizing or debugging a workflow, users may wish to view the start times and durations of various tasks in relation to each other and the workflow as a whole.
This is often referred to as a Waterfall or Timeline diagram. A good example would be the Performance graphs in the developer tools of a modern web browser.

This type of view will typically show time on the X axis, and a set of bars stack along the Y axis. The left edge of each bar indicates when a task started, and the right edge indicates when it ends. 

Using a timeline view, it's much easier to see issues with parallelism and data dependencies. If no bars overlap, there may be an opportunity to optimize your workflow.

This view will be added as a third tab on the Execution details page, alongside the Nodes and Graph tabs.

**Comment by anrusina** [comment]
It is already implemented and can be found in [Release - v0.53.0](https://github.com/flyteorg/flyteconsole/releases/tag/v0.53.0). The only missing part is search for which we have a separate task created.
