### ISSUE TITLE
[BUG] ImageSpec not leveraging build cache for basic example

### ISSUE THREAD

**Issue by jeevb** [flyteorg/flyte#3775]
### Describe the bug

Repeated invocations of `pyflyte run` involving `ImageSpec` rebuild python and apt dependencies from scratch instead of leveraging cache.

### Expected behavior

When an `ImageSpec`definition is not updated, image rebuilds should reuse cached layers where possible to speed up build times.

### Additional context to reproduce

1. Create a script, `wf.py` with the following contents:
```
from flytekit import task, workflow, ImageSpec

image = ImageSpec(
    packages=["smart-open[gcs]"],
    apt_packages=["git"],
)


@task(container_image=image)
def my_task() -> str:
    return "hello, world!"


@workflow
def my_wf() -> str:
    return my_task()
```

2. Run the following command multiple times:
```
pyflyte run --remote wf.py my_wf
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
We're not leveraging https://envd.tensorchord.ai/teams/cache.html yet, right?

**Comment by jeevb** [comment]
> We're not leveraging https://envd.tensorchord.ai/teams/cache.html yet, right?

Not afaict, but the link is for remote cache. I'm surprised daemon-local cache on the local buildkit builder doesn't work.

**Comment by RichhLi** [comment]
That's odd. I'm not running into the same issue. Are you using Docker on Linux? I noticed that when I use Docker on Mac I run into issues. For example, the base image won't even cache on Mac if the image size is too large.

**Comment by kumare3** [comment]
closing this as this has been fixed
