### ISSUE TITLE
[BUG] Error with `torch.nn.Module` and `flytekit` version >1.5.0.

### ISSUE THREAD

**Issue by constanceferragu** [flyteorg/flyte#3783]
### Describe the bug

Flyte throws a warning and error with `torch.nn.Module` and `flytekit` version >1.5.0. 
Flyte uses `PickleFile` with type `nn.Module` as default when importing tasks/workflows. When registering, it does not recognize the type as `nn.Module` but as `PickleFile` - throws an error because the types aren't matching. 

Example of the error:
```
# a.py
from flytekit import task

@task
def foo() -> int:
    return 2

------------------------------------------------------------------------------

# b.py
from flytekit import task
from torch import nn

@task
def bla() -> nn.Module:
    return nn.Module()
```

Warning message: 
```
WARNING  {"asctime": "2023-06-15 17:40:51,991", "name": "flytekit", "levelname": "WARNING", "message": "Unsupported Type <class 'torch.nn.modules.module.Module'> found,      
                                    Flyte will default to use PickleFile as the transport. Pickle can only be used to send objects between the exact same version of Python, and we strongly recommend                   
                                    to use python type that flyte support."}     
```
Error message: 
```
Error 0: Code: MismatchingTypes, Node Id: end-node, Description: Variable [model] (type [blob:<format:"PyTorchModule" > ]) doesn't match expected type [blob:<format:"PythonPickle" > metadata:<fields:<key:"python_class_name" value:<string_value:"Module" > > > ].
Error 1: Code: MismatchingTypes, Node Id: n1, Description: Variable [model] (type [blob:<format:"PythonPickle" > metadata:<fields:<key:"python_class_name" value:<string_value:"Module" > > > ]) doesn't match expected type [blob:<format:"PyTorchModule" > ].
```

### Expected behavior

Should be able to register. 

The culprit is most likely `if is_imported("torch")`: in `flytekit.core.type_engine`

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by zeryx** [comment]
hey @constanceferragu! We love using torch modules.  The warning message just indicates that flyte will serialize the module with cloud pickle; which is totally fine to do! I have a few examples on my side with torch.nn.Module or torch.nn.Sequential being output types of tasks and workflows.

Are you able to share your dependencies and image (Dockerfile?) that you registered this task with? 
Are you running this within a Flyte Cluster or a Sandbox?

**Comment by constanceferragu** [comment]
Hey @zeryx, I've updated the description of the bug and hopefully made it more clear. `PyTorchModuleTransformer` should be used - it supports serializing and deserializing torch modules.

**Comment by Future-Outlier** [comment]
Hey @constanceferragu , I just test the scenarios you mentioned.
```
from flytekit import task
from torch import nn

@task
def bla() -> nn.Module:
    return nn.Module()
```
```
from flytekit import task
from torch import nn

@task
def bla() -> nn.Transformer:
    return nn.Transformer()

```
Both the tasks work correctly by pyflyte register.
Can you give me more details to help you?

**Comment by constanceferragu** [comment]
Hey @Future-Outlier, the naming of the files (`a.py` and `b.py` is important). Did you include this in your tests ?

**Comment by Future-Outlier** [comment]
![image](https://github.com/flyteorg/flyte/assets/76461262/999aea93-0610-44f9-ac2b-4e466f0381f8)
![image](https://github.com/flyteorg/flyte/assets/76461262/5a36ab2a-8073-4cbd-84eb-d13ef176af33)
Can you provide a screenshot or video?
The video could be better.
I've tried to reproduce it, but it doesn't work.

**Comment by eapolinario** [comment]
Closing this as we couldn't repro the issue.
