### ISSUE TITLE
[Docs] Simplify flytesnacks examples build and structure

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3786]
### Description

The purpose of this issue is to make it easier to contribute and maintain flytesnacks examples. This issue involves a few sets of changes:

### Restructure and simplify flytesnacks

Flatten the directory structure so that sets of examples that share dependencies and can logically be grouped together are in a project directory. Basically any directory that contains a Dockerfile and requirements.txt would be a project (Note: we would migrate these projects to use ImageSpec). An example layout would be:

```
flytesnacks/
    core
    aws_athena
    aws_batch
    etc...
```

Where each directory is essentially an isolated flyte project that defines its own dependencies

### Decouple documentation structure from example directory structure

Currently, we use [sphinx gallery](https://sphinx-gallery.github.io/stable/index.html) for examples. This introduces an opinionated structure of how to organize the docs, such that the directory structure of `cookbook` needs to follow a certain structure for the docs to correctly render.

In this issue we'll decouple these two things: the docs should define the structure via the sphinx conventions, and point to various example directories to get content.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
@cosmicBboy, I'm thinking of working on adding ImageSpec to the flytesnacks examples. Should I proceed with it right away or after you're done with this issue? Here's the GitHub issue for reference: https://github.com/flyteorg/flyte/issues/3790.
