### ISSUE TITLE
[BUG] Can't launch workflow when defining `k8sServiceAccount` and `assumableIamRole`

### ISSUE THREAD

**Issue by SuperBo** [flyteorg/flyte#3789]
### Describe the bug

After registering a workflow with following command:
`flytectl register files -d development -p flytesnacks --archive flyte-package.tgz --version "0.0.8" --k8sServiceAccount flyte-user --assumableIamRole arn:aws:iam::<acount_name>:role/<role_name>`.

I can't launch that workflow, whenever I tried to launch that workflow, they returned this error:

`Request failed with status code 500 failed to create workflow in propeller FlyteWorkflow.flyte.lyft.com "atsv5q7rp97m5fdg5kqs" is invalid: [metadata.annotations: Invalid value: "": name part must be non-empty, metadata.annotations: Invalid value: "": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName', or 'my.name', or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')]`

### Expected behavior

Launch Workflow successfully

### Additional context to reproduce

1. pyflyte init my_project
2. cd my_project
3. pyflyte --pkgs workflows package
4. flytectl register files -d development -p flytesnacks --archive flyte-package.tgz --version "0.0.1" --k8sServiceAccount flyte-user --assumableIamRole arn:aws:iam::<account>:role/<Role>
5. Execution workflow via Flyte admin or flytectl.

### Screenshots

![https://imgur.com/a/DlOYUG6](https://i.imgur.com/378Eksn.png)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
I'm able to repro this but now i'm wondering, what's the goal with this?  You want the pod created to have an annotation of
```
iam.amazonaws.com/role: arn:aws:iam::123123:role/my-role
```
What does this do?  I thought all iam roles went through service accounts these days or is that not the case?

**Comment by wild-endeavor** [comment]
```
flyteadmin:
  roleNameKey: "iam.amazonaws.com/role"
```
@SuperBo this needs to be added to the config.  it was missing so it was trying to mount the role with an empty string as the key part of the annotation.  we'll add this to the sample flyte configs.

**Comment by SuperBo** [comment]
> 

You are right, but I am in a process of testing whether I can use another IAM role other than the default one in service account for debug purpose.

This problem won't happen in production, I think
