### ISSUE TITLE
[Docs] Migrate all flytesnacks examples to use ImageSpec

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#3790]
### Description

Currently, when running Flyte tasks and workflows on the Flyte backend, developers need to build a custom Docker image if there are additional dependencies not included in the default flytekit Docker image.

To improve the developer experience, this issue aims to add an ImageSpec to all the flytesnacks examples. This will simplify the process and make it more convenient by eliminating the need to build custom Docker images for handling additional dependencies.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment]
We should figure out what our recommended pattern is for using `ImageSpec` @eapolinario @zeryx @pingsutw @wild-endeavor before we embark on this work.

**Comment by samhita-alla** [comment]
@cosmicBboy, should we still wait on this? Have we reached a decision on what we want to implement?

**Comment by samhita-alla** [comment]
this will be addressed as part of the documentation restructuring.
