### ISSUE TITLE
[BUG] Map Tasks when using min_success_ratio should fail registration if output isn't Optional #3542

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#3794]
### Describe the bug

Using a map task like this:
```python
@task
def some_task(inputs: typing.List[int]) -> int:
  ...

@workflow
def my_wf() -> typing.List[int]
  return map_task(some_task, min_success_ratio=0.5)(inputs=[1, 2, 3, 4])
```

if some of the items fail to process, the resulting output will have shorter length compared to the input list. This is confusing!

### Expected behavior

The task either fails to register because the output should have been `Optional[int]` or the map task should fail completely because it can't "correctly" produce the output..

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
Having to force the return type of the mapped function to be Optional to account for the fact that the return type of the `map_task(t, min_success_ratio=X)(...)` is `List[Optional[T]]` does not seem right. Instead we should detect the case where `min_success_ratio` is set and modify the interface of `map_task` to be list of optional.

We essentially changed the contract of `map_task` under the covers and we probably have users out there that will face this issue when they register workflows that use map tasks.

**Comment by eapolinario** [comment]
https://github.com/flyteorg/flytekit/releases/tag/v1.8.1 fixes this issue.
