### ISSUE TITLE
[Docs] Update the plugin setup guide

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#3799]
### Description

Our existing [plugin setup guide](https://docs.flyte.org/en/latest/deployment/plugins/index.html) provides instructions for the Flyte sandbox environment but does not cover the Flyte demo cluster. To address this issue, we need to:

- Install plugins on the demo cluster.
- Enhance the plugin setup guide by incorporating detailed, user-friendly instructions that are more explicit and comprehensive in nature.

Key points to ponder:

- Can plugins be installed on the demo cluster?
- Is the web API plugins guide necessary in light of Flyte agents' functionality?

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
@eapolinario, tagging you for visibility. Could you please address the questions mentioned in the description?

**Comment by kumare3** [comment]
I think this is important even @ByronHsu was not able to try it out quickly.
