### ISSUE TITLE
[BUG] pyflyte serialize --image doesn't handle image names

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#3800]
### Describe the bug

Specifying `--image name=<image_uri>` raises and error in a `pyflyte serialize` invocation:

```
Failed with Unknown Exception <class 'docker_image.reference.ReferenceInvalidFormat'> Reason: invalid reference format
```

`pyflyte package` can handle this format.

### Expected behavior

`pyflyte serialize` should have the same behavior as `pyflyte package`

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
will work on as part of https://github.com/flyteorg/flytekit/pull/1610/files
