### ISSUE TITLE
[Core feature] Add LaunchPlan Archive/Activate support via flytekit

### ISSUE THREAD

**Issue by samjeckert** [flyteorg/flyte#3804]
### Motivation: Why do you think this is important?

We're able to move most control functionality that was on flytectl to flytekit, but we are missing the capability for activating/archiving existing launchplans. To solve this, we use a hybrid system of both CLI and flytekit, which is a bit unwieldy. 

We're mostly concerned with managing active crons.

### Goal: What should the final outcome look like, ideally?

- Ability to get all launchplan versions for a given lp name
- Ability to deprecate a launchplan
- Ability to activate a launchplan

### Describe alternatives you've considered 

We use calls out to `flytectl` to fetchall, archive, and activate launchplans

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
hey @samjeckert this was added,
`pyflyte register ... --activate-launchplans`

**Comment by kumare3** [comment]
`pyflyte launchplan ... --deactivate`
