### ISSUE TITLE
[Housekeeping] Inconsistent treatment of project id param in flytectl

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#3806]
### Describe the issue

`flytectl update project --help `
shows `id` as a flag:

```
Flags:
...
      --id string               id for the project specified as argument.

```

However attempting to update a project with the id flag fails:
```
flytectl update project --id katrina-test                                                                                                                                                  <region:us-west-2>
Error: project id wasn't passed
```

and requires using the global `-p` flag instead

### What if we do not do this?

Poor DevX using the project noun in flytectl

### Related component(s)

flytectl

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by oliverhu** [comment]
Fixed in https://github.com/flyteorg/flytectl/pull/411/files @katrogan @eapolinario , ptal!
