### ISSUE TITLE
[BUG] Module 'PIL' has no attribute Image

### ISSUE THREAD

**Issue by Benjamintdk** [flyteorg/flyte#3813]
### Describe the bug

Attempting to use the [`ImageRenderer`](https://github.com/flyteorg/flytekit/blob/f17321385c192b2137efef69fc9207cd9fb14aa6/plugins/flytekit-deck-standard/flytekitplugins/deck/renderer.py#L66) from `Flyteplugins.deck.renderer` yields the following error at [this line](https://github.com/flyteorg/flytekit/blob/f17321385c192b2137efef69fc9207cd9fb14aa6/plugins/flytekit-deck-standard/flytekitplugins/deck/renderer.py#L79): "Module PIL has no attribute Image"

### Expected behavior

Don't expect the error to appear as PIL should have been imported at the top of the file.

### Additional context to reproduce

1. Install the library: `pip install flytekitplugins-deck-standard`
2. Import ImageRenderer: `from flytekitplugins.deck.renderer import ImageRenderer`
3. Create a task function as shown below:
```
@task
def func(png_path: str):
    ...
    png_file = PNGImageFile(path=png_path, remote_path=some_remote_path)
    flytekit.Deck("demo", ImageRenderer().to_html(png_file)) <--- error occurs here
    ...
```

### Screenshots

<img width="700" alt="image" src="https://github.com/flyteorg/flyte/assets/45474952/d804bbc0-cb61-4420-bffa-d050a6c2237e">

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Future-Outlier** [comment]
@Benjamintdk 
Hi, can you offer the whole code for us to fix the bug?
In flytekit, we've already tested the scenario.
https://github.com/flyteorg/flytekit/blob/master/plugins/flytekit-deck-standard/tests/test_renderer.py#L60-L72

**Comment by eapolinario** [comment]
@Benjamintdk , can you double-check which version of `pyllow` you installed when you saw this bug?

**Comment by thomasjpfan** [comment]
I am closing, because it has been 5 months without a response from the original author.
