### ISSUE TITLE
System level Timeout

### ISSUE THREAD

**Issue by migueltol22** [flyteorg/flyte#382]
**Motivation: Why do you think this is important?**
For cases when a pod is stuck in Pending for an extended amount of time it would be useful to have a system level timeout where Propeller kills the job. This would differ from the current node level timeout where both Pending and Running time is taken into account.

**Goal: What should the final outcome look like, ideally?**
If a pod is Pending for N amount of time the job will be killed and considered a system failure.

**Describe alternatives you've considered**

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [x] FlytePropeller
- [] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Additional context**

**Is this a blocker for you to adopt Flyte**
Please let us know if this makes it impossible to adopt Flyte

**Comment by kumare3** [comment]
@migueltol22 we have this already

**Comment by migueltol22** [comment]
Closing issue as this already exists.
