### ISSUE TITLE
[BUG] FlyteConsole can't handle the example merge_sort.py

### ISSUE THREAD

**Issue by Future-Outlier** [flyteorg/flyte#3863]
### Describe the bug

When I use the example from merge_sort.py, which is from [here](https://github.com/flyteorg/flytesnacks/blob/master/examples/control_flow/control_flow/merge_sort.py)
Use the following command
```
pyflyte run --remote merge_sort.py merge_sort --numbers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21] --numbers_count=21
```
and open my flyteconsole, the bug will happen.

The output is right, but the behavior isn't.

Note:
I've contributed to the merge_sort.py to change the behavior, but my code can still reproduce the bug.

### Expected behavior

1.See the graph in FlyteConsole.
2.See the Nodes in FlyteConsole.

### Screenshots

![image](https://github.com/flyteorg/flyte/assets/76461262/c9e4602d-266a-440c-b97f-81e4a58eace8)
![image](https://github.com/flyteorg/flyte/assets/76461262/6de842a1-6a97-40a1-9a52-50998ae5bf3a)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
sample run: https://devflyte/console/projects/flytesnacks/domains/development/executions/axvb2b4hgzpjjhhhfls2?duration=all

**Comment by wild-endeavor** [comment]
https://github.com/flyteorg/flyteconsole/pull/788 fixes this issue.

**Comment by wild-endeavor** [comment]
will be in flyte release 1.8.1
