### ISSUE TITLE
[Core feature] Enable dataclass attribute access in workflows

### ISSUE THREAD

**Issue by franzigeiger** [flyteorg/flyte#3864]
### Motivation: Why do you think this is important?

I'd like to access dataclass attributes from within a workflow. This is already possible for `NamedTuple` but those are restricted in usage. 

### Goal: What should the final outcome look like, ideally?

I would like this to work:
```
@dataclass
@dataclass_json
class Config:
    x:int
    y:int
    z:int
    some_unused_additional_config:list[str]

@task
def add(x:int, y:int):
    return x+y
@workflow
def do_something(config:Config):
    add(config.x, config.y)
```

### Describe alternatives you've considered 

Currenlty this is only possible with workarounds. You can:
- Make the workflow dynamic
- Use `NamedTuples` only if the configuration object is an output of another workflow. They can't be a task or workflow input.
- Change the `add` task signatures to take in the full config object, which means taking in unused parameters.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
This is something I've wanted for a while too.  I think it's possible but will require a fair bit of changes.  @franzigeiger were you hoping to contribute?
