### ISSUE TITLE
[UI Feature] Launch form bug-bash items

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyte#3872]
### Motivation: Why do you think this is important?

Users have noted that many of the more complex inputs for launch forms encounter various errors that often block users from being able to launch a WF. This ticket will track bugs found when dealing with these types.

### Goal: What should the final outcome look like, ideally?

The launch form should be completely stable and support all types.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by FrankFlitton** [comment]
Changing union(string|none) from string (boolean etc) to none fails: 
/console/projects/flytesnacks/domains/development/executions/f0add3bd21f7347b9a09

**Comment by FrankFlitton** [comment]
Integer array fails when relaunching a successful LP: /console/projects/flytesnacks/domains/development/executions/asqcrltw47vwpdkgl6lv?duration=all

**Comment by FrankFlitton** [comment]
This is a valid float `0.399999999999999999999999990.39999999999999999999999999453453...e^14`
Minimum replication case: `1.2.3`

**Comment by FrankFlitton** [comment]
This struct shows a textarea with JSON. Is it due to having nested objects? 

/console/projects/flytesnacks/domains/development/executions/apxchdnm285bggc82vvq?duration=all

**Comment by FrankFlitton** [comment]
For scientific notation — if the rest of Flyte can support it:
0.000000004 would be 4e-9
17320000 would be 1.732e+7
The same notation works in javascript, too 

If we don't support / no current issues than no biggies to skip.
