### ISSUE TITLE
[Core feature] Implement local execution of ContainerTask

### ISSUE THREAD

**Issue by eapolinario** [flyteorg/flyte#3876]
### Motivation: Why do you think this is important?

[We can make the assumption that a local docker client is configured and has the right permissions]

In the vein of making flytekit more useful on its own, we could augment `ContainerTask` to run locally, this way decreasing the dependence on a Flyte cluster for local development.

### Goal: What should the final outcome look like, ideally?

Iterating on DAGs that make use of `ContainerTask` is cumbersome as we currently not able to execute tasks of that type locally. 

With https://github.com/flyteorg/flytekit/pull/1745 we're improving the situation somewhat by letting users know that this is an impossibility. That said, there's no fundamental reason for us not to assume certain capabilities, for example access to a docker client, such that we could rely on that to kick off executions of `ContainerTask`.

### Describe alternatives you've considered 

Using a Flyte cluster.

###  Propose: Link/Inline OR Additional context 

As described in https://github.com/flyteorg/flytekit/pull/1745#discussion_r1267276411, we can add support for a subset of what is achievable with `ContainerTask`, with a few exceptions, e.g. Pod templates.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Future-Outlier** [comment]
Currently working on flytekit, if possible please give me a chance!

**Comment by eapolinario** [comment]
@Future-Outlier , for sure. I just assigned this to you. Feel free to tag me on PRs or if you want to discuss this further.
