### ISSUE TITLE
[BUG] Cache loading of nested list fails

### ISSUE THREAD

**Issue by fellhorn** [flyteorg/flyte#3901]
### Describe the bug

Flytepropeller fails loading the cache for a nested list if one sub-list is empty.

Minimal example workflow:
```py
from flytekit import workflow, task

@task(
    cache=True,
    cache_version="0"
)
def my_task() -> list[list[str]]:
    return [["foo"], []]

@workflow
def my_workflow():
    my_task()
```

Flytepropeller logs show this error:
```
Error when trying to reconcile workflow. Error [Failed to check Catalog for previous results: unexpected artifactData: [o0] type: [collection_type:<union_type:<variants:<collection_type:<simple:NONE > > variants:<collection_type:<simple:STRING > > > > ]
```

which looks like that it interprets the type of
```json
{
	"o0": [
		["foo"],
		[]
	]
}
```

as

```py
list[Union[list[None],list[str]]
```
instead of
```py
list[list[str]]
```

## User experience

For the user the task is just stuck in `Queued` and they need access to the flytepropeller logs to do any debugging.

### Expected behavior

* Caching should also work for these nested lists with empty sub-lists
* Ideally flytepropeller error logs are present in the frontend and the task fails for caching issues instead of being stuck in Queued

### Additional context to reproduce

1. Execute the workflow from above once to write the cache
2. Execute it a second time and the task should be stuck in Queued

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by fellhorn** [comment]
It seems like the underlying issue is connected to different types in the sublists. E.g. this workflow will hang too:
```py
from typing import Union

from flytekit import workflow, task

@task(
    cache=True,
    cache_version="union_list"
)
def my_task() -> list[list[Union[str,int]]]:
    return [["foo"], [2]]

@workflow
def my_workflow():
    my_task()
```

**Comment by hamersaw** [comment]
This is related to https://github.com/flyteorg/flytepropeller/pull/599, but the problem seems to be slightly different. In this scenario, the validation between `union` in `collection` is causing issues with validation. Will explore further.

**Comment by hamersaw** [comment]
closed as completed

**Comment by fellhorn** [comment]
Thank you :)
