### ISSUE TITLE
[BUG] eks installation from helm causes propeller crash

### ISSUE THREAD

**Issue by altosongole** [flyteorg/flyte#3905]
### Describe the bug

We are installing on eks using "Flyte Native Scheduler" helm chart
https://raw.githubusercontent.com/flyteorg/flyte/master/charts/flyte-core/values-eks.yaml

flytepropeller crashes with the following error:
```

{"json":{},"level":"error","msg":"Cannot set default plugin [agent-service] for task types [[bigquery_query_job_task]] when it is not configured to be an enabled plugin. Please double check the flytepropeller config.","ts":"2023-07-28T00:00:16Z"}
{"json":{},"level":"error","msg":"Failed to finalize enabled plugins. Error: cannot set default plugin [agent-service] for task types [[bigquery_query_job_task]] when it is not configured to be an enabled plugin","ts":"2023-07-28T00:00:16Z"}
{"json":{},"level":"panic","msg":"cannot set default plugin [agent-service] for task types [[bigquery_query_job_task]] when it is not configured to be an enabled plugin","ts":"2023-07-28T00:00:16Z"}
panic: (*logrus.Entry) 0xc00051d0a0

goroutine 530 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc00051cfc0, 0x0, {0xc0000f0b40, 0x86})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:259 +0x45b
github.com/sirupsen/logrus.(*Entry).Log(0xc00051cfc0, 0x0, {0xc001053370?, 0xc001053370?, 0x0?})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(0x2c66000?, {0xc001053370?, 0x21e3b80?, 0xc0004bac01?})
	/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:331 +0x29
github.com/flyteorg/flytestdlib/logger.Panic({0x2c66000?, 0xc000ede5c0?}, {0xc001053370, 0x1, 0x1})
	/go/pkg/mod/github.com/flyteorg/flytestdlib@v1.0.19/logger/logger.go:143 +0x4d
github.com/flyteorg/flytepropeller/pkg/controller.(*Controller).onStartedLeading.func1()
	/go/src/github.com/flyteorg/flytepropeller/pkg/controller/controller.go:139 +0xa5
created by github.com/flyteorg/flytepropeller/pkg/controller.(*Controller).onStartedLeading
	/go/src/github.com/flyteorg/flytepropeller/pkg/controller/controller.go:137 +0xcd
```

### Expected behavior

All pods should be up and running. It should not be enabling bigquery task 

### Additional context to reproduce

- Install on eks cluster using helm chart with values.yaml from https://raw.githubusercontent.com/flyteorg/flyte/master/charts/flyte-core/values-eks.yaml

### Screenshots

Relevant section from values.yaml...

<img width="1103" alt="Screenshot 2023-07-27 at 5 20 59 PM" src="https://github.com/flyteorg/flyte/assets/122563286/710fc2eb-16b7-48ed-ba21-7bcff28cc076">

--------------------------------------

flyte-propeller-config  config map

<img width="559" alt="Screenshot 2023-07-27 at 5 22 30 PM" src="https://github.com/flyteorg/flyte/assets/122563286/6789ea55-762b-453e-8aeb-5c9dc982bc4a">

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by altosongole** [comment]
I enabled agent-service plugin. Then it worked.
However, it is strange! It is enabling bigquery_query_job_task by default and forcing us to enable agent-service, which I am not sure whether I need!

**Comment by eapolinario** [comment]
This is unexpected, @altosongole . We're going to get it fixed asap.
