### ISSUE TITLE
[BUG] flytekit output returns FlyteLiteral instead of Promise

### ISSUE THREAD

**Issue by RRap0so** [flyteorg/flyte#3923]
### Describe the bug

We have a task that outputs the following:

```
class TaskOutput(NamedTuple):
    uri: str
    ref: str
```

when we do `output.ref` it returns a FlyteLiteral instead of the Promise. We believe this is due to a property set in 
https://github.com/flyteorg/flytekit/blob/41e21f4de56a837e09101a5cf5dd08ec4e8249df/flytekit/core/promise.py#L503

### Expected behavior

Flytekit Output with `ref` field should return a promise.

### Additional context to reproduce
Running this snippet with `pyflyte` will reproduce the issue

```
from typing import NamedTuple
from flytekit import task, workflow

class HelloRefOutput(NamedTuple):
  ref: str
  uri: str

@task
def hello_ref() -> HelloRefOutput:
  return HelloRefOutput(ref="hello", uri="world")

@workflow
def hello_ref_workflow() -> str:
  result = hello_ref()
  print(result) # Output(ref=Promise(node:n0.ref), uri=Promise(node:n0.uri))
  print(result.ref) # <FlyteLiteral node_id: "n0" var: "ref"> -- This should be a Promise not a FLyteLiteral
  print(result.uri) # Promise(node:n0.uri) -- OK!

```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by rafaelraposospot** [comment]
https://github.com/flyteorg/flytekit/pull/1777

**Comment by eapolinario** [comment]
@rafaelraposospot , can you expand a bit more on your use case here? Maybe an example would clarify the intent.

**Comment by rafaelraposospot** [comment]
Sure thing @eapolinario. I've added an example!
