### ISSUE TITLE
[BUG] Development guide setup is not compatible with Macs

### ISSUE THREAD

**Issue by hamersaw** [flyteorg/flyte#3938]
### Describe the bug

In the [development environment setup guide](https://docs.flyte.org/en/latest/community/contribute.html#contribute-flyte) the `sed` command does not have a `-i` flag on mac.

```
sed -i "s|\$HOME|${HOME}|g" ./flyte-single-binary-local.yaml
```

### Expected behavior

This should work on all platforms.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
https://stackoverflow.com/questions/7573368/in-place-edits-with-sed-on-os-x has a few pointers.

**Comment by troychiu** [comment]
One workaround is using -i with the backup file and then delete the backup file
`sed -i.bak "s|\$HOME|${HOME}|g" flyte-single-binary-local.yaml && rm flyte-single-binary-local.yaml.bak`
I have tested it. Works fine on both Linux and Mac.
If it's a feasible solution, feel free to ask me to open a pr.
Reference: https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux

**Comment by troychiu** [comment]
Hi @eapolinario, do you think my previous comment is a feasible solution? If yes, I am going to create a pr.

**Comment by eapolinario** [comment]
@troychiu , https://stackoverflow.com/a/51060063/205787 is a much cleaner solution. Can you try that instead?

**Comment by troychiu** [comment]
Hi @eapolinario , this will work
```
sedi=(-i)
case "$(uname)" in
  Darwin*) sedi=(-i "")
esac

# Expand the parameters in the actual call to "sed"
sed "${sedi[@]}" -e "s|\$HOME|${HOME}|g" flyte-single-binary-local.yaml
```

**Comment by eapolinario** [comment]
Amazing. Thanks for double-checking.

**Comment by troychiu** [comment]
Should I create a pr for this?

**Comment by eapolinario** [comment]
Please, go ahead. 🙂

**Comment by troychiu** [comment]
Hi @eapolinario , the PR is created https://github.com/flyteorg/flyte/pull/4260
