### ISSUE TITLE
[Docs] Wrong indentation in eks-starter.yaml referenced by Single Cluster Simple Cloud Deployment

### ISSUE THREAD

**Issue by edwinyyyu** [flyteorg/flyte#3950]
### Description

https://docs.flyte.org/en/latest/deployment/deployment/cloud_simple.html#installation

https://raw.githubusercontent.com/flyteorg/flyte/master/charts/flyte-binary/eks-starter.yaml
https://github.com/flyteorg/flyte/blob/master/charts/flyte-binary/eks-starter.yaml

The last line
`  eks.amazonaws.com/role-arn: "<FLYTE_BACKEND_IAM_ARN>"`
should be indented by one more level.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by davidmirror-ops** [comment]
Right @edwinyyyu!

Would you be up to fix it?

**Comment by edwinyyyu** [comment]
I can do it after work tomorrow.
