### ISSUE TITLE
[Housekeeping] Remove storage as a task resource option

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#3955]
### Describe the issue

We only respect ephemeral storage request and actually delete the storage request from the generated pod spec: https://github.com/flyteorg/flyteplugins/blob/df62599965f04cd9b0ccfece5a00513ead7fed5d/go/tasks/pluginmachinery/flytek8s/container_helper.go#L162

If the resource is unused we shouldn't allow it to be set since this is a confusing user experience

### What if we do not do this?

Confusing DevX with unrespected task resource specification.

### Related component(s)

flyteidl, flytekit, flyteplugins

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Kota-Karthik** [comment]
hello @katrogan 
I am interested in doing this issue
So kindly assign me this
Thank You : )

**Comment by Vishalk91-4** [comment]
@samhita-alla, can you please assign this issue to me

**Comment by samhita-alla** [comment]
Please go ahead and create a PR, @Kota-Karthik, @Vishalk91-4. We will prioritize PRs based on a first-come, first-serve approach.

**Comment by davidmirror-ops** [comment]
@dado5688 are you still up to work on this?

**Comment by dado5688** [comment]
sure! 
I'd like to know what I need to do is to remove all the usage about Resource Storage 
or to add an warn to tell that Resource Storage is not support anymore when user trying to configure the Resource Storage?

**Comment by samhita-alla** [comment]
@katrogan, could you elaborate on what needs to be done please?
