### ISSUE TITLE
[Docs] Spot/interruptible docs imply retries come from the user retry budget

### ISSUE THREAD

**Issue by andrewwdye** [flyteorg/flyte#3956]
### Description

In the [spot/interruptible docs](https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/containerization/spot_instances.html#setting-interruptible) we have the following note
> If you set retries=n, for instance, and the task gets preempted repeatedly, Flyte will retry on a preemptible/spot instance n-1 times and for the last attempt will retry your task on a non-spot (regular) instance. Please note that tasks will only be retried if at least one retry is allowed using the retries parameter in the task decorator.

This implies that interruptible retries come from the user-specified user error retry budget. However, in practice spot interruptions are taken from the system retry budget.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by davidmirror-ops** [comment]
Keep it open

**Comment by RaghavMangla** [comment]
Hi! I would like to work on this issue

**Comment by RaghavMangla** [comment]
Yes, sure

**Comment by RaghavMangla** [comment]
??

**Comment by ap0calypse8** [comment]
i want to work on this issue

**Comment by davidmirror-ops** [comment]
@ap0calypse8 thank you!
