### ISSUE TITLE
[BUG] [UI] Clicking Flyte Icon sometimes 404s

### ISSUE THREAD

**Issue by FrankFlitton** [flyteorg/flyte#3976]
### Describe the bug

Clicking the Flyte logo to `console/select-project` will sometimes show 404 not found text (not rendering react app).

### Expected behavior

Use react router to navigate to `/console/select-project`.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by ursucarina** [comment]
@FrankFlitton do you have more details or an error log? I can't repro this... were you in a particular deep path?

**Comment by ursucarina** [comment]
should be fixed once this deploys: https://github.com/flyteorg/flyte/pull/3978

**Comment by FrankFlitton** [comment]
Yes. It was caused by the single binary startup serving config.
