### ISSUE TITLE
[BUG] CRD is left behind when flyte-core is uninstalled

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/flyte#3987]
### Describe the bug

When the `flyte-core` chart is uninstalled, it leaves behind the `flyteworkflows.flyte.lyft.com` CRD. 

It causes new installations of the same chart to fail with the `[INSTALLATION FAILED : manifests contain a resource that already exists]` error. 

### Expected behavior

The CRD should be Helm-managed so it's deleted when the chart is uninstalled

### Additional context to reproduce

`flyte-core` chart `v0.1.10` on EKS

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
[helm is upfront about it](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations), there simply isn't support for upgrading or deletion of CRDs in the same chart (unless in the very specific case of non-templated CRDs put in the `crds` directory - worth noting that this option doesn't work for us out-of-the-box as the creation of the flyte CRD is [templated](https://github.com/flyteorg/flyte/blob/master/charts/flyte-core/templates/propeller/crds/flyteworkflow.yaml)).

**Comment by eapolinario** [comment]
We already create the CRD in flytepropeller in case it doesn't exist (it's behind a flag). Let's investigate if we can leave the creation of the CRD up to propeller and remove this from the helm charts.

**Comment by wild-endeavor** [comment]
so the crux of this issue is that propeller is crashing on re-install right?  I think leaving behind the CRD is okay.
