### ISSUE TITLE
[BUG] Investigate memory leak in single-binary deployment

### ISSUE THREAD

**Issue by eapolinario** [flyteorg/flyte#3991]
### Describe the bug

A user in the OSS slack [reported](https://flyte-org.slack.com/archives/CP2HDHKE1/p1692894721174089) that single-binary pods keep getting killed due to OOM errors. Here's a graph of memory consumption in this case (different colors refer to different pods):

![image](https://github.com/flyteorg/flyte/assets/653394/650b4d94-5355-4037-ace2-ab0de1debc1f)

They are running stock Flyte v1.8.1 release.

### Expected behavior

Memory consumption should remain relatively constant.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
look at prometheus metrics, educated guess from dan - every time a task runs, prometheus metrics in propeller might be contributing to memory usage.

**Comment by cpaulik** [comment]
I'm pretty sure this is what I'm seeing as well. See https://flyte-org.slack.com/archives/CP2HDHKE1/p1723819039330009 for more discussion.

**Comment by eapolinario** [comment]
After some investigation, it turns out that accumulating metrics data is the expected behavior of the prometheus golang client, as per https://github.com/prometheus/client_golang/discussions/920. We emit high-cardinality metrics in flytepropeller, as an example you can see [here](https://gist.github.com/eapolinario/4626e39c4d40086454a79764c8d0df6c) the emitted metrics after running a few hundred workflow executions. Note how we maintain a lot of metrics per execution id. This is the [symptom](https://github.com/prometheus/client_golang/discussions/920#discussioncomment-1448783) described in the prometheus client gh issue.

One could argue that emitting metrics per-execution id is the wrong granularity, but that's exactly what we do in the case of [single-binary](https://github.com/flyteorg/flyte/blob/master/cmd/single/start.go#L252).

> would deploying via flyte-core help here?

Knowing what we know now, the set of default metrics emitted by flytepropeller in the [default cause](https://github.com/flyteorg/flyte/blob/master/flytepropeller/pkg/controller/config/config.go#L111-L112) does not cause the issue. Similar argument can be made to [flyteadmin](https://github.com/flyteorg/flyte/blob/master/flyteadmin/pkg/runtime/application_config_provider.go#L26-L29). In other words, this was a single-binary issue-only.

Here's the PR to remove that label from single binary metrics: https://github.com/flyteorg/flyte/pull/5704

**Comment by wild-endeavor** [comment]
Related to https://github.com/flyteorg/flyte/issues/5606

**Comment by divyank000** [comment]
This has solved the issue at a shorter time horizon.  However I still see the issue on the longer time horizon.  
initially for us, it was around few hours on production workload. Now it is around 2 days on production workload.
