### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by psmoros** [flyteorg/flyte#4025]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@andy53) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by EngHabu** [comment]
Thank you @psmoros & [@Andy53](https://github.com/Andy53).
Until we create the SECURITY.md, can you please use: https://github.com/flyteorg/flyte/security/ (or the appropriate repo where the vulnerability is if you know) to report a vulnerability.
