### ISSUE TITLE
[BUG] Could not find LHS for Shell Task

### ISSUE THREAD

**Issue by stephen37** [flyteorg/flyte#4049]
### Describe the bug

Since Flytekit 1.9.1, it seems like there is a bug when serialising a task that is a Shell Task. 

```
pyflyte -c ci/cfg/flyte.config package --image flyte-project-name:xxx -f
Loading packages ['src.workflows'] under source root /code/flyte_projects/flyte-project-name
2023-09-19 13:16:38,009677 ERROR    {"asctime": "2023-09-19 13:16:38,009", "name": "flytekit", "levelname": "ERROR", "message": "Could not find LHS for <flytekit.core.python_function_task.PythonFunctionTask object at 0x11d66a910> in src.workflows.routing_profiles"}             tracker.py:163
Failed with Exception Code: SYSTEM:Unknown
Error looking for LHS in src.workflows.routing_profiles
make: *** [serialize] Error 1
```

When using Flytekit 1.8.1, the serialisation works as expected 
```
pyflyte -c ci/cfg/flyte.config package --image flyte-project-name:xxx  -f
Successfully serialized 19 flyte objects
[...]
Successfully packaged 19 flyte objects into /code/flyte_projects/flyte-project-name/flyte-package.tgz
```

### Expected behavior

Serialisation should work even when using Flytekit 1.9.1 and using Shell Task

### Additional context to reproduce

This is the Shell Task that we have defined.

```python
@task
def upload_routing_profiles() -> FlyteDirectory:
    return FlyteDirectory(path=PROFILES_LOCAL_PATH, remote_directory=PROFILES_S3_PREFIX)


extract_data = ShellTask(
    name="extract_data",
    inputs=kwtypes(dir=FlyteDirectory, profiles=FlyteDirectory),
    output_locs=[
        OutputLocation(
            var="extract_data",
            var_type=FlyteDirectory,
            location="{inputs.dir}",
        )
    ],
    script="""
    set -euo
    <perform_an_action> --profile {inputs.profiles}/foo.bar {inputs.dirr}/foo.pbf
    ls -alh {inputs.dir}
    """,
)
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pingsutw** [comment]
we fixed it in the [PR](https://github.com/flyteorg/flytekit/pull/1829), will cut a new release in the next two weeks

**Comment by stephen37** [comment]
Oh amazing, thank you ❤️

**Comment by stephen37** [comment]
Hey @pingsutw, it seems like it wasn't added to the new release, do you know if it's planned to be added in a minor version release soon? 🙏

**Comment by rybalko-wolt** [comment]
@stephen37 feel free to close this issue in case it has been resolved

**Comment by stephen37** [comment]
Good point, closing as it's the fix has been released here: https://github.com/flyteorg/flyte/releases/tag/v1.10.0
