### ISSUE TITLE
[Docs] tensorflow types: create flytesnacks example page

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#4065]
### Description

Add a page to the [Data Types and IO](https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/data_types_and_io/index.html) section in the user guide that documents all [available TensorFlow types](https://github.com/flyteorg/flytekit/tree/master/flytekit/extras/tensorflow) and explains how they work.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Smartmind12** [comment]
Hey @samhita-alla Can i Work on this issue?

**Comment by Vishalk91-4** [comment]
@samhita-alla, can you please assign this issue to me

**Comment by Smartmind12** [comment]
> @samhita-alla, can you please assign this issue to me

Hey @Vishalk91-4 I am currently waiting for this issue to be assigned to me. Kindly take up another issue to work on!

**Comment by samhita-alla** [comment]
@Smartmind12, are you working on creating a PR?

**Comment by sumana-2705** [comment]
@samhita-alla 

Hello, I'd like to solve this issue. Can you please assign it to me?

**Comment by davidmirror-ops** [comment]
@sumana-2705 Thanks, please let us know soon if you have questions.

**Comment by sumana-2705** [comment]
@davidmirror-ops 
I noticed that other pages in `Data Types and IO` section have references for example code snippet in `Flytesnacks repo`. Should I also create a new file named tensorflow_type.py in Flytesnacks repo. If this is the case, should I need to submit different PRs in 2 repositories?

**Comment by davidmirror-ops** [comment]
@sumana-2705 right. The page should include an example and those live on the flytesnacks repo. Feel free to tag me for review on your PRs. Thanks!

**Comment by sumana-2705** [comment]
@davidmirror-ops  I have created pull requests in both `flyte` and `flytesnacks` repositories, please review and suggest me the changes
