### ISSUE TITLE
[Docs] Azure AD OIDC Issuer URl is not correct.

### ISSUE THREAD

**Issue by EraYaN** [flyteorg/flyte#4068]
### Description

https://docs.flyte.org/en/v1.0.0/deployment/cluster_config/auth_setup.html#openid-connect mentions `https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/authorize` and the Azure AD provider URL. After trying it, this will result in a 404, because the correct URL for Azure AD (v2) OIDC seems to be `https://login.microsoftonline.com/<tenant-id>/v2.0` similar though different. Then it will correctly find the `.well-known` paths and continue.

Still some issues with token cookie length, but it at least retrieves the tokens.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by davidmirror-ops** [comment]
Thank you @EraYaN!
Do you want to submit a PR to fix it?

**Comment by EraYaN** [comment]
I have opened a PR with the replacement of the URL.
