### ISSUE TITLE
[Core feature] Sagemaker Agent

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/flyte#4079]
### Motivation: Why do you think this is important?

This agent can used to submit the training or serving jot to AWS sagemaker. It allows people to easily run SageMaker training in a Flyte workflow.

Currently, we have sagemaker [backend plugin](https://github.com/flyteorg/flyteplugins/tree/master/go/tasks/plugins/k8s/sagemaker) to submit the job, but the code it outdated, and doesn't work for now. We can write an agent in Python for Sagemaker, and it will be easy to maintain as well.

### Goal: What should the final outcome look like, ideally?

We'll able to submit a training job by leveraging agent. 

### Describe alternatives you've considered 

_NA_

###  Propose: Link/Inline OR Additional context 

- [Writing Agents in Python](https://docs.flyte.org/projects/cookbook/en/stable/auto_examples/development_lifecycle/agent_service.html)
- https://github.com/flyteorg/flytekit/pull/1797

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by soumya-dash3** [comment]
Hello @samhita-alla , can I be assigned this issue, please?

**Comment by soumya-dash3** [comment]
Sorry for the inconvenience @pingsutw , you may assign this to someone else.

**Comment by troychiu** [comment]
I can work on this
