### ISSUE TITLE
[UI Feature] Make Flyte Console Default reason is open

### ISSUE THREAD

**Issue by Future-Outlier** [flyteorg/flyte#4088]
### Motivation: Why do you think this is important?

I am currently working on a small feature, and I encountered a scenario where finding the **reason** was not straightforward. 
My work is here: [PR #399](https://github.com/flyteorg/flyteplugins/pull/399).

I spent over 30 minutes trying to figure out that clicking the exclamation mark reveals the reason details.
This process can be quite time-consuming and may not be intuitive, especially for new users or contributors.

### Goal: What should the final outcome look like, ideally?
![image](https://github.com/flyteorg/flyteplugins/assets/76461262/d5f7149b-25df-4a9c-991c-c5ecedddc946)

The reason section should be default open.

### Describe alternatives you've considered
Make the message shows here.
![image](https://github.com/flyteorg/flyte/assets/76461262/ea2a877f-069c-44d3-aa80-0864c0eb0ad7)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by sohamtembhurne** [comment]
hi @Future-Outlier ,
can you please tell the steps to reproduce this ?

**Comment by Future-Outlier** [comment]
@sohamtembhurne 
Just register a task or use `pyflyte run --remote` and you can reproduce it!
![image](https://github.com/flyteorg/flyte/assets/76461262/6bca7176-c31e-4406-8ddd-9c8c20352b06)

**Comment by Future-Outlier** [comment]
@pingsutw, @samhita-alla  Can you add `good first issue` label?
Thanks a lot!

**Comment by adarsh-jha-dev** [comment]
Hey @Future-Outlier , could you please assign me this issue?

**Comment by Future-Outlier** [comment]
@adarsh-jha-dev I don't have permission to assign to you, but you can do it, no one is working on it!
Thanks

**Comment by adarsh-jha-dev** [comment]
@Future-Outlier , could you please let me know where can i find the source code for the frontend?

**Comment by Future-Outlier** [comment]
I just tested it today, and the issue is fixed. (I am really surprised)
I will close this issue, thanks a lot!

**Comment by adarsh-jha-dev** [comment]
> I just tested it today, and the issue is fixed. (I am really surprised) I will close this issue, thanks a lot!

Ok OK , no issues, thanks for the response.
