### ISSUE TITLE
[Flytekit/Pyflyte] Pyflyte register & launchplan commands don't support --envs flag 

### ISSUE THREAD

**Issue by PudgyPigeon** [flyteorg/flyte#4092]
With `pyflyte run` commands, you can specify a `--envs` flag and pass in a JSONified dictionary/object to propagate variables to the container running the workflows/tasks.

Like so:
 `pyflyte run --envs '{"var1":"hello","var2":"world"}' --image etcetcetc workflowfile`

We are requesting an equivalent mode of passing an --envs like dictionary in the context of running `pyflyte register` and `pyflyte launchplan --activate/deactivate` commands

Context being:
`pyflyte register -p flytesnacks --image imagename:1.0.5 --version v0.0.2a ./workflow.py`

And/or
`pyflyte launchplan -p flytesnacks -d staging launchplan-name v0.0.1a --activate`

**Comment by PudgyPigeon** [comment]
@wild-endeavor

**Comment by PudgyPigeon** [comment]
Sorry, I don't mean specifically a Python dictionary but basically a dictionary-like structure/JSON object that you can pass into the container runtime of the pod/task

**Comment by kumare3** [comment]
I have updated pyflyte to now support --env X=y --env a=c instead of a dict.

And you want this env car to be set at the launchplan level? Today that is not available

**Comment by PudgyPigeon** [comment]
> I have updated pyflyte to now support --env X=y --env a=c instead of a dict.
> 
> And you want this env car to be set at the launchplan level? Today that is not available

Ah yes, so basically we want to run `pyflyte register --envs` in a way that mirrors/copies the syntax of `pyflyte run --envs`, if that makes sense.

**Comment by MinuraPunchihewa** [comment]
Hey Flyte Team,
Can I take this up?

**Comment by PudgyPigeon** [comment]
> Hey Flyte Team, Can I take this up?

This PR of ours might help if you want to implement --envs into pyflyte register. Our forks are based off of 1.6.0 so maybe you can do a more updated version

https://github.com/PudgyPigeon/flytekit/pull/6/files

One thing to note is that you might run into JSON decoding errors if you pass Cron statements as one of the --envs variables. We had to use something like the following to replace the whitespace, so maybe you can take some of the code from here:

    class CronParser:    
    def __init__(self):
        self.replacements = {
            " ": "_"
        }   
    def cron_to_string(self, cron: str) -> str:
        return re.sub(r"[\s]", lambda m: self.replacements[m.group()], cron)

    def string_to_cron(self, x: str) -> str:
        return re.sub(r"[_]", lambda m: {v: k for k, v in self.replacements.items()}[m.group()], x)
