### ISSUE TITLE
[Feature] flyte-cli configuration file

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#412]
**Motivation: Why do you think this is important?**
flytekit currently ships with a CLI called flyte-cli that references a config file is assumed to live in `~/.flyte/config` We like this pattern as it mirrors kubectl's `~/.kube/config`.  However, when debugging, or when working with multiple deployments of Flyte (like we have staging and production, in addition to a local deployment), it's often helpful to be able to give it a file to reference instead of always assuming it's at `~/.flyte/config`.

```
[platform]
url=flyte.mycorp.net
auth=True

[credentials]
client_id=abcdef123
redirect_uri=http://localhost:53593/callback
auth_mode=standard
authorization_metadata_key=flyte-authorization
scope=svc
```

Note, workflow repository configs look similar and have many of the same keys (workflow ones have more)
https://github.com/lyft/flytesnacks/blob/master/cookbook/sandbox.config

**Goal: What should the final outcome look like, ideally?**
If not specified, `flyte-cli` should look for a config file at the default location of `~/.flyte/config`.  If `flyte-cli -f /other/file` is given, then the file `/other/file` should be used instead.

Not sure if `f` is the best argument to use, it may already be taken.

**Describe alternatives you've considered**

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
NA

**Additional context**
NA

**Is this a blocker for you to adopt Flyte**
NA

**Comment by kumare3** [comment]
this is not used any more. please use `pyflyte` or `flytectl`
