### ISSUE TITLE
[Docs] Typo in Quick Start Point 3 for the FlyteConsole Repository

### ISSUE THREAD

**Issue by K-Kumar-01** [flyteorg/flyte#4163]
### Description

The point 3 mentioned [here](https://github.com/flyteorg/flyteconsole#-quick-start) has typo.
Instead of  `bash yarn start`, it should be 
```bash
yarn start
``` 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by ShikhaaT44** [comment]
I'm interested in solving this issue!
