### ISSUE TITLE
[Docs] Errors in the "Using Secrets in a Task" documentation

### ISSUE THREAD

**Issue by gdabisias** [flyteorg/flyte#4181]
### Description

FYI found a few typos [here](https://docs.flyte.org/projects/cookbook/en/v0.3.66/auto/core/containerization/use_secrets.html)
```
If the mounting_requirement is not specified then the secret will be injected as an environment variable is possible. Ideally, you need not worry about the mounting requirement, just specify the Secret.name that matches the declared secret in Flyte backend
```
- is possible
- you need not worry
- in THE Flyte backend

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by aryanshb** [comment]
Hi, can I be assigned this issue?

**Comment by aadii0408** [comment]
Hey @davidmirror-ops , I would like to do it.

**Comment by davidmirror-ops** [comment]
> Hey @davidmirror-ops , I would like to do it.

@aadii0408 Thanks for your interest in contributing! Sorry, @aryanshb came first but keep looking at ``hacktoberfest`` issues, there are and there will be more opportunities to get started.

**Comment by aryanshb** [comment]
![image](https://github.com/flyteorg/flyte/assets/77982206/eb941d4d-7940-46de-a97a-3917004574de)

Attempting to modify the source tells me that there is no such file in the master branch. 

![image](https://github.com/flyteorg/flyte/assets/77982206/4496d8ac-b25a-4102-841a-e7cb924a7129)

Any hints on which branch is currently being deployed?

**Comment by Future-Outlier** [comment]
@davidmirror-ops 
This issue should be closed.
Currently, all the typo errors are fixed.
https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/productionizing/use_secrets.html
Please take a look, thanks a lot!

**Comment by Future-Outlier** [comment]
> ![image](https://user-images.githubusercontent.com/77982206/273433622-eb941d4d-7940-46de-a97a-3917004574de.png)
> 
> Attempting to modify the source tells me that there is no such file in the master branch.
> 
> ![image](https://user-images.githubusercontent.com/77982206/273433686-4496d8ac-b25a-4102-841a-e7cb924a7129.png)
> 
> Any hints on which branch is currently being deployed?

https://github.com/search?q=repo%3Aflyteorg%2Fflytesnacks%20%22Using%20Secrets%20in%20a%20Task%22&type=code

**Comment by aryanshb** [comment]
> > ![image](https://user-images.githubusercontent.com/77982206/273433622-eb941d4d-7940-46de-a97a-3917004574de.png)
> > Attempting to modify the source tells me that there is no such file in the master branch.
> > ![image](https://user-images.githubusercontent.com/77982206/273433686-4496d8ac-b25a-4102-841a-e7cb924a7129.png)
> > Any hints on which branch is currently being deployed?
> 
> https://github.com/search?q=repo%3Aflyteorg%2Fflytesnacks%20%22Using%20Secrets%20in%20a%20Task%22&type=code

I have looked through this, and the text in the pyfile is not the same that is being rendered on the documentation web page.


On the website:
> Using Secrets in a Task
> Flyte supports running a wide variety of tasks, from containers to SQL queries and service calls. In order for Flyte-run containers to request and access secrets, Flyte provides a native Secret construct.
> 
> For a simple task that launches a Pod, the flow will look something like this:


whereas in the python file:

> `# Flyte supports running a variety of tasks, from containers to SQL queries and`
> `# service calls, and it provides a native Secret construct to request and access`
> `# secrets.`

**Comment by davidmirror-ops** [comment]
@aadii0408 @aryanshb Any of you still plan to send a PR?

**Comment by aryanshb** [comment]
@davidmirror-ops , could not really find the mentioned errors, as @Future-Outlier  mentioned- this issue should be closed.

**Comment by davidmirror-ops** [comment]
@aryanshb This is strange. I see all the errors that the OP described in the original location.

**Comment by Future-Outlier** [comment]
Yes, but we use the latest version now.
So maybe it's not necessary to fix the old one.
@davidmirror-ops

**Comment by davidmirror-ops** [comment]
The typos are effectively gone in the `latest` version of docs. The build system for the docs site will be adapted to deactivate old versions and avoid this type of confusion.
