### ISSUE TITLE
[BUG] remote workflow called in conditional branch ran into issue

### ISSUE THREAD

**Issue by ysysys3074** [flyteorg/flyte#4184]
### Describe the bug

I have the code below which invoked a reference_launch_plan called `data_launch_plan` inside then() branch of conditional, but got `KeyError: LAUNCH_PLAN:XXX` in compile time. I suspect the issue is due to this https://github.com/flyteorg/flytekit/blob/master/flytekit/remote/remote.py#L364 as `node_launch_plans` is empty dict from what I saw.   And `data_launch_plan` is working and `node_launch_plans` is with values when calling it in a normal way.

```
featurized_dataset_location = (
        conditional("test")
            .if_(has_config.is_true())
            .then(
                data_launch_plan(
                    proxy_as=proxy_as,
                    name=name,
                )
            )
            .else_()
            .then(test(a=a))
```

### Expected behavior

Since this is a TODO, can you plz help to fix this https://github.com/flyteorg/flytekit/blob/master/flytekit/remote/remote.py

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Smartmind12** [comment]
Hey @ysysys3074 The possible reason could be that `data_launch_plan` function was introduced in Flytekit 0.18.0, so maybe you can try to upgrade your Flytekit version to 0.18.0 or later.
