### ISSUE TITLE
[Docs] Update Development Environment Setup Guide

### ISSUE THREAD

**Issue by Yicheng-Lu-llll** [flyteorg/flyte#4188]
### Description

Since moving to a mono repo, we need to update the Development Environment Setup Guide to reflect the structure. 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by ShatilKhan** [comment]
Hi, I'd like to take on this issue

**Comment by samhita-alla** [comment]
@ShatilKhan, https://docs.flyte.org/en/latest/community/contribute.html#development-environment-setup-guide needs to be updated.

**Comment by samhita-alla** [comment]
hey @Yicheng-Lu-llll, will you be working on this issue?

**Comment by Yicheng-Lu-llll** [comment]
Yes. working on it.  It seems that the "hello world" example in [Development Environment Setup Guide](https://docs.flyte.org/en/latest/community/contribute.html#development-environment-setup-guide) is also out of date due to the change of [flytesnacks](https://github.com/flyteorg/flytesnacks).

**Comment by Future-Outlier** [comment]
Just finish it, and please review it, thanks a lot!
I talked to @Yicheng-Lu-llll 3 hours ago, and he said that I can take over it.
