### ISSUE TITLE
Type transformer for PIL Image

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#4193]
Add support for PIL images as a Flyte native type using type transformers. Some examples of existing type transformers include [flytekit-vaex](https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-vaex), [flytekit-onnx-pytorch](https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-onnx-pytorch) and [flytekit-polars](https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-polars).

**Comment by kumare3** [comment]
This one is really simple and beginner friendly

**Comment by JaynouOliver** [comment]
I would like to work on this, kindly assign me?

**Comment by JaynouOliver** [comment]
thanks, will start working on it from now
