### ISSUE TITLE
[Housekeeping] Improve Test Coverage

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/flyte#4209]
### Describe the issue

The test coverage of some components is low. We should add more tests to Flyte repo.
Creating multiple PRs to fix it is fine since it cannot be done in one PR.

<img width="1690" alt="image" src="https://github.com/flyteorg/flyte/assets/37936015/2e821513-9d89-4737-99ab-250daae786ab">

### What if we do not do this?

Test Coverage > 80%

### Related component(s)

https://app.codecov.io/gh/flyteorg/flyte

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by sohamtembhurne** [comment]
Hi @pingsutw,
Can you please elaborate on the issue ?

**Comment by pingsutw** [comment]
@sohamtembhurne we need to add more tests to Flyte repo. For example, we need to add a test for this [file](https://github.com/flyteorg/flyte/blob/master/flytecopilot/data/download.go).

**Comment by u5surf** [comment]
@pingsutw Hi, I'm interesting in this issue but it is a bit wide to make all directories improved the coverage. Can we split issue or task per directory? Hence, I would do some tasks after you decide to split the task.

**Comment by Future-Outlier** [comment]
@u5surf You just have to add the test, create the PR, and mention this issue.
You can refer to this issue: https://github.com/flyteorg/flyte/issues/3936
