### ISSUE TITLE
Expose config for enabling grpc prometheus histograms

### ISSUE THREAD

**Issue by andrewwdye** [flyteorg/flyte#4214]
### Motivation: Why do you think this is important?

We integrate go-grpc-prometheus for grpc api metrics, but by default handling-time histograms are disabled. See https://github.com/grpc-ecosystem/go-grpc-prometheus#histograms.

We should add a flag to admin and other services to optionally turn these on.

### Goal: What should the final outcome look like, ideally?

Simple service config option to enable histograms, which would instruct the service to call `EnableHandlingTimeHistogram()` when [setting up grpc middleware](https://github.com/flyteorg/flyte/blob/b932cf1179b263b7c4404d9ea30b7138b0d00862/flyteadmin/pkg/server/service.go#L108).

### Describe alternatives you've considered 

A bunch of apis and internal functions are wrapped with StopWatch metrics. These provide pre-computed quantile latencies, which cannot be aggregated across service instances.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
So we enabled this in propeller a while back with the flag `enable-grpc-latency-metrics`. I see we added this as `enableGrpcHistograms` to admin. If / when we add to more services it would probably be good to keep some uniformity here.

**Comment by andrewwdye** [comment]
@katrogan want to deprecate the new name and adopt the propeller name here for consistency (before this gets adopted too widely)?

**Comment by katrogan** [comment]
https://github.com/flyteorg/flyte/pull/4280 unfortunately this is inconsistent with the casing we have in the flyteadmin grpc server config

@hamersaw is there a preference one way or the other with the casing/flag consistency here?
