### ISSUE TITLE
Update Twitter logo to X on the community page

### ISSUE THREAD

**Issue by blindaks** [flyteorg/flyte#4221]
The twitter logo on the website is still a bird. We should change it to X.

![image](https://github.com/flyteorg/flyte/assets/128223364/6faa4b07-5817-44b2-908c-df0fdc0a73bb)

I would like to work on this issue. Please assign it to me.

**Comment by davidmirror-ops** [comment]
@blindaks any blocker to submit a PR?

**Comment by imshaaz21** [comment]
I would like to work on this. Can you assign it to me?
