### ISSUE TITLE
[Docs] Modify about Contribute to Documentation in Flytekit

### ISSUE THREAD

**Issue by dado5688** [flyteorg/flyte#4236]
### Description

in [here](https://docs.flyte.org/projects/flytekit/en/latest/contributing.html#contribute-to-documentation)
the method how to install requirement should by `pip install -r doc-requirements.txt` rather then `make doc-requirements.txt`

I would like to work on this issue. Please assign it to me.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
`make` command works too. I don't think we need to modify that.
