### ISSUE TITLE
[UI Feature] Change the previous and next arrow on testimonial section on left and right part 

### ISSUE THREAD

**Issue by singodiyashubham87** [flyteorg/flyte#4238]
### Motivation: Why do you think this is important?

When I was scrolling through the website and reached to the testimonial, At first I was confused that where are the previous and next arrows to look for next testimonials and after some time I found them downwards, which was not a good UX to me.

### Goal: What should the final outcome look like, ideally?

The arrows will be on left and right side of the testimonials, so that the UX will improve

I want to work on this issue, Kindly assign me

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by samhita-alla** [comment]
@singodiyashubham87, thank you for creating the issue! Please note that we are not considering website updates as part of Hacktoberfest. We have a dedicated person working on the website. Therefore, we will be closing this issue.
