### ISSUE TITLE
[Housekeeping] Remove unused setting in deployment charts

### ISSUE THREAD

**Issue by gdabisias** [flyteorg/flyte#4251]
### Describe the issue

The deployment chart for datacatalog has the following entry for grpc-2 which is not needed and it should be removed

```
spec:
  {{- with .Values.datacatalog.service.type}}
  type: {{ . }}
  {{- end }}
  ports:
  - name: grpc-2
    port: 8089
    protocol: TCP
    targetPort: 8089
...
  selector: {{ include "datacatalog.selectorLabels" . | nindent 4 }}
{{- end }}
```

[Code reference ](https://github.com/flyteorg/flyte/blob/a11476916c94eb56a4ee91b4e3583327820f8146/charts/flyte-core/templates/datacatalog/service.yaml#L16)

### What if we do not do this?

Nothing bad will happen, just confusing for users

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by HeetVekariya** [comment]
- @gdabisias I think that issue asks to remove the following code:
```
- name: grpc-2
    port: 8089
    protocol: TCP
    targetPort: 8089
```
- If you find the solution correct, can you please assign me the issue.

**Comment by gdabisias** [comment]
@HeetVekariya yep that is the case. I can't assign things, so I'll let maintainers take it from here

**Comment by HeetVekariya** [comment]
- @gdabisias @davidmirror-ops Thank you for giving me chance to contribute. :+1: 
- I have made a PR, ping me if changes required.

**Comment by davidmirror-ops** [comment]
@HeetVekariya 2 merged PRs will give you swag :) Checkout the process here: https://flyte.org/blog/flyte-at-hacktoberfest-2023

**Comment by HeetVekariya** [comment]
This is my first one, if possible I will make another also 👍
