### ISSUE TITLE
[BUG] Flyte PR checks should wait on squash merge

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#4264]
### Describe the bug

Flyte monorepo allows to merge a PR without the checks to be completed

### Expected behavior

Waits for all the PR prechecks to complete before allowing a squash merge

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pingsutw** [comment]
@EngHabu @kumare3 @eapolinario could you guys help update the settings? I don't have permission.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule#creating-a-branch-protection-rule
