### ISSUE TITLE
[BUG] Default input not supported in Flyte task

### ISSUE THREAD

**Issue by ByronHsu** [flyteorg/flyte#4275]
### Describe the bug

```
@task
def task_with_args(x: int = 2):
    ...

@workflow
def wf():
    task_with_args()
```

```
error:
flytekit.exceptions.user.FlyteAssertion: Input was not specified for: x of type simple: INTEGER
```

### Expected behavior

Default input should be passed to task. i.e.
Set `x` as `2` and pass the compilation. 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by adarsh-jha-dev** [comment]
Hey @ByronHsu , could you please assign this issue to me?

**Comment by Future-Outlier** [comment]
I've already examined this issue.
The primary challenge seems to be that we can access both the workflow's input and output interfaces and the task's input and output interfaces.
We need to discuss a method to allow the workflow to recognize the task's input and output interfaces, and then forward the input to the default input.

**Comment by kumare3** [comment]
the problem here is that flyteidl does not support default values for task interfaces. the reason is, if you use a file, where should the file be uploaded? how and when is that done?. But this ties into https://github.com/flyteorg/flyte/issues/910 and https://github.com/flyteorg/flyte/issues/638

**Comment by kumare3** [comment]
I do not think this is a bug, this is intentional behavior. For now i will keep #638 open and close this one
