### ISSUE TITLE
[BUG]: CHANGELOG FOLDER (CHANGELOG/CHANGELOG-v0.10.0.md)

### ISSUE THREAD

**Issue by Ash0807** [flyteorg/flyte#4287]
### Describe the bug

![Screenshot 2023-10-24 164919](https://github.com/flyteorg/flyte/assets/93093775/dae13ce5-2764-4da6-8d6f-bcb669fd5c13)
- The **Found here** link is not working properly as per the statement behavior, when we are clicking on that link. 

### Expected behavior

It should provide the example which is mentioned in the CHANGELOG-v0.10.0.md file.
![Screenshot 2023-10-24 170101](https://github.com/flyteorg/flyte/assets/93093775/8f67757d-4259-4767-b6a2-57e0ec675ceb)

### Screenshots

![Screenshot 2023-10-24 164937](https://github.com/flyteorg/flyte/assets/93093775/a5133532-c33a-44ee-9497-bfd14a865049)
![Screenshot 2023-10-24 165610](https://github.com/flyteorg/flyte/assets/93093775/b0ca6109-6c9a-4038-abe5-52095e3e3746)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
This is a really old changelog, that's no longer exposed to users (we used to have this in a website somewhere).
