### ISSUE TITLE
[BUG] Removed NotificationsConfig.Region field still referenced

### ISSUE THREAD

**Issue by andrewwdye** [flyteorg/flyte#4296]
### Describe the bug

The [NotificationsConfig.Region](https://github.com/flyteorg/flyte/blob/master/flyteadmin/pkg/runtime/interfaces/application_configuration.go#L542-L543) field is no longer populated by the flyte-core chart template after [this change](https://github.com/flyteorg/flyte/pull/4055/files) in flyte 1.10; however, [this code](https://github.com/search?q=repo%3Aflyteorg%2Fflyte%20%22%3D%20config.region%22&type=code) still assumes it's populated in two places (Emailer, NotificationsProcessor). This causes admin to crash on start when either of these functions are enabled.

As a solution we can either
1. Fully remove `NotificationsConfig.Region` from its struct and all references to it. This would complete the deprecation and continue on the path of a breaking change that we've already gone down in 1.10
2. Bring back `NotificationsConfig.Region` and follow a deprecation/removal path in the future

### Expected behavior

It's possible to configure Emailer and/or NotificationsProcessor such that admin doesn't crash

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by adarsh-jha-dev** [comment]
Hey @andrewwdye , could you please assign me this issue? I'd like to work on this

**Comment by adarsh-jha-dev** [comment]
Hey @andrewwdye , i have raised a PR in regarding this issue, could you please have a look at it and let me know if the changes are relevant ?

**Comment by andrewwdye** [comment]
Hi @adarsh-jha-dev I forgot to cross reference here, but this was fixed by https://github.com/flyteorg/flyte/pull/4299
