### ISSUE TITLE
[BUG] Local execution fails with fsspec >= 2023.10.0

### ISSUE THREAD

**Issue by mark-thm** [flyteorg/flyte#4326]
### Describe the bug

When using fsspec >= 2023.10.0, flyte fails to run local execution fails with FileNotFound exceptions because flyte attempts to write to directories that do not exist. flyte's code correctly tries to make local directories but incorrectly passes URIs to pathlib.Path's constructor, which in turn makes a different directory than the code expects.

### Expected behavior

Flyte should be capable of executing using a local tmp_dir with latest fsspec version.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
Fixed in https://github.com/flyteorg/flytekit/pull/2143.
