### ISSUE TITLE
[Feature][Flytekit] Task and Workflow docstrings should be converted to descriptions

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#434]
**Motivation: Why do you think this is important?**
Python way of adding descriptions is using docstrings. Today this is not very well integrated into flytekit

**Goal: What should the final outcome look like, ideally?**
The description of a task or a Workflow should be the comment in the body of the task/workflow by default. This should then be visible in the UI.

**Describe alternatives you've considered**
NA

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
NA

**Additional context**
NA

**Is this a blocker for you to adopt Flyte**
NA

**Comment by kumare3** [comment]
Today the TaskSpec, WorkflowSpec & LaunchPlanSpec do not have Descriptions.
My preference is that we have 2 parts for a Description and we create a new message called
```proto
message Description {
    string description;
    string content_type; // legal mimetype  like text/string, html etc
};
```

The idea is that we should allow these descriptions to automatically become a documentation.

One thing I found is we can use NamedEntity, but its not clear when to use this - @katrogan

**Comment by evalsocket** [comment]
@kumare3 Can you give me more detail about the issue, Apart from adding `Description` in proto

**Comment by kumare3** [comment]
@evalsocket I am actually in favor of closing this issue in favor of - https://github.com/flyteorg/flyte/issues/531
