### ISSUE TITLE
 [Docs] The --force argument to flytectl is not documented

### ISSUE THREAD

**Issue by tblom** [flyteorg/flyte#4356]
### Description

--force is documented when you `flytectl update launchplan --help` from the CLI.

But it is not documented in the online docs here:

https://docs.flyte.org/projects/flytectl/en/latest/gen/flytectl_update_launchplan.html

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by SophieTech88** [comment]
Can I try this issue? @pingsutw

**Comment by Future-Outlier** [comment]
@SophieTech88 You can try it now, first come first serve, and I can help you.

**Comment by neverett** [comment]
Closed by https://github.com/flyteorg/flytectl/pull/443
