### ISSUE TITLE
[BUG] Large error in task causes workflow to be stuck in RUNNING forever

### ISSUE THREAD

**Issue by annadcunningham** [flyteorg/flyte#4371]
### Describe the bug

If a task raises an error with a very long error message, the message is not truncated, and is too large for flytepropeller/flyteadmin to correctly update the workflow status to FAILED. Instead, propeller continually logs the following:
```
Failed to update workflow. Error [rpc error: code = ResourceExhausted desc = trying to send message larger than max (2805993 vs. 2097152)]
```
and the workflow status stays in RUNNING forever unless aborted via the UI.

### Expected behavior

The workflow status should be updated to FAILED to reflect the task failure.

### Additional context to reproduce

We've been able to reproduce a minimal example of this behavior using flyte milestone release 1.6.2 & flytekit 1.10.0:

```
from flytekit import workflow, task

@task
def raise_giant_error() -> None:
    error_line = "This is a really big error"
    n_lines = 100000
    raise ValueError("\n".join([error_line] * n_lines))

@workflow
def giant_error_wf() -> None:
    raise_giant_error()
```

this results in the task being marked as FAILED showing the full giant error in the UI, but the workflow remains stuck in RUNNING. This happens even with UseOffloadedWorkflowClosure turned on.

### Screenshots

<img width="1711" alt="image" src="https://github.com/flyteorg/flyte/assets/16860843/416e7cdb-0efa-46d2-ac54-13635db579e7">

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
Closing as fixed in https://github.com/flyteorg/flyte/pull/4631 which correctly truncates error messages in flyteadmin events.
