### ISSUE TITLE
[BUG] FAIL_AFTER_EXECUTABLE_NODES_COMPLETE tries to execute nodes which should never start when using dynamic

### ISSUE THREAD

**Issue by fellhorn** [flyteorg/flyte#4384]
### Describe the bug

In a specific complex workflow with dynamic tasks and caching and the `FAIL_AFTER_EXECUTABLE_NODES_COMPLETE` workflow failure policy, we observed a truly peculiar bug:

A node which should never be tried to execute as it depends on an already failed (dynamic) task, is not correctly skipped but can't be started and fails after 50 retries with:

```
Workflow[...] failed. RuntimeExecutionError: max number of system retry attempts [51/50] exhausted. Last known status message: Failed to check Catalog for previous results: failed to read inputs when trying to query catalog: [READ_FAILED] failed to read data from dataDir [.../inputs.pb]., caused by: path:gs://.../inputs.pb: not found
```
from https://github.com/flyteorg/flyte/blob/feeda193f285116a207342d17b173217650f3b0a/flytepropeller/pkg/controller/nodes/cache.go#L96

---

A minimal example:

```py
from flytekit import WorkflowFailurePolicy, dynamic, task, workflow

CACHE = "0.0.25" # Bumping cache between retries
USE_CACHE = True # Bug only occurs with active caching

@task(cache=USE_CACHE, cache_version=CACHE)
def my_task(number: int, will_fail: bool) -> int:
    if will_fail:
        raise Exception("Failure")
    return number + 1


@dynamic
def dyn_task(will_fail: bool) -> int:
    return my_task(number=42, will_fail=will_fail)


@workflow(failure_policy=WorkflowFailurePolicy.FAIL_AFTER_EXECUTABLE_NODES_COMPLETE)
def main():
    result1 = dyn_task(will_fail=False)
	# This dyn_task is never started although it should be due to the failure policy
    my_task(number=result1, will_fail=False) # <- This is stuck in `Unknown`

    result2 = dyn_task(will_fail=True)
	# This my_task should never be executed as it depends on the dyn_task above which will fail
    my_task(number=result2, will_fail=True) # <- This is stuck in `Unknown` and causes the cache check error after 50 retries
```

![image](https://github.com/flyteorg/flyte/assets/26092524/a35281ea-c8a9-4c7c-a8cb-9684cc51b9a6)

### Expected behavior

```py
@workflow(failure_policy=WorkflowFailurePolicy.FAIL_AFTER_EXECUTABLE_NODES_COMPLETE)
def main():
    result1 = dyn_task(will_fail=False)
	# Should be executed
    my_task(number=result1, will_fail=False)

    result2 = dyn_task(will_fail=True)
	# Should be marked as `Skipped`
    my_task(number=result2, will_fail=True)
```

### Additional context to reproduce

We debugged this with flyte `1.10.0` but we believe we have seen this already before.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
Cc @EngHabu / @hamersaw this is an assumption break

**Comment by fg91** [comment]
> Cc @EngHabu / @hamersaw this is an assumption break

Which assumption is broken? Is there a way to catch this and raise an explicit error?

**Comment by hamersaw** [comment]
@fellhorn would you mind testing the proposed fit here? I think I just missed a phase check during the fastcache work.

**Comment by fg91** [comment]
> @fellhorn would you mind testing the proposed fit here? I think I just missed a phase check during the fastcache work.

We definitely will, thanks a lot for looking into this! :)

**Comment by fellhorn** [comment]
@hamersaw We tested the fix in our `staging` setup, looks good so far.

We are about to roll it out to our `production` setup to see if it fixes all occurrences. We usually see the error a couple of times per week. Will come back to you end of the week.

Thanks a lot already!
