### ISSUE TITLE
[Docs] Add instructions to use ImageSpec on apple silicon

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#4419]
### Description

In order to build images with ImageSpec on Apple M* machines, you'll need check off the following box on Docker desktop.

![Screenshot 2023-11-10 at 12 56 20 PM](https://github.com/flyteorg/flyte/assets/2816689/2bd4a88f-62a2-4345-9e6e-2ac0a719c470)

Need to update the doc with this information: https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/customizing_dependencies/image_spec.html

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by thomasjpfan** [comment]
For the last few months, I have had this setting on and it seems to work now. Currently, I am on Docker Desktop `4.32.0` (which is working).
