### ISSUE TITLE
[Feature]Minimal deployment overlay to serve as starting point for Flyte installation

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#444]
**Motivation: Why do you think this is important?**
Provide a minimal kustomize Overlay, which can be used as a starting point for cloud deployments. This should go alongwith a tutorial of how to configure Flyte for AWS/GCP/Azure etc.

**Goal: What should the final outcome look like, ideally?**
Any user should be able to follow this doc and setup Flyte in their own infrastructure.

**Describe alternatives you've considered**
Current getting started doc is too simple. Flyte provides a lot of knobs for complex setups and discovery and documentation for these knobs is not readily available

**Flyte component**
- [ ] Overall
- [x] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Comment by schottra** [comment]
Implemented by lyft/flyteconsole#92
Available in flyteconsole v0.12.0

**Comment by schottra** [comment]
Oops. I didn't realize this issue was tracking more than just the inputs/outputs. Reopened it. I'll let @kumare3 decide when it's done.

**Comment by kumare3** [comment]
all cloud providers are supported through helm and terraform.
