### ISSUE TITLE
[Housekeeping] Use ruff instead of black, flake8, isort, and autoflake.

### ISSUE THREAD

**Issue by thomasjpfan** [flyteorg/flyte#4447]
### Describe the issue

[ruff](https://github.com/astral-sh/ruff) can now be used as a replacement for `flake8`, `isort`, `black` and `autoflake8`. From my experience on other projects, `ruff` has been solid and faster than the previous solutions. Another advantage of `ruff` is that it simplifies the tooling used for development.

### What if we do not do this?

We continue to install `black`, `flake8`, `isort`, and `autoflake` for development and not use the speed improvements from `ruff`.

### Related component(s)

flytekit

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Future-Outlier** [comment]
I think this is great!
Just need to remember to check cases like this.
https://github.com/flyteorg/flytekit/pull/1822/files#diff-46ff2b893d689f1eaae506792c23cb951512e78a48437a9abe45395e11059ae6R248
