### ISSUE TITLE
[Docs] need to improve the documentation around data flow between flyte tasks

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#4456]
### Description

reference slack thread: https://discuss.flyte.org/t/10262872/hi-all-just-getting-my-hands-dirty-and-trying-to-wrap-my-hea

the appropriate location to add the relevant documentation is https://docs.flyte.org/en/latest/concepts/data_management.html.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by DenChenn** [comment]
@davidmirror-ops 
The docs mostly use images to explain data flow between tasks, which might not be super clear.
I’d be glad to help make this section easier to follow :)

**Comment by DenChenn** [comment]
#take

**Comment by DenChenn** [comment]
#take

**Comment by davidmirror-ops** [comment]
@DenChenn thank you! let us know any questions please.

**Comment by DenChenn** [comment]
@davidmirror-ops done :)
