### ISSUE TITLE
[Docs] document file and directory streaming

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#4460]
### Description

the flytefile and flytedirectory streaming feature is currently experimental. nonetheless, it's important that we document it in the user guide: https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/data_types_and_io/file.html and https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/data_types_and_io/folder.html pages. 

streaming PR: https://github.com/flyteorg/flytekit/pull/1512
additional details can be found in the [release notes](https://flyte.org/blog/flyte-1-5-streaming-support-pod-templates-partial-tasks-and-more).

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by neverett** [comment]
Added to planned work for docs team.

**Comment by DenChenn** [comment]
I think I can work on this one~

**Comment by DenChenn** [comment]
@davidmirror-ops done ✅

**Comment by davidmirror-ops** [comment]
Completed in #5879
