### ISSUE TITLE
[Docs] document how to set the cache for container tasks

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#4461]
### Description

the [container tasks documentation](https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/customizing_dependencies/raw_container.html) lacks info on how to set the cache. this can be achieved through metadata:

```python
ContainerTask(metadata=TaskMetadata(cache=True, cache_version="1.0"))
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by neelshah2409** [comment]
Hi @davidmirror-ops I would like to work on it !
