### ISSUE TITLE
[Docs] provide clarification in the docs regarding interruptible behavior when using map tasks

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#4462]
### Description

TL;DR: interruptible should work the same with maptasks as with regular python tasks — the retries field in the task annotation shouldn't be necessary.

slack thread: https://discuss.flyte.org/t/13886407/hey-i-m-seeing-some-differences-in-how-spot-revocation-preem#f766657c-66b4-4e85-9d8c-bef4db83f3f6

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by RaghavMangla** [comment]
Hi, I would like to work on this

**Comment by RaghavMangla** [comment]
Hi! @samhita-alla @davidmirror-ops, my PR: https://github.com/flyteorg/flyte/pull/5845
lmk if any changes are required

**Comment by RaghavMangla** [comment]
Hi! If everything looks fine, I think we can close this issue

**Comment by RaghavMangla** [comment]
Hi, @samhita-alla @davidmirror-ops, my PR: https://github.com/flyteorg/flyte/pull/5845, can u pls provide a review
