### ISSUE TITLE
[Docs] document the process of rendering a notebooktask in a flyte deck

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#4463]
### Description

[the papermill example](https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/papermill_plugin/simple.html) in the flyte docs lacks info on rendering the notebook in a deck. to achieve this, add `render_deck=True` and `disable_deck=False` to the notebooktask.

slack thread for reference: https://discuss.flyte.org/t/15484282/hi-all-flyte-rookie-here-maybe-you-can-help-me-out-i-m-tryin#33b0b813-6822-4451-8977-eaec3387a4ff

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by RaghavMangla** [comment]
Hi, I would like to work on this

**Comment by davidmirror-ops** [comment]
@RaghavMangla a change merged **today** changes location for most of the content in the docs. Please update your fork to prevent conflicts. Thanks!

**Comment by RaghavMangla** [comment]
Hi! this is the link for my pull request, https://github.com/flyteorg/flytesnacks/pull/1741

**Comment by RaghavMangla** [comment]
hi, i have fixed the deprecated issue, it shd work now, link
https://github.com/flyteorg/flytesnacks/pull/1742/commits/954fe57bd0b7c678d17e8256d55038db62c54bb8

**Comment by RaghavMangla** [comment]
https://github.com/flyteorg/flytesnacks/pull/1742

**Comment by RaghavMangla** [comment]
Hi, @davidmirror-ops @samhita-alla, can u pls review my PR, it's 1742, link shared above

**Comment by RaghavMangla** [comment]
<img width="1470" alt="Screenshot 2024-10-07 at 8 13 04 PM" src="https://github.com/user-attachments/assets/c7af4d51-430d-4789-ab13-8236bbefbe57">
Hi! I have shared the screenshot of the notebook being rendered after running the workflow on Flyte sandbox, this is my pull request https://github.com/flyteorg/flytesnacks/pull/1742

**Comment by RaghavMangla** [comment]
i think this pull request does exactly what's desired
https://github.com/flyteorg/flytekit/pull/2791

it changes the notebooktask in papermill plugin in flyte docs, was not able to render html page due to version conflicts but have added enable_deck=True in notebook task

**Comment by RaghavMangla** [comment]
@samhita-alla pls review this pr flyteorg/flytesnacks/pull/1742

**Comment by RaghavMangla** [comment]
@samhita-alla just noticed that my PR https://github.com/https://github.com/flyteorg/flytesnacks/pull/1742 failed with this error 

Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c apt-get update     && apt-get install -y software-properties-common     && add-apt-repository ppa:deadsnakes/ppa     && apt-get install -y     && apt-get update     && apt-get install -y     cmake     curl     python3.8     python3.8-venv     python3.8-dev     make     build-essential     libssl-dev     libffi-dev     python3-pip     zlib1g-dev     vim     wget" did not complete successfully: exit code: 1

can u suggest a fix

**Comment by RaghavMangla** [comment]
Hi! @samhita-alla all tests have passed for https://github.com/flyteorg/flytesnacks/pull/1742, will it be considered for hacktoberfest-accepted

**Comment by RaghavMangla** [comment]
Hi! @samhita-alla are there any updates that I need to make?

**Comment by RaghavMangla** [comment]
Hi! @samhita-alla @davidmirror-ops, my PR (which was relevant to this issue): https://github.com/flyteorg/flytekit/pull/2791 has been merged, in the PR I added the enable_deck=True line in notebookTask in the jupyter notebook documentation of papermill plugin

**Comment by RaghavMangla** [comment]
Could you please share any suggestions or changes that might be required? If everything looks good from your end, I believe we can go ahead and close this issue.

**Comment by RaghavMangla** [comment]
@davidmirror-ops @samhita-alla Could you please share any suggestions or changes that might be required?
