### ISSUE TITLE
[BUG] container_image override does not work with map_task

### ISSUE THREAD

**Issue by gvashishtha** [flyteorg/flyte#4493]
Try this minimal reproducible example:

```
@task
def my_mappable_task(a: int) -> typing.Optional[str]:
    return str(a)

@workflow
def my_map_wf(x: typing.List[int]) -> typing.List[typing.Optional[str]]:
    return map_task(
        my_mappable_task,
        concurrency=10,
        min_success_ratio=0.75,
    )(a=x).with_overrides(container_image="random:image")
```

I would expect to see flyte attempt to pull an image called `random:image` for the `my_mappable_task` invocations. Instead, Flyte uses the default base image

**Comment by pingsutw** [comment]
#take

**Comment by pingsutw** [comment]
fixed it

**Comment by andre-bauer** [comment]
Did that really solve the issue? In my runs it seems the container image is used before `with_overrides` is called 😢  changing it with this method does not work for me.

**Comment by ai-rnatour** [comment]
This is no longer working in version 1.11.0 of flytekit (worked as of 1.10.2).
