### ISSUE TITLE
[BUG] Can't retrieve env vars from pyflyte run

### ISSUE THREAD

**Issue by jiwidi** [flyteorg/flyte#4503]
### Describe the bug

I am not able to retrieve env pars passed to pyflyte run with the --env/--envvars parameter. They are not accessible within the workflow code.

Basing myself on documentation https://docs.flyte.org/projects/flytekit/en/latest/pyflyte.html and issue https://github.com/flyteorg/flyte/issues/4092 where it mentions its possibility.

### Expected behavior

To pass env vars to pyflyte run and access them during code execution time

### Additional context to reproduce

I have a python file main.py:

```
from flytekit import task, workflow
import os

@workflow
def workflow() -> None:
    print([key for key in os.environ])
    print(os.environ["DUMMY_KEY"])
    return None
```

Which can be run with 

`pyflyte run --envvars '{"DUMMY_KEY"="DUMMY_VALUE"}' main.py workflow`
or 
`pyflyte run --env '{"DUMMY_KEY"="DUMMY_VALUE"}' main.py workflow`

Both result in failure:

```
Failed with Unknown Exception <class 'KeyError'> Reason: "Error encountered while executing 'workflow':\n  'DUMMY_KEY'"
"Error encountered while executing 'workflow':\n  'DUMMY_KEY'"
```

Due to the line at print(os.environ["DUMMY_KEY"]) and no presence of DUMMY_KEY in the list of os.ENVIRON

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by jiwidi** [comment]
> _🤖_
> 
> Hello @jiwidi,
> 
> I'm [Dosu](https://dosu.dev), a bot here to assist you with your issues and queries regarding Flyte. While we wait for one of our human maintainers, I'm here to help you understand, troubleshoot, and resolve bugs, as well as guide you on your journey to becoming a contributor. Let's work together to resolve your issue!
> 
> Based on the information you've provided and the similar issues I've found in the Flyte repository, it seems that the environment variables passed to `pyflyte run` with the `--env/--envvars` parameter are not being exported to the environment of your script. This is why they are not accessible within your workflow code.
> 
> To make the environment variables available within the workflow code, you need to export them in your script. Here's how you can modify your script:
> 
> ```shell
> #!/bin/bash
> 
> # Our SDK entrypoint can be configured to call this script
> # This script maps that command to the conventional location of the virtual environment in Flyte containers
> 
> set -e
> 
> # Export the environment variables
> export $(cut -d= -f1 <path_to_your_env_file>)
> 
> . ${VENV}/bin/activate
> 
> exec $*
> ```
> 
> In this script, `<path_to_your_env_file>` should be replaced with the path to the file containing your environment variables. The `cut` command extracts the names of the variables, and `export` makes them available to the environment.
> 
> Please note that this solution assumes that your environment variables are stored in a file in the format `VARNAME=value`. If your environment variables are passed in a different way, you might need to adjust the script accordingly. You can refer to the [flyte_venv.sh](https://github.com/flyteorg/flyte/blob/master/script/flyte_venv.sh?rgh-link-date=2023-11-30T12%3A45%3A52Z) script in the Flyte repository for more details.
> 
> As for the exact mechanism by which the `--env/--envvars` parameter passes environment variables to `pyflyte run`, I wasn't able to find a specific answer within the repository. If you have more information about how you're passing the environment variables or if there's a specific part of the process you're interested in, please let me know and I'll do my best to assist you further.
> 
> I hope this helps! If you have any other questions or need further clarification, feel free to ask.
> 
> -[Dosu](https://dosu.dev)
> 
> ## Sources
> * [[Core feature] Injection of env vars at run time [discussion needed]](https://github.com/flyteorg/flyte/issues/2447)
> * [script/flyte_venv.sh](https://github.com/flyteorg/flyte/blob/master/script/flyte_venv.sh?rgh-link-date=2023-11-30T12%3A45%3A52Z)

This is not the best solution, as the env vars i would be using come from another runner so wont be put on a file. I can hack something prior to flyte running so I put them on a file with a bash script but prefer not to and do directly within the pyflyte command

**Comment by jasonlai1218** [comment]
I would like to work on this, could you assign me, please?

**Comment by jasonlai1218** [comment]
#take

**Comment by jiwidi** [comment]
@jasonlai1218 hey! did you had the time to look on this?

**Comment by jiwidi** [comment]
@eapolinario @jasonlai1218 hello?

**Comment by eapolinario** [comment]
@jiwidi , in your example you're trying to access the environment variables in a workflow, not in a task. The arguments set via `--env` are passed to the tasks that compose a workflow, not the workflow itself (since that's only used at registration time to get the structure of the DAG).

Can you talk about your use case a bit more?

**Comment by jiwidi** [comment]
> @jiwidi , in your example you're trying to access the environment variables in a workflow, not in a task. The arguments set via `--env` are passed to the tasks that compose a workflow, not the workflow itself (since that's only used at registration time to get the structure of the DAG).
> 
> Can you talk about your use case a bit more?

Yeah! Maybe you can tell me if there is a better way to do what i had in plan.

I want to run the same workflow but with different configurations. Lets say is an ML job that fetches from a data source, does its compute, outputs some artifacts and its finished.

I want to parametrize the data source config and the output path, the idea in the original post was to pass those with env variables as those are accessible to me when calling pyflyte. As a workaround right now I'm saving the env vars i need into a yaml file and reading it from the workflow to later on pass the values to the task.

Based on your comment, then my task should have access to the vars passed? When i tried running this workflow:

```python
from flytekit import task, workflow
import os

@task
def sample_task() -> None:
    print([key for key in os.environ])
    print(os.environ["DUMMY_KEY"])
    return None


@workflow
def workflow() -> None:
    sample_task()
    return None
```

With 

`pyflyte run --envvars '{"DUMMY_KEY"="DUMMY_VALUE"}' main.py workflow`
or
`pyflyte run --env '{"DUMMY_KEY"="DUMMY_VALUE"}' main.py workflow`

Both resulted in failure with no access to the var. How can i acess it within the task then?

**Comment by eapolinario** [comment]
@jiwidi , this is a bug in local executions. You should be able to do `pyflyte run --env DUMMY_KEY=DUMMY_VALUE main.py workflow`. The same works on a Flyte cluster, i.e. `pyflyte run --env DUMMY_KEY=DUMMY_VALUE --remote main.py workflow`.

https://github.com/flyteorg/flytekit/pull/2132 has a fix.

**Comment by jiwidi** [comment]
> @jiwidi , this is a bug in local executions. You should be able to do `pyflyte run --env DUMMY_KEY=DUMMY_VALUE main.py workflow`. The same works on a Flyte cluster, i.e. `pyflyte run --env DUMMY_KEY=DUMMY_VALUE --remote main.py workflow`.
> 
> [flyteorg/flytekit#2132](https://github.com/flyteorg/flytekit/pull/2132) has a fix.

Hi! Thats great! Thanks for fixing the bug :)
