### ISSUE TITLE
[Docs] move aws scheduler docs to the legacy section

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#4513]
### Description

delete documentation related to AWS scheduler configuration, as the flyte native scheduler should just work.

reference slack thread: https://discuss.flyte.org/t/15852550/hi-team-i-have-created-a-simple-test-flyte-scheduler-using-b#929e7edd-c801-4dbb-bdbf-61cb36903727

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by RaghavMangla** [comment]
Hi, I would like to work on this

**Comment by RaghavMangla** [comment]
Hi! @samhita-alla, this is the github repo for [flyte docs](https://github.com/RaghavMangla/flytekit), right?

**Comment by RaghavMangla** [comment]
Hi! @samhita-alla, this is my PR: https://github.com/flyteorg/flyte/pull/5826

**Comment by RaghavMangla** [comment]
Hi! @samhita-alla, this is my PR: https://github.com/flyteorg/flyte/pull/5826, can u pls review it

**Comment by RaghavMangla** [comment]
Could you please share any suggestions or changes that might be required? If everything looks good from your end, I believe we can go ahead and close this issue.

**Comment by RaghavMangla** [comment]
@davidmirror-ops @samhita-alla Could you please share any suggestions or changes that might be required?

**Comment by RaghavMangla** [comment]
Hi, @samhita-alla, can u pls review my PR: #5826
