### ISSUE TITLE
[BUG] Failed with running tensorflow plugin in array node map task.

### ISSUE THREAD

**Issue by chaohengstudent** [flyteorg/flyte#4515]
### Describe the bug

Running `array node map task` will failed with following Error:
```
Workflow[flytesnacks:development:my_project.workflows.maptask_with_TFJob_v2.mnist_tensorflow_workflow] failed. 
RuntimeExecutionError: max number of system retry attempts [11/10] exhausted. 
Last known status message: failed at Node[n0]. 
RuntimeExecutionError: failed during plugin execution, caused by: failed to execute handle for plugin [tensorflow]: number of worker should be more then 0
```

It seems that the wrong custom data passing to tensorflow plugin.

### Expected behavior

Pass with no error

### Additional context to reproduce

1. Activate demo cluster with tensorflow plugin enable.
2. pyflyte run following sample code.

```
from flytekit import task, workflow, ImageSpec
from flytekit.experimental import map_task
from flytekitplugins.kftensorflow import TfJob, Worker, Chief, PS, Evaluator
from typing import Optional, List

image_spec = ImageSpec(packages=["flytekit", "flytekitplugins-kftensorflow", "tensorflow"], registry="chaoheng"
                       , registry_config="/home/chaoheng/.docker/config.json")

task_config = TfJob(
    worker=Worker(replicas=1),
    chief=Chief(replicas=1),
    ps=PS(replicas=1),
    evaluator=Evaluator(replicas=1),
)


@task(task_config=task_config, container_image=image_spec)
def t3(a: int) -> int:
    return a + 1


@workflow
def wf() -> List[Optional[int]]:
    mt = map_task(t3)(a=[1, 2, 3])
    return mt

```

### Screenshots

![image](https://github.com/flyteorg/flyte/assets/106939297/3ef48efb-f1cf-474e-9fd8-7d354268b2a8)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
We need to be very careful here. Offically, `ArrayNode` does not officially support task types other than python functions, container tasks, and pod tasks. This may work because the `pluginStateBytes` that are hardcoded in `ArrayNode` fit the kfoperator plugins. Support for all task types and plugins is in the pipeline for `ArrayNode` and will hopefully drop in the next few months.
