### ISSUE TITLE
Add administrator doc for enabling SageMaker plugin

### ISSUE THREAD

**Issue by bnsblue** [flyteorg/flyte#456]

**Comment by kumare3** [comment]
@bnsblue do you know what is the status on this doc? If you have some internal documentation, can you please help fill it out - at-least a PR in this section of the docs - https://docs.flyte.org/en/latest/plugins/aws/index.html

**Comment by kumare3** [comment]
@pingsutw I think you have completed this one right?

**Comment by pingsutw** [comment]
yes, it's done
