### ISSUE TITLE
[FlyteCTL Feature] `flytectl update launchplan --archive` doesn't archive but sets the LP state to inactive

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#4563]
### Describe the feature/command for FlyteCTL

Currently to inactivate a launch plan schedule, `flytectl update launchplan --archive` is the only option available in flytectl but this confusingly conflicts with `flytectl update launchplan-meta --archive`

The former really sets the schedule state to `inactive` so we could consider updating the flag to be clearer.

There should be a clear option to disable a launch plan without necessarily archiving it

### Provide a possible output or UX example

Introduce something like ``flytectl update launchplan --inactive` or something similar as a distinct command.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by asoundarya96** [comment]
@eapolinario I would like to work on this issue.

**Comment by asoundarya96** [comment]
#self-assign

**Comment by asoundarya96** [comment]
@eapolinario - opened a PR to introduce - `flytectl update launchplan --deactivate`
