### ISSUE TITLE
[Housekeeping] Ensure accurate ActiveNodeExecutions and ActiveTaskExecutions metrics

### ISSUE THREAD

**Issue by hamersaw** [flyteorg/flyte#4593]
### Describe the issue

Currently the only `ActiveNodeExecutions` and `ActiveTaskExecutions` metrics exported are from flyteadmin. This can result in inaccuracies if, for example, flyteadmin restarts or there is an uncommon inconsistency in data and control plane state (ex. FlyteWorkflow CR manually deleted).

### What if we do not do this?

If we do nothing, then these metrics are often inaccurate and therefore useless.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
One proposal, is to move these metrics to FlytePropeller so they can more accurately reflect actual execution status. A relatively high-level design is as follows:
- Add `NodeExecutionCount` and `TaskExecutionCount` values to the `ExecutionContext` through the [ControlFlow struct](https://github.com/flyteorg/flyte/blob/master/flytepropeller/pkg/controller/executors/execution_context.go#L33-L33) and increment these accordingly as FlytePropeller progresses through DAG execution ([entrypoint here](https://github.com/flyteorg/flyte/blob/master/flytepropeller/pkg/controller/nodes/executor.go#L177-L177)).
- Maintain an in-memory mapping of `execution_id` to node and task execution counts that is updated as FlytePropeller evaluations executions. This update will in-turn update the prometheus gauge metric.
- Use a separate go routine to periodically iterate over the in-memory mapping and remove executions that have been manually deleted (decrementing the gauge metric).

With this solution the metric under FlytePropeller restarts will be eventually consistent. Although, as the workflow reeval duration is, by default, `30s` it should converge within that timeframe.

**Comment by Future-Outlier** [comment]
@hamersaw Are you working on this issue?
If not, can I try it?

**Comment by hamersaw** [comment]
@Future-Outlier this is already being addressed, will assign accordingly. Thanks for the initiative!
