### ISSUE TITLE
[Docs] document the `pyflyte get launchplan` command

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#4613]
### Description

here's the PR that adds the command to flytekit: https://github.com/flyteorg/flytekit/pull/1930

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by shinigami-777** [comment]
I think this issue is already solved. You can find the documentation at https://docs.flyte.org/en/latest/api/flytekit/pyflyte.html#pyflyte-get-launchplan

**Comment by davidmirror-ops** [comment]
@shinigami-777 you're right. Thank you and sorry.
