### ISSUE TITLE
[Docs] a colon is not allowed in the version string

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#4616]
### Description

add a note specifying that `:` cannot be added to a version.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@samhita-alla , can you add more details to this? IIRC, this was related to flyteconsole not being able to render a task/workflow registered with a version containing a colon, right?

**Comment by samhita-alla** [comment]
yes, we cannot launch a workflow when there's a colon:

<img width="1023" alt="image" src="https://github.com/flyteorg/flyte/assets/27777173/e19fb550-a1ad-4cf5-b760-0354369c7476">
