### ISSUE TITLE
[Docs] Write docs and examples for GPU acceleration

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#4620]
### Description

[This PR](https://github.com/flyteorg/flyte/pull/4172) contains a lot of the information needed to document this feature. Basically we just need to turn this into a flytesnacks example.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by neverett** [comment]
Added to planned work for docs team.

**Comment by davidmirror-ops** [comment]
Just merged https://github.com/flyteorg/flyte/pull/5515 that does exactly this. It's jut not a flytesnacks example but extends the user guide having tested all the use cases on AKS with V100 and A100 GPUs: https://docs.flyte.org/en/latest/user_guide/productionizing/configuring_access_to_gpus.html
