### ISSUE TITLE
[BUG] UI unresponsive for large workflows

### ISSUE THREAD

**Issue by klekass** [flyteorg/flyte#4636]
### Describe the bug

The UI becomes unresponsive/laggy for workflow executions with a large number of nodes.

Example:

```
import string
import random
from flytekit import task, Workflow

@task
def t1() -> str:
    return "".join(random.choice(string.ascii_letters) for _ in range(100))

wb = Workflow(name="my_workflow")
for _ in range(100):
    node = wb.add_entity(t1)
```

This is caused by querying the task status of each task. The UI becomes responsive again, after all the data is loaded.
![image](https://github.com/flyteorg/flyte/assets/48991997/f0601511-fff7-4a26-876a-eb5360d89e2e)

### Expected behavior

The UI should not block until all data is loaded.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
the new ui updated resolved this problem. closing the issue
