### ISSUE TITLE
[Core feature] Allow to specify the working dir for a container image

### ISSUE THREAD

**Issue by vkaiser-mb** [flyteorg/flyte#4638]
### Motivation: Why do you think this is important?

Imagine you have a workflow with 2 tasks A and B. Both tasks have different container images.
Currently, the working dir is per default "/root".
Both container images dont have this folder accessible. Instead it would be great if you could specify for every image the according working dir that is compatible with the image.  
You can change the working dir via the CLI, but this has two downsides:
- You cant specify different working dirs for task A and task B
- Working dir and container depend on each other and therefore should be defined in the same place in code.

Note: In the local usecase, the specified working dir can be ignored, similar like the container_image is ignored.

### Goal: What should the final outcome look like, ideally?

```
@task(container_image=Container(image="imageFoo", working_dir="/home/foo"))
def foo():

@task(container_image=Container(image="imageBar", working_dir="/home/bar"))
def bar():
```

and

```
@task(container_image=Container(image=ImageSpec(....), working_dir="..."))
def foo():
```

of course it could be compatible with the old interface and still allow do specify only images if no working dir modification is needed:
```
@task(container_image="imageFoo")
def foo():

@task(container_image=ImageSpec(....))
def foo():

```

### Describe alternatives you've considered 

To avoid nesting, Imagespec could also have the option of working dir directly:

```
@task(container_image=ImageSpec(base_image="imageFoo", working_dir="/home/foo"))
def foo():
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
We talked about this in slack and there was consensus around letting the working dir be set in the docker images instead. 

Closing this issue for now, please re-open if you feel that this might be worth more discussion.

**Comment by kumare3** [comment]
@eapolinario but we need to make a change to not set any working for as default right

**Comment by vkaiser-mb** [comment]
How exactly would I specify the working dir in the docker image? Will it take the dockers CWD? Would I specify a Env var? Since I did not check the mechanics, I wonder how the upload works. (My assumption was that is the reason for specifying the working dir in advance. In our workaround we also needed to modify the PYTHONPATH env var.) Arent those things that would need to be adapted in the flyte code?

**Comment by vkaiser-mb** [comment]
@eapolinario Happy new year! Will there be another Github issue to resolve this in your proposed way?

**Comment by kumare3** [comment]
@vkaiser-mb - @eapolinario was actually out on vacation and is back tomorrow. I am re-opening the issue to actually make the change in flytekit.

So the change is as follows
1. Change pyflyte run's default run path to be `current_dir` or `.`
2. Change base docker images to set WORKING_DIR to desired location

We will use this issue to track these 2 changes

**Comment by vkaiser-mb** [comment]
Awesome! Thanks.
