### ISSUE TITLE
[Docs] document resolution for forbidden error when accessing dask resources

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#4653]
### Description

the Flyte service account should have access to Dask's custom resources. one may need to bind cluster role to the service account. here's how it can be accomplished: https://discuss.flyte.org/t/16187425/hi-i-am-trying-to-enable-the-dask-plugin-in-my-flyte-deploym#b67e7725-c7e8-4968-bcd5-a8167320c9ad. need to document the same on the dask deployment page.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by RaghavMangla** [comment]
Hi, I would like to work on this

**Comment by davidmirror-ops** [comment]
@RaghavMangla please let us know any questions you may have. Looking forward to your contributions!

**Comment by Soot3** [comment]
@davidmirror-ops I can take this on as well. So editing this [page](https://docs.flyte.org/en/latest/flytesnacks/examples/k8s_dask_plugin/index.html) to explain that a cluster role is needed for dask custom resources

**Comment by davidmirror-ops** [comment]
@Soot3 right, including the suggested permissions
