### ISSUE TITLE
[Docs] document clarifying notes about the data lifecycle

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#4683]
### Description

document to update: https://docs.flyte.org/en/latest/concepts/data_management.html

what to add: https://discuss.flyte.org/t/15995893/hi-community-i-am-trying-to-understand-the-flyte-data-lifecy#b374eea0-0c32-44fd-875a-5b79d4a8180b

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by davidmirror-ops** [comment]
It's a recurring question: how to delete data from S3 buckets. Flyte doesn't have a way to do this but setting a lifecycle policy on the buckets is an usual approach.

**Comment by Murdock9803** [comment]
@samhita-alla @davidmirror-ops I would like to take up this issue, please assign this to me So I can start working on it :raised_hands:

**Comment by davidmirror-ops** [comment]
@Murdock9803 done. Please let us know soon if you have questions or need help. Thanks!

**Comment by Murdock9803** [comment]
Sure, I'll definitely start working on it at the earliest and ask related doubts :raised_hands:

**Comment by popojk** [comment]
Hi @davidmirror-ops @samhita-alla , can I also working on this issue?

**Comment by davidmirror-ops** [comment]
@popojk sure!

**Comment by popojk** [comment]
Hi @davidmirror-ops , thanks for assigning me this issue. I want to clarify whether the information I need to add to doc includes:
1. Flyte cannot cleaned up the raw data stored in storage services such as s3 or minio, but user can do so by setting lifecycle policies in the storage service.
2. If cacheing is enabled, be sure to set the cache expiration smaller than that of storage lifecycle.

Moreover, I found some example code error in the original doc. Do you mind me to fix them in the same PR of this issue?

Thank you very much!

**Comment by davidmirror-ops** [comment]
@popojk 
1. Correct
2. Correct, this is the setting in propeller: https://docs.flyte.org/en/latest/deployment/configuration/generated/flytepropeller_config.html#max-cache-age-config-duration
Thank you!
