### ISSUE TITLE
[Docs] document that execution IDs are unique within a project-domain

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#4684]
### Description

document that execution IDs are unique within a project-domain on https://docs.flyte.org/en/latest/concepts/executions.html page.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Murdock9803** [comment]
@samhita-alla @davidmirror-ops Please assign the issue to me, I would love to contribute 😊 🙌

**Comment by davidmirror-ops** [comment]
@Murdock9803 done :)

**Comment by Murdock9803** [comment]
@davidmirror-ops the [targetted page]( https://docs.flyte.org/en/latest/concepts/executions.html) in the issue description is not found. Is this page too, implemented using agents framework ? Can you guide me where to document about the uniqueness of execution ids within a project domain ?

**Comment by Murdock9803** [comment]
@davidmirror-ops @samhita-alla I think this issue can be closed, as the problem is solved 🙌
