### ISSUE TITLE
[Docs] document ci/cd best practices

### ISSUE THREAD

**Issue by samhita-alla** [flyteorg/flyte#4685]
### Description

document some general ci/cd best practices discussed by Bernhard in this conversation:: https://discuss.flyte.org/t/15853851/hi-team-i-d-like-to-understand-a-little-more-about-best-prac#1eaa0ca8-d3ec-49a9-9f46-b8537c610cb3

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Murdock9803** [comment]
Hello @samhita-alla @davidmirror-ops, 
I would like to take up this issue and contribute to the org. Please assign the issue to me 🙌

**Comment by Murdock9803** [comment]
Sure, I'll ask for any needed context 🙌

**Comment by Murdock9803** [comment]
@davidmirror-ops Since this is my first time adding a document to the codebase, I'd like to know where should I add the document. I tried to thoroughly read the codebase, and found that `docs` directory can be used. In this, `docs/user_guide/basics/` is a good place I believe ?

**Comment by davidmirror-ops** [comment]
@Murdock9803 right, I think adding a section to [this page](https://docs.flyte.org/en/latest/user_guide/flyte_fundamentals/registering_workflows.html#registration-patterns) may work

**Comment by davidmirror-ops** [comment]
@neelshah2409 There you go. Thanks for volunteering. While @Murdock9803 has been working on this, whoever submits the first accepted PR gets the points.
