### ISSUE TITLE
Add support passing integer to flytekit.resource

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/flyte#4691]
### Motivation: Why do you think this is important?

For now, we can only pass a string to the `Resource`. it will be better to support passing an integer to `Resource`
```python
@task(
    requests=Resources(cpu="1", mem="1Gi"),
    limits=Resources(cpu="2", mem="4Gi"),
    container_image=image_spec,
    environment={"KEY": "value"},
)
```

### Goal: What should the final outcome look like, ideally?

passing integers to `Resource`

```python
@task(
    requests=Resources(cpu=1, mem=1024, gpu=3),
    limits=Resources(cpu=2, mem=4096, gpu=2),
    container_image=image_spec,
    environment={"KEY": "value"},
)
```

### Describe alternatives you've considered 

NA

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Shenr0n** [comment]
Hi, I'm a first time contributor. Can you please specify where am I supposed to make these changes?

**Comment by Shenr0n** [comment]
@pingsutw Thank you. I've made the changes and created a pull request.
