### ISSUE TITLE
[BUG] Non-determinism with map task args, causes conflicts for deduping already registered tasks

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#4702]
### Describe the bug

When I attempt to `pyflyte run` this map task workflow: [multiple_inputs_map_workflow](https://github.com/flyteorg/flytesnacks/blob/43a1d2589836239b11f692bebaf249bb81951116/examples/advanced_composition/advanced_composition/map_task.py#L134-L137)

registration occasionally fails to dedupe the task digest because the serialized command in the task template includes args in non-deterministic order

for example
first registration:
```
... args:"--prev-checkpoint" args:"{{.prevCheckpointPrefix}}" args:"--resolver" args:"MapTaskResolver" args:"--" args:"vars" args:"shipping,price" args:"resolver" ...
```

second registration

```
... args:"--prev-checkpoint" args:"{{.prevCheckpointPrefix}}" args:"--resolver" args:"MapTaskResolver" args:"--" args:"vars" args:"price,shipping" args:"resolver" ...
```

note that `"shipping,price"` and `"price,shipping"` are different across different registration invocations.

We store a task digest alongside every registered task and [compare against it](https://github.com/flyteorg/flyte/blob/4a7c3c0040b1995a43939407b99ca3e87b1eb752/flyteadmin/pkg/manager/impl/task_manager.go#L95-L103) when registering tasks with identical identifiers. However, this non-determinism breaks the check to return grpc status code AlreadyExists vs InvalidArgument

pyflyte swallows the former grpc code but correctly, not the latter, so this blocks re-runs of the workflow

### Expected behavior

Can successfully re-register and run executions using the same task definition and computed version

### Additional context to reproduce

Clone flytesnacks and from within the root level flytesnacks/ dir run

```
pyflyte --config ~/.flyte/config-sandbox.yaml run --remote  -p flytesnacks -d development examples/advanced_composition/advanced_composition/map_task.py multiple_inputs_map_workflow
```

repeatedly

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pvditt** [comment]
resolved by: https://github.com/flyteorg/flytekit/pull/2113
