### ISSUE TITLE
[BUG] Array task caching 

### ISSUE THREAD

**Issue by svechinsky** [flyteorg/flyte#4731]
### Describe the bug

When running a cacheable array task (classic or array node) if the task includes a custom hash annotation the task won't cache.
This is due to the cache key being generated based on the function name which is generated from the function signature that includes the HashMethod object instantiation.

### Expected behavior

The task should cache despite the hash annotation.

### Additional context to reproduce

While I haven't tested this you should be able to:
1. Create a task that returns a cached dataframe (same code as the user guide)
2. Run it via map task and see that the cache always misses.

Posted here after being asked to do so at the slack channel

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pvditt** [comment]
@svechinsky thank you for pointing this out. We'll have a fix up for this soon.
