### ISSUE TITLE
[Docs] .hostname is not available in log templates

### ISSUE THREAD

**Issue by olyashok** [flyteorg/flyte#4750]
### Description

.hostname is mentioned as variable in several places in docs but actually is not resolveable by code

https://github.com/flyteorg/flyteplugins/blob/b0684d97a1cf240f1a44f310f4a79cc21844caa9/go/tasks/pluginmachinery/tasklog/template.go#L69

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
good catch! Hostname is indeed not being handled right now, although it should be very easy to add. Before we add it, it's worth understanding how hostname is set in k8s, which is described [here](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields). We simply have to add hostname when instantiating  `taskLog.Input` [here](https://github.com/flyteorg/flyte/blob/master/flyteplugins/go/tasks/logs/logging_utils.go#L54).

**Comment by novahow** [comment]
I am interested in this issue.

**Comment by eapolinario** [comment]
@novahow , feel free to work on it. Tag me on the PR and I'll gladly review it.
