### ISSUE TITLE
[Core feature] Pyflyte 'task with different structure' should show delta

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#4762]
### Motivation: Why do you think this is important?

It's difficult as a user when I try to register Flyte inventory and get back 

```
details: task with different structure already exists with id resource_type:TASK project:"system" domain:"production" name:"task-name" version:"1234" 
```

but I can't tell what's changed in my local version of the task.

Since we already store the registered task template and have the current serialized version of the task template we're trying to register, it would be super slick if flytekit (pyflyte) could compute what parameters in the template changed across registration and highlight that to the end user. (same for workflows and launch plans)

### Goal: What should the final outcome look like, ideally?

Should be straightforward to identify what has changed across registration versions when the back-end blocks a re-registration attempt

### Describe alternatives you've considered 

Current error response code user experience

###  Propose: Link/Inline OR Additional context 

Much like we use json marshalling to compute the hash, we could just json serialization to compute the delta here.

_No response_

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hampusrosvall** [comment]
You can assign this to me!

**Comment by austin362667** [comment]
Hi, @katrogan

Wanna making sure of few things before starting a PR. Thank you~

### 1. Delta what?

> compute what parameters in the template changed across registration

By *parameters*, did you mean like the `task` / `workflow` / `launch plan`  source code itself (different code structure but with the same id)  **OR** in `container.args` dict from  **registration request** bad rpc response e.g.,

Input Request:
```json
{ 
  "id": { 
    "resourceType": "TASK", 
    "project": "flytesnacks",
    "domain": "development",
    "name": "workflow.say_hello",
    "version": "1234"
  },
  "spec": {
    "template": {
      "id": {
        "resourceType": "TASK",
        "project": "flytesnacks",
        "domain": "development",
        "name": "workflow.say_hello",
        "version": "1234"
      },
      "type": "python-task",
      "metadata": {
        "runtime": {
          "type": "FLYTE_SDK",
          "version": "1.10.7",
          "flavor": "python"
        },
        "retries": {}
      },
      "interface": {
        "inputs": {},
        "outputs": {
          "variables": {
            "o0": {
              "type": {
                "simple": "STRING"
              },
              "description": "o0"
            }
          }
        }
      },
      "container": {
        "image": "basics:v1",
        "args": [
          "pyflyte-fast-execute",
          "--additional-distribution",
          "s3://my-s3-bucket/flytesnacks/development/M4GSLZXCTPK46HIL57X6NW6SBM======/fast229fe274ee6e0cb90581d25bcf670186.tar.gz",
          "--dest-dir",
          "/root",
          "--",
          "pyflyte-execute",
          "--inputs",
          "{{.input}}",
          "--output-prefix",
          "{{.outputPrefix}}",
          "--raw-output-data-prefix",
          "{{.rawOutputDataPrefix}}",
          "--checkpoint-path",
          "{{.checkpointOutputPrefix}}",
          "--prev-checkpoint",
          "{{.prevCheckpointPrefix}}",
          "--resolver",
          "flytekit.core.python_auto_container.default_task_resolver",
          "--",
          "task-module",
          "workflow",
          "task-name",
          "say_hello"
        ],
        "resources": {}
      }
    },
    "description": {
      "longDescription": {
        "format": "DESCRIPTION_FORMAT_RST"
      }
    }
  }
}
```

### 2. Where delta?

Should we handle delta computation in backend `flyteadmin` (language-agnostic) or in `flytekit` (python)?

Some tradeoff to consider:
- `proto file` breaking change? 
- `sdk` generalizability?

**Comment by katrogan** [comment]
1)
I think it'd be hard to diff the source code although that would be spectacular, but the diff check performed on the server doesn't even evaluate the source code so in this case it's not super relevant

Ideally we should diff across the task spec (like you dumped!) since that's used to compute the digest that ultimately determines whether the structure has changes across (re-)registration

2) Great question, I like the idea of having a language agnostic implementation!  We can use something like https://github.com/flyteorg/flyte/blob/962d45827646f106265630a0fb1d9ae74968bc32/flyteidl/protos/flyteidl/admin/workflow.proto#L89 and extend the error [message](https://github.com/flyteorg/flyte/blob/962d45827646f106265630a0fb1d9ae74968bc32/flyteidl/protos/flyteidl/admin/workflow.proto#L77-L79) to include structured data about what in the spec has changed

For example, this where we initialize the error message in flyteadmin code: https://github.com/flyteorg/flyte/blob/962d45827646f106265630a0fb1d9ae74968bc32/flyteadmin/pkg/errors/errors.go#L112-L126

**Comment by austin362667** [comment]
> 2\. extend the error [message](https://github.com/flyteorg/flyte/blob/962d45827646f106265630a0fb1d9ae74968bc32/flyteidl/protos/flyteidl/admin/workflow.proto#L77-L79) to include structured data about what in the spec has changed

What if we just show `diff` as string, in order to prevent modify the `task` proto buff

**Comment by katrogan** [comment]
@austin362667 can we close this out?

**Comment by austin362667** [comment]
Certainly! Thank you, Katrina.

**Comment by katrogan** [comment]
thank you @austin362667 for all your work in improving this!!
