### ISSUE TITLE
[BUG] None should not be allows as maptask output

### ISSUE THREAD

**Issue by hamersaw** [flyteorg/flyte#4779]
### Describe the bug

Using `None` as a maptask output can cause undefined behavior when executing, especially when used with `min_success_ratio`.

### Expected behavior

`None` should _probably_ not be allowed as a maptask output type. A comprehensive test to determine the correct behavior should be scoped here.

### Additional context to reproduce

This workflow will fail:
```
@task
def hello_none(name: str) -> None:
    if name == "b":
        raise Exception("B is not allowed")

    return

@workflow
def test_hello():
    map_task(hello_none, min_success_ratio=0.1)(name=["a", "b", "c"])
```
whereas this workflow completes without any output values:
```
@task
def hello_none(name: str) -> None:
    return

@workflow
def test_hello():
    map_task(hello_none, min_success_ratio=0.1)(name=["a", "b", "c"])
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pvditt** [comment]
This was not an issue with the ArrayNode implementation for maptasks. For some reason https://github.com/flyteorg/flytekit/pull/2242 fixes it for legacy maptasks. Looked into for longer than I should've and couldn't quickly figure out why.
