### ISSUE TITLE
[Housekeeping] Push image on each commit

### ISSUE THREAD

**Issue by bstadlbauer** [flyteorg/flyte#4788]
### Describe the issue

Based on [this slack conversation](https://flyte-org.slack.com/archives/CP2HDHKE1/p1706177242898739) it would be nice to push an image of all components on a merge to master. 

This allows users to alpha-test new changes, implicitly improving the next releases.

### What if we do not do this?

Users will have to wait for new releases for their bugfixes.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by bstadlbauer** [comment]
Image of the slack conversation in case it becomes too old

<img width="1359" alt="image" src="https://github.com/flyteorg/flyte/assets/11799671/3d641367-6ef3-4d03-b273-82289757b091">

**Comment by kumare3** [comment]
i do not think this is relevant any more. closing the issue
