### ISSUE TITLE
[Docs] Rename flyin to flyteinteractive 

### ISSUE THREAD

**Issue by ByronHsu** [flyteorg/flyte#4792]
### Description

Due to Linkedin's policy, we will change the name flyin to flyteinteractive before we go GA. The changes include

1. [flyin code](https://github.com/search?q=repo%3Aflyteorg%2Fflytekit%20flyin&type=code)
2. [flyin folder name](https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-flyin)
3. [flytesnacks doc](https://github.com/search?q=repo:flyteorg/flytesnacks%20flyin&type=code)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by srini047** [comment]
@ByronHsu I would like to get assigned and work on this issue.

**Comment by MortalHappiness** [comment]
@ByronHsu Can I work on this issue? Thanks.
