### ISSUE TITLE
[BUG] Set serviceAccount for submitterPod for Ray integration

### ISSUE THREAD

**Issue by peterghaddad** [flyteorg/flyte#4797]
### Describe the bug

Flyte + Ray Integration currently lacks the ability to pass a serviceAccount to the submitterPod of a Ray Job, which defaults to default. This limitation is problematic because the Ray Submitter pod image is set via the Flyte Python SDK, and certain Kubernetes configurations require a specific serviceAccount to successfully pull images from a private container registry.

To address this issue, we should enhance the integration to allow users to specify a serviceAccount for the submitterPod of a Ray Job. This feature would be particularly useful for users who need to run Ray Jobs on Kubernetes clusters that require a specific serviceAccount to access private container registries.

### Expected behavior

Set the RayJob spec to use the same serviceAccount specified via the configuration.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by novahow** [comment]
@peterghaddad 
Hi, when you say "submitterPod", do you mean the head pod in https://github.com/flyteorg/flyteplugins/blob/9c949260ea17279564dba7c7fc3bd5ab934ea52d/go/tasks/plugins/k8s/ray/ray.go#L158 ? Or am I misunderstanding something?

**Comment by peterghaddad** [comment]
@novahow the submitter pod is what KubeRay uses to submit the job to the Ray Cluster.

https://docs.ray.io/en/latest/cluster/kubernetes/getting-started/rayjob-quick-start.html#rayjob-configuration
Look for `submitterPodTemplate`

**Comment by novahow** [comment]
@peterghaddad Thanks for the clarification. So are you aiming to enable users to specify a service account for submitterPod from their end? like
```python=
ray_config = RayJobConfig(
    head_node_config=HeadNodeConfig(ray_start_params={"log-color": "True"}),
    worker_node_config=[WorkerNodeConfig(group_name="ray-group", replicas=1)],
    runtime_env={"pip": ["numpy", "pandas"]},  # or runtime_env="./requirements.txt",
    service_account="serviceAccountName"
)

@task(
    task_config=ray_config,
    requests=Resources(mem="2Gi", cpu="2"),
    container_image=custom_image,
)
def ray_task(n: int) -> typing.List[int]:
    futures = [f.remote(i) for i in range(n)]
    return ray.get(futures)
```
?
