### ISSUE TITLE
[Core feature] Automate sandbox-bundled YAML Updates with Helm Charts in Makefile

### ISSUE THREAD

**Issue by Future-Outlier** [flyteorg/flyte#4798]
### Motivation: Why do you think this is important?

When updating agent values in helm, it is hard for beginners to notice we need to update both helm charts in [charts/flyteagent](https://github.com/flyteorg/flyte/tree/master/charts/flyteagent) and [docker/sandbox-bundled/manifests](https://github.com/flyteorg/flyte/tree/master/docker/sandbox-bundled/manifests).

### Goal: What should the final outcome look like, ideally?

We should combine the step generate manifest [here ](https://github.com/flyteorg/flyte/blob/master/docker/sandbox-bundled/Makefile#L18-L35) with Makefile [here](https://github.com/flyteorg/flyte/blob/master/Makefile).

### Describe alternatives you've considered 

Stay the same.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Future-Outlier** [comment]
@davidmirror-ops Can you take a look?
I am not sure whether this is a good solution or not, thank you!

**Comment by ryanatfazz** [comment]
#take

**Comment by lowc1012** [comment]
#take

**Comment by Future-Outlier** [comment]
> #take

I can help you review this PR, thank you

**Comment by Future-Outlier** [comment]
First come first serve
