### ISSUE TITLE
[BUG] API Docs down

### ISSUE THREAD

**Issue by bimtauer** [flyteorg/flyte#4812]
### Describe the bug

Is it just me or are the generated API docs not available? Have they been moved? E.g.: https://docs.flyte.org/en/latest/api/flytekit/generated/flytekit.remote.remote.FlyteRemote.html used to work for me at the start of the week. Now its 404.

### Expected behavior

Access to API docs

### Screenshots

![image](https://github.com/flyteorg/flyte/assets/30375389/22a9bf24-626d-4fbe-858b-d1244ba14a38)
![image](https://github.com/flyteorg/flyte/assets/30375389/658ae796-871b-4e7d-b53a-118cc16a19c3)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by neverett** [comment]
@bimtauer thanks for flagging -- this should be fixed now by https://github.com/flyteorg/flyte/pull/4815 . That page (and others that were missing) is showing up for me now, but let me know if you're still seeing missing docs.
