### ISSUE TITLE
[BUG] Excdeeding 63 character limit for Volume names in Flyte Propeller Container Plugin

### ISSUE THREAD

**Issue by alexbeach-bc** [flyteorg/flyte#4824]
### Describe the bug

I am running this tutorial

https://github.com/unionai-oss/llm-fine-tuning/tree/main/flyte_llama

I am running the command in the readme:

```bash
pyflyte -c $FLYTECTL_CONFIG run --remote \
    --copy-all \
    flyte_llama/workflows.py train_workflow \
    --config config/flyte_llama_7b_qlora_v0.json
```

The only code modifications is that I am using gcp registry and a self hosted flyte cluster in GKE. The flyte cluster i have, contains node pools with the required gpu, memory, and cpu resources to run.

 Note that the registry name is very long due to how the urls are constructed by gcp

```
image_spec = ImageSpec(
    name="flyte-llama-qlora",
    apt_packages=["git"],
    registry="us-central1-docker.pkg.dev/xx-xxxxxxx-xxxxxxxxx-xxxxx/flyte",
    requirements="requirements.txt",
    python_version="3.9",
    cuda="11.7.1",
    env={"VENV": "/opt/venv"},
)

```

The first tasks succeeds, but the second task is stuck in Queue state:
<img width="1392" alt="Screenshot 2024-02-01 at 4 02 24 PM" src="https://github.com/flyteorg/flyte/assets/139262984/73ae5972-778d-428a-9cd8-7f674189a0e8">

After looking at the flyte-propeller k8s logs, i see this error. 
```
 {"json":{"exec_id":"fb3bf107c6ddd4889a74","ns":"flytesnacks-development","res_ver":"8124851","routine":"worker-8","wf":"flytesnacks:development:flyte_llama.workflows.train_workflow"},"level":"error","msg":"Error when trying to recon │
│ cile workflow. Error [failed at Node[n1]. RuntimeExecutionError: failed during plugin execution, caused by: failed to execute handle for plugin [container]: [Invalid] failed to create resource, caused by: Pod \"fb3bf107c6ddd4889a74- │
│ n1-0\" is invalid: [spec.volumes[1].name: Invalid value: \"mfzg3otbo4ztu32fmnzgk4dtnvqw3ylhmvzdu4ltfvswc32ufuzdumzvgy2dgmzqgyzdanryhjzwky2smv1duxy\": must be no more than 63 characters, spec.containers[0].volumeMounts[1].name: Not f │
│ ound: \"mfzg3otbo4ztu32fmnzgk4dtnvqw3ylhmvzdu4ltfvswc32ufuzdumzvgy2dgmzqgyzdanryhjzwky2smv1duxy\"]]. Error Type[*errors.NodeErrorWithCause]","ts":"2024-02-02T00:25:57Z"}    
```

How are the volume names generated? Could it be because the long registry name is used in the volume name?

### Expected behavior

I would expect valid Volume names to be generated and the tutorial task to complete.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pvditt** [comment]
@alexbeach-bc apologies for just now getting to this issue. 

Reproduced the invalid volume name error with running a task with a PodSpec with a > 63 char volume name. The latest version of Flyte properly handles the error so I don’t believe there was a regression with launching pods. This is sufficient to close concern on propeller’s end. Will follow up on issue to see how the volume name was generated.

![image](https://github.com/flyteorg/flyte/assets/37558497/13482871-3d7d-4611-96b8-2fa570429a29)

What Flyte version are you running?

**Comment by pvditt** [comment]
closing after discussion offline

**Comment by andylizf** [comment]
encountered this again. Any suggestions?

> Workflow[flytesnacks:development:.flytegen.flyte_llama.workflows.tune_batch_size_eager] failed. RuntimeExecutionError: max number of system retry attempts [11/10] exhausted. Last known status message: failed at Node[flytellamaworkflowstunebatchsizeeager]. RuntimeExecutionError: failed during plugin execution, caused by: failed to execute handle for plugin [container]: [Invalid] failed to create resource, caused by: Pod "f522b9b0dd4044607860-f1heqpqi-0" is invalid: [spec.volumes[1].name: Invalid value: "mfzg3otbo4ztu32fmnzgk4dtnvqw3ylhmvzdu4ltfvswc32ufuzdumzvgy2dgmzqgyzdanryhjzwky2smv1duxy": must be no more than 63 characters, spec.containers[0].volumeMounts[1].name: Not found: "mfzg3otbo4ztu32fmnzgk4dtnvqw3ylhmvzdu4ltfvswc32ufuzdumzvgy2dgmzqgyzdanryhjzwky2smv1duxy"]
