### ISSUE TITLE
[Docs]  `FlyteScopedUserException 'JavaPackage' object is not callable` if spark plugin is not enabled

### ISSUE THREAD

**Issue by jasonlai1218** [flyteorg/flyte#4826]
### Description

When executing `Spark Task`, flyte binary does not enable spark plugin, it will happen...
```
FlyteScopedUserException: 'JavaPackage' object is not callable
 
TypeError: Encountered error while executing workflow 'wf':
  Error encountered while executing 'wf':
  'JavaPackage' object is not callable
```

But it is difficult to know this from the error message. I think it can be recorded in troubleshooting.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by MortalHappiness** [comment]
#self-assign
