### ISSUE TITLE
[BUG] separateGrpcIngress flag not working in flyte-binary helm chart  

### ISSUE THREAD

**Issue by spacepirate0001** [flyteorg/flyte#4870]
### Describe the bug

separateGrpcIngress: false flag should force flyte-binary chart to create one ingress service for http and grpc but the condition is included in flyte-core only. Also flyte-flyte-http and flyte-flyte-grpc services should follow the same behavior to simplify http/grpc connections.

### Expected behavior

separateGrpcIngress: false flag should be included in flyte-binary chart and condition reflected on yaml files.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by spacepirate0001** [comment]
The following two services should also be combined into one.
flyte-flyte-binary-grpc	Node Port	<IP_ADDRESS>:8089 TCP
flyte-flyte-binary-http	Node Port	<IP_ADDRESS>:8088 TCP

**Comment by eapolinario** [comment]
@spacepirate0001 , would you be willing to contribute this change?

**Comment by lowc1012** [comment]
Hi @eapolinario,
I'd like to take this one.

**Comment by lowc1012** [comment]
#take
