### ISSUE TITLE
[BUG] Flytectl demo start with GITHUB_TOKEN throws 401

### ISSUE THREAD

**Issue by jsong336** [flyteorg/flyte#4879]
When `flytectl demo start` is ran with `GITHUB_TOKEN`, it throws 401 error. Setting `GITHUB_TOKEN` empty works. 
```
flytectl demo --logger.level 5 --logger.show-source start
INFO[0000] [0] Couldn't find a config file []. Relying on env vars and pflags. 
{"json":{"src":"viper.go:400"},"level":"debug","msg":"Config section [admin] updated. Firing updated event.","ts":"2024-02-12T02:17:43-05:00"}
🧑‍🏭 Bootstrapping a brand new Flyte cluster... 🔨 🔧
Error: GET https://api.github.com/repos/flyteorg/flyte/releases?per_page=100: 401 Bad credentials []
{"json":{"src":"main.go:13"},"level":"error","msg":"GET https://api.github.com/repos/flyteorg/flyte/releases?per_page=100: 401 Bad credentials []","ts":"2024-02-12T02:17:43-05:00"}
```
It seems to do something with when flytectl tries to list list available images with authenticated GHRepoService 
https://github.com/flyteorg/flytectl/blob/9c87165667b75efedd678707aeacc5a4e4981261/pkg/github/githubutil.go#L75

**Comment by pingsutw** [comment]
@jsong336, Is it still not working for you?

**Comment by jsong336** [comment]
@pingsutw It works when I set the GITHUB_TOKEN empty. I think the flytectl uses GITHUB_TOKEN if it exists while getting the list available images and throw 401 since I dont have access over the repos which I think is very strange behaviour

**Comment by pingsutw** [comment]
I think Flytectl should check if GITHUB_TOKEN Zia empty or not.
Would you like to open a pr for this?

**Comment by jsong336** [comment]
Yeah I could, I probably would like to dig the code bit more to see what should be expected behaviour.

**Comment by jsong336** [comment]
@pingsutw https://github.com/flyteorg/flytectl/pull/463
