### ISSUE TITLE
[Core feature] Retrieval of stdout/stderr from ShellTask

### ISSUE THREAD

**Issue by benoistlaurent** [flyteorg/flyte#4888]
### Motivation: Why do you think this is important?

Description:
Currently, there is a limitation in the functionality of `ShellTask` where users are unable to retrieve standard output (stdout) and standard error (stderr) from executed ShellTasks directly. Users would have to write both channels to the disk, reading them back to retrieve the command result, and finally deleting them. All those are unnecessary steps which increase disk accesses and make the task writing heavier.

### Goal: What should the final outcome look like, ideally?

Expected Behavior:
Users should have the capability to access the stdout and stderr outputs generated during the execution of a ShellTask.

### Describe alternatives you've considered 

I've considered implementing a custom `ShellTask` class that would be 99% the same code as ` flytekit.extras.tasks.shell.ShellTask`... Not very satisfying...

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@benoistlaurent , exposing stdout and stderr in an ergonomic way should be possible. Please, feel free to open a PR and tag me on it.
