### ISSUE TITLE
[BUG] Server-Level Ray CRD Version Override

### ISSUE THREAD

**Issue by arvind-chandra** [flyteorg/flyte#4905]
### Describe the bug

Currently the crd version for a Ray can only be changed at the user level, we should make it such that you can set this version at the server level.

### Expected behavior

Add the ability to set a global config value for the Ray crd version at the server level that can be overriden by the user. 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
This was recently added in https://github.com/flyteorg/flyte/commit/d6747c1e6e6e9c7a3e8f2e3f4bb6f37274d4bf82. It went out in the [latest release](https://github.com/flyteorg/flyte/releases/tag/v1.10.7).

**Comment by eapolinario** [comment]
Closing this issue for now. Please, re-open if you find that any issues with the new flag.
