### ISSUE TITLE
[Core feature] Allow setting concurrency policy for launch plans with schedule.

### ISSUE THREAD

**Issue by debajyoti-truefoundry** [flyteorg/flyte#4932]
### Motivation: Why do you think this is important?

It will be nice to set a concurrency policy when creating a launch plan with a schedule. I have added relevant documentation from K8s CronJobs.

https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#concurrency-policy
https://argo-workflows.readthedocs.io/en/latest/fields/#cronworkflowspec (Please check the `concurrencyPolicy` field.)

 

### Goal: What should the final outcome look like, ideally?

I can set `Allow`, `Forbid` or `Replace` as concurrency policy for launch plans with a schedule.

### Describe alternatives you've considered 

None.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by debajyoti-truefoundry** [comment]
I just found another issue discussing the same feature. Feel free to close this issue if the projecting tracks this feature there. 

https://github.com/flyteorg/flyte/issues/267#issuecomment-616245775

**Comment by eapolinario** [comment]
An idea similar to this is actually being discussed in https://github.com/flyteorg/flyte/discussions/3754. Please, engage there so that we can prioritize this accordingly.
