### ISSUE TITLE
[BUG] generate_helm.sh doesn't update helm docs for all charts

### ISSUE THREAD

**Issue by lowc1012** [flyteorg/flyte#4950]
### Describe the bug

When I updated values.yaml in `flyte-binary` chart and ran `make helm`, the README.md didn't be modified

### Expected behavior

README.md should be modified if I modified the values.yaml in charts. Need to check if each helm doc can be modified with changed vaules.yaml via generate_helm.sh.

### Screenshots

<img width="1107" alt="截圖 2024-02-26 凌晨12 21 37" src="https://github.com/flyteorg/flyte/assets/52355146/c936ffcb-1ffe-4d69-a826-7d0e2fa0cf78">

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by lowc1012** [comment]
#take

**Comment by lowc1012** [comment]
Root cause:
In generate_helm.sh, we uses latest norwoodj/helm-docs which use go1.22
https://github.com/norwoodj/helm-docs/commit/6cdd5ff340b10810d47011b7486c869a8e05df47

But flyte targets go1.21, so that it failed to generate helm-doc
https://github.com/flyteorg/flyte/blob/master/go.mod#L3

**Comment by davidmirror-ops** [comment]
Fixed by https://github.com/flyteorg/flyte/pull/4995
