### ISSUE TITLE
[BUG] [LIMIT_EXCEEDED] limit exceeded. 5.357096mb > 2mb. with Flyte-binary Chart

### ISSUE THREAD

**Issue by spacepirate0001** [flyteorg/flyte#4951]
### Describe the bug

In Flyte, tasks are subject to a default download size limit of 2MB. This constraint is enforced to manage resource utilization and ensure optimal performance across the system. If a task attempts to download data exceeding this threshold, it will terminate with an error indicating that the limit has been surpassed. For example, a task failing due to attempting to download 5.357096MB, which exceeds the 2MB limit, would result in the following error message: [LIMIT_EXCEEDED] limit exceeded. 5.357096mb > 2mb.

This download size limit is configurable through the Flyte system's settings, specifically via the .values.configuration.storage.limits.maxDownloadMBs parameter. However, it is important to note that this configuration option is not directly available within the flyte-binary Helm chart. 

### Expected behavior

Flyte-binary chart values.yaml `.values.configuration.storage.limits.maxDownloadMBs` should be added.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by spacepirate0001** [comment]
Yes! I used inline to get around this for now but configuration should be included properly.

**Comment by eapolinario** [comment]
@spacepirate0001 , since you already diagnosed the problem and offered a solution, would you be willing to contribute? Tag me on the PR, I'll gladly review it!

**Comment by kumare3** [comment]
i think this has been merged
