### ISSUE TITLE
[Housekeeping] Add kubeconform check to validate generated manifests in CI

### ISSUE THREAD

**Issue by lowc1012** [flyteorg/flyte#4973]
### Motivation: Why do you think this is important?

Once we modify helm charts and execute `make helm`, this command just generates/updates k8s manifests & helm docs. 
These manifests may not have been validated against the schema for Kubernetes.

[Kubeconform](https://github.com/yannh/kubeconform) is a Kubernetes manifest validator; it takes all the manifests and validates them against the schema from the Kubernetes repository.

### Goal: What should the final outcome look like, ideally?

Add `kubeconform` check in helm-charts.yaml github action wf. At least we should have to validate all manifests under `deployment` and `docker/sandbox-bundled/manifests` when we want to modify them.

### Describe alternatives you've considered 

First, we can check if `make helm` is executed once PR includes changes to charts. Second, we validate manifests under `deployment` and `docker/sandbox-bundled/manifests`.

###  Propose: Link/Inline OR Additional context 

1. https://github.com/yannh/kubeconform
2. https://www.fairwinds.com/blog/gitops-best-practices-and-the-kubernetes-guardrails-you-need

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by lowc1012** [comment]
I'm not sure if we have to check the manifests generated via `kustomize`

**Comment by pingsutw** [comment]
@lowc1012 Feel free to open a PR.

**Comment by lowc1012** [comment]
#take

**Comment by lowc1012** [comment]
#take
