### ISSUE TITLE
[Housekeeping] Move to go 1.22

### ISSUE THREAD

**Issue by eapolinario** [flyteorg/flyte#4994]
### Describe the issue

Go 1.22 was [released](https://go.dev/blog/go1.22) on 2/6/2024. This release mentions a 2-14% performance increase.

### What if we do not do this?

We'll eventually have to move go versions, so tracking this in this issue for now.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by lowc1012** [comment]
#take
