### ISSUE TITLE
[BUG] Documentation build hang on reading flytekitplugins.bigquery.BigQueryTask

### ISSUE THREAD

**Issue by MortalHappiness** [flyteorg/flyte#4997]
### Describe the bug

While building the documentation, the process hang on reading `flytekitplugins.bigquery.BigQueryTask`.

### Expected behavior

The documentation should build successfully.

### Screenshots

![image](https://github.com/flyteorg/flyte/assets/47914085/bf2a363a-96ab-4378-81a5-9a46c6c3c1ab)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by MortalHappiness** [comment]
#take

**Comment by neverett** [comment]
I think @pingsutw might be looking into this already https://github.com/flyteorg/flyte/pull/5000

**Comment by MortalHappiness** [comment]
I find that the problematic commit is [this one](https://github.com/flyteorg/flytekit/commit/39f5d49fda6d7b375fad0189d44deff5273bb127)

And after reverting the changes of `plugins/flytekit-bigquery/flytekitplugins/bigquery/agent.py` and `plugins/flytekit-snowflake/flytekitplugins/snowflake/agent.py` in this commit, the docs built successfully in my localhost.

Hope this information helps!

**Comment by MortalHappiness** [comment]
Closed by https://github.com/flyteorg/flyte/pull/5000
