### ISSUE TITLE
[Core feature] Add a gke-starter.yaml file for minimal deployment of flyte-binary on GKE clusters

### ISSUE THREAD

**Issue by cjidboon94** [flyteorg/flyte#5016]
### Motivation: Why do you think this is important?

There is an eks-starter.yaml with preset-values for a minimal deployment on AWS's EKS. It would be really helpful for new flyte users who are on GCP to be able to deploy it on GKE.

### Goal: What should the final outcome look like, ideally?

a gke-starter.yaml file added to the flyte-binary chart

### Describe alternatives you've considered 

There's deploy-flyte which I'm going to try deploying with.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@cjidboon94 , this would be an awesome contribution!
