### ISSUE TITLE
[BUG] nodes of a Dynamic Task in "View Children" view cannot be expanded

### ISSUE THREAD

**Issue by bnsblue** [flyteorg/flyte#503]
**Describe the bug**
Sub nodes of a Dynamic Task in "View Children" view cannot be expanded. In contrast, in the normal "Execution" view, the nodes can be expanded so the users can access the information of the tasks under a sub node.

**Expected behavior**

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [x] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
1. ...
2. ...

**Screenshots**

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**

**Comment by jsonporter** [comment]
Hey I am new to the team and was looking through the backlog and I was not able to repoduce this bug.  I suspect it may have been fixed?  Could you verify?

**Comment by bnsblue** [comment]
@jsonporter It has been almost a year so I can't remember exactly. It probably has been fixed. Haven't noticed this behavior recently.

**Comment by kumare3** [comment]
Closing stale un-reproducible bug.
