### ISSUE TITLE
[BUG] sql_alchemy plugin doesn't support pandas version > 2.1.4

### ISSUE THREAD

**Issue by Future-Outlier** [flyteorg/flyte#5031]
### Describe the bug

When using sql alchemy plugin example from here.
https://docs.flyte.org/en/latest/flytesnacks/examples/sql_plugin/sql_alchemy.html#sql-alchemy
And using latest pandas version by `pip install -U pandas`.
`python sql_example.py`
We will meet a bug.
![image](https://github.com/flyteorg/flyte/assets/76461262/7aee5853-bf96-4bac-9552-54d4f2275e32)
For more details, you can refer this PR.
https://github.com/flyteorg/flytekit/pull/2249

### Expected behavior

No bug.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by ChengyanOo** [comment]
Hi @Future-Outlier, I'd love to work on this issue, could you assign it to me?

**Comment by Future-Outlier** [comment]
> Hi @Future-Outlier, I'd love to work on this issue, could you assign it to me?

first come first serve

**Comment by ChengyanOo** [comment]
> > Hi @Future-Outlier, I'd love to work on this issue, could you assign it to me?
> 
> first come first serve

Oh got it, I thought no one is working on this😅

**Comment by Terryhung** [comment]
Hi @Future-Outlier , I noticed that another PR: https://github.com/flyteorg/flytekit/pull/2517 has removed the pandas restriction that you had previously added.
