### ISSUE TITLE
[Docs] Raw Container Task Julia Docker Image Doesn't support Arm64

### ISSUE THREAD

**Issue by Future-Outlier** [flyteorg/flyte#5069]
### Description

When downloading `ghcr.io/flyteorg/rawcontainers-julia:v2`, and start the image as container, we will find that `julia` command is not available.
<img width="1166" alt="image" src="https://github.com/flyteorg/flyte/assets/76461262/aedaaa14-e7f0-44de-a999-d2d0037c9b6f">

Reference: https://docs.flyte.org/en/latest/user_guide/customizing_dependencies/raw_containers.html#raw-container

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
I can't repro this, @Future-Outlier. This is what I see:
```
❯ docker run -it --rm --platform linux/amd64 ghcr.io/flyteorg/rawcontainers-julia:v2  /bin/sh
# julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.4 (2021-11-19)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia>
#

~ 
❯ docker images | grep julia
ghcr.io/flyteorg/rawcontainers-julia          v2                                             810ea9ce17e6   16 months ago   484MB
```

This [dockerfile](https://github.com/flyteorg/flytesnacks/blob/master/examples/customizing_dependencies/raw-containers-supporting-files/per-language/julia/Dockerfile) was used to build that image. Can you try building it locally?

**Comment by Future-Outlier** [comment]
> I can't repro this, @Future-Outlier. This is what I see:
> 
> ```
> ❯ docker run -it --rm --platform linux/amd64 ghcr.io/flyteorg/rawcontainers-julia:v2  /bin/sh
> # julia
>                _
>    _       _ _(_)_     |  Documentation: https://docs.julialang.org
>   (_)     | (_) (_)    |
>    _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
>   | | | | | | |/ _` |  |
>   | | |_| | | | (_| |  |  Version 1.6.4 (2021-11-19)
>  _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
> |__/                   |
> 
> julia>
> #
> 
> ~ 
> ❯ docker images | grep julia
> ghcr.io/flyteorg/rawcontainers-julia          v2                                             810ea9ce17e6   16 months ago   484MB
> ```
> 
> This [dockerfile](https://github.com/flyteorg/flytesnacks/blob/master/examples/customizing_dependencies/raw-containers-supporting-files/per-language/julia/Dockerfile) was used to build that image. Can you try building it locally?

I think the main problem will be we need to support multi arch for the Docker Image, when I build by myself, it works, but when I use the official image, it doesn't.
<img width="959" alt="image" src="https://github.com/flyteorg/flyte/assets/76461262/0c6fba32-74d3-4177-b59b-249f8cbcf488">
<img width="742" alt="image" src="https://github.com/flyteorg/flyte/assets/76461262/21a7eaf3-828b-489b-9287-8b572871378b">

**Comment by Future-Outlier** [comment]
cc @samhita-alla , Do you know how to update the image?
Here is the command I use
```zsh
docker buildx build -t localhost:30000/julia:0321 -f DockerfileJulia . --load
```

**Comment by Future-Outlier** [comment]
@eapolinario Can you also take a look at my PR about local container task execution?
Thank you.
Also if you can provide input and output with List and Dict in Raw Container task remote execution, it will help me a lot.
I've traced the code in `flytecopilot`, but it still couldn't help me use `List` or `Dict` as input/output types.

**Comment by Future-Outlier** [comment]
https://github.com/flyteorg/flytekit/pull/2258

**Comment by eapolinario** [comment]
Let's separate these issues out: (1) support for multi-arch images for the julia example, and (2) local raw containers and other raw containers limitations.

For (1), since this image to run the julia examples doesn't change frequently, I pushed a multi-arch version of that image (in fact I pushed multiarch versions of all raw container images): https://github.com/orgs/flyteorg/packages/container/rawcontainers-julia/194176739?tag=v2

I'm going to review the [PR](https://github.com/flyteorg/flytekit/pull/2258) related to (2) shortly.

**Comment by eapolinario** [comment]
We now have multi-arch images for the julia example.
