### ISSUE TITLE
[BUG] Flytekit Dolt Plugin Can't Convert Python Value To Literal

### ISSUE THREAD

**Issue by Future-Outlier** [flyteorg/flyte#5074]
### Describe the bug

Run the example in flytesnacks, and you will get an error.
https://docs.flyte.org/en/latest/flytesnacks/examples/dolt_plugin/dolt_quickstart_example.html
Note: 
1. remember to set up dolt environment first.
2. Since this PR will change the behavior of type transformer, we might need to tweak some code to make it work.

### Expected behavior

The sample code should work correctly.

### Screenshots

<img width="753" alt="image" src="https://github.com/flyteorg/flyte/assets/76461262/d084c539-0b69-48dd-88e8-fd18215de4b5">

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Future-Outlier** [comment]
The implement version should be looked like this PR's example.
https://github.com/flyteorg/flytekit/pull/2279

**Comment by davidmirror-ops** [comment]
@Future-Outlier have you been able to use the Dolt plugin for other use cases?

**Comment by Future-Outlier** [comment]
> @Future-Outlier have you been able to use the Dolt plugin for other tasks?

Haven't tried it for other tasks, but Kevin and I both found this error.

**Comment by kumare3** [comment]
deprecating dolt plugin. closing issue
