### ISSUE TITLE
[BUG] Propeller should fail the workflow when it can't write to etcd

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#511]
**Describe the bug**
Propeller doesn't error on
```
msg:Failed to update workflow. Error [Request entity too large: limit is 3145728]
```

**Expected behavior**
It should be recorded as an internal error.  After system retries, the workflow should fail with that message.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [x] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
1. Run a dynamic task with thousands and thousands of subtasks.

**Screenshots**

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**

**Comment by kumare3** [comment]
related to #363. currently in PR
