### ISSUE TITLE
[BUG] Register workflow by image sha256

### ISSUE THREAD

**Issue by gilbert-stripe** [flyteorg/flyte#5132]
### Describe the bug

Flyte supports[ passing image](https://docs.flyte.org/en/latest/api/flytekit/pyflyte.html#cmdoption-pyflyte-register-i) while registering workflow by pyflyte. However, it requires passing image tag and hasn't supported image sha256.

Example:
cmd: ` PYTHONPATH=/pay/src/zoolander pyflyte register src/python/flyte/ml_exploration/dynamic_resource_allocation_example -p ml-exploration -d adhoc -i "containers.global.qa.stripe.io/stripe-qa/flyte/flyte-workflow-minimal-images-2@sha256:1f5b27f07f2ee6c68cb480562dad950184c9bcac590c4f6b2fa220c9173e4f3b" -v gilbert3-123456 --deref-symlinks`

Error:
`AssertionError: Incorrectly formatted image containers.global.qa.stripe.io/stripe-qa/flyte/flyte-workflow-minimal-images-2@sha256:1f5b27f07f2ee6c68cb480562dad950184c9bcac590c4f6b2fa220c9173e4f3b, missing tag value
 `

Is it possible to support image sha256 in pyflyte?

### Expected behavior

Support image sha 256 when registering workflow by pyflyte.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Tom-Newton** [comment]
I'm also very interested in supporting this, though I think my error is actually a bit different. 
```
AssertionError: Incorrectly formatted image containers.global.qa.stripe.io/stripe-qa/flyte/flyte-workflow-minimal-images-2@sha256:1f5b27f07f2ee6c68cb480562dad950184c9bcac590c4f6b2fa220c9173e4f3b, missing tag value 
```
Comes from https://github.com/flyteorg/flytekit/blob/4c6e704eb600b4fed38434bfe1e68b55ad7fac19/flytekit/configuration/__init__.py#L221 but this actually seems to work for me. Looking at the implementation of [parse_repository_tag](https://github.com/docker/docker-py/blob/9ad4bddc9ee23f3646f256280a21ef86274e39bc/docker/utils/utils.py#L223) it looks to me like this part should work. 

The problem I have is that the `:` gets replaced with an `@` in `Image.full` and `get_registerable_container_image`. I created a draft PR that adds sha256 test cases in a bunch of relevant tests https://github.com/flyteorg/flytekit/pull/2335.

**Comment by Tom-Newton** [comment]
@eapolinario have you started working this? I am very keen to get it fixed fast so if you are not working on it I can probably do it.

**Comment by Tom-Newton** [comment]
@gilbert-stripe which version of `flytekit` are you using. I can't reproduce your error on the latest version. I suspect its because https://github.com/flyteorg/flytekit/pull/1978 recently change the library used for parsing the tag or digest.

**Comment by gilbert-stripe** [comment]
@Tom-Newton Hi!
I believe the version is 1.3.2. We got that upgrade to 1.9.1.
Will that resolve the issue?

**Comment by Tom-Newton** [comment]
Only only solves a tiny bit of the issue. I have made a PR that should fix the rest https://github.com/flyteorg/flytekit/pull/2335
