### ISSUE TITLE
lack of documentation on http+json requests example

### ISSUE THREAD

**Issue by secureness** [flyteorg/flyte#5158]
### Description

Hi, I really need to work directly with HTTP requests, I read that you have grpc-gateway, but there are no examples in the documentation of how we can use HTTP requests instead of a command like:
```bash
 pyflyte --verbose run --remote -p my-project -d development my-project.py say_hello --name myProject
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pingsutw** [comment]
@secureness We expose an open API definition endpoint (`localhost:30080/api/v1/openapi`), you can use it on the [swagger](https://petstore.swagger.io/?_gl=1*8rj2nt*_gcl_au*MzQ3MTg0MTY3LjE3MTE4Njg4MjU.&_ga=2.138279480.98378179.1711868825-1021132267.1711868824#/AdminService) UI to see the HTTP request example.  

https://docs.flyte.org/en/latest/reference/swagger.html#reference-swagger
