### ISSUE TITLE
[Feature] Validation of Flyte fields to create new projects

### ISSUE THREAD

**Issue by kosigz-lyft** [flyteorg/flyte#519]
**Motivation: Why do you think this is important?**
In a previous PR, I added the capability for teams using Flyte to inject custom labels onto their projects, e.g. "slack" => "#machinelearning" or "email" => "locations@lyft.com". This is useful for adding metadata to projects. However, one problem we have observed is that it's difficult to keep these labels up to date (and populated) if there is not some logic that organizations can add to the Flyte Admin control plane to disallow creation of new projects should labels not be included.

**Goal: What should the final outcome look like, ideally?**
A generic piece that organizations can use to add validation to the labels on a Flyte project. e.g. being able to require that all projects in your organization have a Slack channel attached.

**Describe alternatives you've considered**
The alternative is to build an external system to Flyte that monitors for changes, i.e. new projects without a Slack, and alerts.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [x] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
Draft: https://github.com/lyft/flyteadmin/pull/119

**Is this a blocker for you to adopt Flyte**
This feature will be very useful.

**Comment by kumare3** [comment]
Labels are already supported on flyte, https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/productionizing/workflow_labels_annotations.html#adding-workflow-labels-and-annotations
