### ISSUE TITLE
[BUG] Auto refreshing on change tabs

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/flyte#5197]
### Describe the bug

Flyte docs keeps auto-refreshing when switching tab

### Expected behavior

should not auto refresh

### Screenshots

https://github.com/flyteorg/flyte/assets/37936015/2e444626-99dd-4b26-9374-4859b75d805e

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
I agree this is the left side bar- does not maintain position

**Comment by MortalHappiness** [comment]
https://github.com/pydata/pydata-sphinx-theme/blob/733d9f3264020c8a5bd3dde38f3ee3e5cdb2979a/src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js#L133-L175
This theme uses sessionStorage to preserve the state of scrollbar position. We can reference it.

**Comment by pingsutw** [comment]
cc @cosmicBboy Do you know how to fix it?

**Comment by cosmicBboy** [comment]
not sure, these might be helpful: https://pradyunsg.me/furo/contributing/internals/#contents-sidebar, https://github.com/pradyunsg/furo/blob/main/src/furo/assets/scripts/furo.js#L11-L69

**Comment by cosmicBboy** [comment]
> This is combined with some custom JS to scroll to the currently active heading in the toctree, which results in the contents sidebar scrolling with the user as they go.

Seems like this part isn't working

**Comment by cosmicBboy** [comment]
@pingsutw see #5229
