### ISSUE TITLE
[Docs] Clear instructions for exposing prometheus metrics for flyte-binary

### ISSUE THREAD

**Issue by cjidboon94** [flyteorg/flyte#5205]
### Description

Currently it's unclear how to setup flyte-binary so that it exposes prometheus metrics.
It seems that it is possible as is suggested by #3758 , however that issues also describe that even if one sets up the metrics they might not be able to get all the metrics that flyte provides.
For flyte-core this seems straightforward and there are clear fields in the values file for the helm chart.
Would be great to have something similar in the flyte-binary chart (and documentation if not possible)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
@cjidboon94 i'm not sure if the issue you linked is still an issue, but you should be able to see prometheus metrics out of the box in the flyte-binary deployment.  At least testing using the `flytectl demo` environment, if I just port-forward the flyte pod, port 10254, I'm able to see it.  flytectl doesn't port forward that port out of the box but once you do you should be able to see it.  Is it not working for you?  Can you confirm nothing's being served on that port in your case?
