### ISSUE TITLE
[Feature] Make ProjectLabels available to plugins

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#521]
**Motivation: Why do you think this is important?**
FlyteAdmin offers a way to associate free-form metadata with each project. They are meant to be agnostic to Flyte system but available for querying at various stages. This feature request is to make them available to plugins to be used for tagging some external system that are aware of the keys in these dictionaries.

**Goal: What should the final outcome look like, ideally?**
A `GetProjectLabels() map[string]string` method defined [here](https://github.com/lyft/flyteplugins/blob/master/go/tasks/pluginmachinery/core/exec_metadata.go#L24) that gets filled in from FlyteAdmin all the way to plugins.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [X] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [X] FlyteAdmin (Control Plane service)
- [X] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
In order to achieve that, a few changes will need to happen:
- FlyteWorkflow WorkflowMeta (defined in FlytePropeller repo [here](https://github.com/lyft/flytepropeller/blob/master/pkg/apis/flyteworkflow/v1alpha1/workflow.go#L73)) an additional `ProjectLabels map[string]string` added.
- FlyteAdmin, when it creates a FlyteWorkflow [here](https://github.com/lyft/flyteadmin/blob/4aa11786a7efafef61b1a0f39b87369570eeb6fe/pkg/workflowengine/impl/propeller_executor.go#L100), needs to set that new field. 
- Add a `GetProjectLabels() map[string]string` method defined [here](https://github.com/lyft/flyteplugins/blob/master/go/tasks/pluginmachinery/core/exec_metadata.go#L24)
- FlytePropeller [TaskExecutionContext](https://github.com/lyft/flytepropeller/blob/7cec5c3fc0559f89a4ad36b537777313bbe567f4/pkg/controller/nodes/task/taskexec_context.go#L117) (the implementation of the above interface) should then implement this new function.

**Comment by kumare3** [comment]
@EngHabu my preference is to use the K8s labels for the CRD as a way to pass along the project labels too. Thus project labels become the base set of labels applied to every workflow execution and can be overriden per execution etc.
This also requires no changes to propeller or any of the plugins. and the behavior is easy to understand. Otherwsie its not clear what project labels and workflow labels are and how they differ

**Comment by kumare3** [comment]
This is merged and available

**Comment by EngHabu** [comment]
Triage: WorkflowId and WorkflowExecutionId have been made available to plugins' consumption but not Project labels. It satisfied the request at the moment. Closing
