### ISSUE TITLE
[BUG] Failing Databricks tasks are not retried

### ISSUE THREAD

**Issue by rambrus** [flyteorg/flyte#5210]
### Describe the bug

I created a Flyte task running in Databricks, task retries are set to 3 like this:
```
@task(task_config=databricks_conf, retries = 3)
def db_bad_luck_task():
    raise ValueError("Bad luck, this one failed") 
```
Unfortunately, this task is never retried, we only have a single attempt to run the task.

Just for double-checking, I created a Python tasks running on K8 with a similar configs:
```
@task(task_config=databricks_conf, retries = 3)
def db_bad_luck_task():
    raise ValueError("Bad luck, this one failed")
```
In this case, we have 3 attempts to run the task. (this is the behavior we expect in the case of the Databricks task also)

I assume it needs to be defined in the plugin implementation what LifeCycleState / ResultState can be retried. Is that correct?

### Expected behavior

Flyte will attempt to run the Databricks task 3 times.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by pingsutw** [comment]
@rambrus that's because we always return non-recoverable failure [here](https://github.com/flyteorg/flyte/blob/0dcfb3b7a1cb2a9d5061ff649cecda2a7598e01c/flyteplugins/go/tasks/plugins/webapi/databricks/plugin.go#L280-L284). 

This is also an expected behavior. When you raise a `ValueError` in the regular task, Flyte won't retry as well.
```python
@task(retries = 3)
def t1():
    raise ValueError("Bad luck, this one failed") 
```

**Comment by rambrus** [comment]
I did some investigation on the Databricks side and found that if the Databricks cluster start fails for any reason, [Get a single job run](https://docs.databricks.com/api/workspace/jobs/getrun) will return this state:
```
...
    "state": {
        "life_cycle_state": "INTERNAL_ERROR",
        "result_state": "FAILED",
        "state_message": "<Error details>",
        "user_cancelled_or_timedout": false
    },
...
```

In fact, Databricks' built-in orchestration framework [Databricks Workflows](https://docs.databricks.com/en/workflows/index.html) classifies `life_cycle_state: INTERNAL_ERROR` as a retryable error (see [here](https://docs.databricks.com/api/workspace/jobs/create#tasks-max_retries)), it would probably make sense to provide an identical behavior in Flyte.

I'm proposing this change in [plugins/webapi/databricks/plugin.go](https://github.com/flyteorg/flyte/blob/master/flyteplugins/go/tasks/plugins/webapi/databricks/plugin.go#L289):
```
	case "INTERNAL_ERROR":
		return core.PhaseInfoRetryableFailure(string(rune(http.StatusInternalServerError)), message, taskInfo), nil
	}
```

@pingsutw How does that sound to you?

**Comment by pingsutw** [comment]
https://github.com/flyteorg/flyte/pull/5277
