### ISSUE TITLE
[BUG] Failed to launch workflows due to too many requests

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/flyte#5234]
### Describe the bug

I get the below error when I run a workflow with 100 Launch plans, and each launch plan has 100 tasks. 

- max Parallelism: 100

```bash
Workflow[flytesnacks:development:workflow.agent.load_test.sleep_wf] failed. RuntimeExecutionError: max number of system 
retry attempts [52/50] exhausted. Last known status message: Workflow[] failed. ErrorRecordingError: failed to publish event, 
caused by: EventSinkError: Error sending event, caused by [rpc error: code = Unavailable desc = unexpected HTTP status 
code received from server: 429 (Too Many Requests); transport: received unexpected content-type "text/html"]
```

### Expected behavior

Workflow should not fail

### Screenshots

![image](https://github.com/flyteorg/flyte/assets/37936015/96a6916d-2a32-441d-aac4-8befb34deeeb)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wild-endeavor** [comment]
For the 429 backoff, #5166 will help with this some. Can we try again locally after that is merged and see if we can repro?
https://github.com/flyteorg/flyte/blob/master/flytepropeller/events/config.go#L26-L27

The other issue is a bit different.  We should probably make it a different ticket.

**Comment by hamersaw** [comment]
closing this as the aforementioned PR is the best mitigation.
