### ISSUE TITLE
[BUG] Use remote LP with default inputs and no fixe inputs is not working

### ISSUE THREAD

**Issue by andresgomezfrr** [flyteorg/flyte#5270]
### Describe the bug

Use remote LP with default input and no fixed inputs fails during registration time with:
https://github.com/flyteorg/flytekit/blob/master/flytekit/core/promise.py#L972
```python
    raise _user_exceptions.FlyteAssertion("Missing input `{}` type `{}`".format(k, var.type))
```

### Expected behavior

The LP should be registered properly if the inputs are provided using the default inputs even if there are no fixed inputs configured.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by davidmirror-ops** [comment]
Fixed on https://github.com/flyteorg/flytekit/pull/2372
