### ISSUE TITLE
[Core feature] Flytekit support for positional args

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#5320]
### Motivation: Why do you think this is important?

Curently only kwargs are supported
```
@task
def foo(x: int, y: int) -> int:
     ...

@workflow
def wf(x: int, y: int) -> int:
    return foo(x=x, y=y)
```

### Goal: What should the final outcome look like, ideally?

Support positional args
```
@task
def foo(x: int, y: int) -> int:
     ...

@workflow
def wf(x: int, y: int) -> int:
    return foo(x, y)
```

### Describe alternatives you've considered 

NA

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
Then it will be possible to support
```
@task
def foo(*args, **kwargs) -> int:
     return int
```

**Comment by MortalHappiness** [comment]
#take
