### ISSUE TITLE
[Core feature] Flytekit create automatic bindings for Task default values

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#5321]
### Motivation: Why do you think this is important?

Currently this will not work, as rotation is not provided
```python
@task(cache=True, cache_version="1")
def rotate_image(img: FlyteFile, rotation: int = 180) -> FlyteFile:
    img.download()
    with Image.open(img.path) as im:
        rotated = im.rotate(rotation)
        rotated.save("/tmp/rotated.jpeg")
    return FlyteFile("/tmp/rotated.jpeg")


@workflow
def wf(img: FlyteFile = "testdir/maradona.jpeg") -> FlyteFile:
    return rotate_image(img=img)
```

### Goal: What should the final outcome look like, ideally?

Ideally we should automatically create a node binding in the workflow where the default value in the task inputs should be added to the node in the workflow

### Describe alternatives you've considered 

NA

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
```[tasklist]
### Tasks
```

**Comment by Future-Outlier** [comment]
Will start it after 5/12, thank you

**Comment by MortalHappiness** [comment]
#take
