### ISSUE TITLE
[BUG] Subworkflow status is not reported to the parent workflow

### ISSUE THREAD

**Issue by pablocasares** [flyteorg/flyte#5335]
### Describe the bug

After upgrading our cluster to v1.12.0 some workflow executions got stuck in "running" state when a subworkflow node failed. It seems that the failed state from the subworkflow is not being reported to the parent workflow so the workflow gets stuck in running state.

We rolled back flytepropeller to v1.11.0 and the issue disappeared. Looks like a race condition issue because it happens from time to time and restarting the workflow seems to mitigate the problem.

### Expected behavior

The subworkflow status should be reported back to the parent workflow.

### Screenshots

![image](https://github.com/flyteorg/flyte/assets/4056828/1fc2f64b-6c9b-4093-935b-57c23d25acd0)

Logs keeps saying `LaunchPlan running, parallelism is now set to [X]` - Node Event [failing] seems missing.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
This is a pretty serious bug? cc @pvditt

**Comment by pvditt** [comment]
@pablocasares thank you for pointing this out. Were you able to determine if the workflow was still getting executed by propeller or was it just the console showing it as running? (Looking to see if this is just an eventing/persisting of state to admin bug)

**Comment by pvditt** [comment]
@pablocasares My initial thoughts were this had to do with the [cache](https://github.com/flyteorg/flyte/blob/43c0f1a61b288ce150968630de3aef0fd0aa980e/flytepropeller/pkg/controller/nodes/subworkflow/launchplan/admin.go#L172) not getting updated but I'm not noticing anything while stepping through the code + looking at the updates.

Are you able to provide a workflow that could reproduce the error?

**Comment by pvditt** [comment]
@pablocasares thank you for the added info. And just to circle back/confirm, 

- Were you able to determine if the parent workflow was still getting executed by propeller or was it just the console showing it as running?

- When you mention it happens time to time, does that mean you had cases of external/child workflows failing and then the parent workflow correctly handling that state while running propeller on 1.12.0?

**Comment by pablocasares** [comment]
- Were you able to determine if the parent workflow was still getting executed by propeller or was it just the console showing it as running?

The parent workflow was still getting executed but stuck because it thought that the subworkflow node was still running (you can check the yaml I sent in our internal Slack channel)

- When you mention it happens time to time, does that mean you had cases of external/child workflows failing and then the parent workflow correctly handling that state while running propeller on 1.12.0?

Yes, we have workflows with external subworkflows failing that are correctly handled on 1.12.0. 

- When "restarting the workflow seems to mitigate the problem" - with this did you terminate and then relaunch a parent workflow while on propeller 1.12.0?

Yes, aborted the workflow and then relaunch. As I said, this happen only in some of the executions. The external subworkflow failing is needed for this to happen but having a external subworkflow failing doesn't mean the issue happens. In other words, this happens sometimes when the external subworkflow fails. In some executions the external subworkflow fails and it is handled properly.

**Comment by pvditt** [comment]
@pablocasares thank you for the follow up. Apologies for the mix up - was just added to the slack channel. 

```
    get-subsregs-partition:
      laStartedAt: "2024-05-08T07:50:33Z"
      lastUpdatedAt: "2024-05-08T07:50:33Z"
      message: running
      phase: 2
      queuedAt: "2024-05-08T07:50:32Z"
      startedAt: "2024-05-08T07:50:33Z"
      workflowNodeStatus:
        phase: 1
```

the phase undefined is interesting as opposed to being in phase executing. Let me look back into this.

**Comment by pvditt** [comment]
@pablocasares would you still have access to your propeller logs? If so, can you check if [Retrieved Launch Plan status is nil. This might indicate pressure on the admin cache.](https://github.com/flyteorg/flyte/blob/2f38d65e45b1f098393feea72d8906b5aa645ade/flytepropeller/pkg/controller/nodes/subworkflow/launchplan.go#L170) is popping up in your logs?

**Comment by pablocasares** [comment]
Hi again @pvditt, I checked the logs and I can see that message happening when we had propeller v1.12.0 and even now with v1.11.0. Seems to be happening several times per minute.

**Comment by pvditt** [comment]
@pablocasares 

I think we've pinned the problem down, but am having difficulty reproducing the race condition. Would you still have access to the flyteadmin logs from when child/external workflow were not propagating status to their parent workflow? Interested to see if you're seeing continued polling to GetExecution for the execution_id of a subworkflow by the admin-launcher's cache update loop.

ie:
```
2024/05/16 01:11:16 /Users/pauldittamo/src/flyte/flyteadmin/pkg/repositories/gormimpl/execution_repo.go:44
[15.565ms] [rows:1] SELECT * FROM "executions" WHERE "executions"."execution_project" = 'flytesnacks' AND "executions"."execution_domain" = 'development' AND "executions"."execution_name" = 'fh662hcses4ry1' LIMIT 1
```

Note, there could still be logs showing this occasionally as other parts of Flyte such as console will ping this endpoint. Looking to see if you don't see continued logs at the cadence of ~[cache sync cycle duration (defaults to 30s)](https://github.com/flyteorg/flyte/blob/9e41df200e8a62faf13966b161f8f2bb3c652679/flytepropeller/pkg/controller/config/config.go#L134) while the parent workflow is stuck in running.

**Comment by pablocasares** [comment]
Hi @pvditt thanks for the update.

I did a quick search on the logs and I found only 1 line with the parent wf execution id:

```
SELECT * FROM "executions" WHERE "executions"."execution_project" = 'key-metrics-pipelines' AND "executions"."execution_domain" = 'production' AND "executions"."execution_name" = 'nfu3ftwauvzag7e23pgx' LIMIT 1
```

I used the same filter with the subworkflow execution id and I couldn't find any line.

I don't see continued logs for the parent execution id (just 1 line) and no logs at all for the child wf.

**Comment by RRap0so** [comment]
Hey friends! 

We've tested this with the RC candidate. Things seem somewhat better but we're still seeing the same problem but this time the pipelines eventually finish at around the 1h. 

We couldn't reproduce it but found a couple of runs where the Remote LaunchPlan just stay stuck but checking the sub execution everything is green.

**Comment by pvditt** [comment]
@RRap0so thank you for testing this out.

What value do you have set for [downstream-eval-duration](https://github.com/flyteorg/flyte/blob/242303bf092688ad1b2f87f25205f4b0111d6759/flytepropeller/pkg/controller/config/config.go#L134) ?

**Comment by RRap0so** [comment]
```downstream-eval-duration: 10s```

**Comment by pvditt** [comment]
@RRap0so thank you again.

With those couple runs that were stuck, did they resolve themselves to the correct state without any intervention?

Also, did those instances occur during times when there were a higher number of external sub-workflows running across that propeller instance? Would you still have access to the metrics from when those workflows were stuck? I'd be interested in [admin-launcher:SyncErrors](https://github.com/flyteorg/flyte/blob/5cc7f583d05b27efb13d799177551be17f7bc654/flytestdlib/cache/auto_refresh.go#L48) and [admin-launcher:Size ](https://github.com/flyteorg/flyte/blob/5cc7f583d05b27efb13d799177551be17f7bc654/flytestdlib/cache/auto_refresh.go#L53C2-L53C6)

**Comment by RRap0so** [comment]
They resolved themselves (taking roughly 1h 20 min). The way we have things setup is that most workflows we're running use sub-workflows. We have a some shared workflows within the org where folks use to do dependency checking etc...

I'll try to find those metrics for you.

**Comment by pvditt** [comment]
https://github.com/flyteorg/flyte/commit/d0628249f5935542c1a09f0f257e8274a7eef5c7
