### ISSUE TITLE
[Housekeeping] Use uv to cut on build time

### ISSUE THREAD

**Issue by eapolinario** [flyteorg/flyte#5346]
### Describe the issue

As a quality of life improvement, let's use [`uv`](https://github.com/astral-sh/uv) to install flytekit dependencies in CI and also when building the different flytekit images.

### What if we do not do this?

We won't benefit from the blazingly fast build times `uv` can give us.

### Related component(s)

flytekit

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by thomasjpfan** [comment]
`uv` was integrated in https://github.com/flyteorg/flytekit/pull/2403
