### ISSUE TITLE
[Feature] Have cluster resource controller leverage k8s secrets

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#541]
**Motivation: Why do you think this is important?**
In addition to reading substitutable secret values from mounted file paths or injected environment variables, it would be useful to access kubernetes secrets when running the [cluster resource controller](https://lyft.github.io/flyte/administrator/install/managing_customizable_resources.html).

**Goal: What should the final outcome look like, ideally?**
It should be possible to inject kubernetes secrets as substitutable template values in the cluster resource controller.

**Describe alternatives you've considered**

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [x] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Additional context**

**Is this a blocker for you to adopt Flyte**
Please let us know if this makes it impossible to adopt Flyte

**Comment by katrogan** [comment]
cc @jeevb

**Comment by jeevb** [comment]
Thank you @katrogan. Would it be reasonable to also leverage config maps in the same way?

**Comment by kumare3** [comment]
@jeevb Secrets has been merged - https://github.com/flyteorg/flytesnacks/blob/master/cookbook/core/intermediate/use_secrets.py and I think we can take this up in the next month

**Comment by EngHabu** [comment]
Can somebody elaborate on a concrete use-case for this?
@jeevb @katrogan

**Comment by kumare3** [comment]
Most folks use secret manager the recommended path for this. Please refer to https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/productionizing/use_secrets.html#using-secrets-in-a-task
