### ISSUE TITLE
[Core feature] Update/register multiple launch plans with different inputs

### ISSUE THREAD

**Issue by peterklingelhofer** [flyteorg/flyte#5415]
### Describe the feature/command for FlyteCTL

I have a cron launch plan which takes a site_id as a parameter. There is not currently a way to activate a recurring launch plan with a different input parameter, and you have to hard-code each individual launch plan with every different site_id I would ever want to activate.

```
cron_6hourly_lp = setup_launch_plan(
    name="workflow.6hourly",
    workflow=workflow_cron_wf,
    default_inputs={
        "site_id": "<UUID>",
    },
    schedule=CronSchedule(
        schedule="0 */6 * * *",
    ),
)

flytectl update launchplan \
  --project dev \
  --domain development \
  workflow_cron_wf \
  --version 2024-05-21-19-55-02 \
  --activate \
  --parameters '{
    "site_id": "<UUID>"
  }'
Error: unknown flag: --parameters
ERRO[0000] unknown flag: --parameters
```

Discussed here: https://flyte-org.slack.com/archives/CP2HDHKE1/p1716384291302639

### Provide a possible output or UX example

```
flytectl update launchplan \
  --project dev \
  --domain development \
  workflow_cron_wf \
  --version 2024-05-21-19-55-02 \
  --activate \
  --parameters '{
    "site_id": "<UUID>"
  }'
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@peterklingelhofer , as explained in the [Schedules](https://docs.flyte.org/en/latest/concepts/schedules.html) documentation, only one launchplan can be active for a given schedule. 

Unfortunately, changing that assumption would require a redesign of schedules and it's not in the plans for the project. Does having separate schedules solve your use case?

**Comment by peterklingelhofer** [comment]
@eapolinario Thank you for that context. It seems that probably the best move here is to just define multiple launch plans with varying fixed inputs. I'll close this issue since that should work decent enough for my use case.
