### ISSUE TITLE
[BUG] `uri` of the input with `Any` type of the workflow is incorrect when run remotely

### ISSUE THREAD

**Issue by Mecoli1219** [flyteorg/flyte#5426]
### Describe the bug

When running this workflow in remote Flyte deployment with command`pyflyte run --remote <file_name>.py wf1 --a 1`, the `uri` of the input will be like `/var/.....`. This will cause an error as the remote entity couldn't access the local file.

My python file:
```
from flytekit import task, workflow
from typing import Any

@task()
def t1(a: Any) -> int:
    if type(a) == int:
        return a + 1
    return 0

@workflow()
def wf1(a: Any) -> int:
    return t1(a=a)
```

Error Message:
```
FileNotFoundError: Failed to convert inputs of task '<file_name>.t1':
  [Errno 2] No such file or directory: '/var/folders/bl/kvjgvw0n5dddmglqdwy4zmpw0000gn/T/flyte-dlkg2l19/raw/2c9421ed6fd50ff5693cd38840c39c48/57b865dff2967bb348047887fad8262c'
```

### Expected behavior

Similar to FlyteFile, Flytekit should upload the data to s3 so that the data will be accessible to the workflow & task.

![image](https://github.com/flyteorg/flyte/assets/72752478/2a9fa4c3-8e41-4d4e-8318-4cc0352bee29)
Image provided by @Future-Outlier 

### Screenshots

<img width="1478" alt="image" src="https://github.com/flyteorg/flyte/assets/72752478/122432fb-21a7-4e79-bea6-e4a31e710fcc">

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
We have some code in the implementation of the [`run` subcommand](https://github.com/flyteorg/flytekit/blob/master/flytekit/clis/sdk_in_container/run.py#L372-L377) that translates stdin in to Flyte literals. We have to add support for `Any` (and pickle those values).

**Comment by Mecoli1219** [comment]
I'll take a look at this part, Thanks!
