### ISSUE TITLE
[BUG] Plugin Collector does not include group

### ISSUE THREAD

**Issue by trevormcguire** [flyteorg/flyte#5429]
### Describe the bug

Flytepropeller tracks how many objects there for each resource type (such as TfJob, PyTorchjob, etc). However, the plugin collector go client does not include group names in the apiVerison when searching for these resources (such as kubeflow/v1), so a warning is raised `failed to list objects for` when attempting to list them. 

https://github.com/flyteorg/flyte/blob/75b33f80dacb737a098b223ad24c2fee49351e31/flytepropeller/pkg/controller/nodes/task/k8s/plugin_collector.go#L52-L61

This seems to have been introduced when we were testing out 1.12 and can be traced back to #5238

Here is an example for SparkApplication.v1beta2
```
{"json":{"routine":"k8s-resource-level-monitor"},"level":"warning","msg":"failed to list objects for SparkApplication.v1beta2: failed to get API group resources: unable to retrieve the complete list of server APIs: v1beta2: the server could not find the requested resource","ts":"2024-05-29T19:25:22Z"}
```

### Expected behavior

Resource Manager is able to correctly list custom resources 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment]
@trevormcguire would you be willing to submit a PR to correctly set the API version?

**Comment by trevormcguire** [comment]
> @trevormcguire would you be willing to submit a PR to correctly set the API version?

@hamersaw sure, will work on that
