### ISSUE TITLE
[Core Feature] Local logs for local container task executions.

### ISSUE THREAD

**Issue by dansola** [flyteorg/flyte#5436]
It would be nice if we could have something like a boolean flag that controls if local container tasks output logs to the terminal. 

I think think could be added somewhere around [here](https://github.com/flyteorg/flytekit/blob/59413c2926311a42e691aaf7ec32416201f16614/flytekit/core/container_task.py#L247) using the `.logs()` method of the docker client shown on [this page](https://docker-py.readthedocs.io/en/stable/containers.html).

An example of the SDK UX could be something like this:

```
from flytekit import ContainerTask, workflow

echo_container_task = ContainerTask(
    name="echo",
    image="alpine:latest",
    command=["echo", "'a test to show stdout'"],
    local_logs=True,
)

@workflow
def echo_workflow() -> None:
    return echo_container_task()

if __name__ == "__main__":
    print(echo_workflow())
```

where `local_logs` is ignored if it is a remote execution.

**Comment by aditya7302** [comment]
I would like to work on this issue can you assign it to me ?

**Comment by dansola** [comment]
Hi @aditya7302. Of course! Thank you for taking on this issue. 🚀 🙏
