### ISSUE TITLE
[BUG] The inputs/outputs Python code snippet leads to a "Failed to connect" error

### ISSUE THREAD

**Issue by ddl-rliu** [flyteorg/flyte#5578]
### Describe the bug

The code snippet in flyteconsole leads to an error like:
```
FlyteSystemException: SYSTEM:Unknown: error=None, cause=InactiveRpcError ...
error = "UNKNOWN:Error received from peer  grpc_message:failed to connect to all addresses; ... "
```

This is because the code snippet is built around `FlyteRemote.get` which uses gRPC, while [the code snippet generated in the Flyte UI uses `window.location.host` e.g. `Config.for_endpoint(window.location.host)`](https://github.com/flyteorg/flyteconsole/blob/7636e32d2b1dbefb7d08fb79e5ed063c3ad44ca4/packages/oss-console/src/components/Executions/ExecutionDetails/ExecutionNodeURL.tsx#L39), however this URL does not necessarily map to the gRPC endpoint.

## Idea for Fix

Users already configure flytekit in `~/.flyte/config.yaml` to set `admin.endpoint` to the correct gRPC endpoint. We can leverage this by using `Config.auto()` auto config, and building the code snippet around this Config.

Proposed fix in PR: https://github.com/flyteorg/flyteconsole/pull/883

### Expected behavior

The inputs/outputs Python code snippet works

### Screenshots

Current behavior:
![image](https://github.com/user-attachments/assets/e190cae2-4133-45c7-b273-51af84ae2f60)

Proposed fix, when configured to use auto config:
![image](https://github.com/user-attachments/assets/e4fa6927-4960-44ae-86fa-9d65f1466b21)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
It's worth mentioning that this solution only works in the cases where the default config file, i.e. `~/.flyte/config.yaml`, points to the right place. 

Given that the proposed solution is opt-in, this is more than acceptable. The next Flyte release is going to contain that.
