### ISSUE TITLE
[Feature] Add multi-query Presto support

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#562]
**Motivation: Why do you think this is important?**
When developing the Presto plugin, we overlooked the fact that users can't submit multiple queries within one query like they can in Hive and most other query languages.  Thus the practice of setting up temp tables to stage data before a final query is not something that is easily done.

We shoul further investigate this need, and amend the Presto task/plugin to be able to support this use case.  Perhaps a series of related queries can be passed in per task that can be run sequentially.  This brings in questions around atomicity of course.

**Goal: What should the final outcome look like, ideally?**
Support users who want to first query into a temp table, and then make a final query.  Should investigate if this is possible with with statements in the current framework.

**Describe alternatives you've considered**
with statements?

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [x] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Additional context**

**Is this a blocker for you to adopt Flyte**
Please let us know if this makes it impossible to adopt Flyte

**Comment by kumare3** [comment]
I think we should close this issue, as Flyte Agent framework can add support for this, if needed
