### ISSUE TITLE
[Feature] Presto InsertOverride behavior

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#563]
**Motivation: Why do you think this is important?**
Figure out issues with the existing with insert override, insert append, and other query types Presto supports.  Document the issues here and figure out what the open-source solution should be.

**Goal: What should the final outcome look like, ideally?**
TBD

**Describe alternatives you've considered**
TBD.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [x] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Additional context**

**Is this a blocker for you to adopt Flyte**
Please let us know if this makes it impossible to adopt Flyte

**Comment by kumare3** [comment]
With agent support this should be moved to agent and agent can support arbitrary behavior
