### ISSUE TITLE
[Housekeeping] Drop support for python 3.8

### ISSUE THREAD

**Issue by eapolinario** [flyteorg/flyte#5633]
### Describe the issue

As per https://devguide.python.org/versions/, python 3.8 will stop receiving security patches in November-2024. We should stop supporting that version once that happens.

### What if we do not do this?

We won't be able to use a lot of more modern python conventions and features.

### Related component(s)

flytekit

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Terryhung** [comment]
#take

**Comment by Terryhung** [comment]
#take
