### ISSUE TITLE
[Housekeeping] Release new version of flytectl

### ISSUE THREAD

**Issue by bcvanmeurs** [flyteorg/flyte#5638]
### Describe the issue

flytectl/v0.9.0 does not pass our security audits due to a known and fixed CVE in [github.com/docker/docker](https://github.com/advisories/GHSA-v23v-6jw2-98fq), I noticed that the flytectl dependencies in main are already updated to `http://github.com/docker/docker v26.1.5+incompatible` which does not have the CVE.

Could you create a new release to fix this?

### What if we do not do this?

Flytectl contains known CVE

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
https://github.com/flyteorg/flyte/releases/tag/flytectl%2Fv0.9.1 is out.
