### ISSUE TITLE
[Docs] Improve registration patterns docs

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/flyte#5669]
### Description

Questions related to this topic lead to think that expanding and updating the [Registering workflows](https://docs.flyte.org/en/latest/flyte_fundamentals/registering_workflows.html) section would be useful to make sure it's easier to understand.

[Question](https://discuss.flyte.org/t/22925077/hi-again-wave-we-ve-been-going-around-in-circles-with-this-o)
[Question](https://flyte-org.slack.com/archives/CREL4QVAQ/p1724062662953219)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by siiddhantt** [comment]
hi, could I be assigned this issue, I'd like to work on it

**Comment by davidmirror-ops** [comment]
@siiddhantt done. Please let us know soon if you have questions or need help. Thanks!

**Comment by siiddhantt** [comment]
Thanks @davidmirror-ops , I've opened a PR for this issue. Do lmk if it needs improvement or anything else.

**Comment by JiangJiaWei1103** [comment]
Hello, could I also work on this issue? Thanks.
