### ISSUE TITLE
[Housekeeping] Improve ImageSpec error message on wrong registry format

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/flyte#5689]
### Describe the issue

When, by mistake, I use an incorrectly formatted registry in the ImageSpec config:

```sklearn_image_spec = ImageSpec(
    base_image="ghcr.io/flyteorg/flytekit:py3.9-latest",
    packages=["scikit-learn"],
    registry="ghcr.io/davidmirror-ops/flyte-scklearn:latest", 
)
```

Instead of failing, `pyflyte run` throws a misleading message and proceeds with execution:

```Running Execution on Remote.
Image ghcr.io/davidmirror-ops/flyte-sklearn:latest/flytekit:QDS_o1_Z2WBpkL_QFfWuYw found. Skip building.
```

Of course the image is not there in the registry, so not sure why it says `found`

### What if we do not do this?

New users could spend cycles troubleshooting this. 

It's important to note that the console gives a better error message, one that actually points to the problem:

`|Failed to apply default image tag "ghcr.io/davidmirror-ops/flyte-sklearn:latest/flytekit:iF_UE5oVrp6HRxnCSINhEg": couldn't parse image name "ghcr.io/davidmirror-ops/flyte-sklearn:latest/flytekit:iF_UE5oVrp6HRxnCSINhEg": invalid reference format`

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
Can we validate the registry naming rule?
