### ISSUE TITLE
[BUG] flytestdlib/cache unit tests are flaky

### ISSUE THREAD

**Issue by Sovietaced** [flyteorg/flyte#5711]
### Describe the bug

During a recent build in CI I encountered a unit test failure. I noticed that pluggable / test time sources aren't being used in thees unit tests which may lead to flakes depending on how slowly the unit tests are executed. It would be best to use a test time source instead, it will also speed up the tests because they won't have to sleep. 

```
--- FAIL: TestCacheFour (8.11s)
    --- FAIL: TestCacheFour/Test_panic_on_sync_and_shutdown (5.50s)
        auto_refresh_test.go:200: 
            	Error Trace:	/home/runner/work/flyte/flyte/flytestdlib/cache/auto_refresh_test.go:200
            	Error:      	Condition never satisfied
            	Test:       	TestCacheFour/Test_panic_on_sync_and_shutdown
        auto_refresh_test.go:208: 
            	Error Trace:	/home/runner/work/flyte/flyte/flytestdlib/cache/auto_refresh_test.go:208
            	Error:      	Not equal: 
            	            	expected: 10
            	            	actual  : 0
            	Test:       	TestCacheFour/Test_panic_on_sync_and_shutdown
```

### Expected behavior

The unit tests pass and are deterministic.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@Sovietaced , this is a great idea. We should integrate https://pkg.go.dev/k8s.io/utils/clock/testing as part of these tests. Example in https://github.com/kubernetes/client-go/blob/master/util/workqueue/rate_limiting_queue_test.go#L26.

**Comment by Sovietaced** [comment]
> @Sovietaced , this is a great idea. We should integrate https://pkg.go.dev/k8s.io/utils/clock/testing as part of these tests. Example in https://github.com/kubernetes/client-go/blob/master/util/workqueue/rate_limiting_queue_test.go#L26.
> 
> Do you want to give this a try?

Yeah I'll take care of this.
