### ISSUE TITLE
[Core feature] Support specifying workflow labels for the default launch plan in the workflow definition

### ISSUE THREAD

**Issue by swarup-stripe** [flyteorg/flyte#5774]
### Motivation: Why do you think this is important?

Currently [workflow labels/annotations](https://docs.flyte.org/en/latest/user_guide/productionizing/workflow_labels_and_annotations.html) can only be supplied when you launch an execution or when you create a launch plan that's not the default. This creates a big friction point to specifying labels since you have to manually toggle something in the Flyte Console (either to specify the label or switch the launch plan to the one with the label). This will help us add workflow-level metadata and propagate that to all tasks easier.

### Goal: What should the final outcome look like, ideally?

Specifying labels directly in the workflow definition like the decorator e.g. `@workflow(labels=Labels({"sample-label": "sample-value"})`.

### Describe alternatives you've considered 

We can currently specify it when creating a launch plan but this involves manually switching the launch plan in Flyte Console which is prone to accidents. We can also directly enter in the Flyte Console when launching executions. But again this is prone to accidents. Since the label metadata is semantically tied to the whole workflow not just that particular launch plan, this isn't ideal. We can also leverage `pod_template` to specify labels to each pod but we'd have to annotate each task in the workflow manually.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by davidmirror-ops** [comment]
Original post on Slack: https://flyte-org.slack.com/archives/CP2HDHKE1/p1726850294050909

**Comment by Mecoli1219** [comment]
#take

**Comment by pingsutw** [comment]
@swarup-stripe, if we support setting another launch plan as default, would that address your issue? Therefore, you won't need to switch the launch plan in Flyte Console.

**Comment by swarup-stripe** [comment]
Thank you all for the quick turnaround time and for the PR @Mecoli1219!!! 

@pingsutw That could technically address it, but ideally we want to enforce having a label and avoid having any unlabelled launch plans so this is definitely the better solution.
