### ISSUE TITLE
Flyte Hacktoberfest 2024: issues and guidelines

### ISSUE THREAD

**Issue by davidmirror-ops** [flyteorg/flyte#5783]
### Describe the issue

Hello hello 👋!

It's that time of year again! We're excited to kick off Hacktoberfest and get you started on your open-source contributions. 

This page covers all the issues and contribution guidelines to help you get started with Flyte and Hacktoberfest!

### Resources 
- [Contribution guide](https://docs.flyte.org/en/latest/community/contribute.html) 
- Questions? Go to the [#hacktoberfest-2024](https://flyte-org.slack.com/archives/C07NTJH4WDV) channel

### Guidelines
- Before working on an issue, ask questions and make sure you understand the problem and how to fix it. Then, add a comment on the issue requesting to be assigned or leave a comment with #take.
- On the PR, use one of the [Github-supported keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to link it back to the issue.
- After a first review, the PR will get the `hacktobertfest-accepted` label and we expect you to apply feedback and shepherd your contribution until it's merged.
- If the issue is assigned to you, but someone else sends a valid PR before you do, we'll ask and wait for 2 days to get your PR. Otherwise, the first PR will be accepted.

### Prizes

To thank you for your contributions, we have prizes!  From exclusive **Flyte t-shirts and stickers to cozy sweatshirts, and a pair of the new AirPods Pro 2 for those big contributions (including new integrations/plugins).** Every contribution registered in the form will receive a prize, the more contributions you make, and the more significant the contribution, the greater the prize.

Fill out [this form](https://tally.so/r/mJJ14r) to register your merged PRs or content contributions on or before Oct. 31, 2024.

---
# Content contributions

If you're here, you're probably at the same time learning Flyte and trying to improve the codebase, which is hard.
You can split the effort and increase your chances of earning well-deserved swag:

- Write a blog post teaching something you learned about Flyte.  Examples include: how to install Flyte, how to use a particular plugin/agent, how to fix a common problem, etc.

- Record a demo showcasing something you learned about Flyte.

In any of these cases, let us know in the [#hacktoberfest-2024](https://flyte-org.slack.com/archives/C07NTJH4WDV) channel or by commenting here where you post/plan to post the content and we'll review it. Once reviewed and accepted, swag will be yours.

---

# Code and Documentation Contribution opportunities

This year we wanted to focus on the many aspects of the Flyte documentation and examples that can be improved.

The following is a detailed breakdown of all the available issues against the repository they relate to:

| Repo | Scope | Tech stack | Section |
| -------- | -------- | -------- | ------- |
| [Flytekit](https://github.com/flyteorg/flytekit)     | Python SDK & Integrations     | Python | [Flytekit](#flytekit)
| [Flytesnacks](https://github.com/flyteorg/flytesnacks) | Examples | Python, Sphinx | [Flytesnacks](#flytesnacks)
| [Flyte](https://github.com/flyteorg/flyte) | Backend, documentation, console | Golang, Markdown , reStructuredText| [Flyte](#flyte) |

## Flytesnacks

[Contribution Guide](https://docs.flyte.org/en/latest/flytesnacks/contribute.html)

- [ ] https://github.com/flyteorg/flyte/issues/5738
- [ ] https://github.com/flyteorg/flyte/issues/4455
- [ ] https://github.com/flyteorg/flyte/issues/4066
- [x] https://github.com/flyteorg/flyte/issues/4065
- [ ] https://github.com/flyteorg/flyte/issues/3516
- [ ] https://github.com/flyteorg/flyte/issues/3448
- [ ] https://github.com/flyteorg/flyte/issues/3447
- [ ] https://github.com/flyteorg/flyte/issues/3285
- [x] https://github.com/flyteorg/flyte/issues/4463
- [ ] https://github.com/flyteorg/flyte/issues/4194
- [ ] https://github.com/flyteorg/flyte/issues/3135
- [ ] https://github.com/flyteorg/flyte/issues/3084

## Flyte
[Contribution guide](https://docs.flyte.org/en/latest/community/contribute.html#)
- [ ] https://github.com/flyteorg/flyte/issues/1512
- [ ] https://github.com/flyteorg/flyte/issues/5760
- [x] https://github.com/flyteorg/flyte/issues/5669
- [ ] https://github.com/flyteorg/flyte/issues/5552
- [ ] https://github.com/flyteorg/flyte/issues/5534
- [ ] https://github.com/flyteorg/flyte/issues/5435
- [ ] https://github.com/flyteorg/flyte/issues/5021
- [ ] https://github.com/flyteorg/flyte/issues/4955
- [ ] https://github.com/flyteorg/flyte/issues/4953
- [ ] https://github.com/flyteorg/flyte/issues/4881
- [ ] https://github.com/flyteorg/flyte/issues/4830
- [x] https://github.com/flyteorg/flyte/issues/4764
- [x] https://github.com/flyteorg/flyte/issues/4685
- [x] https://github.com/flyteorg/flyte/issues/4684
- [x] https://github.com/flyteorg/flyte/issues/4683
- [ ] https://github.com/flyteorg/flyte/issues/4653
- [ ] https://github.com/flyteorg/flyte/issues/4623
- [x] https://github.com/flyteorg/flyte/issues/4614
- [x] https://github.com/flyteorg/flyte/issues/4613
- [x] https://github.com/flyteorg/flyte/issues/4513
- [ ] https://github.com/flyteorg/flyte/issues/4464
- [x] https://github.com/flyteorg/flyte/issues/4462
- [x] https://github.com/flyteorg/flyte/issues/4461
- [x] https://github.com/flyteorg/flyte/issues/4460
- [ ] https://github.com/flyteorg/flyte/issues/4459
- [x] https://github.com/flyteorg/flyte/issues/4457
- [x] https://github.com/flyteorg/flyte/issues/4456
- [x] https://github.com/flyteorg/flyte/issues/4392
- [ ] https://github.com/flyteorg/flyte/issues/4067
- [x] https://github.com/flyteorg/flyte/issues/4052
- [x] https://github.com/flyteorg/flyte/issues/3956
- [ ] https://github.com/flyteorg/flyte/issues/3791
- [ ] https://github.com/flyteorg/flyte/issues/3341
- [ ] https://github.com/flyteorg/flyte/issues/3328
- [ ] https://github.com/flyteorg/flyte/issues/3322
- [ ] https://github.com/flyteorg/flyte/issues/3249
- [ ] https://github.com/flyteorg/flyte/issues/3163
- [ ] https://github.com/flyteorg/flyte/issues/2754
- [ ] https://github.com/flyteorg/flyte/issues/2513

## Flytekit

[Contribution Guide](https://docs.flyte.org/en/latest/api/flytekit/contributing.html)
- [ ] https://github.com/flyteorg/flyte/issues/3005
- [ ] https://github.com/flyteorg/flyte/issues/2963

## Flyteconsole

[Contribution Guide](https://github.com/flyteorg/flyteconsole/blob/master/README.md)

- [ ] https://github.com/flyteorg/flyte/issues/5194
- [ ] https://github.com/flyteorg/flyte/issues/5099
- [ ] https://github.com/flyteorg/flyte/issues/2908

---

We hope you enjoy the contribution experience and are looking forward to seeing what you come up with!

Happy Hacktoberfest!

**Comment by abhirajadhikary06** [comment]
Can you put the **slack link** in comment. Unable to access it from the README.

**Comment by ini-tech** [comment]
wrote an article about Flyte: https://medium.com/@iniabasie/how-does-flyte-enhance-machine-learning-workflow-efficiency-for-businesses-34ee38fab426

what do you guys think?

**Comment by davidmirror-ops** [comment]
@ini-tech thank you. Just left some comments on the post.

**Comment by abhirajadhikary06** [comment]
Any updates on receiving/shipping of swags ?

**Comment by ini-tech** [comment]
@davidmirror-ops updated the docs accordingly, thanks

**Comment by davidmirror-ops** [comment]
@Soot3 awesome, here are the [unassigned issues](https://github.com/flyteorg/flyte/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee). Thank you!

**Comment by davidmirror-ops** [comment]
@abhirajadhikary06 yeah, we'll be reaching out to each contributor with shipping confirmation. Thank you!

**Comment by davidmirror-ops** [comment]
We want to thank everyone who contributed to Flyte during Hacktoberfest this year. We have received your feedback, contribution details, and shipping information in [the form](https://tally.so/r/mJJ14r) and we'll be reaching out to you with shipping confirmation for your well-earned swag. Thanks!
