### ISSUE TITLE
[BUG] TypeTransformerFailedError when using empty dict

### ISSUE THREAD

**Issue by linhai-fn** [flyteorg/flyte#5804]
### Describe the bug

Before [flyteorg/flytekit#2743](https://github.com/flyteorg/flytekit/pull/2743) introduced in `1.13.6`, the workflow/task like below can handle empty dict.

```python
from flytekit import task, workflow

@task
def print_dict(x: dict[str, str]) -> None:
    for k, v in x.items():
        print(f"{k}: {v}")

@workflow
def print_workflow() -> None:
    print_dict(x={})


if __name__ == "__main__":
    print(f"Running print_workflow() {print_workflow()}")
```

With `>=1.13.6`, the flyte will throw a TypeTransformerFailedError error:

```bash
% pyflyte run workflow.py print_workflow
Running Execution on local.
TypeTransformerFailedError: Failed to convert inputs of task 'workflow.print_dict':
  Failed argument 'x': Not all values in '{}' are of type <class 'str'>
```

### Expected behavior

The workflow/task should be able to accept empty dict like they used to in `<1.13.6`. Unless this breaking change is intentional?

### Additional context to reproduce

The cause of the error is due to [this part of the code](https://github.com/flyteorg/flytekit/blob/ea1c00fa3830d1097f2e34cab5a0fcf13578c740/flytekit/core/type_engine.py#L165-L171). Similar error will raise for empty list/tuple/set due to [similar logic](https://github.com/flyteorg/flytekit/blob/ea1c00fa3830d1097f2e34cab5a0fcf13578c740/flytekit/core/type_engine.py#L159-L163).

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by charliemoriarty** [comment]
We are also encountering this issue, and it has broken several of our tasks and unit tests. As a temporary workaround, we've switched to using the deprecated `typing.List` and `typing.Dict` types for lists/dicts that need support for being empty, but this feels quite messy..

**Comment by wild-endeavor** [comment]
will be in v1.13.9 and later.
