### ISSUE TITLE
[BUG] pyflyte run should execute the active launch plan by default

### ISSUE THREAD

**Issue by avasani** [flyteorg/flyte#5834]
### Describe the bug

When executing a launch plan using pyflyte run, the execution currently defaults to the latest version of the launch plan, ignoring the active version set by the user. This behavior can lead to unexpected executions, especially when a user has intentionally activated an older version for rollback purposes.

### Expected behavior

pyflyte run should execute the active version of the launch plan when one is set. If no active version is specified, it could default to the latest version or best would throw some error or queue it.

### Additional context to reproduce

pyflyte run remote-launchplan <lp_name>
The execution uses the latest version of the launch plan, disregarding the active version setting.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@avasani , this feature was implemented in https://github.com/flyteorg/flytekit/pull/2796. It's already present in the flytekit beta release 1.14.0b1 and will go out in the next official release 1.14.0.
