### ISSUE TITLE
[BUG] Enable Resolving Attribute Path for List or Dict Workflow Inputs

### ISSUE THREAD

**Issue by Mecoli1219** [flyteorg/flyte#5856]
### Describe the bug

When we define a workflow where one of the tasks will take a list as input. When we use a Promise with an attribute path from another task or sub-workflow as one element of the input, It will throw an error. For instance:

```
@task(container_image=image)
def task_1(in1: int) -> typing.List[int]:
    return list(range(max(2, in1)))

@task(container_image=image)
def task_2(in1: int, in2: typing.List[int]) -> int:
    return in1 + sum(in2)

@workflow
def my_wf(in1: int, in2: int) -> int:
    a = task_1(in1=in1)
    a1 = a[0]
    a2 = a[1]
    return task_2(in1=5, in2=[a1, a2, in2])
```

Here, `in2` of the input `task_2` will be a list of Promise, and [promise::_translate_inputs_to_literals](https://github.com/flyteorg/flytekit/blob/1f8a273bff85e322c7f0a8e244acf15e6186e10e/flytekit/core/promise.py#L53C1-L58C42) will transform it to Literal (`LiteralCollection` in this case). However, it didn't try to resolve the attribute path of the Promises inside the list. Therefore, this error is received:
<img width="849" alt="image" src="https://github.com/user-attachments/assets/afa22624-d5e1-4a0a-b9eb-af9a1124070b">

This is just an example of a List of Promises. There should be a similar error with Dictionary and Tuple (Tuple is currently under development).

### Expected behavior

It should be supported. 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Mecoli1219** [comment]
#take

**Comment by eapolinario** [comment]
Thank you.
