### ISSUE TITLE
[Docs] 404 Error on Documentation Contribution Page

### ISSUE THREAD

**Issue by Sean-fn** [flyteorg/flyte#5868]
### Description

The CONTRIBUTING.md file links to a documentation page that returns a 404 error.
The file direct me to [here](https://docs.flyte.org/en/latest/community/contribute.html)

### Are you sure this issue hasn't been raised already?

- [x] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by taieeuu** [comment]
#take
