### ISSUE TITLE
[BUG] The plugins workqueue seem to be processing the same items over and over again

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#587]
**Expected behavior**
Each item is processed only once if successful. 

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [x] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Comment by kumare3** [comment]
@EngHabu the associated PR seems to be stale, should we move it to the next milestone?

**Comment by kumare3** [comment]
@EngHabu I do see a PR for this. Is this still a problem?

**Comment by EngHabu** [comment]
After further investigation, there is no bug here... the current behavior automatically marks items as done.
