### ISSUE TITLE
[Feature] Support "Enum/Options" type as Flyte Input

### ISSUE THREAD

**Issue by thechopkins** [flyteorg/flyte#590]
**Motivation: Why do you think this is important?**
One pain point today for kicking off workflows manually is with users specifying invalid inputs. An example, if you have a workflow that takes color as an input and only works for three values (blue, green, orange), we should be able to limit the options that the user enters into the workflow. Instead today, we generally have to write a single initial task that validates that the input is in a specific set and fast-fail if it is outside of a recommended value

**Goal: What should the final outcome look like, ideally?**
Ideally, when a workflow is kicked off from the UI, instead of being a free text field, a combo box could show up, populated with items that are specified in the workflow's definition. An example `Input` definition could then look like:
`Input(Types.String, default='green', options=['green', 'blue', 'orange'])`

**Describe alternatives you've considered**
Another potential option here is enabling a validation hook specifically on an input field before a workflow runs that could run either in ui, or on a delta change for an input text box.
ex. `Input(Types.String, default='green', validation_fn=lambda x: x in {'blue', 'green', 'orange'}, validation_failure_string="Input must be in {'blue', 'green', 'orange'})`

**Flyte component**
- [x] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [x] FlyteStdlib (common libraries)
- [x] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Additional context**

**Is this a blocker for you to adopt Flyte**
Please let us know if this makes it impossible to adopt Flyte

**Comment by mahanh** [comment]
This is going to be the great feature and needed for us as well.
The same as above description we would also like to limit users to pick the right option and not a free text for inputs.

**Comment by kumare3** [comment]
@mahanh / @thechopkins this is in progress - https://github.com/flyteorg/flyteidl/pull/183

**Comment by EngHabu** [comment]
Pushing to next milestone. I _think_ the remaining work is in flyte console? @kumare3

**Comment by kumare3** [comment]
@EngHabu yes, but I want to create a separate UI task for this, as we can then group together all of this into the Flyteconsole project

**Comment by kumare3** [comment]
@thechopkins / @mahanh / @EngHabu this is available now and can be used through flytectl (no console support yet)
