### ISSUE TITLE
[错误]Cannot add Flyte library

### ISSUE THREAD

**Issue by yujiaxin123** [flyteorg/flyte#5906]
### Describe the bug

helm repo add flyteorg https://flyteorg.github.io/flyte
Error: looks like "https://flyteorg.github.io/flyte" is not a valid chart repository or cannot be reached: Get "https://flyteorg.github.io/flyte/index.yaml": EOF

### Expected behavior

Previously, it was accessible, but now it cannot be accessed. How can we solve this problem? Need help

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by davidmirror-ops** [comment]
@yujiaxin123 what version of Helm are you using? what OS? I couldn't reproduce this with Helm 3.15.4 on macOSx

**Comment by yujiaxin123** [comment]
> @yujiaxin123你使用的是哪个版本的 Helm？什么操作系统？我无法在 macOSx 上使用 Helm 3.15.4 重现此问题
我使用的是tencentos的操作系统，helm版本是v3.16.1。

**Comment by eapolinario** [comment]
This is surprising, since `helm.flyte.org` is just a [CNAME](https://github.com/flyteorg/flyte/blob/gh-pages/CNAME) backed by github page. In other words, we rely on github to serve https://flyteorg.github.io/flyte/index.yaml.

**Comment by yujiaxin123** [comment]
> 这很令人惊讶，因为`helm.flyte.org`它只是一个由 github 页面支持的[CNAME](https://github.com/flyteorg/flyte/blob/gh-pages/CNAME)。换句话说，我们依赖 github 来提供https://flyteorg.github.io/flyte/index.yaml。

已经解决了，感谢您支持，这面使用离线下载的方式可以成功部署
