### ISSUE TITLE
[BUG] Make Flytefile and Flytedirectory's copilot local execution work correctly

### ISSUE THREAD

**Issue by Future-Outlier** [flyteorg/flyte#5929]
### Describe the bug

In the unit test below, `"{{.inputs.inputs}}"`, is a wrong syntax, please make `/var/inputs` work.
(for FlyteFile and FlyteDirectory, we should not use the template's syntax above.
If we use it, the propeller will retrieve the blob type's path, which is not the expected behavior we want.

https://github.com/flyteorg/flytekit/blob/master/tests/flytekit/unit/core/test_local_raw_container.py#L16-L61

### Expected behavior

For flyte directory and flyte file,
make `/var/inputs` work and make `"{{.inputs.inputs}}"` doesn't.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wayner0628** [comment]
#take
