### ISSUE TITLE
[BUG] github.com/flyteorg/flyte/flytectl/cmd/sandbox	unit test is flaky 

### ISSUE THREAD

**Issue by Sovietaced** [flyteorg/flyte#5937]
### Describe the bug

Its not clear why but this unit test seems to flake when running on CI. 
```
FAIL	github.com/flyteorg/flyte/flytectl/cmd/sandbox	0.086s
```

https://github.com/flyteorg/flyte/actions/runs/11580285322/job/32238460143?pr=5814

### Expected behavior

I expect the unit test to pass. 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by nkwangleiGIT** [comment]
seems this testcase was successful at the latest attempt, it's not clear why it failed here, and not able to reproduce it locally.
do we have any log to check for the root cause in the CI? or we can add one for later investigation.

**Comment by Sovietaced** [comment]
> seems this testcase was successful at the latest attempt, it's not clear why it failed here, and not able to reproduce it locally.
> 
> do we have any log to check for the root cause in the CI? or we can add one for later investigation.

I don't but I have a hunch the flakiness is related to transient issues with the docker calls and the GitHub runner.

**Comment by eapolinario** [comment]
This is related to https://github.com/flyteorg/flyte/pull/5325 in that that PR didn't replace all instances of the `testutils.Setup` with the corresponding teardown.

Here's a PR with the fix: https://github.com/flyteorg/flyte/pull/5950
