### ISSUE TITLE
[BUG] Structured Dataset create with remote uri and read directly will fail

### ISSUE THREAD

**Issue by Future-Outlier** [flyteorg/flyte#5954]
### Describe the bug

This case should work.
```python
@task
def return_sd() -> StructuredDataset:
    sd = StructuredDataset(uri="s3://my-s3-bucket/s3_flyte_dir/df.parquet", file_format="parquet")
    print("sd:", sd.open(pd.DataFrame).all())
    return sd
```

### Expected behavior

This should work.

### Additional context to reproduce

1. we should upload a parquet file to s3 storage first.
2. FlyteFile maybe has the same bug by @pingsutw 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by JiangJiaWei1103** [comment]
Hi @Future-Outlier,

If I'm not mistaken, steps to reproduce the error are described as follows:
1. Upload a simple parquet file to s3 storage:

![Screenshot 2024-11-05 at 9 45 56 PM](https://github.com/user-attachments/assets/57819c3d-c806-4c42-a95f-29c03dbfbdb5)

2. Run the task remotely by executing this command:
```
pyflyte run --remote reprod.py return_sd
```

### Error Message
![Screenshot 2024-11-05 at 9 51 59 PM](https://github.com/user-attachments/assets/0a71afb6-8ad0-44d5-bee5-b686c7ff29d5)

Does this match your experience?

**Comment by Future-Outlier** [comment]
> Hi @Future-Outlier,
> 
> If I'm not mistaken, steps to reproduce the error are described as follows:
> 
> 1. Upload a simple parquet file to s3 storage:
> 
> ![Screenshot 2024-11-05 at 9 45 56 PM](https://private-user-images.githubusercontent.com/36886416/383170739-57819c3d-c806-4c42-a95f-29c03dbfbdb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTgzMjAsIm5iZiI6MTczMDgxODAyMCwicGF0aCI6Ii8zNjg4NjQxNi8zODMxNzA3MzktNTc4MTljM2QtYzgwNi00YzQyLWE5NWYtMjljMDNkYmZiZGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE0NDcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1OTEwMmE1ZDFiMmFlZmMwY2NkZDU1ZTAxMjg5NDVlOWI0YThkZjM3ODE5YzdkN2U0ZGY0ZDI4NDljMzA4MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SyN69MeKDKs48QmuTiXi7EwyL7XNZC9EpKn-l58HBaY)
> 
> 2. Run the task remotely by executing this command:
> 
> ```
> pyflyte run --remote reprod.py return_sd
> ```
> 
> ### Error Message
> ![Screenshot 2024-11-05 at 9 51 59 PM](https://private-user-images.githubusercontent.com/36886416/383172763-0a71afb6-8ad0-44d5-bee5-b686c7ff29d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTgzMjAsIm5iZiI6MTczMDgxODAyMCwicGF0aCI6Ii8zNjg4NjQxNi8zODMxNzI3NjMtMGE3MWFmYjYtOGFkMC00NGQ1LWJlZTUtYjY4NmM3ZmYyOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE0NDcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyM2U4NzkyNDc4NmMwZDZjZWMzNDUzNmUyODcxNWIzODQ1ODE3MzMxMmY2YjFjOTRkNTY3Yjc0YjQwMjk3MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k6-qL_FQlxxvs4FPlbH7kuF-9qAPplfnSYvGXnoV35g)
> 
> Does this match your experience? Thanks.

yes and this will not work in local too.

**Comment by Future-Outlier** [comment]
> Hi @Future-Outlier,
> 
> If I'm not mistaken, steps to reproduce the error are described as follows:
> 
> 1. Upload a simple parquet file to s3 storage:
> 
> ![Screenshot 2024-11-05 at 9 45 56 PM](https://private-user-images.githubusercontent.com/36886416/383170739-57819c3d-c806-4c42-a95f-29c03dbfbdb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTgzMjAsIm5iZiI6MTczMDgxODAyMCwicGF0aCI6Ii8zNjg4NjQxNi8zODMxNzA3MzktNTc4MTljM2QtYzgwNi00YzQyLWE5NWYtMjljMDNkYmZiZGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE0NDcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1OTEwMmE1ZDFiMmFlZmMwY2NkZDU1ZTAxMjg5NDVlOWI0YThkZjM3ODE5YzdkN2U0ZGY0ZDI4NDljMzA4MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SyN69MeKDKs48QmuTiXi7EwyL7XNZC9EpKn-l58HBaY)
> 
> 2. Run the task remotely by executing this command:
> 
> ```
> pyflyte run --remote reprod.py return_sd
> ```
> 
> ### Error Message
> ![Screenshot 2024-11-05 at 9 51 59 PM](https://private-user-images.githubusercontent.com/36886416/383172763-0a71afb6-8ad0-44d5-bee5-b686c7ff29d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTgzMjAsIm5iZiI6MTczMDgxODAyMCwicGF0aCI6Ii8zNjg4NjQxNi8zODMxNzI3NjMtMGE3MWFmYjYtOGFkMC00NGQ1LWJlZTUtYjY4NmM3ZmYyOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE0NDcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyM2U4NzkyNDc4NmMwZDZjZWMzNDUzNmUyODcxNWIzODQ1ODE3MzMxMmY2YjFjOTRkNTY3Yjc0YjQwMjk3MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k6-qL_FQlxxvs4FPlbH7kuF-9qAPplfnSYvGXnoV35g)
> 
> Does this match your experience? Thanks.

my suggestion is that we should make local execution work first.

**Comment by JiangJiaWei1103** [comment]
## Follow-up Issues

After testing some cases, I observe two more errors:
* Open `StructuredDataset` with `df` set to a pandas DataFrame
```python
@task
def return_sd() -> StructuredDataset:
    sd = StructuredDataset(
        df=pd.DataFrame({
            "name": ["hanru", "jiawei"],
            "height": [190, 172]
        })
    )
    print("sd:", sd.open(pd.DataFrame).all())
    return sd
```

* Open `StructuredDataset` with local `uri`
```python
@task
def return_sd() -> StructuredDataset:
    sd = StructuredDataset(
        uri="./tmp/df.parquet",
        file_format="parquet"
    )
    print("sd:", sd.open(pd.DataFrame).all())
    return sd
```

Both of the cases are expected to work. I think they're highly related to this issue. But, I will fix the main error in the original proposal first. Draft PR can be found [here](https://github.com/flyteorg/flytekit/pull/2914).

**Comment by Future-Outlier** [comment]
Very nice, let's push it this week, will reach out you

**Comment by wild-endeavor** [comment]
in the [follow-up](https://github.com/flyteorg/flyte/issues/5954#issuecomment-2465223443) issues, i think the second one is more important than the first.  The first is a bit odd, esp if the type of the dataframe is different (polars, etc.)


Yeah, to what @pingsutw said, this issue affects files and folders also.  cc @eapolinario since he's trying to spend some time on this.  I think this is not so much a bug (it is that too) as it is a failure in ux design.
