### ISSUE TITLE
[BUG] Make Protobuf Struct Attribute Access local execurtion the same as remote execution

### ISSUE THREAD

**Issue by Future-Outlier** [flyteorg/flyte#5959]
### Describe the bug

When you run this example in the PR, if you set `os.environ["FLYTE_USE_OLD_DC_FORMAT"] = "true"` and run it in local execution, this will not work.
Good news is that remote work, and the root cause is that local execution has differ behavior from remote execution.

https://github.com/flyteorg/flytekit/pull/2894

### Expected behavior

Make local execution and remote execution have the same behavior.

#### Local Execution (wrong)
https://github.com/flyteorg/flytekit/blob/6e4e53bb89debbeef764d3a0a16e499e0bcd18e2/flytekit/core/promise.py#L164-L171

#### Remote Execution (correct)
https://github.com/flyteorg/flyte/blob/a87585ab7cbb6a047c76d994b3f127c4210070fd/flytepropeller/pkg/controller/nodes/attr_path_resolver.go#L72-L106

### Additional context to reproduce

flyte: master branch (wait for this PR to be merged: https://github.com/flyteorg/flytekit/pull/2894)
flytekit: master branch
2024/11/5

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by JiangJiaWei1103** [comment]
Hi @Future-Outlier,

Before embarking on solving this issue, I would like to ask whether the following error message matches your observation:

![Screenshot 2024-11-11 at 11 34 50 PM](https://github.com/user-attachments/assets/737fb05b-4d69-446b-b706-1da12007efad)

Btw, I confirm that the remote execution works as expected.

**Comment by Future-Outlier** [comment]
WILL REPLY YOU TMR
