### ISSUE TITLE
[BUG] MessagePack Decoder Fails to Deserialize Union with more than two non-None variants

### ISSUE THREAD

**Issue by mao3267** [flyteorg/flyte#5986]
### Describe the bug

Mentioned in flyteorg/flytekit#2859, while using dataclasses with union properties that have more than two non-None variants, the msgpack decoder will fail to decode the binary back to dataclass.  Currently, I have raised an issue at https://github.com/Fatal1ty/mashumaro/issues/255 describing this problem.

```py
from dataclasses import dataclass
from flytekit import task
from flytekit.types.file import FlyteFile
from typing import Union
from flytekit.image_spec import ImageSpec


flytekit_hash = "d4171c3cd79ed406988d4213e4e79ee2b0bd2a93"
flytekit = f"git+https://github.com/mao3267/flytekit.git@{flytekit_hash}"

image_spec = ImageSpec(
    name="serialize-union-1",
    packages=[flytekit],
    builder="default",
    registry="localhost:30000",
    apt_packages=["git", "gh"],
)

@dataclass
class DC:
    ff: Union[None, int, FlyteFile]

@task(container_image=image_spec)
def t_dc() -> DC:
    return DC(ff="s3://path")
```

### Expected behavior

The expected output should be something like `DC(ff=/var/folders/nc/zmjfff853y33j17lwwdk299w0000gn/T/flyte-h8b6o6_w/sandbox/local_flytekit/9489edd65d6ce1b52fa248a4ba0ba6a4/path)`, where `ff` is a FlyteFile type.

Current Output: `DC(ff={'path': 's3://path'})`, where the `ff` is a dict.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by Future-Outlier** [comment]
this is fixed by mashumaro!

**Comment by eapolinario** [comment]
Can you add a unit test to show that this works?

**Comment by mao3267** [comment]
It seems that it just released the new version, will add a unit test to make sure it works.
