### ISSUE TITLE
[copilot] rename sidecar to uploader

### ISSUE THREAD

**Issue by wayner0628** [flyteorg/flyte#5995]
### Motivation: Why do you think this is important?

The current naming of the upload container in Copilot as `sidecar` can be confusing, especially since we also have a dedicated `downloader` container. Given that this container primarily handles upload tasks, renaming it to something more descriptive would improve readability and understanding of its role.

### Goal: What should the final outcome look like, ideally?

The final outcome should involve renaming all instances of `sidecar` related to the upload container—both in the UI and codebase—to `uploader`.

### Describe alternatives you've considered 

NA

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by wayner0628** [comment]
#take

**Comment by Future-Outlier** [comment]
thank you, this is AMAZING

**Comment by eapolinario** [comment]
Thank you. This should be as simple as changing the string value [here](https://github.com/flyteorg/flyte/blob/b3330ba4430538f91ae9fc7d868a29a2e96db8bd/flyteplugins/go/tasks/pluginmachinery/flytek8s/copilot.go#L23), right? Please, make sure that it works end-to-end.

**Comment by wayner0628** [comment]
I think we also need to change the file and function names? Sure, I'll make it works e2e.

**Comment by kumare3** [comment]
i think this has been done, can we close this?

**Comment by wayner0628** [comment]
Yes!
