### ISSUE TITLE
[BUG] `LAZY_MODULES` is populated with modules, not strings.

### ISSUE THREAD

**Issue by patrick-kidger** [flyteorg/flyte#6046]
### Describe the bug

On this line: 

https://github.com/flyteorg/flytekit/blob/6f8b9a09c24b22553e249308abb36b14ff6a6876/flytekit/lazy_import/lazy_module.py#L21

Then `module_name not in LAZY_MODULES` will always return `True` as the list is populated with modules, not module names (i.e. strings).

That means that this check:

https://github.com/flyteorg/flytekit/blob/6f8b9a09c24b22553e249308abb36b14ff6a6876/flytekit/core/type_engine.py#L1264-L1266

will actually import all of pandas. This is slow.

### Expected behavior

I think the check you probably want here instead is `object.__getattribute__(module, "__class__") is not importlib.util._LazyModule`.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@pingsutw , can you take a look?
