### ISSUE TITLE
[Docs] Add error handling example for Raw containers

### ISSUE THREAD

**Issue by machichima** [flyteorg/flyte#6083]
### Description

In Raw container, we cannot raise error and trigger retries by simply using `raise`. Instead, the retry will be triggered when the container task write the `_ERROR` file to its output folder. This should be documented in the raw container example.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by machichima** [comment]
#take

**Comment by eapolinario** [comment]
Thank you for https://github.com/flyteorg/flyte/pull/6084!
