### ISSUE TITLE
[BUG] hostname v.s. nodeName in logging link template

### ISSUE THREAD

**Issue by ketian-indeed** [flyteorg/flyte#6086]
### Describe the bug

It's about the `{{ .hostname }}` parameter to generate a templated logging link.
As per the doc (https://docs.flyte.org/en/latest/user_guide/productionizing/configuring_logging_links_in_the_ui.html), this parameter is

> The hostname where the pod is running and logs reside

I interpreted it as the **specific node's hostname** where the pod has been scheduled to run, i.e., the pod's `spec.nodeName`.

However, it's currently set to the pod's `spec.hostname`, which is used to override the hostname the pod uses internally within its own network namespace:
https://github.com/flyteorg/flyte/blob/v1.13.3/flyteplugins/go/tasks/logs/logging_utils.go#L57

In practice, the node name is likely more useful for generating a logging link than the `spec.hostname` (actually, we're using it to generate a Datadog dashboard link and need this to query the host metrics).

### Expected behavior

I expect `{{ .hostname }}` parameter to be the hostname where the pod has been scheduled to run (`pod.Spec.NodeName`) instead of `pod.Spec.Hostname`.

If we believe it makes sense to have `{{ .hostname }}` parameter presenting `pod.Spec.Hostname`. It's better to update the doc mentioned above and also add a new parameter e.g. `{{ .nodeName }}`.

Thanks!

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@ketian-indeed , feel free to open a PR to disambiguate the meaning there. Here's the file to edit: https://github.com/flyteorg/flyte/blob/master/docs/user_guide/productionizing/configuring_logging_links_in_the_ui.md. Thank you!

**Comment by ketian-indeed** [comment]
@eapolinario, thanks! I filed https://github.com/flyteorg/flyte/pull/6088.
