### ISSUE TITLE
SdkTask/SdkLaunchPlan.Fetch go/nogo

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#611]

**Comment by katrogan** [comment]
@wild-endeavor @EngHabu what's the background on this? can we close?

**Comment by EngHabu** [comment]
The question we needed to answer is whether Reference tasks/launchplans/workflows are enough or whether we should support `SdkTask.Fetch`. I do not think we have actually revisited that decision since we were trying to finish off existing functionality...

@wild-endeavor @kumare3 have you guys thought about this some more?

**Comment by EngHabu** [comment]
This is now implemented in the new `remote` package.
CC @cosmicBboy
