### ISSUE TITLE
[Feature] Flyteadmin cluster resource controller should perform deletion changes

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#622]
**Motivation: Why do you think this is important?**
If a user adds a template to the cluster resource controller and then later on removes it, there's no automated process for picking up the deletion and applying it as a patch to existing resources.

**Goal: What should the final outcome look like, ideally?**
Deleting a custom template should result in the state of the world appearing as if the template had never existed.

**Describe alternatives you've considered**
The current implementation requires system administrators to go through and apply a patch to remove.deleted k8s resource attributes. This is a manual process and potentially error-prone.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [x] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Additional context**
N/A

**Is this a blocker for you to adopt Flyte**
N/A

**Comment by kumare3** [comment]
again not a useful feature
