### ISSUE TITLE
[Feature] Add a configurable limit for the number of active launch plans per workflow

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#629]
**Motivation: Why do you think this is important?**
It's possible for a stray user to activate many launch plans, all with schedules and potentially DDOS flyte. Configurable limits should be in place cap the number of schedules.

**Goal: What should the final outcome look like, ideally?**
Each workflow should have a max permitted number of active launch plans associated with it.

**Describe alternatives you've considered**
Per-project cap on active workflows (this is less granular)

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [x] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
All summarized above

**Additional context**
N/A

**Is this a blocker for you to adopt Flyte**
N/A

**Comment by kumare3** [comment]
this is not a requested feature
