### ISSUE TITLE
[Feature] SparkConfig should also look for kubernetes core configurations

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#632]
**Motivation: Why do you think this is important?**
`spark.kubernetes.executor.request.cores` should also be used to calculate the default limit/request in spark operator.

https://spark.apache.org/docs/latest/running-on-kubernetes.html
```
spark.kubernetes.executor.request.cores | (none) | Specify the cpu request for each executor pod. Values conform to the Kubernetes convention. Example values include 0.1, 500m, 1.5, 5, etc., with the definition of cpu units documented in CPU units. This is distinct from spark.executor.cores: it is only used and takes precedence over spark.executor.cores for specifying the executor pod cpu request if set. Task parallelism, e.g., number of tasks an executor can run concurrently is not affected by this. | 2.4.0
-- | -- | -- | --
spark.kubernetes.executor.limit.cores | (none) | Specify a hard cpu limit for each executor pod launched for the Spark Application. | 2.3.0
```

**Goal: What should the final outcome look like, ideally?**
Users may set either executor.cores or `spark.kubernetes.executor.request.cores` and the value should propagate correctly

**Describe alternatives you've considered**
NA

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [x] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Is this a blocker for you to adopt Flyte**
No

**Comment by kumare3** [comment]
@akhurana001 any updates on this?

**Comment by akhurana001** [comment]
Sorry, missed this. Should have a PR out later today or early next week.
