### ISSUE TITLE
[Feature] [FlyteKit] intra-task checkpointing and resumable task execution

### ISSUE THREAD

**Issue by bnsblue** [flyteorg/flyte#634]
**Motivation: Why do you think this is important?**
ML training processes are usually iterative and long-running. The ML community has developed the checkpointing mechanism to preserve partial progress of a training process. The benefit of this mechanism is two-fold. Firstly, it allows users to jump-start the next time in the case of crashing or things going unexpectedly. Secondly, some of those intermediate checkpoints might actually be higher-quality models. It is not uncommon to see ML practitioners keep track of the best checkpoints (e.g., in terms of performance on validation dataset) in addition to the final model.

Checkpointing not only helps ML practitioners make the training more robust and efficient but also has an implication on cost optimization. 

Today's cloud providers usually supply some types of interruptible compute instances as a way to maximize their own resource utilization. The incentive these providers give to the users is that leveraging these interruptible instances, such as AWS Spot Instances, gains the users some steep discounts on the hourly rates and therefore has the potential to save significantly.

Flyte's current way of leveraging spot instances works as follows: when a Flyte task is marked as interruptible, Flyte would first try to execute it on a spot instance and hope the execution to finish before getting interrupted. If the execution receives an interruption from the Spot Service, it is aborted and will be restarted from the beginning on the next instance it got scheduled onto. If the execution got interrupted too many times, to the extent that is beyond a predetermined level of tolerance, Flyte will then schedule it onto a normal, uninterruptible EC2 instance instead to ensure its completion.

This approach, however, has its limitations. When an execution runs on a Spot instance and gets interrupted, the progress is lost completely no matter how close it is to its completion. This lack of "resumability" incurs a significant amount of compute overhead, which naturally translates into extra dollars.

Checkpointing, luckily, provides the much-needed resumability. It allows users to persist some intermediate artifacts and data which allows the interrupted execution to resume from the partial progress made earlier without wasting time and money on computing what's already computed previously. 

**Goal: What should the final outcome look like, ideally?**
Flyte workflows are designed to be a way to checkpoint as they provide users a way to code a state machine with isolated failure domains. DataCatalog then helps in the recovery in alternate runs. With these two components working together, Flyte provides the checkpointing and resumption ability at task boundaries.

In this proposal, on the other hand, we aim to formulate the idea of explicit intra-task checkpointing. Our definition of intra-task checkpointing means a mechanism that (a) persists some intermediate artifacts that execution of user code produces on-demand, and (b) exposes them later to the same or a different execution of the same piece of user code so that users can "resume"

**Describe alternatives you've considered**

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [x] FlytePropeller
- [] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [x] FlytePlugins
- [x] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [x] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
Link to the design doc: https://docs.google.com/document/d/1Ds8TlZpiHjDV48yWNITqrUkXNZNv6tA7VwcYEOYonf4/edit?ts=5fb7050a#

**Additional context**

**Is this a blocker for you to adopt Flyte**
Please let us know if this makes it impossible to adopt Flyte

**Comment by kumare3** [comment]
@bnsblue are you going to continue working on this, or should we unassign you?

**Comment by bnsblue** [comment]
Sorry was on vacation. I saw you already unassigned me so I guess no further actions from my side?

**Comment by kumare3** [comment]
Quick thoughts for this task.

Some benefits of this solution for simple python tasks
1. Resume simple task executions especially in the case of Spot or other instance failures
2. Ability to have extremely long running tasks

Solution blueprint
1. FlytePropeller supports Task templating system - which is implemented here - https://github.com/flyteorg/flyteplugins/blob/master/go/tasks/pluginmachinery/core/template/template.go#L47. this can be extended to allow a new template parameters like `{{.previousCheckpointPath}}` and `{{.checkpointPath}}`. 
2. FlytePropeller can construct these checkpoint paths deterministically for every task execution (individual retries) - as is done for outputprefix.
3. Flytekits psuedo code should be something like
```python
class Checkpoint():
   def __init__(self, previous_checkpoint: Optional[str], new_checkpoint_location):
         ....

if previous_checkpoint_path != "":
    checkpoint = Checkpoint(previous=previous, new=new)
else:
     checkpoint = Checkpoint(new=new)

# In user core
cp = flytekit.current_context().checkpointer
bytearray = cp.restore() # Or none
....
cp.save(new_bytearray) # Currently we can store this synchronously, but the semantics can be best effort to eventually make this async
```

**Comment by kumare3** [comment]
cc @varshaparthay

**Comment by kumare3** [comment]
To add to the above, it should be possible to output the checkpoint information as an output of a task, this way the checkpoint is retrievable. This may need us to add a TypeTransformer for Checkpoint

**Comment by varshaparthay** [comment]
Thanks Ketan, I will get started on this by next week and share a document on impl details

**Comment by kumare3** [comment]
@varshaparthay one more thing we might want to consider is that we may want to keep the checkpoints between different retries distinct. Thus Propeller may need logic to pass the checkpoints between retries. This should be doable, but is some work

**Comment by kumare3** [comment]
The core PR's for intratask checkpointing support in backend have been merged. Now flytekit changes are still needed.
The following variable substitutions should be used to get platform specified prefixes for storing and retrieving checkpoint information.
 - `{{ .PrevCheckpointPrefix }}` A path to the checkpoint directory for the previous attempt. If this is the first attempt
    then this is replaced by an empty string
 - `{{ .CheckpointOutputPrefix }}` A Flyte aware path where the current execution should write the checkpoints.

**Comment by kumare3** [comment]
Moving the work in flytekit to the next milestone

**Comment by bnsblue** [comment]
This is amazing @kumare3!

**Comment by kumare3** [comment]
> This is amazing @kumare3! Can't wait to use this feature!

Though the scope has been changed to be per execution only. I am not sure if cross executions is desirable and really useful

**Comment by bnsblue** [comment]
> Though the scope has been changed to be per execution only. I am not sure if cross executions is desirable and really useful.

How does per execution checkpoint work? What's the use case?

**Comment by kumare3** [comment]
> > Though the scope has been changed to be per execution only. I am not sure if cross executions is desirable and really useful.
> 
> 
> 
> How does per execution checkpoint work? What's the use case?

Across retries, spot instance usage

**Comment by bnsblue** [comment]
Sounds good! Yeah I agree those are the first class use cases for this feature. Cross execution cases require more thoughts from the users and might be counterintuitive to use.

**Comment by bnsblue** [comment]
It however might still have some niche uses such as faster iterations for debugging given that Flyte maintains relationships between executions.

**Comment by kumare3** [comment]
@bnsblue i think you can still, use it for debugging, as the checkpoints are maintained. Good point, that the checkpoint paths are not exposed to the control plane
