### ISSUE TITLE
[Feature][UI] Show link to k8s dashboard on Execution Details page.

### ISSUE THREAD

**Issue by schottra** [flyteorg/flyte#642]
Administrators debugging issues with Flyte infrastructure would benefit from quick access to the k8s dashboard in order to access more information.
This link is cluster and region-specific, but typically each region will run its own instance of `flytconsole`. So, the UI just needs to be able to construct a link by substituting the `project`, `domain`, and `cluster` values from an Execution into a format string.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [x] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
* Flyteconsole will add an additional environment variable specifying the k8s dashboard format string, with placeholders for the `project`, `domain`, and `cluster` values. If this value is present in the client-side bundle, we will render an additional link on the ExecutionDetails page to the k8s dashboard for the cluster.

**Comment by kumare3** [comment]
@schottra how do we know where the cluster is hosted at - I mean the endpoint? 
At Lyft we use the cluster id in a dns configuration, but that may not be true always. This seems to be a configuration that should be driven from FlyteAdmin. @anandswaminathan ?

**Comment by schottra** [comment]
@kumare3 Platform administrators in any given deployment know what the url is and that would be provided as an environment variable to flyteconsole. My understanding is that the only parts which change regularly are the cluster/project/domain. 
So, for example, we may provide an environment variable of the form:
```
K8S_DASHBOARD_FORMAT_STRING=https://dashboard.ingress.{{cluster}}.us-east-1.mycompany.com/#!/pod?namespace={{project}}-{{domain}}
```
Flyteconsole would read this env variable and do a string format to insert the correct values fro cluster/project/domain.

I agree that a more robust solution would be to add the dashboard link as a field on an entity returned by Admin and have administrators configure Admin with the correct values. That may require more effort than is available at the moment. :-)

**Comment by kumare3** [comment]
@schottra thank you for the detailed explanation. So just a couple things
1. Absence of this configuration removes the link from the UI?
2. not all the placeholders required right? - For example some deployments do not use project-domain as the namesapce - L5

**Comment by schottra** [comment]
@kumare3 
> Absence of this configuration removes the link from the UI?

Correct.

> not all the placeholders required right? - For example some deployments do not use project-domain as the namesapce - L5

I interpret this to mean that the url for the k8s dashboard/namespace may not include all of the fields mentioned above from the execution. If so, then yes. It can be implemented such that there is a set of values that _can_ be pulled from an execution and inserted into the format string, but that they do not all have to be used. So `https://{{cluster}}.k8s.mycompany.com` is a valid value for the URL.


That does make me wonder if there are any other values that we should consider allowing in the format string aside from the `id.project`, `id.domain` and `system_metadata.execution_cluster` fields of an `Execution`. We could potentially follow the same patterns used in filtering in Admin, where fields are fully-qualified and we will attempt to look them up on the record in question and insert them into the string.

@anandswaminathan, curious about your thoughts as well.

**Comment by anandswaminathan** [comment]
I believe `id.project, id.domain and spec.metadata.system_metadata.execution_cluster` is enough for now.

@kumare3 What is the namespace in the L5? If nothing is specified, it will just go to default. Or we can have a namespace parameter, and specify formats for namespace (but that we can do later)

**Comment by kumare3** [comment]
@anandswaminathan you should check with @migueltol22 but I think they route it to just `id.domain`

**Comment by anandswaminathan** [comment]
That makes it even better. Will work in Randy’s solution.

**Comment by kumare3** [comment]
@anandswaminathan is this done?

**Comment by anandswaminathan** [comment]
I don't believe so.

**Comment by kumare3** [comment]
Dashboard is not a requirement and this is not a desirable feature
