### ISSUE TITLE
[Feature] Group executions by owners

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#645]
**Motivation: Why do you think this is important?**
As a Flyte user it would be useful to search executions based on who launched them (amongst other useful search params).

**Goal: What should the final outcome look like, ideally?**
It should be straightforward to search for executions triggered by a user.

**Describe alternatives you've considered**
Current behavior which exposes owners in protobuf only and is retrievable for each individual execution

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [x] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [x] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Additional context**
TBD: search by labels, inputs too

**Is this a blocker for you to adopt Flyte**

**Comment by katrogan** [comment]
flyteadmin: https://github.com/lyft/flyteadmin/pull/150

**Comment by kumare3** [comment]
The flyteadmin implementation is complete, we have separate tickets for flyteconsole and flytectl. Closting this issue
