### ISSUE TITLE
[BUG] flytekit module should hide imported packages/classes

### ISSUE THREAD

**Issue by honnix** [flyteorg/flyte#652]
**Describe the bug**
Historically flytekit has been pretty good at strictly hiding imported packages/classes in the shape of `from foo import bar as _bar`. This is a very good practice to avoid users of flytekit accidentally importing undesired stuff into their code space.

In recent code changes it seems this is not the case anymore.

**Expected behavior**
Imported packages and classes are hidden from users.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
N/A

**Screenshots**
N/A

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**
N/A

**Comment by kumare3** [comment]
@honnix so the new way we are trying to do is - 
`from flytekit import x` we are trying to expose things are a module level. do you think thats ok?

**Comment by honnix** [comment]
I don't really have a strong opinion, so please feel free to close this.

**Comment by katrogan** [comment]
closing since imports are now exposed at the module level
