### ISSUE TITLE
[BUG] Fast register broken for spark

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#653]
**Describe the bug**
For spark tasks using containers with custom entrypoints (e.g. at Lyft) fast-register is broken. This is due to how fast-register sets up the task container args to feed in the execute command into fast-execute. The container image entrypoint attempts to run spark submit with pyflyte execute (which predictably fails)

**Expected behavior**
Fast-register should work for spark tasks.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
1. Fast-register a workflow with a spark task
2. Execute the fast registered workflow

**Screenshots**

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**

**Comment by katrogan** [comment]
cc @akhurana001

**Comment by kumare3** [comment]
@katrogan I think this is fixed with the new `flytekit==0.16.0b1` right?

**Comment by kumare3** [comment]
we could use the same `serialization settings` and backport it if we want it to work for v0.15.x

**Comment by katrogan** [comment]
@kumare3 let me test this to confirm before closing out

**Comment by kumare3** [comment]
@katrogan I think we can close this one out, it works with the new versions of flytekit==0.16.0b* right

**Comment by katrogan** [comment]
yes the customizable entrypoint should address this
