### ISSUE TITLE
[Feature]Generic Type should support JSON Schema association

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#654]
**Motivation: Why do you think this is important?**
Flyte supports JSON types using the Generic Struct attribute. But, it is hard to build an auto-completing UI as well as ensuring type-safety at the time of passing in parameters. Optional JSON schema offers this additional guarantee

**Goal: What should the final outcome look like, ideally?**
Users can use Launch form, that automatically completes or creates a prototype json object for them based on the json schema. For ensuring this is simple and without a lot of overhead this can be completely optional

**Describe alternatives you've considered**
None

**Flyte component**
- [x] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Is this a blocker for you to adopt Flyte**
NA

**Comment by EngHabu** [comment]
What's the end goal of this? should it be closed when we have it in the UI?

**Comment by kumare3** [comment]
@EngHabu I think the UI part should be a separate task. Let me create one
