### ISSUE TITLE
[BUG] Workflows with the last node as a branch node do not produce outputs

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#667]
**Describe the bug**
Having a workflow with a branch node as the last node does not produce outputs.

```
@workflow
def mywf(x: int) -> int:
    return conditional("test")
      .if_(x > 5)
      .then(t1())
      .else_()
      .then(t2())
```

**Expected behavior**
`mywf(x=4)` should produce a value when run remotely just like it does when running locally.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [X] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [X] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Comment by kumare3** [comment]
@EngHabu can we close this one?
