### ISSUE TITLE
[Feature] Allow executions to be filtered based on who launched them

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#671]
**Motivation: Why do you think this is important?**
Individual users iterating on workflows are mostly concerned with the executions they've most recently launched. Since we have auth and can capture who launched an execution we should expose this so users can filter by their own (or others') executions.

**Goal: What should the final outcome look like, ideally?**
It should be possible to see executions you have launched (ideally, chronologically).

**Describe alternatives you've considered**
The current method of filtering through the executions page looking for your own.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [x] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [x] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Additional context**

**Is this a blocker for you to adopt Flyte**
Please let us know if this makes it impossible to adopt Flyte

**Comment by georgesnelling** [comment]
Hey all, one of the companies I helped start before is called labkey.  they build db management tools for researchers.  Check out there sorting and filter UI for their bug tracker:    https://www.labkey.org/home/Developer/issues/issues-list.view

They've been working at it for 20 years or so, but all their data tables and views support the same feature set.  They use PostgreSQL as a backend as well.  

Notice that as you add filter and change sorting, the URL is modified with a syntax that is not dissimilar to what qraphql does, but follows URL rules.  All the code is open source:  server side is Java, client is typescript.

**Comment by georgesnelling** [comment]
Prashant and friends:  Please ignore my previous comment when looking at this issue.  I am talking about a much larger feature than simply adding a filter for this one field.

**Comment by kumare3** [comment]
One thing to note - there are 2 cases
1. When Authentication is disabled (DISABLE_AUTH) flag is set. Then, filterering by user/principal is not possible
2. When authn is enabled, this should be available in the console

**Comment by katrogan** [comment]
To clarify Ketan's comment it is actually possible to filter by user even when authentication is disabled. In this case, the user can pass a role when launching an execution that gets recorded in the filterable user field in the back-end.

To create an execution with a custom role you can use for testing this feature out, we'll use flyte-cli to get a launch plan "urn" (unique identifier) to create an execution with.


Using the go greet workflow as an example, let's walk through how to do that.

First, get existing launch plans. 

```
$ flyte-cli list-launch-plan-names -p flytetester -d development -i -h localhost:30081
    ...
    recipes.basic.lp.go_greet
    ...
```

then we need to figure out a specific version to launch the execution with.

```
$ flyte-cli list-launch-plan-names -p flytetester -d development -i -h localhost:30081 -n recipes.basic.lp.go_greet
Welcome to Flyte CLI! Version: 0.17.0b2
Launch Plan Versions Found for flytetester:development:recipes.basic.lp.go_greet

Version                                            Urn                                                                              Schedule                       Schedule State 
1ea80638e9dd2ddaef6f199fffae0b439f445e5d           lp:flytetester:development:recipes.basic.lp.go_greet:1ea80638e9dd2ddaef6f199fffae0b439f445e5d 
...
```

Now that we have an urn, let's launch that. Note that the inputs `number` and `day_of_week` are workflow execution inputs.

```
flyte-cli execute-launch-plan -p flytetester -d development -i -h localhost:30081 -u lp:flytetester:development:recipes.basic.lp.go_greet:1ea80638e9dd2ddaef6f199fffae0b439f445e5d -r dariel -- number=2 day_of_week=Weds
```

Success, now we can view the execution in the console.

You can also view the raw execution data by visiting `https://localhost:30081/api/v1/executions/flytetester/development/<execution name>`

where the execution id was what was output in the above command, e.g. `Launched execution: ex:flytetester:development:f77fc8bb1c34c45e39b3` -> has an execution name of `f77fc8bb1c34c45e39b3`

Verify that the raw execution data does indeed have your role captured. You should see something like

```
"metadata": {
  "principal": "dariel",
...
``` 

You should now be able to use https://docs.flyte.org/en/latest/dive_deep/admin_service.html#using-the-admin-service to filter executions by user "dariel"
