### ISSUE TITLE
[Feature] Keep processing the same workflow as long as there are changes

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#676]
**Motivation: Why do you think this is important?**
It can speed up progressing workflows drastically.

**Goal: What should the final outcome look like, ideally?**
Propeller's algorithm today does the following:
- Sync WFs from informer
- Iterate on WFs, traverse each and attempt to make progress
- Store 
- Wait for next sync period.

With the change, it would:
1- Sync WFs from informer
2- Iterate on WFs
3- Traverse each and attempt to make progress
4- Store 
5- If a change is detected (https://github.com/lyft/flytepropeller/blob/master/pkg/controller/handler.go#L212), go back to 3, if not, go to 6
6- Wait for next sync period.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [X] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Comment by kumare3** [comment]
This has been merged and tested at scale. WE can observe and order of magnitude performance imrpovements
