### ISSUE TITLE
[BUG] "Writing your first workflow" doc is not working

### ISSUE THREAD

**Issue by sylock** [flyteorg/flyte#677]
**Describe the bug**
When following the quickstart documentation to create the first workflow:
https://lyft.github.io/flyte/user/getting_started/create_first.html

After following the documentation, building and registering the workflow. I cannot see the workflow named  "workflows.edges.EdgeDetectorWf" from the UI. Instead I find "multi_step_linear.diabetes_xgboost.DiabetesXGBoostModelTrainer"

Here is the screenshot:
![Screenshot from 2021-01-25 18-45-10](https://user-images.githubusercontent.com/2362405/105744527-91482400-5f3d-11eb-95ef-04717f82d007.png)

**Expected behavior**
What I see from the UI is what is described in the documentation. I should find the workflow named "workflows.edges.EdgeDetectorWf"

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [X] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
1. Follow the doc https://lyft.github.io/flyte/user/getting_started/create_first.html
2. Check the UI
3. From the UI you cannot find the workflow described in the documentation

**Environment**
**Flyte component**
- [X] Sandbox (local or on one machine) with minikube
- [ ] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**
As I'm completely new to Flyte, I don't really know where to search to fix the issue.

**Comment by kumare3** [comment]
@sylock Thank you for the issue. we are going through a major Docs overhaul. Can you please refer to https://flytecookbook.readthedocs.io/en/latest/

**Comment by kumare3** [comment]
@sylock #682 is an update to the getting started, if you noticed we recently moved orgs, so a few things have been in Flux. Thank you for your patience and support.

**Comment by kumare3** [comment]
@katrogan I think you merged this, I am going to close the Issue. @sylock please try again.
