### ISSUE TITLE
[DOC] Document how to write backend plugins, the different plugin types and examples

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#681]
**Describe the bug**
Document how to develop new backend plugins, the supported plugin types, the iteration, validation and testing story. How to expose metrics and write logs. How to maintain the statemachine and best practices to avoid a corrupt or an inconsistent state.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [X] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Comment by cosmicBboy** [comment]
this issue is covered in https://github.com/flyteorg/flyte/issues/1541
