### ISSUE TITLE
[BUG] Flytecookbook for `v0.16.0b1` has bugs

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#687]
**Describe the bug**
Unable to register workflows using latest flytecookbook instructions. 

Bugs
1. make register command does not have `--insecure` option for local deployment
2. Bug in registering kfpytorch example
```bash
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Type MEMORY for [resource_type:TASK project:"flytetester" domain:"development" name:"recipes.plugins.kfpytorch.pytorch_mnist.mnist_pytorch_job" version:"1dd37fc240178837bab476d429e1ee09232a6c05" ] cannot set limit > platform limit"
```
3. Make register uses
`--kubernetes-service-account demo`
This fails at runtime with 
```bash
[1/1] currentAttempt done. Last Error: USER::pods "oze826a6ot-n0-0" is forbidden: error looking up service account flytetester-development/demo: serviceaccount "demo" not found
```
4. Then the image itself is not pushed
```bash
[1/1] currentAttempt done. Last Error: USER::containers with unready status: [wj6a59yv8j-n0-0]|Back-off pulling image "flytecookbook:1dd37fc240178837bab476d429e1ee09232a6c05"
```
5. Also Case-studies docker image is not pushed
```
  File "/root/recipes/case_studies/pima_diabetes/diabetes.py", line 10, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
```
6. Mergesort fails, because flyteadmin new version is not deployed
```
	Error 7: Code: ParameterNotBound, Node Id: fxw4uysi, Description: Parameter not bound [numbers].
	Error 8: Code: ParameterNotBound, Node Id: fxw4uysi, Description: Parameter not bound [numbers_count].
	Error 9: Code: UnreachableNodes, Node Id: start-node, Description: The Workflow contain unreachable nodes [fxw4uysi,fxk4upea,fxo4usiy].
```

**Expected behavior**
Examples should be registered in one go.

**Flyte component**
- [ ] Overall
- [x] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
Start local sandbox cluster
run make serialize and make register as follows
`OUTPUT_DATA_PREFIX=s3://my-s3-bucket/raw_data FLYTE_HOST=localhost:80 make register`

**Environment**
**Flyte component**
- [x] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**
NA

**Comment by katrogan** [comment]
@kumare3 do you mind using your blazing fast connection to push the missing images?

**Comment by kumare3** [comment]
@EngHabu can you close this once you push out your changes for flytesnacks

**Comment by kumare3** [comment]
These issues have been resolved. My tests worked
