### ISSUE TITLE
[Feature] [Plugin] Redshift

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#705]
**Motivation: Why do you think this is important?**
Redshift is a common database favored for small databases (e.g. for analytics) due to its low latency query execution.

**Goal: What should the final outcome look like, ideally?**
An easy to use FlyteKit plugin for users to write Redshift queries and a FlytePlugins backend plugin to send and monitor jobs.

[AWS Redshift Data API](https://docs.aws.amazon.com/redshift/latest/mgmt/data-api.html)
[FlytePlugins WebAPI](https://pkg.go.dev/github.com/lyft/flyteplugins@master/go/tasks/pluginmachinery/webapi)
[AWS Athena Plugin](https://github.com/flyteorg/flyteplugins/tree/master/go/tasks/plugins/webapi/athena)
[FlyteKit Hive Plugin](https://github.com/flyteorg/flytekit/blob/master/plugins/hive/flytekitplugins/hive/task.py)

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [X] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [X] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Comment by kumare3** [comment]
closing this - will be covered by agents
