### ISSUE TITLE
[Feature] [Plugins] EMR Hive/Spark

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#707]
**Motivation: Why do you think this is important?**
AWS EMR offers a Hadoop managed service to run hive and containerized spark workloads that promises scalability and less management overhead.

**Goal: What should the final outcome look like, ideally?**
[backend webAPI](https://pkg.go.dev/github.com/lyft/flyteplugins@master/go/tasks/pluginmachinery/webapi) plugins to run hive and spark workloads on AWS EMR.

Ideally these plugins should not require flytekit work and should be able to leverage existing spark/hive protos to target EMR.
[Example for AWS Athena plugin](https://github.com/flyteorg/flyteplugins/tree/master/go/tasks/plugins/webapi/athena)
[AWS EMR Spark Example](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-spark-submit-step.html)
[Current k8s-based Spark Plugin](https://github.com/flyteorg/flyteplugins/tree/master/go/tasks/plugins/k8s/spark)
[Current Hive plugin](https://github.com/flyteorg/flyteplugins/tree/master/go/tasks/plugins/hive)

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [X] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [X] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Comment by kumare3** [comment]
close, all will move to agents
