### ISSUE TITLE
[Core Feature] FlyteAdmin/Propeller should allow offloaded workflow specs

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#722]
**Motivation: Why do you think this is important?**
There are cases in which the spec increases to a very large size - workflowtemplate or tasktempaltes with queries are very large. Also having the spec in etcD does not really offer any benefit. 

**Goal: What should the final outcome look like, ideally?**
When a user executes a workflow, instead of writing the entire workflow to the CRD, we could write the spec to the Blob store and just  pass a reference. This would have following benefits
1. Extremely large workflow graphs (today Flyte supports workflow graphs in order of 5k, but this is subject to size of a task). This could increase graph to be arbitrarily large.
2. Faster sync loops with etcD. This will improve transition performance

**Describe alternatives you've considered**
Spec compression. This is very complicated and debugging will be harder.

**[Optional] Propose: Link/Inline OR Additional context**
Instead of the inline spec - we can just have a reference to the spec in blob store - https://github.com/flyteorg/flytepropeller/blob/master/pkg/apis/flyteworkflow/v1alpha1/workflow.go#L29

**Comment by hamersaw** [comment]
Completed in https://github.com/flyteorg/flyte/issues/2705
