### ISSUE TITLE
[FLYTECTL] Update references from GitHub.com/lyft/flytectl to GitHub.com/flyteorg/flytectl

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#729]
**Describe the bug**
The repo references Lyft GitHub org, not flyteorg.

**Expected behavior**
references should be from GitHub.com/flyteorg/flytectl not  GitHub.com/lyft/flytectl

**Comment by kumare3** [comment]
@brucearctor actually this has to be done for all repos. I wanted to start with flytestdlib, but I guess flytectl is great, we can always use a `replacement` to replace all dependencies e.g. `flyteorg/flytestdlib -> lyft/flytestdlib`

**Comment by brucearctor** [comment]
ya, I imagine you copied all the things over, but that wasn't 100% confirmed...  So started here with all ctl, so I don't comment about individual files in `flytectl` via PRs.  

Do you mean the other way:   lyft/flytestdlib -> (becomes) flyteorg/flytestdlib ?  easy enough to update all of these things (do you want ALL in the same PR?  Or separate things?  ex:  ALL GitHub.com/lyft/ to become GitHub.com/flyteorg (we probably can't be that global.  So github.com/lyft/{flytectl,flytestdlib,...} becomes GitHub.com/flyteorg/{flytectl,flytestdlib,...}

In that case, do you want to suggest the list of ALL the dependencies to update?  

Perhaps easy to just take everything that is in flyteorg and look for matches :-) :

flytepropeller
flytectl
flyte
flyteorg.github.io
flytesnacks
flytekit
flytestdlib
flyteplugins
flytekit-python-template
flyteadmin
flyteidl
flytetools
flyteconsole
datacatalog
boilerplate
flyteproto

**Comment by brucearctor** [comment]
And, there is also teasing apart updating the code in flytectl.  to reference itself.  But, perhaps this needs to be done in all the other repos as well for each of them.  Lots more tickets to create ;-)

**Comment by evalsocket** [comment]
@kumare3 i can help in migration for all repo

**Comment by evalsocket** [comment]
@brucearctor @kumare3  can you change the scope of issue. Let's use same issue for all repository checklist

**Comment by kumare3** [comment]
I think there is another issue for all repos

**Comment by brucearctor** [comment]
We don't have to keep this one, if there is an issue for all issues and we want to track via there.

**Comment by brucearctor** [comment]
Not seeing other issues (I might be missing keywords).  Anyways, I Figure this is as good a place to start as any.  

@evalsocket -- I'm not worried about who does which, so advise on how you want to split and/or don't let me stop you from doing whatever you're into.  It just seems best to do sooner than later, so wanted to kick it off.  ;-)
