### ISSUE TITLE
[BUG] FlyteIDL references Lyft GitHub org, not flyteorg.  

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#743]
**Describe the bug**
 FlyteIDL references Lyft GitHub org, not flyteorg.  

**Expected behavior**
Current Github org/package/modules should be defined.

**Comment by kumare3** [comment]
II actually dont think, this is a bug, but more of a clean-up tech-debt

**Comment by brucearctor** [comment]
It is definitely clean-up of tech-debt.  But, of all the categories available... seemed most fitting?  Would you categorize. it differently?  

Other choices (from the UI when entering an issue):
* Plugin Request
* Bug Report
* Docs bug/update request
* Core feature request
* Flytectl feature request
* UI Feature request

**Comment by kumare3** [comment]
@brucearctor true, I think we should create a category called tech-debt to ensure we hang onto these issue

**Comment by kumare3** [comment]
@brucearctor / @evalsocket I see you guys are working on these issues. Lets target 0.12.0 for all these changes. 0.12.0 will be end of march
