### ISSUE TITLE
[BUG] Flytestdlib references Lyft GitHub org, not flyteorg.  

### ISSUE THREAD

**Issue by brucearctor** [flyteorg/flyte#744]
**Describe the bug**
 Flytestdlib references Lyft GitHub org, not flyteorg.  

**Expected behavior**
Current Github org/package/modules should be defined.

**Comment by kumare3** [comment]
@brucearctor do you think this is complete?

**Comment by brucearctor** [comment]
I *think* sufficiently.

There is a separate question around what to do with the boilerplate/lyft repo (esp. in each location).  I haven't fully wrapped my head around approach there.

**Comment by brucearctor** [comment]
https://github.com/flyteorg/flytestdlib/pull/73 <- closed by this merge (sorry for being sloppy and not having the merge close this issue :-/
