### ISSUE TITLE
[Plugin] SQLAlchemy based plugin for querying from RDBMS

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#749]
**Why would this plugin be helpful to the Flyte community**
It is often that data resides in Relational databases and Flyte should be able to connect to SQL databases and retrieve data for processing it.

Python flytekit already has a plugin for [SQLite3](https://github.com/flyteorg/flytekit/blob/master/flytekit/extras/sqlite3/task.py#L50). This can be easily extended / replicated for SQLAlchemy supported databases like postgres, mysql, oracle, MS-sql etc. This would make it extremely easy for many users to access data into a pandas data-frame using Flyte - just by providing a query.

**Type of Plugin**
- [x] Python interface only plugin
- [ ] Web Service (e.g. AWS Sagemaker, GCP DataFlow, Qubole etc...)
- [ ] Kubernetes Operator (e.g. TfOperator, SparkOperator, FlinkK8sOperator, etc...)
- [ ] Customized Plugin using native kubernetes constructs
- [ ] Other

**Comment by fediazgon** [comment]
I think this one is fixed by https://github.com/flyteorg/flytekit/commit/d77a7739b53186d6c822dbfba29bc74dce66e8aa

**Comment by kumare3** [comment]
@fediazgon you are right - @max-hoffman

**Comment by kumare3** [comment]
I cannot assign to Max hoffman till he gets added to as a contributor. Invite is on its way.
