### ISSUE TITLE
[BUG] ERROR:root:Error creating Flyte entity because of invalid arguments.

### ISSUE THREAD

**Issue by mneilly-et** [flyteorg/flyte#755]
**Describe the bug**
I am trying to follow the getting started instructions and register the hello workflow per https://docs.flyte.org/en/latest/tutorials/run_on_flyte.html#running-your-flyte-workflows.

When running the following command:
```
FLYTE_PLATFORM_URL="http://flyte-host:30081" FLYTE_AWS_ENDPOINT=http://flyte-host:30083 FLYTE_AWS_ACCESS_KEY_ID=minio FLYTE_AWS_SECRET_ACCESS_KEY=miniostorage make fast_register FLYTE_HOST=flyte-host:30081
```

I get the following error:
> ERROR:root:Error creating Flyte entity because of invalid arguments. Create request:
> ...
> grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "failed to validate that project [flyteexamples] and domain [development] are registered, err: [entry not found]"

The full output follows:

> (venv) mneilly@MyHost$ FLYTE_PLATFORM_URL="http://flyte-host:30081" FLYTE_AWS_ENDPOINT=http://flyte-host:30083 FLYTE_AWS_ACCESS_KEY_ID=minio FLYTE_AWS_SECRET_ACCESS_KEY=miniostorage make fast_register FLYTE_HOST=flyte-host:30081
echo /home/mneilly/Projects/flyte/first_workflow/flyteexamples
/home/mneilly/Projects/flyte/first_workflow/flyteexamples
mkdir /home/mneilly/Projects/flyte/first_workflow/flyteexamples/_pb_output || true
mkdir: cannot create directory ‘/home/mneilly/Projects/flyte/first_workflow/flyteexamples/_pb_output’: File exists
rm /home/mneilly/Projects/flyte/first_workflow/flyteexamples/_pb_output/* || true
pyflyte --pkgs myapp.workflows serialize --in-container-config-path /root/flyte.config --image ghcr.io/flyteorg/flytekit-python-template:latest fast workflows -f _pb_output/
Configuration file 'flytekit.config' could not be loaded. Using values from environment.
Flyte Admin URL http://flyte-host:30081
Serializing Flyte elements with image ghcr.io/flyteorg/flytekit-python-template:latest
Writing output to _pb_output/
Writing compressed archive to _pb_output/fast1a21a17dfbe333303cd4e67ede26864b.tar.gz
2021-02-21 12:43:47,082-flytekit-DEBUG$ Task returns unnamed native tuple <class 'str'>
2021-02-21 12:43:47,082-flytekit-DEBUG$ Task returns unnamed native tuple <class 'str'>
Found 2 tasks/workflows
  Writing type: TASK, myapp.workflows.example.greet to
    0_myapp.workflows.example.greet_1.pb
  Writing type: WORKFLOW, myapp.workflows.example.hello_world to
    1_myapp.workflows.example.hello_world_2.pb
WARNING:root:Using deprecated `role` from config. Please update your config to use `assumable_iam_role` instead
  Writing type: LAUNCH_PLAN, myapp.workflows.example.hello_world to
    2_myapp.workflows.example.hello_world_3.pb
Successfully serialized 3 flyte objects
flyte-cli fast-register-files -h flyte-host:30081 -i -p flyteexamples -d development \
        --additional-distribution-dir s3://my-s3-bucket/flyte-fast-distributions _pb_output/*
Config file not found at default location, relying on environment variables instead.
                        To setup your config file run 'flyte-cli setup-config'
Welcome to Flyte CLI! Version: 0.16.0b13
Parsing files...
  _pb_output/0_myapp.workflows.example.greet_1.pb
  _pb_output/1_myapp.workflows.example.hello_world_2.pb
  _pb_output/2_myapp.workflows.example.hello_world_3.pb
Uploaded compressed code archive _pb_output/fast1a21a17dfbe333303cd4e67ede26864b.tar.gz to s3://my-s3-bucket/flyte-fast-distributions/fast1a21a17dfbe333303cd4e67ede26864b.tar.gz
ERROR:root:Error creating Flyte entity because of invalid arguments. Create request:
ERROR:root:{
  "id": {
    "resourceType": "TASK",
    "project": "flyteexamples",
    "domain": "development",
    "name": "myapp.workflows.example.greet",
    "version": "fast1a21a17dfbe333303cd4e67ede26864b"
  },
  "spec": {
    "template": {
      "id": {
        "resourceType": "TASK",
        "project": "flyteexamples",
        "domain": "development",
        "name": "myapp.workflows.example.greet",
        "version": "fast1a21a17dfbe333303cd4e67ede26864b"
      },
      "type": "python-task",
      "metadata": {
        "runtime": {
          "type": "FLYTE_SDK",
          "version": "0.16.0",
          "flavor": "python"
        },
        "retries": {},
        "interruptible": false
      },
      "interface": {
        "inputs": {
          "variables": {
            "name": {
              "type": {
                "simple": "STRING"
              },
              "description": "name"
            }
          }
        },
        "outputs": {
          "variables": {
            "o0": {
              "type": {
                "simple": "STRING"
              },
              "description": "o0"
            }
          }
        }
      },
      "container": {
        "image": "ghcr.io/flyteorg/flytekit-python-template:latest",
        "args": [
          "pyflyte-fast-execute",
          "--additional-distribution",
          "s3://my-s3-bucket/flyte-fast-distributions/fast1a21a17dfbe333303cd4e67ede26864b.tar.gz",
          "--dest-dir",
          ".",
          "--",
          "pyflyte-execute",
          "--task-module",
          "myapp.workflows.example",
          "--task-name",
          "greet",
          "--inputs",
          "{{.input}}",
          "--output-prefix",
          "{{.outputPrefix}}",
          "--raw-output-data-prefix",
          "{{.rawOutputDataPrefix}}"
        ],
        "resources": {},
        "env": [
          {
            "key": "FLYTE_INTERNAL_CONFIGURATION_PATH",
            "value": "/root/flyte.config"
          },
          {
            "key": "FLYTE_INTERNAL_IMAGE",
            "value": "ghcr.io/flyteorg/flytekit-python-template:latest"
          }
        ]
      }
    }
  }
}
Traceback (most recent call last):
  File "/home/mneilly/Projects/flyte/first_workflow/venv/bin/flyte-cli", line 8, in <module>
    sys.exit(_flyte_cli())
  File "/home/mneilly/Projects/flyte/first_workflow/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/mneilly/Projects/flyte/first_workflow/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/mneilly/Projects/flyte/first_workflow/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mneilly/Projects/flyte/first_workflow/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mneilly/Projects/flyte/first_workflow/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/mneilly/Projects/flyte/first_workflow/venv/lib/python3.7/site-packages/flytekit/clis/flyte_cli/main.py", line 1875, in fast_register_files
    _extract_and_register(host, insecure, project, domain, version, pb_files, patches)
  File "/home/mneilly/Projects/flyte/first_workflow/venv/lib/python3.7/site-packages/flytekit/clis/flyte_cli/main.py", line 1698, in _extract_and_register
    client.raw.create_task(_task_pb2.TaskCreateRequest(id=id, spec=flyte_entity))
  File "/home/mneilly/Projects/flyte/first_workflow/venv/lib/python3.7/site-packages/flytekit/clients/raw.py", line 83, in handler
    return fn(*args, **kwargs)
  File "/home/mneilly/Projects/flyte/first_workflow/venv/lib/python3.7/site-packages/flytekit/clients/raw.py", line 122, in handler
    raise e
  File "/home/mneilly/Projects/flyte/first_workflow/venv/lib/python3.7/site-packages/flytekit/clients/raw.py", line 115, in handler
    fn(self, create_request)
  File "/home/mneilly/Projects/flyte/first_workflow/venv/lib/python3.7/site-packages/flytekit/clients/raw.py", line 200, in create_task
    return self._stub.CreateTask(task_create_request, metadata=self._metadata)
  File "/home/mneilly/Projects/flyte/first_workflow/venv/lib/python3.7/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/mneilly/Projects/flyte/first_workflow/venv/lib/python3.7/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "failed to validate that project [flyteexamples] and domain [development] are registered, err: [entry not found]"
        debug_error_string = "{"created":"@1613936638.604141164","description":"Error received from peer ipv4:10.10.1.74:30081","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"failed to validate that project [flyteexamples] and domain [development] are registered, err: [entry not found]","grpc_status":3}"
make: *** [Makefile:62: fast_register] Error 1
(venv) mneilly@MyHost$

**Expected behavior**
No errors...

**Additional context**
***To Reproduce***
1. pip install flytekit==0.16.0b6 (tried both 0.16.0b6 and 0.16.0b13)
2. git clone git@github.com:flyteorg/flytekit-python-template.git flyteexamples
3. cd flyteexamples
4. rm -rf .git
5. git init
6. FLYTE_PLATFORM_URL="http://flyte-host:30081" FLYTE_AWS_ENDPOINT=http://flyte-host:30083 FLYTE_AWS_ACCESS_KEY_ID=minio FLYTE_AWS_SECRET_ACCESS_KEY=miniostorage make fast_register FLYTE_HOST=flyte-host:3008

**Comment by kumare3** [comment]
@mneilly-et, is it possible to paste a screenshot of the `first` UI page in `flyteconsole`. So the reason is the project `flyteexamples` is not present in your `flyte deployment`. This seems to be a bug in the getting started as the `default project of flyteexamples for removed in a recent check-in`. Extremely sorry about that. It is simple to create a new project. In your virtual enviornment just type the following command

```bash
cd /home/mneilly/Projects/flyte/first_workflow/flyteexamples
flyte-cli -h localhost:30081 -i register-project -p flyteexamples -n "Flyte Examples project" -d "Getting started with flyte examples project"
```

**Comment by kumare3** [comment]
@mneilly-et - I have a PR to fix this issue - https://github.com/flyteorg/flyte/pull/756

**Comment by kumare3** [comment]
Just waiting on tests passing and then will be merging it. this would mean, you can just re-run the entire - getting started again and it should work!. Also please feel free to ping me on Slack - @ketan - Thank you for reporting the bug!

**Comment by kumare3** [comment]
@mneilly-et thank you again, I have merged the PR, you can tear down the example and retry. This would work now. Please feel free to open a bug again

**Comment by mneilly-et** [comment]
Thanks @kumare3, that did the trick.

**Comment by kumare3** [comment]
> Thanks @kumare3, that did the trick.

Thank you the response @mneilly-et !
