### ISSUE TITLE
[TechDebt] Remove files literals.go from flytepropeller and flyteplugins

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#757]
Following files 
https://github.com/flyteorg/flyteplugins/blob/master/go/tasks/pluginmachinery/utils/literals.go
https://github.com/flyteorg/flytepropeller/blob/master/pkg/utils/literals.go
have functionality that is already available in 
https://github.com/flyteorg/flyteidl/blob/master/clients/go/coreutils/literals.go
Or any additional functionality that exists is getting moved in the following PR 
https://github.com/flyteorg/flyteidl/pull/101

This issue should cover removing these overriden files in flyteplgins and flytepropeller along with changing the references in there corresponding repos.

**Comment by kumare3** [comment]
@pmahindrakar-oss can you handle this one now, i think its been a while

**Comment by pmahindrakar-oss** [comment]
@kumare3 please provide commit access to flyteplugins and flytepropeller.
