### ISSUE TITLE
[Feature] Enable pyflyte-execute can run with local files

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#762]
Currently the typical command that a container runs with looks something like this.

```
pyflyte-execute --task-module app.workflows.work --task-name task_function_name --inputs s3://flyteorg/metadata/propeller/production/flyteexamples-development-ff1641613c2674cee9d5/task_function_name/data/inputs.pb --output-prefix s3://flyteorg/metadata/propeller/production/flyteexamples-development-ff1641613c2674cee9d5/task_function_name/data/0 --raw-output-data-prefix s3://flyteorg/offloaded-data/
```

This is the typical output of a task serialization/registration process, and can be seen in the Task JSON tab in the Flyte console UI as well.

For debugging, often the user (or contributor) has access to the container itself and sometimes it's helpful to be able to run the full command.  However, usually even though the user has the container, the user does not have permissions to s3 from within the container - but can download those files locally using some other authenticated process.

In these cases, it's nice to be able to run.

```
pyflyte-execute --task-module app.workflows.work --task-name task_function_name --inputs /my/local/inputs.pb --output-prefix /my/local/outputs/ --raw-output-data-prefix /my/local/data
```

The existing `DataProxy` classes already handles talking to the various file backends, but this detection needs to be hooked up to the pyflyte-execute click commands.

**Comment by kumare3** [comment]
cc @wild-endeavor I think my changed to data persistence layer should handle some of this.

**Comment by wild-endeavor** [comment]
this probably works at this point... closing, can open again in the future if necessary.
