### ISSUE TITLE
[BUG] flytesnacks: Unable to find image 'flytecookbook:core-' locally                                             

### ISSUE THREAD

**Issue by mneilly-et** [flyteorg/flyte#766]
**Describe the bug**
Following the tutorial at https://flytecookbook.readthedocs.io/en/latest/tutorial.html and running "make fast_register" in step 6 results in the following error:

> $ make fast_register                                                                                                                              
Fast registering example workflows in cookbook/core                                                                                                                        
docker exec -it -e MAKEFLAGS -e REGISTRY= -e DOCKER_BUILDKIT=1 -e VERSION= -w /usr/src flyte-sandbox make -C cookbook/core fast_register                                   
Tagged Image:                                                                                                                                                              
flytecookbook:core-                                                                                                                                                        
/usr/src/cookbook/core                                                               
Unable to find image 'flytecookbook:core-' locally                                                                                                                         
docker: Error response from daemon: pull access denied for flytecookbook, repository does not exist or may require 'docker login': denied: requested access to the resource
 is denied.                                                                                                                                                                
See 'docker run --help'.                                                                                                                                                   
make: *** [../common/Makefile:135: fast_register] Error 125                                                                                                                
make: *** [Makefile:116: fast_register] Error 2              

**Expected behavior**
A successfully registered workflow.

**[Optional] Additional context**
***To Reproduce***
Steps 1 to 6 per https://flytecookbook.readthedocs.io/en/latest/tutorial.html

It looks like the Makefile is passing empty env vars to docker exec as:
`docker exec -it -e MAKEFLAGS -e REGISTRY= -e DOCKER_BUILDKIT=1 -e VERSION= -w /usr/src flyte-sandbox make -C cookbook/core fast_register`

and the following allowed the process to complete:

```
$ git diff master -- Makefile
diff --git a/Makefile b/Makefile
index 8d967d1..dbe0465 100644
--- a/Makefile
+++ b/Makefile
@@ -26,7 +26,7 @@ echo "$(shell tput bold)$(shell tput setaf 2)$(1)$(shell tput sgr0)"
 endef
 
 define ERROR
-echo >&2 "$(shell tput bold)$(shell tput setaf 1)$(1)! Please 'make teardown' and 'make start' again to retry.$(shell tput sgr0)"; exit 1
+{ echo >&2 "$(shell tput bold)$(shell tput setaf 1)$(1)! Please 'make teardown' and 'make start' again to retry.$(shell tput sgr0)"; exit 1; }
 endef
 
 define RUN_IN_SANDBOX
@@ -105,4 +105,4 @@ register: _requires-sandbox-up  ## Register Flyte cookbook workflows
 .PHONY: fast_register
 fast_register: _requires-sandbox-up  ## Fast register Flyte cookbook workflows
        $(call LOG,Fast registering example workflows in cookbook/$(EXAMPLES_MODULE))
-       $(call RUN_IN_SANDBOX,make -C cookbook/$(EXAMPLES_MODULE) fast_register)
+       $(call RUN_IN_SANDBOX,bash -c "REGISTRY=ghcr.io/flyteorg VERSION=latest make -C cookbook/$(EXAMPLES_MODULE) fast_register")
```

The failing master is:
```
$ git rev-parse HEAD
1364536c87e04fa65bba0be3076d9d9f7e1fec5c
```

**Comment by kumare3** [comment]
@mneilly-et again thank you, you are beating us. We are constantly revving this and you are far ahead :). Appreciate it. We should have a fix soon. cc @jeevb

**Comment by jeevb** [comment]
Fixed with https://github.com/flyteorg/flytesnacks/pull/122. The issue was that we were passing empty environment variables into the container, as opposed to passing them on only if they exist.
