### ISSUE TITLE
[Docs] Minor typo/spelling on Task Cache flytesnacks page

### ISSUE THREAD

**Issue by mneilly-et** [flyteorg/flyte#769]
**Describe the documentation update**

For the page at https://flytecookbook.readthedocs.io/en/latest/auto_core_basic/task_cache.html in the following paragraph:

> In the above example, calling square(n=2) twice (even if it’s across different executions or different workflows), will only actually execution the multiplication operation once. The second time the output will be made available immediately.

"execution" should be "execute"

**Comment by kumare3** [comment]
PR https://github.com/flyteorg/flytesnacks/pull/121
