### ISSUE TITLE
[Docs]Improving getting started to add example of how Flyte can be used for ML/DL frameworks

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#774]
by Community member @samhita-alla copied from issue #752 

- https://docs.flyte.org/projects/cookbook/en/latest/auto_core_remote_flyte/index.html - Accompanying every step, it'd be useful if we explain the reason behind doing so. For example, in the first step, there's building Dockerfile. Here, if we tell the user about how that has to be done, it'd be great. (We might need to at least point to an example Dockerfile that has already been built for the same purpose).
- The lesser the commands that the user has to run, the more user-friendly the tool/application would be. In the link - https://docs.flyte.org/projects/cookbook/en/latest/auto_core_remote_flyte/index.html, if there's a possibility to reduce the load of commands that the user has to run to leverage the Flyte backend, it'd be great.
- https://docs.flyte.org/projects/cookbook/en/latest/core.html - This link can be included while explaining about how Flyte works. It needn't be there in the cookbook while explaining the examples employing Flyte.
- https://docs.flyte.org/projects/cookbook/en/latest/auto_core_basic/index.html - Rather than including task and workflow in the basic examples section, we can move it on to the top level where we talk about Flyte. Flyte in general has tasks and workflows. So it's better if we introduce these terms in the introductory part itself.
- https://docs.flyte.org/projects/cookbook/en/latest/auto_core_basic/hello_world.html#sphx-glr-auto-core-basic-hello-world-py - This is a duplicate of the first 'Hello World' example. 
- https://docs.flyte.org/projects/cookbook/en/latest/core.html - We can depict more examples explaining how datatype conversions happen for the ones not mentioned in the table. Say, we can pick official examples from TensorFlow and PyTorch to explain how Flyte embeds with the usual DL frameworks. Also for instance, how will we pass Numpy arrays from one task to the other? -  as this isn't a datatype for which the automatic conversion happens. It could be just utilizing the ones already mentioned, but the user might not be knowing about it. In general, it'd be better if we show examples that do not employ many direct data type conversions (from Python to Flyte) as such.

**Comment by EngHabu** [comment]
@samhita-alla will you be able to take care of this in 0.16.0 (i.e. July)?

**Comment by samhita-alla** [comment]
We can close this. It was a long time ago!
