### ISSUE TITLE
[BUG]  flytekit.current_context().working_directory on windows returns an unusable path

### ISSUE THREAD

**Issue by josephwinston** [flyteorg/flyte#782]
**Describe the bug**
Call `flytekit.current_context().working_directory` and it returns '/tmp/flyte\\user_space'

**Expected behavior**
On Windows, use the environment variable `TMP` or  `TEMP` to form the base of the scratch directory

1. Invoke `flytekit.current_context().working_directory`

**Comment by kumare3** [comment]
@josephwinston are you using flytekit on windows, thank you for the bug, we will address this in the next release

**Comment by josephwinston** [comment]
It sounds like there is work to be done on windows.  That’s fine.  I just need to document it.

**Comment by kumare3** [comment]
Ya to be honest - none of us even have a windows machine to test, so bugs are welcome

**Comment by josephwinston** [comment]
I have developers that use windows.  I’ll see what bugs I can find since things almost work.

**Comment by EngHabu** [comment]
Hi @josephwinston, it seems like it might be a while before we can dedicate resources for making Windows support first class... as you saw we have been coding to be cloud and OS agnostic but some bugs will slip here and there... is this something you can help us fix as you find?

**Comment by EngHabu** [comment]
@cosmicBboy mind taking a look to see if it's a quick fix?
