### ISSUE TITLE
[Docs] Flytecookbook multi-image docs update and example to show where it can be used

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#788]
**Describe the documentation update**
Currently we have docs for Multi-Image support [here](https://docs.flyte.org/projects/cookbook/en/latest/auto_core_intermediate/multi_images.html?highlight=container_image#working-with-multiple-container-images-in-the-same-workflow). However, it does not show how to use `{{.image.<name>}}` as an example. It also does not carry a good real world example showing the usefulness of multiple-images

**Comment by cosmicBboy** [comment]
This issue was created with the old docs structure, it's redundant with this issue https://github.com/flyteorg/flyte/issues/1797

closing this one
