### ISSUE TITLE
[Core Feature] Flyte Security Context

### ISSUE THREAD

**Issue by EngHabu** [flyteorg/flyte#800]
**Motivation: Why do you think this is important?**
Flyte launches many entities through different execution engines, defining what identity each one should impersonate when executing has been one of the confusing aspects of using Flyte. Let's step back, define what the right model is based on what we know today and make sure it works across the stack.

**Goal: What should the final outcome look like, ideally?**

1. Works with Tasks that run on pods, remote containers (e.g. AWS Batch) where you have user's custom code that runs and need an identity to communicate with other resources as well as metadata tasks (e.g. SQL Queries, WebAPI calls... etc.) where the execution of user's code is more controlled.
2. Defaults can be set at Task level but should be overridable at LaunchPlan and Execution levels
3. Support passing secrets, IAM and k8s service accounts.

**Comment by kumare3** [comment]
This is merged and will be available in the next platform release (it is available in the nightly build) - Example: https://github.com/flyteorg/flytesnacks/blob/master/cookbook/core/intermediate/use_secrets.py
