### ISSUE TITLE
[BUG] Flytekit model file organization improvement

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#803]
**Describe the bug**
This is not really a bug, but is a minor annoyance that's probably worth correcting.

Please first read through this quick blurb describing what model files are - https://docs.flyte.org/projects/flytekit/en/latest/design/models.html

The model files in flytekit are working fine, but over time, they've somehow fallen out of sync with the [Flyte IDL](https://github.com/flyteorg/flyteidl/tree/master/protos/flyteidl) structure.

For example there's a duplicate `CompiledTask` object [here](https://github.com/flyteorg/flytekit/blob/master/flytekit/models/core/compiler.py#L124) and some [admin objects](https://github.com/flyteorg/flytekit/blob/master/flytekit/models/task.py#L420) aren't in the `admin/` folder.

**Expected behavior**
Clean up the structure to align with Flyte IDL.  I don't think there should be any circular import issues in the correct structure.

**Comment by kumare3** [comment]
cc @wild-endeavor / @pingsutw can you guys help @aeioulisa?
