### ISSUE TITLE
[Docs] [Bug] Task Cache documentation is breaking

### ISSUE THREAD

**Issue by coder46** [flyteorg/flyte#805]
The hyperlink to describe details on how the caching signature is created is broken. It redirects to this page which doesn't exist https://docs.flyte.org/en/stable/user/features/task_cache.html#features-task-cache

**Comment by kumare3** [comment]
cc @EngHabu can you please update the docs?

**Comment by kumare3** [comment]
@SandraGH5 this might be a simple fix

**Comment by SandraGH5** [comment]
@cosmicBboy Any ideas?

**Comment by SandraGH5** [comment]
Please see https://github.com/flyteorg/flytesnacks/pull/161
