### ISSUE TITLE
[Docs]Documentation for various plugins and how to use/configure them

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#820]
**Describe the documentation update**
Flyte has a lot of built-in plugins and for new users, there should be a clear documentation of how to enable these plugins and use them. Much like K8s/spark example.

K8s Plugins 

- [x] #1785
- [x] Kubeflow MPI (https://github.com/flyteorg/flyte/pull/1397)
- [x] kubeflow pytorch Operator (https://github.com/flyteorg/flyte/pull/1719)
- [x] Spark Operator (https://github.com/flyteorg/flyte/pull/1764)
- [ ] #1769
- [x] #1770
- [ ] container (Optional)

Web API

- [x] #1773
- [x] #1771
- [x] #1772

Hive
- [ ] #1774

Presto
- [ ] #1775

**Comment by kumare3** [comment]
Note: @kumare3 to break this into smaller issues and hand it out to an oss developer

**Comment by evalsocket** [comment]
Example PR for docs https://github.com/flyteorg/flyte/pull/1397

**Comment by r-sreesaran** [comment]
I can work on this issue.

**Comment by samhita-alla** [comment]
@kumare3 Can a first-time contributor work on this? If so, do we need to draw up a shortlist?

**Comment by kumare3** [comment]
@samhita-alla maybe, @evalsocket has created an example, we can make each of them a separate issue. This will need digging into the code

**Comment by EngHabu** [comment]
Sagemaker docs are tracked [here](https://github.com/flyteorg/flyte/issues/1769).
Since Hive and Presto require writing new clients, I don't think we need to/can document them right now.
