### ISSUE TITLE
[Housekeeping] Moving idl for datacatalog to flyteidl

### ISSUE THREAD

**Issue by tnsetting** [flyteorg/flyte#827]
**Describe the Issue**
Currently the proto/idl for datacatalog lives in this repo but it makes more sense to move to the flyteidl repo since all flyte idls are defined there. 

**What if we do not do this?**
It will be a bit confusing that datacatalog has it own idl in the repo. Also flyte propeller have dependency with datacatalog which can be removed.

***Related component***
Either Specific / all

**Comment by kumare3** [comment]
@tnsetting can you also update flytepropeller (remove the dependency on datacatalog) and just use the flyteidl proto def?
