### ISSUE TITLE
[BUG] Custom_info for task plugins shouldn't be overwritten

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#832]
**Describe the bug**
The task execution [custom](https://github.com/flyteorg/flyteplugins/blob/1f0adb319e87b7f339a7a4d74d0736f2243e3c37/go/tasks/pluginmachinery/core/phase.go#L74) can be overridden in successive event updates.

**Expected behavior**
The custom should at the very least not be overridden and successfully merged for subsequent event updates.

**[Optional] Additional context**
***To Reproduce***
1. 
2. 

***Screenshots***

**Comment by katrogan** [comment]
cc/fyi @regadas @kumare3 @kanterov

**Comment by kanterov** [comment]
Does it happen for logs as well?

**Comment by katrogan** [comment]
@kanterov no these should be merged more intelligently, currently: https://github.com/flyteorg/flyteadmin/blob/c80c8d8fd97f607da83db3ebb84cf0aec3b1f191/pkg/repositories/transformers/task_execution.go#L133
