### ISSUE TITLE
[Docs]Flesh out complete documentation on how to extend Flytekit

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#834]
**Describe the documentation update**
Flytekit can be extended in multiple ways
 - Type Extensions as somewhat explained [here](https://docs.flyte.org/en/latest/plugins/extend/intro.html#case-1-i-want-to-use-my-special-types-e-g-my-own-dataframe-format)
 - SDK side task extensions, as somewhat explained [here](https://flytecookbook.readthedocs.io/en/latest/auto_core_advanced/custom_task_plugin.html#advanced-custom-task-plugin)

Ideally [this](https://docs.flyte.org/en/latest/plugins/extend/flytekit_python.html) section should provide the user all the tools and links needed to extend flytekit for their needs.

An important note that should be emphasized is When to extend only flytekit - as documented [here](https://docs.flyte.org/en/latest/plugins/extend/intro.html). There is actually a flowchart that explains when to extend flytekit.

A good example of writing a flytekit only plugin can be documented [for SQLite3 plugin](https://docs.flyte.org/en/latest/plugins/sqlite3.html), which is a core plugin [code here](https://github.com/flyteorg/flytekit/blob/master/flytekit/extras/sqlite3/task.py#L50)

An example usage for this task is available [here](https://github.com/flyteorg/flytekit/blob/master/tests/flytekit/unit/extras/sqlite3/test_task.py#L39-L54)

**Comment by smariotti** [comment]
I'll be happy to have a look at this!

**Comment by cosmicBboy** [comment]
we haven't specifically accounted for this issue yet in the [docs revamp RFC](https://docs.google.com/document/d/1Yp5cYujKT6UMv17Y6r1djMchaMZWAlPNUTZnbw1sZvc/edit#), however it should be fairly straightforward to map it into the *Extending Flyte* section in the [detailed hierarchy](https://docs.google.com/document/d/1Yp5cYujKT6UMv17Y6r1djMchaMZWAlPNUTZnbw1sZvc/edit#heading=h.5om32za6qk0g)

This issue should ideally happen after docs have been re-structured by @samhita-alla

**Comment by cosmicBboy** [comment]
Closing this as it's redundant with https://github.com/flyteorg/flyte/issues/1541.

[This section](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/extend_flyte/index.html) in flytesnacks is the entrypoint for user guides relating to extending flyte.
