### ISSUE TITLE
[Housekeeping] Update flyteidl version in all flyte component after flyteidl release

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#868]
**Describe the Issue**
Every time we merge a change in flyteidl, we need to go update flyte propeller, flyte admin, flyte console, flyte kit with the latest version so they can get the new messages/fields in protos... maybe another github workflow that lives in flyteIdl that can open PRs against all other Repos when a release is created in flyteidl? we can generalize the model to all other repos too... like merging a change in flyteplugins should trigger a flytepropeller update.. etc.... but flyteidl is more important and more scoped

**What if we do not do this?**
Short description of potential consequences

***Related component***

- [ ] [flyteidl](https://github.com/flyteorg/flyteidl/pull/132)
- [x] [flytepropeller](https://github.com/flyteorg/flytepropeller/pull/247)
- [x] [flyteadmin ](https://github.com/flyteorg/flyteadmin/pull/170)
- [x] [flyteconsole](https://github.com/flyteorg/flyteconsole/pull/153)
- [x] [flyteplugins](https://github.com/flyteorg/flyteplugins/pull/169)
- [x] [datacatalog](https://github.com/flyteorg/datacatalog/pull/37)
- [ ] flytekit

**Comment by EngHabu** [comment]
Done, thank you @evalsocket !
