### ISSUE TITLE
[BUG] Explore using connection pooling for flyteadmin db

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#881]
**Describe the bug**
Network usage is high, could be ameliorated by imposing a limit on db connection pooling

**Expected behavior**

**[Optional] Additional context**
***To Reproduce***
1. 
2. 

***Screenshots***

**Comment by evalsocket** [comment]
@katrogan Are we need anything else apart from these config
```
// Set the maximum lifetime of a connection to 1 hour. Setting it to 0
// means that there is no maximum lifetime and the connection is reused
// forever (which is the default behavior).
db.SetConnMaxLifetime(time.Hour)

// Set the number of open connections (in-use + idle) to a maximum total of 3.
db.SetMaxOpenConns(3)

db.SetMaxIdleConns(25)
```

**Comment by katrogan** [comment]
this looks good!

**Comment by evalsocket** [comment]
closing it because of duplicate https://github.com/flyteorg/flyte/issues/1956
