### ISSUE TITLE
[Flytectl Feature] Add config managment like kubectl

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#895]
**Describe the feature/command for flytectl**
Currently, we need to pass config file in each command and it only works for managing a single cluster.  Idea is to create config management like kubectl.  

**Provide a possible output or ux example**

1. If config flag is not passed then use env variable to detect flytectl config (`FLYTE_CONFIG`) if not then try `~/.flyte/config`

```bash
# Generate default config at ~/.flyte/config
# --output flag for defining path
# --url flag for defining flyte cluster URL 
flytectl config init  
```

**Comment by EngHabu** [comment]
This would be amazing!

CC @pmahindrakar-oss

**Comment by pmahindrakar-oss** [comment]
Yeah we have this in our list  from the comparison study too https://github.com/flyteorg/flyte/issues/1124

**Comment by pmahindrakar-oss** [comment]
This is now available .
```
Usage:
  flytectl config init [flags]

Aliases:
  init, 

Flags:
  -h, --help          help for init
      --host string   Endpoint of flyte admin
      --insecure      Enable insecure mode (default true)
      --storage       Enable storage provider config


```
Closing this issue. @evalsocket we will need to fix the docs here https://docs.flyte.org/projects/flytectl/en/stable/gen/flytectl_config_init.html

They mention 
```
bin/flytectl configuration config --host=flyte.myexample.com
```
instead of 

```
bin/flytectl config init --host=flyte.myexample.com
```
