### ISSUE TITLE
[Housekeeping] Explore using gorm validations in flyteadmin

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#896]
**Describe the Issue**
Explore https://github.com/qor/validations and see if it's a viable option for replacing some hand-crafted model validation in flyteadmin.

**What if we do not do this?**
Potentially messier code

***Related component***
Flyteadmin > repositories

**Comment by evalsocket** [comment]
Related #336

**Comment by evalsocket** [comment]
@katrogan we can close this issue.  we can continue our discussion on issue #336
