### ISSUE TITLE
[Flytectl Feature] Add --dry-run to register-files 

### ISSUE THREAD

**Issue by filippobrizzi** [flyteorg/flyte#901]
**Describe the feature/command for flytectl**
Adding `--dry-run` flag to `flyte-cli register-files`. 
A dry run option would allow to validate the workflows and test them before the actual registration.

**Comment by kumare3** [comment]
@filippobrizzi that does make sense. I think it should be a trivial add. Would you be open to contributing?

**Comment by kumare3** [comment]
I think we should add the same to flytectl - which we are trying to make the default CLI (please give it a try) https://flytectl.readthedocs.io/en/latest/

**Comment by kumare3** [comment]
cc @pmahindrakar-oss

**Comment by filippobrizzi** [comment]
Hi @kumare3, I'll be happy to contribute, however, I am totally new to Flyte implementation so it may take a bit for me to be able to come with the implementation.

**Comment by kumare3** [comment]
> Hi @kumare3, I'll be happy to contribute, however, I am totally new to Flyte implementation so it may take a bit for me to be able to come with the implementation.

No worries just let us know how we can help you
