### ISSUE TITLE
[Docs] (Minor) Broken Workflows Link

### ISSUE THREAD

**Issue by j-houston** [flyteorg/flyte#906]
In the [Write a Sample Workflow](https://docs.flyte.org/projects/cookbook/en/latest/auto_core_basic/basic_workflow.html#write-a-simple-workflow)  section there's a link to a Lyft discussion on workflows that is broken. The existing link is:

https://lyft.github.io/flyte/user/concepts/workflows_nodes.html#workflows

I was able to find an old version of what the link would be here:

https://docs.flyte.org/en/v0.1.0/user/concepts/workflows_nodes.html

I brand-new to learning about Flyte, so if I can find where the docs are hosted I'll gladly push the PR fix myself. Just a bug here to record it and remind me :)

**Comment by kumare3** [comment]
Thank you @j-houston, docs are
Built using Sphinx and hosted on the Flyte repo. https://docs.flyte.org/en/latest/community/docs.html

Flyte/rsts is the folder for all the docs

**Comment by SandraGH5** [comment]
Thank you @j-houston for spotting this.
The link has been updated.
