### ISSUE TITLE
[BUG] "View Input and Output" UI doesn't correctly show parameters

### ISSUE THREAD

**Issue by PhoenixLiAtLyft** [flyteorg/flyte#909]
**Describe the bug**
Hi Team, we noticed that sometimes if you open "View Inputs & Outputs" UI, it doesn't show the same parameters exactly as your input. For example, in my attached screenshot, we accidentally added an extra space before "turn_features". But in the "View Inputs & Outputs" UI there is no extra space. We only found it when we opened "Relaunch" UI.
Can you fix it? I believe it will help all flyte users to debug if they accidentally added a space in their input.

**Expected behavior**
The "View Inputs & Outputs" UI should also show the extra space

**[Optional] Additional context**
***To Reproduce***
1. Choose any workflow. Give an extra space in one of the input and launch it
2. Open "View Inputs & Outputs" and you won't see the extra space

***Screenshots***
<img width="767" alt="Screen Shot 2021-04-13 at 10 25 30 AM" src="https://user-images.githubusercontent.com/59625933/114594867-9cf4de00-9c42-11eb-91b3-2cb9135c8b9a.png">
<img width="566" alt="Screen Shot 2021-04-13 at 10 27 27 AM" src="https://user-images.githubusercontent.com/59625933/114595101-dd545c00-9c42-11eb-98d5-205ecf9ec419.png">

**Comment by kumare3** [comment]
@jsonporter in your copious free time

**Comment by jsonporter** [comment]
Hey @PhoenixLiAtLyft - thinking through this bug, I think the right move would be to stop this at the source and add validation on the input to ensure no leading/trailing whitespace.  Does that sound good to you?
