### ISSUE TITLE
[flytekit] Non-primitive defaults to workflows

### ISSUE THREAD

**Issue by wild-endeavor** [flyteorg/flyte#910]
Currently you can specify defaults to a workflow like so
```
@workflow
def wf(a: int = 3):
   ...
```

The `3` here will get picked up as the default value in any launch plan that gets created from this workflow (unless overridden at launch plan creation time).

This also works today:
```
@workflow
def wf(a: List[int] = [1, 2, 3]):
   ...
```

However, this is not Pythonic and may lead to errors.  Specifically, this is actually an [anti-pattern](https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html).

The correct way to handle complex default values in Python is to make the default `None` and then check for that in the code, and then setting the input to the default in code.  This isn't really doable in flytekit today (or possibly ever).  Also, flytekit today doesn't handle `None` values and there is no such thing as an `Optional` type in Flyte IDL (yet, union types may be supported in the future).

This issue also affects maps, and all other mutable custom objects (protos or dataclass types).

## First Need To Test
We should add some tests to flytekit first to see how big of a problem this is, and actual user-code-pattern that breaks.  This should help refine the scope of this ticket, and should help inform a solution.

### Leave it as is
While it is an anti-pattern, it is concise and keeps the default-specification pattern consistent between primitives and more complex types.  We can try to leave it as is, but add code to deep copy the values before passing them on.  A deep copy already happens with lists and dicts and such because when a workflow is run locally, it already gets converted into Flyte Literals before tasks get a chance to mess with them.

### Add options to the workflow decorator
We can specify things in the workflow decorator
```
@workflow(a=[1,2,3])
def wf(a: Optional[List[int]] = None):
    ...
```
We'll still need to do a deep copy, because we're still only given one copy of the literal.  The type engine will have to understand that we're not really trying to specify an Optional type, and launch plans will pick up the default value when created.

### Require frozen things
There's a frozen list (though no frozen dict) that we can maybe force people to use when declaring defaults.  This adds complexity in the type engine however.

**Comment by kumare3** [comment]
@wild-endeavor how about
```python
@workflow(parameters={"a": Parameter(required=True, default=..., description=""), "b": Parameter(....))
def wf(a: List[], b: ...)
    ...
```

**Comment by wild-endeavor** [comment]
I haven't thought about this in a bit but it actually came up on my list of things to do recently.  Have not gotten to it quite yet though sorry.  Do you have any suggestions for ux?

**Comment by rnatour** [comment]
For my use case either introducing `Optional` typed inputs or allowing empty `Lists` would be fine. The logic I have is to parallelize over the `List` if it is provided, otherwise I crawl a `FlyteDirectory` to generate the input to my `map_task` dynamically. 

I'd rather not set up a separate workflow just to take out the `List` parameter, so instead I'm using a global `List` with a dummy value as a sentinel (which to be fair, is also not ideal).

**Comment by wild-endeavor** [comment]
optional is already supported though.

**Comment by rnatour** [comment]
When I attempt to launch a pipeline that contains an `Optional` parameter defaulted to `None`:
```python
@workflow
def foo(bar: Optional[str] = None) -> None:
    ...
```

I see this error:
```sh
> pyflyte run /path/to foo
Missing option '--bar'
```

Further, running `--help` tells me that `foo` is required:
```sh
> pyflyte run /path/to foo --help
...
Options:
  --bar TEXT  bar  [required]
  --help      Show this message and exit.
```
`flytectl` is at version 0.6.45 and `flytekit` is at 1.9.0

**Comment by rnatour** [comment]
I've observed this same bug when invoking a workflow as a subworkflow: if I leave out an input to the subworkflow that is marked `Optional` and defaulted to `None`, the first task that uses that input will fail.

**Comment by wild-endeavor** [comment]
Yeah there's an edge case bug wrt default Optional inputs.  Default inputs everywhere but especially when the default is None needs to be handled better.  We'll either fix that as part of this issue or create a separate one and link here.

**Comment by wild-endeavor** [comment]
Related: https://github.com/flyteorg/flyte/issues/4275

**Comment by kumare3** [comment]
related to #638
