### ISSUE TITLE
[UI] Add version cmd/info in Flyte console

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#913]
**Describe the Issue**
As a user of Flyte and a system administrator, it should be easy to identify the versions of flyteadmin component from the FlyteCLI & Flyte console. 

**Proposal**
In issue #173 we added a new service `GetVersion` in [flyteidl](https://github.com/flyteorg/flyteidl/blob/bd97959712b625bedf062c881d475a085eb10f31/protos/flyteidl/service/admin.proto#L492-L499). GetVersion API call also implemented in [flyteadmin](https://github.com/flyteorg/flyteadmin/blob/master/pkg/manager/interfaces/version.go). 

- [ ] FlyteCLI - add a new command version which will display flyteadmin & flytecli version 
- [x] FlyteCtl - add a new command version which will display flyteadmin & flytectl version (done #173) 
- [ ] Flyte console - add a new API call for displaying flyteadmin version, along with flyteconsole version 

***Related component***
- [ ] FlyteCLI 
- [x] FlyteCtl
- [ ] Flyte console

**Comment by kumare3** [comment]
thank you @evalsocket !

**Comment by kumare3** [comment]
We are working on the UX for this

**Comment by jsonporter** [comment]
Reopening this because we want to remove "Platform version" and update the UI Version to display what is currently being called "Platform version".

**Comment by anrusina** [comment]
UI version and Admin version are both present now in Flyteconsole.
