### ISSUE TITLE
[BUG] flytekit generates incorrect pod spec for sidecar_task

### ISSUE THREAD

**Issue by ddalenka** [flyteorg/flyte#920]
**Describe the bug**
1. When creating a sidecar_task with resources and /dev/shm volume Flyte fails to execute the task
Task definition:
```python
from flytekit.sdk.tasks import sidecar_task
import k8s.io.apimachinery.pkg.api.resource.generated_pb2 as resources_pb2
import k8s.io.api.core.v1.generated_pb2 as k8s_pb2

shared_volume_mount = k8s_pb2.VolumeMount(
    name='dshm',
    mountPath='/dev/shm',
)
primary_container = k8s_pb2.Container(name='primary')
primary_container.volumeMounts.extend([shared_volume_mount])

pod_spec = k8s_pb2 .PodSpec()
pod_spec.volumes.extend([
    k8s_pb2.Volume(
        name='dshm',
        volumeSource=k8s_pb2.VolumeSource(
            emptyDir=k8s_pb2.EmptyDirVolumeSource(
                medium='Memory',
                sizeLimit=resources_pb2.Quantity(string='4Gi')
            ),
        ),
    ),
])
pod_spec.containers.extend([primary_container])

@sidecar_task(
    memory_limit='16Gi',
    memory_request='16Gi',
    gpu_request='1',
    gpu_limit='1',
    pod_spec=pod_spec,
    primary_container_name='primary'
)
def task():
    pass
```
This generates the volumes and the container resources in the following format:
```json
"volumes": [
    {
        "name": "dshm",
        "volumeSource": {
            "emptyDir": {
                "medium": "Memory",
                "sizeLimit": {
                    "string": "4Gi"
                }
            }
        }
    }
]
```
```json
"resources": {
    "limits": {
        "gpu": {
            "string": "1"
        },
        "memory": {
            "string": "16Gi"
        }
    },
    "requests": {
        "gpu": {
            "string": "1"
        },
        "memory": {
            "string": "16Gi"
        }
    }
}
```
However, this Flyte fails to run this task with the error:
```
Err: [quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$']
```
Additionally, the shared volume is not mounted correctly as Flyte ignores the volume configuration completely.
In k8s pod spec I see the following:
```yaml
volumes:
  - name: cache-volume
    emptyDir: {}
```

**Expected behavior**
Flytekit generates correct pod spec. Flyte runs the sidecar_task 
I believe, that to be correctly parsed by the k8s API resources and volumes must look like this:
```json
"volumes": [
    {
        "name": "dshm",
        "emptyDir": {
            "medium": "Memory",
            "sizeLimit": "4Gi"
        }
    }
]
```
```json
"resources": {
    "limits": {
        "memory": "16Gi",
        "gpu": "1"
    },
    "requests": {
        "memory": "16Gi",
        "gpu": "1"
    }
}
```
At least, when I manually fixed the pod spec in such way - everything worked correctly

**[Optional] Additional context**
Python environment:
Python 3.8.6
```
flyteidl==0.18.32
flytekit==0.17.0
k8s-proto==0.0.3
```

***To Reproduce***
1. Define sidecar_task with resources and /dev/shm volume
2. Run the workflow in Flyte

**Comment by kumare3** [comment]
@ddalenka is it possible for you to migrate to the new flytekit interface? [cookbook](https://docs.flyte.org/projects/cookbook/en/latest/).
 We now call sidecar as pod tasks and instead of using k8s proto we use standard k8s python client [as shown here](https://docs.flyte.org/projects/cookbook/en/latest/auto_plugins_pod/index.html)

**Comment by ddalenka** [comment]
Ok, thanks. I'll try to do it with a pod task

**Comment by kumare3** [comment]
@ddalenka any updates? This is the new api, so you might need to upgrade your code to work with the new api. But, we think this API is way more user friendly and nicer

**Comment by ddalenka** [comment]
Not yet. We plan to do the Flyte workflows optimization soon, and then we will try the new API. Someone from my team will update you about the results.

**Comment by kumare3** [comment]
@ddalenka thank you for the update?

**Comment by arturdryomov** [comment]
@kumare3, hey, I think links above are kinda broken. Do you refer to the new type-based API (instead of the annotation one) and plugins (the `pod` one in particular)?

**Comment by kumare3** [comment]
@arturdryomov yes, the python type based api is the new one. We did some reorganization on the docs- (pod)[https://docs.flyte.org/projects/cookbook/en/latest/auto/integrations/kubernetes/pod/index.html]

**Comment by EngHabu** [comment]
This is only supported in the new API as indicated above. There are currently no plans to back-port it to the old one. Please reopen if there is a reason you can't move to the new API and let's figure out a path forward.
