### ISSUE TITLE
[Docs] Docs for File format aliases not showing up

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#935]
**Describe the documentation update**
It seems the documentation string for FlyteFile aliases that help in users use some pre-created Format aliases, are incorrect and do not show up in the generated documentation.

Example docs [here](https://github.com/flyteorg/flytekit/blob/master/flytekit/types/file/__init__.py#L31-L35)
Example render [here](https://docs.flyte.org/projects/flytekit/en/latest/generated/flytekit.types.file.HDF5EncodedFile.html)

**Comment by kumare3** [comment]
@samhita-alla / @SandraGH5 / @cosmicBboy

**Comment by EngHabu** [comment]
Mind taking care of this in 0.16.0? @cosmicBboy

**Comment by cosmicBboy** [comment]
@SmritiSatyanV this is also another good one to try and tackle, we can also chat about this one next week

**Comment by cosmicBboy** [comment]
for reference: this is an example of inline docstrings for variables/attributes:
https://github.com/flyteorg/flytekit/blob/master/flytekit/core/context_manager.py#L546-L551

**Comment by samhita-alla** [comment]
https://github.com/flyteorg/flytekit/pull/844
