### ISSUE TITLE
[Docs] Working with Files examples can be better

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#936]
**Describe the documentation update**
The working with Files example can be seen [here](https://docs.flyte.org/projects/cookbook/en/latest/auto_core_basic/files.html)

Ideally the input to function `rotate` should accept a `FlyteFile`. This will make it easier for users to understand how to use FlyteFile when testing locally as inputs or workflows

Example of how the function can be re-written

```
def rotate(image_location: JPEGImageFile) -> JPEGImageFile:
    pass
```
And then we should explain what `JPEGImageFile` is.

This is because most users have been asking a question as to how they can use FlyteFile as an input, how to deal with local vs remote files etc

**Comment by kumare3** [comment]
@wild-endeavor / @samhita-alla update please?

**Comment by kumare3** [comment]
Cc @samhita-alla  can you take care of this one?

**Comment by samhita-alla** [comment]
> Cc @samhita-alla can you take care of this one?

Sure, @kumare3!

**Comment by SandraGH5** [comment]
@samhita-alla can this be closed?

**Comment by kumare3** [comment]
I think so?

**Comment by samhita-alla** [comment]
Yes, we can close this.
