### ISSUE TITLE
[BUG] Pytorch images are getting heavier causing githubworkflow runs to fail

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#938]
**Describe the bug**
Following flytesnacks run failed while download pytorch library for sagemaker plugin cookbook run.

https://github.com/flyteorg/flytesnacks/runs/2425119942
```
ApplyLayer exit status 1 stdout:  stderr: write /root/.cache/pip/http/8/9/d/0/b/89d0bbe36a0f0ca557bad26c88606913c2a3e65d8a4521dc9b6c82b3: no space left on device
```

The image sizes are over 5g 
 https://hub.docker.com/r/pytorch/pytorch/tags?page=1&ordering=last_updated

Image used by the workflow run 5.15 GB
https://hub.docker.com/layers/pytorch/pytorch/1.7.0-cuda11.0-cudnn8-devel/images/sha256-837e6964e5db6e5b35f4d5e98e9cac073ab757766039b9503f39c14beafb0e98?context=explore

**Expected behavior**
Download should succeed . 
We might want to use lighter version of pytorch if available.

**[Optional] Additional context**
***To Reproduce***
1.  Push a change to flytesnacks repo 
2.  Check the push sagemake pytorch plugin run

***Screenshots***

**Comment by kumare3** [comment]
This has been completed
