### ISSUE TITLE
[Housekeeping] Support ~/.flyte as search path for config.yaml

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#941]
**Describe the Issue**
Currently the config.yaml file is searched in the following locations.

- currentDir
- /etc/flyte/config
- $GOPATH/src/github.com/lyft/flytestdlib

To make it compatible with flytekit we should also add homedir/.flyte directory to search path.

**What if we do not do this?**
Users have to keep the config.yaml in currentDir or /etc/flyte/config or $GOPATH/src/github.com/lyft/flytestdlib

Alternatives available to user to pass explicitly the path to config but he has to do this for every command.
```
flytectl get project --config ~/.flyte/config.yaml
```

***Related component***
flytestdlib

**Comment by wild-endeavor** [comment]
add milestone and close?

**Comment by pmahindrakar-oss** [comment]
Done . Released new version which also supports Oauth.
https://github.com/flyteorg/flytectl/releases/tag/v0.1.6
