### ISSUE TITLE
[Housekeeping] Use functional test scripts to replace e2e tests

### ISSUE THREAD

**Issue by evalsocket** [flyteorg/flyte#946]
**Describe the Issue**
- Improve Get Started guide 
- Add GitHub workflow for e2e test on different runner 

**What if we do not do this?**
- Flytesnacks github workflow to automatically serialize all the examples into *.pb files split into 3 folders (p0, p1 and p2).
   1. Store the serialized workflows as release assets in flytesnacks
   2. Drive the p0, p1 and p2 categorization based on a manually updated manifest file in the same repo.
- Update getting started to use Flytectl register using these generated assets
- Publish kustomize manifests in github.com/flyteorg/flyte/releases assets
- Test Suite Executor github workflow to run on different runners. Initially only support github’s default ubunut-latest but later we can add flyte-aws runner that runs on an EC2  machine and has permissions to create EKS clusters… etc. 
  1. The workflow steps should be generic enough to apply to different runners
  2.  Support manual invocation
  
***Related component***
Either Specific / all

**Comment by kumare3** [comment]
@evalsocket whats the progress on this?

**Comment by evalsocket** [comment]
- [ ] Flytesnack serialize proto is released in Github 
- [ ] Publish flyte manifest in github release 
- [ ] Pytest remote cluster support  (Will start work on this)

**Comment by evalsocket** [comment]
@kumare3 3 task are remaining. @samhita-alla  is working on pytest-flyte, I will start other remaining issue after samhita is done with pytest-flyte

**Comment by kumare3** [comment]
@evalsocket is this still valid?

**Comment by evalsocket** [comment]
@EngHabu I created a separate issue for reaming task https://github.com/flyteorg/flyte/issues/1932, I am closing this for now
