### ISSUE TITLE
[Docs] Provide a clear explanation for setting up tasks requiring GPUs

### ISSUE THREAD

**Issue by katrogan** [flyteorg/flyte#947]
It's not immediately clear how to set up a Flyte platform deployment to enable GPU usage for tasks specifying GPU resources.

See https://flyte-org.slack.com/archives/CREL4QVAQ/p1619539288364000 for background. We should capture this thoroughly in Flyte docs

cc @kumare3

**Comment by SandraGH5** [comment]
Where would be a good place to put the link to: https://docs.flyte.org/projects/cookbook/en/latest/auto_core_remote_flyte/customizing_resources.html?highlight=limits#customizing-task-resources-like-mem-cpu
(Ideally the pages with instructions to set up Flyte task containers to be scheduled on specific gpu nodes.)

**Comment by SandraGH5** [comment]
Please refer to PR:
https://github.com/flyteorg/flytesnacks/pull/171
