### ISSUE TITLE
[Housekeeping] Flyteconsole upgrade to Latest node version - Node 12 will be deprecated soon

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#977]
**Describe the Issue**
Flyteconsole currently is tested on Node-12 and builds only for node 12. We should upgrade it to match the latest version
https://nodejs.org/en/about/releases/

**What if we do not do this?**
Flyteconsole will use a deprecated version of node.

***Related component***
Flyteconsole

**Comment by jsonporter** [comment]
This has been fixed; current supported version is node 14.
