### ISSUE TITLE
[BUG] Kubernetes service account or IAM role needs to be supplied when running tasks from the UI

### ISSUE THREAD

**Issue by annadcunningham** [flyteorg/flyte#980]
**Describe the bug**
The kubernetes service account used during workflow registration is not correctly propagated in the UI when trying to run a single task.

**Expected behavior**
I registered my workflows and can run them fine from the UI, but if I want to run a task I have to supply either a `IAM role` or `Kubernetes Service Account` before I can launch the task.

**[Optional] Additional context**
***To Reproduce***
1. Register some workflows; here is my config:
```
[sdk]
workflow_packages=sunflower.workflows.flyte_workflows

[auth]
kubernetes_service_account=default

[platform]
cloud_provider=gcp
url=localhost:51234
insecure=True

[gcp]
gsutil_parallelism=true
```
2. Try to launch a task in the UI. If I don't put anything in `IAM Role` or `Kubernetes Service Account`, it won't let me Launch, saying that a value is required. I can put `default` into the `Kubernetes Service Account` and then it launches fine.

***Screenshots***
![image](https://user-images.githubusercontent.com/16860843/117185769-0a51e580-ad8f-11eb-9e50-1e1dbe37b375.png)

**Comment by kumare3** [comment]
@annadcunningham sorry for the delayed response. But, you are right, you have to specify the service account to use. This is because the service account is only bound to the launch plan which is associated with the workflow. Would you prefer that we use the serviceaccount that you have configured?

**Comment by kumare3** [comment]
@annadcunningham as you can supply a service account today, I will mark this as an enhancement. As I understand that you would like to have a default service account that is registered a should be used if one is not provided

**Comment by annadcunningham** [comment]
Thanks for responding! Yes, I agree - it works as-is, but would be an enhancement if the service account defaults to the one configured.

**Comment by kumare3** [comment]
Ya currently the configured service account in flytekit gets applied only to launchplans. But I like this idea

**Comment by anrusina** [comment]
Done by:
https://github.com/flyteorg/flyteconsole/pull/255
https://github.com/flyteorg/flyteconsole/pull/253
